# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from typed_boto3.services.lambda_client import LambdaClient
from typed_boto3.services.s3_client import S3Client

__all__ = ["LambdaClient", "S3Client"]
