# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.apigatewayv2.apigatewayv2_classes import (
    CreateApiMappingRequestTypeDef,
    CreateApiMappingResponseTypeDef,
    CreateApiRequestTypeDef,
    CreateApiResponseTypeDef,
    CreateAuthorizerRequestTypeDef,
    CreateAuthorizerResponseTypeDef,
    CreateDeploymentRequestTypeDef,
    CreateDeploymentResponseTypeDef,
    CreateDomainNameRequestTypeDef,
    CreateDomainNameResponseTypeDef,
    CreateIntegrationRequestTypeDef,
    CreateIntegrationResponseRequestTypeDef,
    CreateIntegrationResponseResponseTypeDef,
    CreateIntegrationResultTypeDef,
    CreateModelRequestTypeDef,
    CreateModelResponseTypeDef,
    CreatePortalProductRequestTypeDef,
    CreatePortalProductResponseTypeDef,
    CreatePortalRequestTypeDef,
    CreatePortalResponseTypeDef,
    CreateProductPageRequestTypeDef,
    CreateProductPageResponseTypeDef,
    CreateProductRestEndpointPageRequestTypeDef,
    CreateProductRestEndpointPageResponseTypeDef,
    CreateRouteRequestTypeDef,
    CreateRouteResponseRequestTypeDef,
    CreateRouteResponseResponseTypeDef,
    CreateRouteResultTypeDef,
    CreateRoutingRuleRequestTypeDef,
    CreateRoutingRuleResponseTypeDef,
    CreateStageRequestTypeDef,
    CreateStageResponseTypeDef,
    CreateVpcLinkRequestTypeDef,
    CreateVpcLinkResponseTypeDef,
    DeleteAccessLogSettingsRequestTypeDef,
    DeleteApiMappingRequestTypeDef,
    DeleteApiRequestTypeDef,
    DeleteAuthorizerRequestTypeDef,
    DeleteCorsConfigurationRequestTypeDef,
    DeleteDeploymentRequestTypeDef,
    DeleteDomainNameRequestTypeDef,
    DeleteIntegrationRequestTypeDef,
    DeleteIntegrationResponseRequestTypeDef,
    DeleteModelRequestTypeDef,
    DeletePortalProductRequestTypeDef,
    DeletePortalProductSharingPolicyRequestTypeDef,
    DeletePortalRequestTypeDef,
    DeleteProductPageRequestTypeDef,
    DeleteProductRestEndpointPageRequestTypeDef,
    DeleteRouteRequestParameterRequestTypeDef,
    DeleteRouteRequestTypeDef,
    DeleteRouteResponseRequestTypeDef,
    DeleteRouteSettingsRequestTypeDef,
    DeleteRoutingRuleRequestTypeDef,
    DeleteStageRequestTypeDef,
    DeleteVpcLinkRequestTypeDef,
    DisablePortalRequestTypeDef,
    ExportApiRequestTypeDef,
    ExportApiResponseTypeDef,
    GetApiMappingRequestTypeDef,
    GetApiMappingResponseTypeDef,
    GetApiMappingsRequestTypeDef,
    GetApiMappingsResponseTypeDef,
    GetApiRequestTypeDef,
    GetApiResponseTypeDef,
    GetApisRequestTypeDef,
    GetApisResponseTypeDef,
    GetAuthorizerRequestTypeDef,
    GetAuthorizerResponseTypeDef,
    GetAuthorizersRequestTypeDef,
    GetAuthorizersResponseTypeDef,
    GetDeploymentRequestTypeDef,
    GetDeploymentResponseTypeDef,
    GetDeploymentsRequestTypeDef,
    GetDeploymentsResponseTypeDef,
    GetDomainNameRequestTypeDef,
    GetDomainNameResponseTypeDef,
    GetDomainNamesRequestTypeDef,
    GetDomainNamesResponseTypeDef,
    GetIntegrationRequestTypeDef,
    GetIntegrationResponseRequestTypeDef,
    GetIntegrationResponseResponseTypeDef,
    GetIntegrationResponsesRequestTypeDef,
    GetIntegrationResponsesResponseTypeDef,
    GetIntegrationResultTypeDef,
    GetIntegrationsRequestTypeDef,
    GetIntegrationsResponseTypeDef,
    GetModelRequestTypeDef,
    GetModelResponseTypeDef,
    GetModelTemplateRequestTypeDef,
    GetModelTemplateResponseTypeDef,
    GetModelsRequestTypeDef,
    GetModelsResponseTypeDef,
    GetPortalProductRequestTypeDef,
    GetPortalProductResponseTypeDef,
    GetPortalProductSharingPolicyRequestTypeDef,
    GetPortalProductSharingPolicyResponseTypeDef,
    GetPortalRequestTypeDef,
    GetPortalResponseTypeDef,
    GetProductPageRequestTypeDef,
    GetProductPageResponseTypeDef,
    GetProductRestEndpointPageRequestTypeDef,
    GetProductRestEndpointPageResponseTypeDef,
    GetRouteRequestTypeDef,
    GetRouteResponseRequestTypeDef,
    GetRouteResponseResponseTypeDef,
    GetRouteResponsesRequestTypeDef,
    GetRouteResponsesResponseTypeDef,
    GetRouteResultTypeDef,
    GetRoutesRequestTypeDef,
    GetRoutesResponseTypeDef,
    GetRoutingRuleRequestTypeDef,
    GetRoutingRuleResponseTypeDef,
    GetStageRequestTypeDef,
    GetStageResponseTypeDef,
    GetStagesRequestTypeDef,
    GetStagesResponseTypeDef,
    GetTagsRequestTypeDef,
    GetTagsResponseTypeDef,
    GetVpcLinkRequestTypeDef,
    GetVpcLinkResponseTypeDef,
    GetVpcLinksRequestTypeDef,
    GetVpcLinksResponseTypeDef,
    ImportApiRequestTypeDef,
    ImportApiResponseTypeDef,
    ListPortalProductsRequestTypeDef,
    ListPortalProductsResponseTypeDef,
    ListPortalsRequestTypeDef,
    ListPortalsResponseTypeDef,
    ListProductPagesRequestTypeDef,
    ListProductPagesResponseTypeDef,
    ListProductRestEndpointPagesRequestTypeDef,
    ListProductRestEndpointPagesResponseTypeDef,
    ListRoutingRulesRequestTypeDef,
    ListRoutingRulesResponseTypeDef,
    PreviewPortalRequestTypeDef,
    PublishPortalRequestTypeDef,
    PutPortalProductSharingPolicyRequestTypeDef,
    PutRoutingRuleRequestTypeDef,
    PutRoutingRuleResponseTypeDef,
    ReimportApiRequestTypeDef,
    ReimportApiResponseTypeDef,
    ResetAuthorizersCacheRequestTypeDef,
    TagResourceRequestTypeDef,
    UntagResourceRequestTypeDef,
    UpdateApiMappingRequestTypeDef,
    UpdateApiMappingResponseTypeDef,
    UpdateApiRequestTypeDef,
    UpdateApiResponseTypeDef,
    UpdateAuthorizerRequestTypeDef,
    UpdateAuthorizerResponseTypeDef,
    UpdateDeploymentRequestTypeDef,
    UpdateDeploymentResponseTypeDef,
    UpdateDomainNameRequestTypeDef,
    UpdateDomainNameResponseTypeDef,
    UpdateIntegrationRequestTypeDef,
    UpdateIntegrationResponseRequestTypeDef,
    UpdateIntegrationResponseResponseTypeDef,
    UpdateIntegrationResultTypeDef,
    UpdateModelRequestTypeDef,
    UpdateModelResponseTypeDef,
    UpdatePortalProductRequestTypeDef,
    UpdatePortalProductResponseTypeDef,
    UpdatePortalRequestTypeDef,
    UpdatePortalResponseTypeDef,
    UpdateProductPageRequestTypeDef,
    UpdateProductPageResponseTypeDef,
    UpdateProductRestEndpointPageRequestTypeDef,
    UpdateProductRestEndpointPageResponseTypeDef,
    UpdateRouteRequestTypeDef,
    UpdateRouteResponseRequestTypeDef,
    UpdateRouteResponseResponseTypeDef,
    UpdateRouteResultTypeDef,
    UpdateStageRequestTypeDef,
    UpdateStageResponseTypeDef,
    UpdateVpcLinkRequestTypeDef,
    UpdateVpcLinkResponseTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class Apigatewayv2Client(TypedClientBase):
    _service_name = ServiceName.APIGATEWAYV2


    def create_api(
        self, request: CreateApiRequestTypeDef,
    ) -> CreateApiResponseTypeDef:
        return self._call(
            "create_api",
            request,
            CreateApiResponseTypeDef,
        )


    def create_api_mapping(
        self, request: CreateApiMappingRequestTypeDef,
    ) -> CreateApiMappingResponseTypeDef:
        return self._call(
            "create_api_mapping",
            request,
            CreateApiMappingResponseTypeDef,
        )


    def create_authorizer(
        self, request: CreateAuthorizerRequestTypeDef,
    ) -> CreateAuthorizerResponseTypeDef:
        return self._call(
            "create_authorizer",
            request,
            CreateAuthorizerResponseTypeDef,
        )


    def create_deployment(
        self, request: CreateDeploymentRequestTypeDef,
    ) -> CreateDeploymentResponseTypeDef:
        return self._call(
            "create_deployment",
            request,
            CreateDeploymentResponseTypeDef,
        )


    def create_domain_name(
        self, request: CreateDomainNameRequestTypeDef,
    ) -> CreateDomainNameResponseTypeDef:
        return self._call(
            "create_domain_name",
            request,
            CreateDomainNameResponseTypeDef,
        )


    def create_integration(
        self, request: CreateIntegrationRequestTypeDef,
    ) -> CreateIntegrationResultTypeDef:
        return self._call(
            "create_integration",
            request,
            CreateIntegrationResultTypeDef,
        )


    def create_integration_response(
        self, request: CreateIntegrationResponseRequestTypeDef,
    ) -> CreateIntegrationResponseResponseTypeDef:
        return self._call(
            "create_integration_response",
            request,
            CreateIntegrationResponseResponseTypeDef,
        )


    def create_model(
        self, request: CreateModelRequestTypeDef,
    ) -> CreateModelResponseTypeDef:
        return self._call(
            "create_model",
            request,
            CreateModelResponseTypeDef,
        )


    def create_portal(
        self, request: CreatePortalRequestTypeDef,
    ) -> CreatePortalResponseTypeDef:
        return self._call(
            "create_portal",
            request,
            CreatePortalResponseTypeDef,
        )


    def create_portal_product(
        self, request: CreatePortalProductRequestTypeDef,
    ) -> CreatePortalProductResponseTypeDef:
        return self._call(
            "create_portal_product",
            request,
            CreatePortalProductResponseTypeDef,
        )


    def create_product_page(
        self, request: CreateProductPageRequestTypeDef,
    ) -> CreateProductPageResponseTypeDef:
        return self._call(
            "create_product_page",
            request,
            CreateProductPageResponseTypeDef,
        )


    def create_product_rest_endpoint_page(
        self, request: CreateProductRestEndpointPageRequestTypeDef,
    ) -> CreateProductRestEndpointPageResponseTypeDef:
        return self._call(
            "create_product_rest_endpoint_page",
            request,
            CreateProductRestEndpointPageResponseTypeDef,
        )


    def create_route(
        self, request: CreateRouteRequestTypeDef,
    ) -> CreateRouteResultTypeDef:
        return self._call(
            "create_route",
            request,
            CreateRouteResultTypeDef,
        )


    def create_route_response(
        self, request: CreateRouteResponseRequestTypeDef,
    ) -> CreateRouteResponseResponseTypeDef:
        return self._call(
            "create_route_response",
            request,
            CreateRouteResponseResponseTypeDef,
        )


    def create_routing_rule(
        self, request: CreateRoutingRuleRequestTypeDef,
    ) -> CreateRoutingRuleResponseTypeDef:
        return self._call(
            "create_routing_rule",
            request,
            CreateRoutingRuleResponseTypeDef,
        )


    def create_stage(
        self, request: CreateStageRequestTypeDef,
    ) -> CreateStageResponseTypeDef:
        return self._call(
            "create_stage",
            request,
            CreateStageResponseTypeDef,
        )


    def create_vpc_link(
        self, request: CreateVpcLinkRequestTypeDef,
    ) -> CreateVpcLinkResponseTypeDef:
        return self._call(
            "create_vpc_link",
            request,
            CreateVpcLinkResponseTypeDef,
        )


    def delete_access_log_settings(
        self, request: DeleteAccessLogSettingsRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_access_log_settings",
            request,
            None,
        )


    def delete_api(
        self, request: DeleteApiRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_api",
            request,
            None,
        )


    def delete_api_mapping(
        self, request: DeleteApiMappingRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_api_mapping",
            request,
            None,
        )


    def delete_authorizer(
        self, request: DeleteAuthorizerRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_authorizer",
            request,
            None,
        )


    def delete_cors_configuration(
        self, request: DeleteCorsConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_cors_configuration",
            request,
            None,
        )


    def delete_deployment(
        self, request: DeleteDeploymentRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_deployment",
            request,
            None,
        )


    def delete_domain_name(
        self, request: DeleteDomainNameRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_domain_name",
            request,
            None,
        )


    def delete_integration(
        self, request: DeleteIntegrationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_integration",
            request,
            None,
        )


    def delete_integration_response(
        self, request: DeleteIntegrationResponseRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_integration_response",
            request,
            None,
        )


    def delete_model(
        self, request: DeleteModelRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_model",
            request,
            None,
        )


    def delete_portal(
        self, request: DeletePortalRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_portal",
            request,
            None,
        )


    def delete_portal_product(
        self, request: DeletePortalProductRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_portal_product",
            request,
            None,
        )


    def delete_portal_product_sharing_policy(
        self, request: DeletePortalProductSharingPolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_portal_product_sharing_policy",
            request,
            None,
        )


    def delete_product_page(
        self, request: DeleteProductPageRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_product_page",
            request,
            None,
        )


    def delete_product_rest_endpoint_page(
        self, request: DeleteProductRestEndpointPageRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_product_rest_endpoint_page",
            request,
            None,
        )


    def delete_route(
        self, request: DeleteRouteRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_route",
            request,
            None,
        )


    def delete_route_request_parameter(
        self, request: DeleteRouteRequestParameterRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_route_request_parameter",
            request,
            None,
        )


    def delete_route_response(
        self, request: DeleteRouteResponseRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_route_response",
            request,
            None,
        )


    def delete_route_settings(
        self, request: DeleteRouteSettingsRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_route_settings",
            request,
            None,
        )


    def delete_routing_rule(
        self, request: DeleteRoutingRuleRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_routing_rule",
            request,
            None,
        )


    def delete_stage(
        self, request: DeleteStageRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_stage",
            request,
            None,
        )


    def delete_vpc_link(
        self, request: DeleteVpcLinkRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_vpc_link",
            request,
            None,
        )


    def disable_portal(
        self, request: DisablePortalRequestTypeDef,
    ) -> None:
        return self._call(
            "disable_portal",
            request,
            None,
        )


    def export_api(
        self, request: ExportApiRequestTypeDef,
    ) -> ExportApiResponseTypeDef:
        return self._call(
            "export_api",
            request,
            ExportApiResponseTypeDef,
        )


    def get_api(
        self, request: GetApiRequestTypeDef,
    ) -> GetApiResponseTypeDef:
        return self._call(
            "get_api",
            request,
            GetApiResponseTypeDef,
        )


    def get_api_mapping(
        self, request: GetApiMappingRequestTypeDef,
    ) -> GetApiMappingResponseTypeDef:
        return self._call(
            "get_api_mapping",
            request,
            GetApiMappingResponseTypeDef,
        )


    def get_api_mappings(
        self, request: GetApiMappingsRequestTypeDef,
    ) -> GetApiMappingsResponseTypeDef:
        return self._call(
            "get_api_mappings",
            request,
            GetApiMappingsResponseTypeDef,
        )


    def get_apis(
        self, request: GetApisRequestTypeDef,
    ) -> GetApisResponseTypeDef:
        return self._call(
            "get_apis",
            request,
            GetApisResponseTypeDef,
        )


    def get_authorizer(
        self, request: GetAuthorizerRequestTypeDef,
    ) -> GetAuthorizerResponseTypeDef:
        return self._call(
            "get_authorizer",
            request,
            GetAuthorizerResponseTypeDef,
        )


    def get_authorizers(
        self, request: GetAuthorizersRequestTypeDef,
    ) -> GetAuthorizersResponseTypeDef:
        return self._call(
            "get_authorizers",
            request,
            GetAuthorizersResponseTypeDef,
        )


    def get_deployment(
        self, request: GetDeploymentRequestTypeDef,
    ) -> GetDeploymentResponseTypeDef:
        return self._call(
            "get_deployment",
            request,
            GetDeploymentResponseTypeDef,
        )


    def get_deployments(
        self, request: GetDeploymentsRequestTypeDef,
    ) -> GetDeploymentsResponseTypeDef:
        return self._call(
            "get_deployments",
            request,
            GetDeploymentsResponseTypeDef,
        )


    def get_domain_name(
        self, request: GetDomainNameRequestTypeDef,
    ) -> GetDomainNameResponseTypeDef:
        return self._call(
            "get_domain_name",
            request,
            GetDomainNameResponseTypeDef,
        )


    def get_domain_names(
        self, request: GetDomainNamesRequestTypeDef,
    ) -> GetDomainNamesResponseTypeDef:
        return self._call(
            "get_domain_names",
            request,
            GetDomainNamesResponseTypeDef,
        )


    def get_integration(
        self, request: GetIntegrationRequestTypeDef,
    ) -> GetIntegrationResultTypeDef:
        return self._call(
            "get_integration",
            request,
            GetIntegrationResultTypeDef,
        )


    def get_integration_response(
        self, request: GetIntegrationResponseRequestTypeDef,
    ) -> GetIntegrationResponseResponseTypeDef:
        return self._call(
            "get_integration_response",
            request,
            GetIntegrationResponseResponseTypeDef,
        )


    def get_integration_responses(
        self, request: GetIntegrationResponsesRequestTypeDef,
    ) -> GetIntegrationResponsesResponseTypeDef:
        return self._call(
            "get_integration_responses",
            request,
            GetIntegrationResponsesResponseTypeDef,
        )


    def get_integrations(
        self, request: GetIntegrationsRequestTypeDef,
    ) -> GetIntegrationsResponseTypeDef:
        return self._call(
            "get_integrations",
            request,
            GetIntegrationsResponseTypeDef,
        )


    def get_model(
        self, request: GetModelRequestTypeDef,
    ) -> GetModelResponseTypeDef:
        return self._call(
            "get_model",
            request,
            GetModelResponseTypeDef,
        )


    def get_model_template(
        self, request: GetModelTemplateRequestTypeDef,
    ) -> GetModelTemplateResponseTypeDef:
        return self._call(
            "get_model_template",
            request,
            GetModelTemplateResponseTypeDef,
        )


    def get_models(
        self, request: GetModelsRequestTypeDef,
    ) -> GetModelsResponseTypeDef:
        return self._call(
            "get_models",
            request,
            GetModelsResponseTypeDef,
        )


    def get_portal(
        self, request: GetPortalRequestTypeDef,
    ) -> GetPortalResponseTypeDef:
        return self._call(
            "get_portal",
            request,
            GetPortalResponseTypeDef,
        )


    def get_portal_product(
        self, request: GetPortalProductRequestTypeDef,
    ) -> GetPortalProductResponseTypeDef:
        return self._call(
            "get_portal_product",
            request,
            GetPortalProductResponseTypeDef,
        )


    def get_portal_product_sharing_policy(
        self, request: GetPortalProductSharingPolicyRequestTypeDef,
    ) -> GetPortalProductSharingPolicyResponseTypeDef:
        return self._call(
            "get_portal_product_sharing_policy",
            request,
            GetPortalProductSharingPolicyResponseTypeDef,
        )


    def get_product_page(
        self, request: GetProductPageRequestTypeDef,
    ) -> GetProductPageResponseTypeDef:
        return self._call(
            "get_product_page",
            request,
            GetProductPageResponseTypeDef,
        )


    def get_product_rest_endpoint_page(
        self, request: GetProductRestEndpointPageRequestTypeDef,
    ) -> GetProductRestEndpointPageResponseTypeDef:
        return self._call(
            "get_product_rest_endpoint_page",
            request,
            GetProductRestEndpointPageResponseTypeDef,
        )


    def get_route(
        self, request: GetRouteRequestTypeDef,
    ) -> GetRouteResultTypeDef:
        return self._call(
            "get_route",
            request,
            GetRouteResultTypeDef,
        )


    def get_route_response(
        self, request: GetRouteResponseRequestTypeDef,
    ) -> GetRouteResponseResponseTypeDef:
        return self._call(
            "get_route_response",
            request,
            GetRouteResponseResponseTypeDef,
        )


    def get_route_responses(
        self, request: GetRouteResponsesRequestTypeDef,
    ) -> GetRouteResponsesResponseTypeDef:
        return self._call(
            "get_route_responses",
            request,
            GetRouteResponsesResponseTypeDef,
        )


    def get_routes(
        self, request: GetRoutesRequestTypeDef,
    ) -> GetRoutesResponseTypeDef:
        return self._call(
            "get_routes",
            request,
            GetRoutesResponseTypeDef,
        )


    def get_routing_rule(
        self, request: GetRoutingRuleRequestTypeDef,
    ) -> GetRoutingRuleResponseTypeDef:
        return self._call(
            "get_routing_rule",
            request,
            GetRoutingRuleResponseTypeDef,
        )


    def get_stage(
        self, request: GetStageRequestTypeDef,
    ) -> GetStageResponseTypeDef:
        return self._call(
            "get_stage",
            request,
            GetStageResponseTypeDef,
        )


    def get_stages(
        self, request: GetStagesRequestTypeDef,
    ) -> GetStagesResponseTypeDef:
        return self._call(
            "get_stages",
            request,
            GetStagesResponseTypeDef,
        )


    def get_tags(
        self, request: GetTagsRequestTypeDef,
    ) -> GetTagsResponseTypeDef:
        return self._call(
            "get_tags",
            request,
            GetTagsResponseTypeDef,
        )


    def get_vpc_link(
        self, request: GetVpcLinkRequestTypeDef,
    ) -> GetVpcLinkResponseTypeDef:
        return self._call(
            "get_vpc_link",
            request,
            GetVpcLinkResponseTypeDef,
        )


    def get_vpc_links(
        self, request: GetVpcLinksRequestTypeDef,
    ) -> GetVpcLinksResponseTypeDef:
        return self._call(
            "get_vpc_links",
            request,
            GetVpcLinksResponseTypeDef,
        )


    def import_api(
        self, request: ImportApiRequestTypeDef,
    ) -> ImportApiResponseTypeDef:
        return self._call(
            "import_api",
            request,
            ImportApiResponseTypeDef,
        )


    def list_portal_products(
        self, request: ListPortalProductsRequestTypeDef,
    ) -> ListPortalProductsResponseTypeDef:
        return self._call(
            "list_portal_products",
            request,
            ListPortalProductsResponseTypeDef,
        )


    def list_portals(
        self, request: ListPortalsRequestTypeDef,
    ) -> ListPortalsResponseTypeDef:
        return self._call(
            "list_portals",
            request,
            ListPortalsResponseTypeDef,
        )


    def list_product_pages(
        self, request: ListProductPagesRequestTypeDef,
    ) -> ListProductPagesResponseTypeDef:
        return self._call(
            "list_product_pages",
            request,
            ListProductPagesResponseTypeDef,
        )


    def list_product_rest_endpoint_pages(
        self, request: ListProductRestEndpointPagesRequestTypeDef,
    ) -> ListProductRestEndpointPagesResponseTypeDef:
        return self._call(
            "list_product_rest_endpoint_pages",
            request,
            ListProductRestEndpointPagesResponseTypeDef,
        )


    def list_routing_rules(
        self, request: ListRoutingRulesRequestTypeDef,
    ) -> ListRoutingRulesResponseTypeDef:
        return self._call(
            "list_routing_rules",
            request,
            ListRoutingRulesResponseTypeDef,
        )


    def preview_portal(
        self, request: PreviewPortalRequestTypeDef,
    ) -> None:
        return self._call(
            "preview_portal",
            request,
            None,
        )


    def publish_portal(
        self, request: PublishPortalRequestTypeDef,
    ) -> None:
        return self._call(
            "publish_portal",
            request,
            None,
        )


    def put_portal_product_sharing_policy(
        self, request: PutPortalProductSharingPolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "put_portal_product_sharing_policy",
            request,
            None,
        )


    def put_routing_rule(
        self, request: PutRoutingRuleRequestTypeDef,
    ) -> PutRoutingRuleResponseTypeDef:
        return self._call(
            "put_routing_rule",
            request,
            PutRoutingRuleResponseTypeDef,
        )


    def reimport_api(
        self, request: ReimportApiRequestTypeDef,
    ) -> ReimportApiResponseTypeDef:
        return self._call(
            "reimport_api",
            request,
            ReimportApiResponseTypeDef,
        )


    def reset_authorizers_cache(
        self, request: ResetAuthorizersCacheRequestTypeDef,
    ) -> None:
        return self._call(
            "reset_authorizers_cache",
            request,
            None,
        )


    def tag_resource(
        self, request: TagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def untag_resource(
        self, request: UntagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_api(
        self, request: UpdateApiRequestTypeDef,
    ) -> UpdateApiResponseTypeDef:
        return self._call(
            "update_api",
            request,
            UpdateApiResponseTypeDef,
        )


    def update_api_mapping(
        self, request: UpdateApiMappingRequestTypeDef,
    ) -> UpdateApiMappingResponseTypeDef:
        return self._call(
            "update_api_mapping",
            request,
            UpdateApiMappingResponseTypeDef,
        )


    def update_authorizer(
        self, request: UpdateAuthorizerRequestTypeDef,
    ) -> UpdateAuthorizerResponseTypeDef:
        return self._call(
            "update_authorizer",
            request,
            UpdateAuthorizerResponseTypeDef,
        )


    def update_deployment(
        self, request: UpdateDeploymentRequestTypeDef,
    ) -> UpdateDeploymentResponseTypeDef:
        return self._call(
            "update_deployment",
            request,
            UpdateDeploymentResponseTypeDef,
        )


    def update_domain_name(
        self, request: UpdateDomainNameRequestTypeDef,
    ) -> UpdateDomainNameResponseTypeDef:
        return self._call(
            "update_domain_name",
            request,
            UpdateDomainNameResponseTypeDef,
        )


    def update_integration(
        self, request: UpdateIntegrationRequestTypeDef,
    ) -> UpdateIntegrationResultTypeDef:
        return self._call(
            "update_integration",
            request,
            UpdateIntegrationResultTypeDef,
        )


    def update_integration_response(
        self, request: UpdateIntegrationResponseRequestTypeDef,
    ) -> UpdateIntegrationResponseResponseTypeDef:
        return self._call(
            "update_integration_response",
            request,
            UpdateIntegrationResponseResponseTypeDef,
        )


    def update_model(
        self, request: UpdateModelRequestTypeDef,
    ) -> UpdateModelResponseTypeDef:
        return self._call(
            "update_model",
            request,
            UpdateModelResponseTypeDef,
        )


    def update_portal(
        self, request: UpdatePortalRequestTypeDef,
    ) -> UpdatePortalResponseTypeDef:
        return self._call(
            "update_portal",
            request,
            UpdatePortalResponseTypeDef,
        )


    def update_portal_product(
        self, request: UpdatePortalProductRequestTypeDef,
    ) -> UpdatePortalProductResponseTypeDef:
        return self._call(
            "update_portal_product",
            request,
            UpdatePortalProductResponseTypeDef,
        )


    def update_product_page(
        self, request: UpdateProductPageRequestTypeDef,
    ) -> UpdateProductPageResponseTypeDef:
        return self._call(
            "update_product_page",
            request,
            UpdateProductPageResponseTypeDef,
        )


    def update_product_rest_endpoint_page(
        self, request: UpdateProductRestEndpointPageRequestTypeDef,
    ) -> UpdateProductRestEndpointPageResponseTypeDef:
        return self._call(
            "update_product_rest_endpoint_page",
            request,
            UpdateProductRestEndpointPageResponseTypeDef,
        )


    def update_route(
        self, request: UpdateRouteRequestTypeDef,
    ) -> UpdateRouteResultTypeDef:
        return self._call(
            "update_route",
            request,
            UpdateRouteResultTypeDef,
        )


    def update_route_response(
        self, request: UpdateRouteResponseRequestTypeDef,
    ) -> UpdateRouteResponseResponseTypeDef:
        return self._call(
            "update_route_response",
            request,
            UpdateRouteResponseResponseTypeDef,
        )


    def update_stage(
        self, request: UpdateStageRequestTypeDef,
    ) -> UpdateStageResponseTypeDef:
        return self._call(
            "update_stage",
            request,
            UpdateStageResponseTypeDef,
        )


    def update_vpc_link(
        self, request: UpdateVpcLinkRequestTypeDef,
    ) -> UpdateVpcLinkResponseTypeDef:
        return self._call(
            "update_vpc_link",
            request,
            UpdateVpcLinkResponseTypeDef,
        )

