# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.athena.athena_classes import (
    BatchGetNamedQueryInputTypeDef,
    BatchGetNamedQueryOutputTypeDef,
    BatchGetPreparedStatementInputTypeDef,
    BatchGetPreparedStatementOutputTypeDef,
    BatchGetQueryExecutionInputTypeDef,
    BatchGetQueryExecutionOutputTypeDef,
    CancelCapacityReservationInputTypeDef,
    CreateCapacityReservationInputTypeDef,
    CreateDataCatalogInputTypeDef,
    CreateDataCatalogOutputTypeDef,
    CreateNamedQueryInputTypeDef,
    CreateNamedQueryOutputTypeDef,
    CreateNotebookInputTypeDef,
    CreateNotebookOutputTypeDef,
    CreatePreparedStatementInputTypeDef,
    CreatePresignedNotebookUrlRequestTypeDef,
    CreatePresignedNotebookUrlResponseTypeDef,
    CreateWorkGroupInputTypeDef,
    DeleteCapacityReservationInputTypeDef,
    DeleteDataCatalogInputTypeDef,
    DeleteDataCatalogOutputTypeDef,
    DeleteNamedQueryInputTypeDef,
    DeleteNotebookInputTypeDef,
    DeletePreparedStatementInputTypeDef,
    DeleteWorkGroupInputTypeDef,
    ExportNotebookInputTypeDef,
    ExportNotebookOutputTypeDef,
    GetCalculationExecutionCodeRequestTypeDef,
    GetCalculationExecutionCodeResponseTypeDef,
    GetCalculationExecutionRequestTypeDef,
    GetCalculationExecutionResponseTypeDef,
    GetCalculationExecutionStatusRequestTypeDef,
    GetCalculationExecutionStatusResponseTypeDef,
    GetCapacityAssignmentConfigurationInputTypeDef,
    GetCapacityAssignmentConfigurationOutputTypeDef,
    GetCapacityReservationInputTypeDef,
    GetCapacityReservationOutputTypeDef,
    GetDataCatalogInputTypeDef,
    GetDataCatalogOutputTypeDef,
    GetDatabaseInputTypeDef,
    GetDatabaseOutputTypeDef,
    GetNamedQueryInputTypeDef,
    GetNamedQueryOutputTypeDef,
    GetNotebookMetadataInputTypeDef,
    GetNotebookMetadataOutputTypeDef,
    GetPreparedStatementInputTypeDef,
    GetPreparedStatementOutputTypeDef,
    GetQueryExecutionInputTypeDef,
    GetQueryExecutionOutputTypeDef,
    GetQueryResultsInputTypeDef,
    GetQueryResultsOutputTypeDef,
    GetQueryRuntimeStatisticsInputTypeDef,
    GetQueryRuntimeStatisticsOutputTypeDef,
    GetResourceDashboardRequestTypeDef,
    GetResourceDashboardResponseTypeDef,
    GetSessionEndpointRequestTypeDef,
    GetSessionEndpointResponseTypeDef,
    GetSessionRequestTypeDef,
    GetSessionResponseTypeDef,
    GetSessionStatusRequestTypeDef,
    GetSessionStatusResponseTypeDef,
    GetTableMetadataInputTypeDef,
    GetTableMetadataOutputTypeDef,
    GetWorkGroupInputTypeDef,
    GetWorkGroupOutputTypeDef,
    ImportNotebookInputTypeDef,
    ImportNotebookOutputTypeDef,
    ListApplicationDPUSizesInputTypeDef,
    ListApplicationDPUSizesOutputTypeDef,
    ListCalculationExecutionsRequestTypeDef,
    ListCalculationExecutionsResponseTypeDef,
    ListCapacityReservationsInputTypeDef,
    ListCapacityReservationsOutputTypeDef,
    ListDataCatalogsInputTypeDef,
    ListDataCatalogsOutputTypeDef,
    ListDatabasesInputTypeDef,
    ListDatabasesOutputTypeDef,
    ListEngineVersionsInputTypeDef,
    ListEngineVersionsOutputTypeDef,
    ListExecutorsRequestTypeDef,
    ListExecutorsResponseTypeDef,
    ListNamedQueriesInputTypeDef,
    ListNamedQueriesOutputTypeDef,
    ListNotebookMetadataInputTypeDef,
    ListNotebookMetadataOutputTypeDef,
    ListNotebookSessionsRequestTypeDef,
    ListNotebookSessionsResponseTypeDef,
    ListPreparedStatementsInputTypeDef,
    ListPreparedStatementsOutputTypeDef,
    ListQueryExecutionsInputTypeDef,
    ListQueryExecutionsOutputTypeDef,
    ListSessionsRequestTypeDef,
    ListSessionsResponseTypeDef,
    ListTableMetadataInputTypeDef,
    ListTableMetadataOutputTypeDef,
    ListTagsForResourceInputTypeDef,
    ListTagsForResourceOutputTypeDef,
    ListWorkGroupsInputTypeDef,
    ListWorkGroupsOutputTypeDef,
    PutCapacityAssignmentConfigurationInputTypeDef,
    StartCalculationExecutionRequestTypeDef,
    StartCalculationExecutionResponseTypeDef,
    StartQueryExecutionInputTypeDef,
    StartQueryExecutionOutputTypeDef,
    StartSessionRequestTypeDef,
    StartSessionResponseTypeDef,
    StopCalculationExecutionRequestTypeDef,
    StopCalculationExecutionResponseTypeDef,
    StopQueryExecutionInputTypeDef,
    TagResourceInputTypeDef,
    TerminateSessionRequestTypeDef,
    TerminateSessionResponseTypeDef,
    UntagResourceInputTypeDef,
    UpdateCapacityReservationInputTypeDef,
    UpdateDataCatalogInputTypeDef,
    UpdateNamedQueryInputTypeDef,
    UpdateNotebookInputTypeDef,
    UpdateNotebookMetadataInputTypeDef,
    UpdatePreparedStatementInputTypeDef,
    UpdateWorkGroupInputTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class AthenaClient(TypedClientBase):
    _service_name = ServiceName.ATHENA


    def batch_get_named_query(
        self, request: BatchGetNamedQueryInputTypeDef,
    ) -> BatchGetNamedQueryOutputTypeDef:
        return self._call(
            "batch_get_named_query",
            request,
            BatchGetNamedQueryOutputTypeDef,
        )


    def batch_get_prepared_statement(
        self, request: BatchGetPreparedStatementInputTypeDef,
    ) -> BatchGetPreparedStatementOutputTypeDef:
        return self._call(
            "batch_get_prepared_statement",
            request,
            BatchGetPreparedStatementOutputTypeDef,
        )


    def batch_get_query_execution(
        self, request: BatchGetQueryExecutionInputTypeDef,
    ) -> BatchGetQueryExecutionOutputTypeDef:
        return self._call(
            "batch_get_query_execution",
            request,
            BatchGetQueryExecutionOutputTypeDef,
        )


    def cancel_capacity_reservation(
        self, request: CancelCapacityReservationInputTypeDef,
    ) -> None:
        return self._call(
            "cancel_capacity_reservation",
            request,
            None,
        )


    def create_capacity_reservation(
        self, request: CreateCapacityReservationInputTypeDef,
    ) -> None:
        return self._call(
            "create_capacity_reservation",
            request,
            None,
        )


    def create_data_catalog(
        self, request: CreateDataCatalogInputTypeDef,
    ) -> CreateDataCatalogOutputTypeDef:
        return self._call(
            "create_data_catalog",
            request,
            CreateDataCatalogOutputTypeDef,
        )


    def create_named_query(
        self, request: CreateNamedQueryInputTypeDef,
    ) -> CreateNamedQueryOutputTypeDef:
        return self._call(
            "create_named_query",
            request,
            CreateNamedQueryOutputTypeDef,
        )


    def create_notebook(
        self, request: CreateNotebookInputTypeDef,
    ) -> CreateNotebookOutputTypeDef:
        return self._call(
            "create_notebook",
            request,
            CreateNotebookOutputTypeDef,
        )


    def create_prepared_statement(
        self, request: CreatePreparedStatementInputTypeDef,
    ) -> None:
        return self._call(
            "create_prepared_statement",
            request,
            None,
        )


    def create_presigned_notebook_url(
        self, request: CreatePresignedNotebookUrlRequestTypeDef,
    ) -> CreatePresignedNotebookUrlResponseTypeDef:
        return self._call(
            "create_presigned_notebook_url",
            request,
            CreatePresignedNotebookUrlResponseTypeDef,
        )


    def create_work_group(
        self, request: CreateWorkGroupInputTypeDef,
    ) -> None:
        return self._call(
            "create_work_group",
            request,
            None,
        )


    def delete_capacity_reservation(
        self, request: DeleteCapacityReservationInputTypeDef,
    ) -> None:
        return self._call(
            "delete_capacity_reservation",
            request,
            None,
        )


    def delete_data_catalog(
        self, request: DeleteDataCatalogInputTypeDef,
    ) -> DeleteDataCatalogOutputTypeDef:
        return self._call(
            "delete_data_catalog",
            request,
            DeleteDataCatalogOutputTypeDef,
        )


    def delete_named_query(
        self, request: DeleteNamedQueryInputTypeDef,
    ) -> None:
        return self._call(
            "delete_named_query",
            request,
            None,
        )


    def delete_notebook(
        self, request: DeleteNotebookInputTypeDef,
    ) -> None:
        return self._call(
            "delete_notebook",
            request,
            None,
        )


    def delete_prepared_statement(
        self, request: DeletePreparedStatementInputTypeDef,
    ) -> None:
        return self._call(
            "delete_prepared_statement",
            request,
            None,
        )


    def delete_work_group(
        self, request: DeleteWorkGroupInputTypeDef,
    ) -> None:
        return self._call(
            "delete_work_group",
            request,
            None,
        )


    def export_notebook(
        self, request: ExportNotebookInputTypeDef,
    ) -> ExportNotebookOutputTypeDef:
        return self._call(
            "export_notebook",
            request,
            ExportNotebookOutputTypeDef,
        )


    def get_calculation_execution(
        self, request: GetCalculationExecutionRequestTypeDef,
    ) -> GetCalculationExecutionResponseTypeDef:
        return self._call(
            "get_calculation_execution",
            request,
            GetCalculationExecutionResponseTypeDef,
        )


    def get_calculation_execution_code(
        self, request: GetCalculationExecutionCodeRequestTypeDef,
    ) -> GetCalculationExecutionCodeResponseTypeDef:
        return self._call(
            "get_calculation_execution_code",
            request,
            GetCalculationExecutionCodeResponseTypeDef,
        )


    def get_calculation_execution_status(
        self, request: GetCalculationExecutionStatusRequestTypeDef,
    ) -> GetCalculationExecutionStatusResponseTypeDef:
        return self._call(
            "get_calculation_execution_status",
            request,
            GetCalculationExecutionStatusResponseTypeDef,
        )


    def get_capacity_assignment_configuration(
        self, request: GetCapacityAssignmentConfigurationInputTypeDef,
    ) -> GetCapacityAssignmentConfigurationOutputTypeDef:
        return self._call(
            "get_capacity_assignment_configuration",
            request,
            GetCapacityAssignmentConfigurationOutputTypeDef,
        )


    def get_capacity_reservation(
        self, request: GetCapacityReservationInputTypeDef,
    ) -> GetCapacityReservationOutputTypeDef:
        return self._call(
            "get_capacity_reservation",
            request,
            GetCapacityReservationOutputTypeDef,
        )


    def get_data_catalog(
        self, request: GetDataCatalogInputTypeDef,
    ) -> GetDataCatalogOutputTypeDef:
        return self._call(
            "get_data_catalog",
            request,
            GetDataCatalogOutputTypeDef,
        )


    def get_database(
        self, request: GetDatabaseInputTypeDef,
    ) -> GetDatabaseOutputTypeDef:
        return self._call(
            "get_database",
            request,
            GetDatabaseOutputTypeDef,
        )


    def get_named_query(
        self, request: GetNamedQueryInputTypeDef,
    ) -> GetNamedQueryOutputTypeDef:
        return self._call(
            "get_named_query",
            request,
            GetNamedQueryOutputTypeDef,
        )


    def get_notebook_metadata(
        self, request: GetNotebookMetadataInputTypeDef,
    ) -> GetNotebookMetadataOutputTypeDef:
        return self._call(
            "get_notebook_metadata",
            request,
            GetNotebookMetadataOutputTypeDef,
        )


    def get_prepared_statement(
        self, request: GetPreparedStatementInputTypeDef,
    ) -> GetPreparedStatementOutputTypeDef:
        return self._call(
            "get_prepared_statement",
            request,
            GetPreparedStatementOutputTypeDef,
        )


    def get_query_execution(
        self, request: GetQueryExecutionInputTypeDef,
    ) -> GetQueryExecutionOutputTypeDef:
        return self._call(
            "get_query_execution",
            request,
            GetQueryExecutionOutputTypeDef,
        )


    def get_query_results(
        self, request: GetQueryResultsInputTypeDef,
    ) -> GetQueryResultsOutputTypeDef:
        return self._call(
            "get_query_results",
            request,
            GetQueryResultsOutputTypeDef,
        )


    def get_query_runtime_statistics(
        self, request: GetQueryRuntimeStatisticsInputTypeDef,
    ) -> GetQueryRuntimeStatisticsOutputTypeDef:
        return self._call(
            "get_query_runtime_statistics",
            request,
            GetQueryRuntimeStatisticsOutputTypeDef,
        )


    def get_resource_dashboard(
        self, request: GetResourceDashboardRequestTypeDef,
    ) -> GetResourceDashboardResponseTypeDef:
        return self._call(
            "get_resource_dashboard",
            request,
            GetResourceDashboardResponseTypeDef,
        )


    def get_session(
        self, request: GetSessionRequestTypeDef,
    ) -> GetSessionResponseTypeDef:
        return self._call(
            "get_session",
            request,
            GetSessionResponseTypeDef,
        )


    def get_session_endpoint(
        self, request: GetSessionEndpointRequestTypeDef,
    ) -> GetSessionEndpointResponseTypeDef:
        return self._call(
            "get_session_endpoint",
            request,
            GetSessionEndpointResponseTypeDef,
        )


    def get_session_status(
        self, request: GetSessionStatusRequestTypeDef,
    ) -> GetSessionStatusResponseTypeDef:
        return self._call(
            "get_session_status",
            request,
            GetSessionStatusResponseTypeDef,
        )


    def get_table_metadata(
        self, request: GetTableMetadataInputTypeDef,
    ) -> GetTableMetadataOutputTypeDef:
        return self._call(
            "get_table_metadata",
            request,
            GetTableMetadataOutputTypeDef,
        )


    def get_work_group(
        self, request: GetWorkGroupInputTypeDef,
    ) -> GetWorkGroupOutputTypeDef:
        return self._call(
            "get_work_group",
            request,
            GetWorkGroupOutputTypeDef,
        )


    def import_notebook(
        self, request: ImportNotebookInputTypeDef,
    ) -> ImportNotebookOutputTypeDef:
        return self._call(
            "import_notebook",
            request,
            ImportNotebookOutputTypeDef,
        )


    def list_application_dpu_sizes(
        self, request: ListApplicationDPUSizesInputTypeDef,
    ) -> ListApplicationDPUSizesOutputTypeDef:
        return self._call(
            "list_application_dpu_sizes",
            request,
            ListApplicationDPUSizesOutputTypeDef,
        )


    def list_calculation_executions(
        self, request: ListCalculationExecutionsRequestTypeDef,
    ) -> ListCalculationExecutionsResponseTypeDef:
        return self._call(
            "list_calculation_executions",
            request,
            ListCalculationExecutionsResponseTypeDef,
        )


    def list_capacity_reservations(
        self, request: ListCapacityReservationsInputTypeDef,
    ) -> ListCapacityReservationsOutputTypeDef:
        return self._call(
            "list_capacity_reservations",
            request,
            ListCapacityReservationsOutputTypeDef,
        )


    def list_data_catalogs(
        self, request: ListDataCatalogsInputTypeDef,
    ) -> ListDataCatalogsOutputTypeDef:
        return self._call(
            "list_data_catalogs",
            request,
            ListDataCatalogsOutputTypeDef,
        )


    def list_databases(
        self, request: ListDatabasesInputTypeDef,
    ) -> ListDatabasesOutputTypeDef:
        return self._call(
            "list_databases",
            request,
            ListDatabasesOutputTypeDef,
        )


    def list_engine_versions(
        self, request: ListEngineVersionsInputTypeDef,
    ) -> ListEngineVersionsOutputTypeDef:
        return self._call(
            "list_engine_versions",
            request,
            ListEngineVersionsOutputTypeDef,
        )


    def list_executors(
        self, request: ListExecutorsRequestTypeDef,
    ) -> ListExecutorsResponseTypeDef:
        return self._call(
            "list_executors",
            request,
            ListExecutorsResponseTypeDef,
        )


    def list_named_queries(
        self, request: ListNamedQueriesInputTypeDef,
    ) -> ListNamedQueriesOutputTypeDef:
        return self._call(
            "list_named_queries",
            request,
            ListNamedQueriesOutputTypeDef,
        )


    def list_notebook_metadata(
        self, request: ListNotebookMetadataInputTypeDef,
    ) -> ListNotebookMetadataOutputTypeDef:
        return self._call(
            "list_notebook_metadata",
            request,
            ListNotebookMetadataOutputTypeDef,
        )


    def list_notebook_sessions(
        self, request: ListNotebookSessionsRequestTypeDef,
    ) -> ListNotebookSessionsResponseTypeDef:
        return self._call(
            "list_notebook_sessions",
            request,
            ListNotebookSessionsResponseTypeDef,
        )


    def list_prepared_statements(
        self, request: ListPreparedStatementsInputTypeDef,
    ) -> ListPreparedStatementsOutputTypeDef:
        return self._call(
            "list_prepared_statements",
            request,
            ListPreparedStatementsOutputTypeDef,
        )


    def list_query_executions(
        self, request: ListQueryExecutionsInputTypeDef,
    ) -> ListQueryExecutionsOutputTypeDef:
        return self._call(
            "list_query_executions",
            request,
            ListQueryExecutionsOutputTypeDef,
        )


    def list_sessions(
        self, request: ListSessionsRequestTypeDef,
    ) -> ListSessionsResponseTypeDef:
        return self._call(
            "list_sessions",
            request,
            ListSessionsResponseTypeDef,
        )


    def list_table_metadata(
        self, request: ListTableMetadataInputTypeDef,
    ) -> ListTableMetadataOutputTypeDef:
        return self._call(
            "list_table_metadata",
            request,
            ListTableMetadataOutputTypeDef,
        )


    def list_tags_for_resource(
        self, request: ListTagsForResourceInputTypeDef,
    ) -> ListTagsForResourceOutputTypeDef:
        return self._call(
            "list_tags_for_resource",
            request,
            ListTagsForResourceOutputTypeDef,
        )


    def list_work_groups(
        self, request: ListWorkGroupsInputTypeDef,
    ) -> ListWorkGroupsOutputTypeDef:
        return self._call(
            "list_work_groups",
            request,
            ListWorkGroupsOutputTypeDef,
        )


    def put_capacity_assignment_configuration(
        self, request: PutCapacityAssignmentConfigurationInputTypeDef,
    ) -> None:
        return self._call(
            "put_capacity_assignment_configuration",
            request,
            None,
        )


    def start_calculation_execution(
        self, request: StartCalculationExecutionRequestTypeDef,
    ) -> StartCalculationExecutionResponseTypeDef:
        return self._call(
            "start_calculation_execution",
            request,
            StartCalculationExecutionResponseTypeDef,
        )


    def start_query_execution(
        self, request: StartQueryExecutionInputTypeDef,
    ) -> StartQueryExecutionOutputTypeDef:
        return self._call(
            "start_query_execution",
            request,
            StartQueryExecutionOutputTypeDef,
        )


    def start_session(
        self, request: StartSessionRequestTypeDef,
    ) -> StartSessionResponseTypeDef:
        return self._call(
            "start_session",
            request,
            StartSessionResponseTypeDef,
        )


    def stop_calculation_execution(
        self, request: StopCalculationExecutionRequestTypeDef,
    ) -> StopCalculationExecutionResponseTypeDef:
        return self._call(
            "stop_calculation_execution",
            request,
            StopCalculationExecutionResponseTypeDef,
        )


    def stop_query_execution(
        self, request: StopQueryExecutionInputTypeDef,
    ) -> None:
        return self._call(
            "stop_query_execution",
            request,
            None,
        )


    def tag_resource(
        self, request: TagResourceInputTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def terminate_session(
        self, request: TerminateSessionRequestTypeDef,
    ) -> TerminateSessionResponseTypeDef:
        return self._call(
            "terminate_session",
            request,
            TerminateSessionResponseTypeDef,
        )


    def untag_resource(
        self, request: UntagResourceInputTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_capacity_reservation(
        self, request: UpdateCapacityReservationInputTypeDef,
    ) -> None:
        return self._call(
            "update_capacity_reservation",
            request,
            None,
        )


    def update_data_catalog(
        self, request: UpdateDataCatalogInputTypeDef,
    ) -> None:
        return self._call(
            "update_data_catalog",
            request,
            None,
        )


    def update_named_query(
        self, request: UpdateNamedQueryInputTypeDef,
    ) -> None:
        return self._call(
            "update_named_query",
            request,
            None,
        )


    def update_notebook(
        self, request: UpdateNotebookInputTypeDef,
    ) -> None:
        return self._call(
            "update_notebook",
            request,
            None,
        )


    def update_notebook_metadata(
        self, request: UpdateNotebookMetadataInputTypeDef,
    ) -> None:
        return self._call(
            "update_notebook_metadata",
            request,
            None,
        )


    def update_prepared_statement(
        self, request: UpdatePreparedStatementInputTypeDef,
    ) -> None:
        return self._call(
            "update_prepared_statement",
            request,
            None,
        )


    def update_work_group(
        self, request: UpdateWorkGroupInputTypeDef,
    ) -> None:
        return self._call(
            "update_work_group",
            request,
            None,
        )

