# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.bedrock.bedrock_classes import (
    BatchDeleteEvaluationJobRequestTypeDef,
    BatchDeleteEvaluationJobResponseTypeDef,
    CancelAutomatedReasoningPolicyBuildWorkflowRequestTypeDef,
    CreateAutomatedReasoningPolicyRequestTypeDef,
    CreateAutomatedReasoningPolicyResponseTypeDef,
    CreateAutomatedReasoningPolicyTestCaseRequestTypeDef,
    CreateAutomatedReasoningPolicyTestCaseResponseTypeDef,
    CreateAutomatedReasoningPolicyVersionRequestTypeDef,
    CreateAutomatedReasoningPolicyVersionResponseTypeDef,
    CreateCustomModelDeploymentRequestTypeDef,
    CreateCustomModelDeploymentResponseTypeDef,
    CreateCustomModelRequestTypeDef,
    CreateCustomModelResponseTypeDef,
    CreateEvaluationJobRequestTypeDef,
    CreateEvaluationJobResponseTypeDef,
    CreateFoundationModelAgreementRequestTypeDef,
    CreateFoundationModelAgreementResponseTypeDef,
    CreateGuardrailRequestTypeDef,
    CreateGuardrailResponseTypeDef,
    CreateGuardrailVersionRequestTypeDef,
    CreateGuardrailVersionResponseTypeDef,
    CreateInferenceProfileRequestTypeDef,
    CreateInferenceProfileResponseTypeDef,
    CreateMarketplaceModelEndpointRequestTypeDef,
    CreateMarketplaceModelEndpointResponseTypeDef,
    CreateModelCopyJobRequestTypeDef,
    CreateModelCopyJobResponseTypeDef,
    CreateModelCustomizationJobRequestTypeDef,
    CreateModelCustomizationJobResponseTypeDef,
    CreateModelImportJobRequestTypeDef,
    CreateModelImportJobResponseTypeDef,
    CreateModelInvocationJobRequestTypeDef,
    CreateModelInvocationJobResponseTypeDef,
    CreatePromptRouterRequestTypeDef,
    CreatePromptRouterResponseTypeDef,
    CreateProvisionedModelThroughputRequestTypeDef,
    CreateProvisionedModelThroughputResponseTypeDef,
    DeleteAutomatedReasoningPolicyBuildWorkflowRequestTypeDef,
    DeleteAutomatedReasoningPolicyRequestTypeDef,
    DeleteAutomatedReasoningPolicyTestCaseRequestTypeDef,
    DeleteCustomModelDeploymentRequestTypeDef,
    DeleteCustomModelRequestTypeDef,
    DeleteEnforcedGuardrailConfigurationRequestTypeDef,
    DeleteFoundationModelAgreementRequestTypeDef,
    DeleteGuardrailRequestTypeDef,
    DeleteImportedModelRequestTypeDef,
    DeleteInferenceProfileRequestTypeDef,
    DeleteMarketplaceModelEndpointRequestTypeDef,
    DeletePromptRouterRequestTypeDef,
    DeleteProvisionedModelThroughputRequestTypeDef,
    DeleteResourcePolicyRequestTypeDef,
    DeregisterMarketplaceModelEndpointRequestTypeDef,
    ExportAutomatedReasoningPolicyVersionRequestTypeDef,
    ExportAutomatedReasoningPolicyVersionResponseTypeDef,
    GetAutomatedReasoningPolicyAnnotationsRequestTypeDef,
    GetAutomatedReasoningPolicyAnnotationsResponseTypeDef,
    GetAutomatedReasoningPolicyBuildWorkflowRequestTypeDef,
    GetAutomatedReasoningPolicyBuildWorkflowResponseTypeDef,
    GetAutomatedReasoningPolicyBuildWorkflowResultAssetsRequestTypeDef,
    GetAutomatedReasoningPolicyBuildWorkflowResultAssetsResponseTypeDef,
    GetAutomatedReasoningPolicyNextScenarioRequestTypeDef,
    GetAutomatedReasoningPolicyNextScenarioResponseTypeDef,
    GetAutomatedReasoningPolicyRequestTypeDef,
    GetAutomatedReasoningPolicyResponseTypeDef,
    GetAutomatedReasoningPolicyTestCaseRequestTypeDef,
    GetAutomatedReasoningPolicyTestCaseResponseTypeDef,
    GetAutomatedReasoningPolicyTestResultRequestTypeDef,
    GetAutomatedReasoningPolicyTestResultResponseTypeDef,
    GetCustomModelDeploymentRequestTypeDef,
    GetCustomModelDeploymentResponseTypeDef,
    GetCustomModelRequestTypeDef,
    GetCustomModelResponseTypeDef,
    GetEvaluationJobRequestTypeDef,
    GetEvaluationJobResponseTypeDef,
    GetFoundationModelAvailabilityRequestTypeDef,
    GetFoundationModelAvailabilityResponseTypeDef,
    GetFoundationModelRequestTypeDef,
    GetFoundationModelResponseTypeDef,
    GetGuardrailRequestTypeDef,
    GetGuardrailResponseTypeDef,
    GetImportedModelRequestTypeDef,
    GetImportedModelResponseTypeDef,
    GetInferenceProfileRequestTypeDef,
    GetInferenceProfileResponseTypeDef,
    GetMarketplaceModelEndpointRequestTypeDef,
    GetMarketplaceModelEndpointResponseTypeDef,
    GetModelCopyJobRequestTypeDef,
    GetModelCopyJobResponseTypeDef,
    GetModelCustomizationJobRequestTypeDef,
    GetModelCustomizationJobResponseTypeDef,
    GetModelImportJobRequestTypeDef,
    GetModelImportJobResponseTypeDef,
    GetModelInvocationJobRequestTypeDef,
    GetModelInvocationJobResponseTypeDef,
    GetModelInvocationLoggingConfigurationResponseTypeDef,
    GetPromptRouterRequestTypeDef,
    GetPromptRouterResponseTypeDef,
    GetProvisionedModelThroughputRequestTypeDef,
    GetProvisionedModelThroughputResponseTypeDef,
    GetResourcePolicyRequestTypeDef,
    GetResourcePolicyResponseTypeDef,
    GetUseCaseForModelAccessResponseTypeDef,
    ListAutomatedReasoningPoliciesRequestTypeDef,
    ListAutomatedReasoningPoliciesResponseTypeDef,
    ListAutomatedReasoningPolicyBuildWorkflowsRequestTypeDef,
    ListAutomatedReasoningPolicyBuildWorkflowsResponseTypeDef,
    ListAutomatedReasoningPolicyTestCasesRequestTypeDef,
    ListAutomatedReasoningPolicyTestCasesResponseTypeDef,
    ListAutomatedReasoningPolicyTestResultsRequestTypeDef,
    ListAutomatedReasoningPolicyTestResultsResponseTypeDef,
    ListCustomModelDeploymentsRequestTypeDef,
    ListCustomModelDeploymentsResponseTypeDef,
    ListCustomModelsRequestTypeDef,
    ListCustomModelsResponseTypeDef,
    ListEnforcedGuardrailsConfigurationRequestTypeDef,
    ListEnforcedGuardrailsConfigurationResponseTypeDef,
    ListEvaluationJobsRequestTypeDef,
    ListEvaluationJobsResponseTypeDef,
    ListFoundationModelAgreementOffersRequestTypeDef,
    ListFoundationModelAgreementOffersResponseTypeDef,
    ListFoundationModelsRequestTypeDef,
    ListFoundationModelsResponseTypeDef,
    ListGuardrailsRequestTypeDef,
    ListGuardrailsResponseTypeDef,
    ListImportedModelsRequestTypeDef,
    ListImportedModelsResponseTypeDef,
    ListInferenceProfilesRequestTypeDef,
    ListInferenceProfilesResponseTypeDef,
    ListMarketplaceModelEndpointsRequestTypeDef,
    ListMarketplaceModelEndpointsResponseTypeDef,
    ListModelCopyJobsRequestTypeDef,
    ListModelCopyJobsResponseTypeDef,
    ListModelCustomizationJobsRequestTypeDef,
    ListModelCustomizationJobsResponseTypeDef,
    ListModelImportJobsRequestTypeDef,
    ListModelImportJobsResponseTypeDef,
    ListModelInvocationJobsRequestTypeDef,
    ListModelInvocationJobsResponseTypeDef,
    ListPromptRoutersRequestTypeDef,
    ListPromptRoutersResponseTypeDef,
    ListProvisionedModelThroughputsRequestTypeDef,
    ListProvisionedModelThroughputsResponseTypeDef,
    ListTagsForResourceRequestTypeDef,
    ListTagsForResourceResponseTypeDef,
    PutEnforcedGuardrailConfigurationRequestTypeDef,
    PutEnforcedGuardrailConfigurationResponseTypeDef,
    PutModelInvocationLoggingConfigurationRequestTypeDef,
    PutResourcePolicyRequestTypeDef,
    PutResourcePolicyResponseTypeDef,
    PutUseCaseForModelAccessRequestTypeDef,
    RegisterMarketplaceModelEndpointRequestTypeDef,
    RegisterMarketplaceModelEndpointResponseTypeDef,
    StartAutomatedReasoningPolicyBuildWorkflowRequestTypeDef,
    StartAutomatedReasoningPolicyBuildWorkflowResponseTypeDef,
    StartAutomatedReasoningPolicyTestWorkflowRequestTypeDef,
    StartAutomatedReasoningPolicyTestWorkflowResponseTypeDef,
    StopEvaluationJobRequestTypeDef,
    StopModelCustomizationJobRequestTypeDef,
    StopModelInvocationJobRequestTypeDef,
    TagResourceRequestTypeDef,
    UntagResourceRequestTypeDef,
    UpdateAutomatedReasoningPolicyAnnotationsRequestTypeDef,
    UpdateAutomatedReasoningPolicyAnnotationsResponseTypeDef,
    UpdateAutomatedReasoningPolicyRequestTypeDef,
    UpdateAutomatedReasoningPolicyResponseTypeDef,
    UpdateAutomatedReasoningPolicyTestCaseRequestTypeDef,
    UpdateAutomatedReasoningPolicyTestCaseResponseTypeDef,
    UpdateCustomModelDeploymentRequestTypeDef,
    UpdateCustomModelDeploymentResponseTypeDef,
    UpdateGuardrailRequestTypeDef,
    UpdateGuardrailResponseTypeDef,
    UpdateMarketplaceModelEndpointRequestTypeDef,
    UpdateMarketplaceModelEndpointResponseTypeDef,
    UpdateProvisionedModelThroughputRequestTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class BedrockClient(TypedClientBase):
    _service_name = ServiceName.BEDROCK


    def batch_delete_advanced_prompt_optimization_job(
        self,
    ) -> None:
        return self._call(
            "batch_delete_advanced_prompt_optimization_job",
            None,
            None,
        )


    def batch_delete_evaluation_job(
        self, request: BatchDeleteEvaluationJobRequestTypeDef,
    ) -> BatchDeleteEvaluationJobResponseTypeDef:
        return self._call(
            "batch_delete_evaluation_job",
            request,
            BatchDeleteEvaluationJobResponseTypeDef,
        )


    def cancel_automated_reasoning_policy_build_workflow(
        self, request: CancelAutomatedReasoningPolicyBuildWorkflowRequestTypeDef,
    ) -> None:
        return self._call(
            "cancel_automated_reasoning_policy_build_workflow",
            request,
            None,
        )


    def create_advanced_prompt_optimization_job(
        self,
    ) -> None:
        return self._call(
            "create_advanced_prompt_optimization_job",
            None,
            None,
        )


    def create_automated_reasoning_policy(
        self, request: CreateAutomatedReasoningPolicyRequestTypeDef,
    ) -> CreateAutomatedReasoningPolicyResponseTypeDef:
        return self._call(
            "create_automated_reasoning_policy",
            request,
            CreateAutomatedReasoningPolicyResponseTypeDef,
        )


    def create_automated_reasoning_policy_test_case(
        self, request: CreateAutomatedReasoningPolicyTestCaseRequestTypeDef,
    ) -> CreateAutomatedReasoningPolicyTestCaseResponseTypeDef:
        return self._call(
            "create_automated_reasoning_policy_test_case",
            request,
            CreateAutomatedReasoningPolicyTestCaseResponseTypeDef,
        )


    def create_automated_reasoning_policy_version(
        self, request: CreateAutomatedReasoningPolicyVersionRequestTypeDef,
    ) -> CreateAutomatedReasoningPolicyVersionResponseTypeDef:
        return self._call(
            "create_automated_reasoning_policy_version",
            request,
            CreateAutomatedReasoningPolicyVersionResponseTypeDef,
        )


    def create_custom_model(
        self, request: CreateCustomModelRequestTypeDef,
    ) -> CreateCustomModelResponseTypeDef:
        return self._call(
            "create_custom_model",
            request,
            CreateCustomModelResponseTypeDef,
        )


    def create_custom_model_deployment(
        self, request: CreateCustomModelDeploymentRequestTypeDef,
    ) -> CreateCustomModelDeploymentResponseTypeDef:
        return self._call(
            "create_custom_model_deployment",
            request,
            CreateCustomModelDeploymentResponseTypeDef,
        )


    def create_evaluation_job(
        self, request: CreateEvaluationJobRequestTypeDef,
    ) -> CreateEvaluationJobResponseTypeDef:
        return self._call(
            "create_evaluation_job",
            request,
            CreateEvaluationJobResponseTypeDef,
        )


    def create_foundation_model_agreement(
        self, request: CreateFoundationModelAgreementRequestTypeDef,
    ) -> CreateFoundationModelAgreementResponseTypeDef:
        return self._call(
            "create_foundation_model_agreement",
            request,
            CreateFoundationModelAgreementResponseTypeDef,
        )


    def create_guardrail(
        self, request: CreateGuardrailRequestTypeDef,
    ) -> CreateGuardrailResponseTypeDef:
        return self._call(
            "create_guardrail",
            request,
            CreateGuardrailResponseTypeDef,
        )


    def create_guardrail_version(
        self, request: CreateGuardrailVersionRequestTypeDef,
    ) -> CreateGuardrailVersionResponseTypeDef:
        return self._call(
            "create_guardrail_version",
            request,
            CreateGuardrailVersionResponseTypeDef,
        )


    def create_inference_profile(
        self, request: CreateInferenceProfileRequestTypeDef,
    ) -> CreateInferenceProfileResponseTypeDef:
        return self._call(
            "create_inference_profile",
            request,
            CreateInferenceProfileResponseTypeDef,
        )


    def create_marketplace_model_endpoint(
        self, request: CreateMarketplaceModelEndpointRequestTypeDef,
    ) -> CreateMarketplaceModelEndpointResponseTypeDef:
        return self._call(
            "create_marketplace_model_endpoint",
            request,
            CreateMarketplaceModelEndpointResponseTypeDef,
        )


    def create_model_copy_job(
        self, request: CreateModelCopyJobRequestTypeDef,
    ) -> CreateModelCopyJobResponseTypeDef:
        return self._call(
            "create_model_copy_job",
            request,
            CreateModelCopyJobResponseTypeDef,
        )


    def create_model_customization_job(
        self, request: CreateModelCustomizationJobRequestTypeDef,
    ) -> CreateModelCustomizationJobResponseTypeDef:
        return self._call(
            "create_model_customization_job",
            request,
            CreateModelCustomizationJobResponseTypeDef,
        )


    def create_model_import_job(
        self, request: CreateModelImportJobRequestTypeDef,
    ) -> CreateModelImportJobResponseTypeDef:
        return self._call(
            "create_model_import_job",
            request,
            CreateModelImportJobResponseTypeDef,
        )


    def create_model_invocation_job(
        self, request: CreateModelInvocationJobRequestTypeDef,
    ) -> CreateModelInvocationJobResponseTypeDef:
        return self._call(
            "create_model_invocation_job",
            request,
            CreateModelInvocationJobResponseTypeDef,
        )


    def create_prompt_router(
        self, request: CreatePromptRouterRequestTypeDef,
    ) -> CreatePromptRouterResponseTypeDef:
        return self._call(
            "create_prompt_router",
            request,
            CreatePromptRouterResponseTypeDef,
        )


    def create_provisioned_model_throughput(
        self, request: CreateProvisionedModelThroughputRequestTypeDef,
    ) -> CreateProvisionedModelThroughputResponseTypeDef:
        return self._call(
            "create_provisioned_model_throughput",
            request,
            CreateProvisionedModelThroughputResponseTypeDef,
        )


    def delete_automated_reasoning_policy(
        self, request: DeleteAutomatedReasoningPolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_automated_reasoning_policy",
            request,
            None,
        )


    def delete_automated_reasoning_policy_build_workflow(
        self, request: DeleteAutomatedReasoningPolicyBuildWorkflowRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_automated_reasoning_policy_build_workflow",
            request,
            None,
        )


    def delete_automated_reasoning_policy_test_case(
        self, request: DeleteAutomatedReasoningPolicyTestCaseRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_automated_reasoning_policy_test_case",
            request,
            None,
        )


    def delete_custom_model(
        self, request: DeleteCustomModelRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_custom_model",
            request,
            None,
        )


    def delete_custom_model_deployment(
        self, request: DeleteCustomModelDeploymentRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_custom_model_deployment",
            request,
            None,
        )


    def delete_enforced_guardrail_configuration(
        self, request: DeleteEnforcedGuardrailConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_enforced_guardrail_configuration",
            request,
            None,
        )


    def delete_foundation_model_agreement(
        self, request: DeleteFoundationModelAgreementRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_foundation_model_agreement",
            request,
            None,
        )


    def delete_guardrail(
        self, request: DeleteGuardrailRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_guardrail",
            request,
            None,
        )


    def delete_imported_model(
        self, request: DeleteImportedModelRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_imported_model",
            request,
            None,
        )


    def delete_inference_profile(
        self, request: DeleteInferenceProfileRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_inference_profile",
            request,
            None,
        )


    def delete_marketplace_model_endpoint(
        self, request: DeleteMarketplaceModelEndpointRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_marketplace_model_endpoint",
            request,
            None,
        )


    def delete_model_invocation_logging_configuration(
        self,
    ) -> None:
        return self._call(
            "delete_model_invocation_logging_configuration",
            None,
            None,
        )


    def delete_prompt_router(
        self, request: DeletePromptRouterRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_prompt_router",
            request,
            None,
        )


    def delete_provisioned_model_throughput(
        self, request: DeleteProvisionedModelThroughputRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_provisioned_model_throughput",
            request,
            None,
        )


    def delete_resource_policy(
        self, request: DeleteResourcePolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_resource_policy",
            request,
            None,
        )


    def deregister_marketplace_model_endpoint(
        self, request: DeregisterMarketplaceModelEndpointRequestTypeDef,
    ) -> None:
        return self._call(
            "deregister_marketplace_model_endpoint",
            request,
            None,
        )


    def export_automated_reasoning_policy_version(
        self, request: ExportAutomatedReasoningPolicyVersionRequestTypeDef,
    ) -> ExportAutomatedReasoningPolicyVersionResponseTypeDef:
        return self._call(
            "export_automated_reasoning_policy_version",
            request,
            ExportAutomatedReasoningPolicyVersionResponseTypeDef,
        )


    def get_advanced_prompt_optimization_job(
        self,
    ) -> None:
        return self._call(
            "get_advanced_prompt_optimization_job",
            None,
            None,
        )


    def get_automated_reasoning_policy(
        self, request: GetAutomatedReasoningPolicyRequestTypeDef,
    ) -> GetAutomatedReasoningPolicyResponseTypeDef:
        return self._call(
            "get_automated_reasoning_policy",
            request,
            GetAutomatedReasoningPolicyResponseTypeDef,
        )


    def get_automated_reasoning_policy_annotations(
        self, request: GetAutomatedReasoningPolicyAnnotationsRequestTypeDef,
    ) -> GetAutomatedReasoningPolicyAnnotationsResponseTypeDef:
        return self._call(
            "get_automated_reasoning_policy_annotations",
            request,
            GetAutomatedReasoningPolicyAnnotationsResponseTypeDef,
        )


    def get_automated_reasoning_policy_build_workflow(
        self, request: GetAutomatedReasoningPolicyBuildWorkflowRequestTypeDef,
    ) -> GetAutomatedReasoningPolicyBuildWorkflowResponseTypeDef:
        return self._call(
            "get_automated_reasoning_policy_build_workflow",
            request,
            GetAutomatedReasoningPolicyBuildWorkflowResponseTypeDef,
        )


    def get_automated_reasoning_policy_build_workflow_result_assets(
        self, request: GetAutomatedReasoningPolicyBuildWorkflowResultAssetsRequestTypeDef,
    ) -> GetAutomatedReasoningPolicyBuildWorkflowResultAssetsResponseTypeDef:
        return self._call(
            "get_automated_reasoning_policy_build_workflow_result_assets",
            request,
            GetAutomatedReasoningPolicyBuildWorkflowResultAssetsResponseTypeDef,
        )


    def get_automated_reasoning_policy_next_scenario(
        self, request: GetAutomatedReasoningPolicyNextScenarioRequestTypeDef,
    ) -> GetAutomatedReasoningPolicyNextScenarioResponseTypeDef:
        return self._call(
            "get_automated_reasoning_policy_next_scenario",
            request,
            GetAutomatedReasoningPolicyNextScenarioResponseTypeDef,
        )


    def get_automated_reasoning_policy_test_case(
        self, request: GetAutomatedReasoningPolicyTestCaseRequestTypeDef,
    ) -> GetAutomatedReasoningPolicyTestCaseResponseTypeDef:
        return self._call(
            "get_automated_reasoning_policy_test_case",
            request,
            GetAutomatedReasoningPolicyTestCaseResponseTypeDef,
        )


    def get_automated_reasoning_policy_test_result(
        self, request: GetAutomatedReasoningPolicyTestResultRequestTypeDef,
    ) -> GetAutomatedReasoningPolicyTestResultResponseTypeDef:
        return self._call(
            "get_automated_reasoning_policy_test_result",
            request,
            GetAutomatedReasoningPolicyTestResultResponseTypeDef,
        )


    def get_custom_model(
        self, request: GetCustomModelRequestTypeDef,
    ) -> GetCustomModelResponseTypeDef:
        return self._call(
            "get_custom_model",
            request,
            GetCustomModelResponseTypeDef,
        )


    def get_custom_model_deployment(
        self, request: GetCustomModelDeploymentRequestTypeDef,
    ) -> GetCustomModelDeploymentResponseTypeDef:
        return self._call(
            "get_custom_model_deployment",
            request,
            GetCustomModelDeploymentResponseTypeDef,
        )


    def get_evaluation_job(
        self, request: GetEvaluationJobRequestTypeDef,
    ) -> GetEvaluationJobResponseTypeDef:
        return self._call(
            "get_evaluation_job",
            request,
            GetEvaluationJobResponseTypeDef,
        )


    def get_foundation_model(
        self, request: GetFoundationModelRequestTypeDef,
    ) -> GetFoundationModelResponseTypeDef:
        return self._call(
            "get_foundation_model",
            request,
            GetFoundationModelResponseTypeDef,
        )


    def get_foundation_model_availability(
        self, request: GetFoundationModelAvailabilityRequestTypeDef,
    ) -> GetFoundationModelAvailabilityResponseTypeDef:
        return self._call(
            "get_foundation_model_availability",
            request,
            GetFoundationModelAvailabilityResponseTypeDef,
        )


    def get_guardrail(
        self, request: GetGuardrailRequestTypeDef,
    ) -> GetGuardrailResponseTypeDef:
        return self._call(
            "get_guardrail",
            request,
            GetGuardrailResponseTypeDef,
        )


    def get_imported_model(
        self, request: GetImportedModelRequestTypeDef,
    ) -> GetImportedModelResponseTypeDef:
        return self._call(
            "get_imported_model",
            request,
            GetImportedModelResponseTypeDef,
        )


    def get_inference_profile(
        self, request: GetInferenceProfileRequestTypeDef,
    ) -> GetInferenceProfileResponseTypeDef:
        return self._call(
            "get_inference_profile",
            request,
            GetInferenceProfileResponseTypeDef,
        )


    def get_marketplace_model_endpoint(
        self, request: GetMarketplaceModelEndpointRequestTypeDef,
    ) -> GetMarketplaceModelEndpointResponseTypeDef:
        return self._call(
            "get_marketplace_model_endpoint",
            request,
            GetMarketplaceModelEndpointResponseTypeDef,
        )


    def get_model_copy_job(
        self, request: GetModelCopyJobRequestTypeDef,
    ) -> GetModelCopyJobResponseTypeDef:
        return self._call(
            "get_model_copy_job",
            request,
            GetModelCopyJobResponseTypeDef,
        )


    def get_model_customization_job(
        self, request: GetModelCustomizationJobRequestTypeDef,
    ) -> GetModelCustomizationJobResponseTypeDef:
        return self._call(
            "get_model_customization_job",
            request,
            GetModelCustomizationJobResponseTypeDef,
        )


    def get_model_import_job(
        self, request: GetModelImportJobRequestTypeDef,
    ) -> GetModelImportJobResponseTypeDef:
        return self._call(
            "get_model_import_job",
            request,
            GetModelImportJobResponseTypeDef,
        )


    def get_model_invocation_job(
        self, request: GetModelInvocationJobRequestTypeDef,
    ) -> GetModelInvocationJobResponseTypeDef:
        return self._call(
            "get_model_invocation_job",
            request,
            GetModelInvocationJobResponseTypeDef,
        )


    def get_model_invocation_logging_configuration(
        self,
    ) -> GetModelInvocationLoggingConfigurationResponseTypeDef:
        return self._call(
            "get_model_invocation_logging_configuration",
            None,
            GetModelInvocationLoggingConfigurationResponseTypeDef,
        )


    def get_prompt_router(
        self, request: GetPromptRouterRequestTypeDef,
    ) -> GetPromptRouterResponseTypeDef:
        return self._call(
            "get_prompt_router",
            request,
            GetPromptRouterResponseTypeDef,
        )


    def get_provisioned_model_throughput(
        self, request: GetProvisionedModelThroughputRequestTypeDef,
    ) -> GetProvisionedModelThroughputResponseTypeDef:
        return self._call(
            "get_provisioned_model_throughput",
            request,
            GetProvisionedModelThroughputResponseTypeDef,
        )


    def get_resource_policy(
        self, request: GetResourcePolicyRequestTypeDef,
    ) -> GetResourcePolicyResponseTypeDef:
        return self._call(
            "get_resource_policy",
            request,
            GetResourcePolicyResponseTypeDef,
        )


    def get_use_case_for_model_access(
        self,
    ) -> GetUseCaseForModelAccessResponseTypeDef:
        return self._call(
            "get_use_case_for_model_access",
            None,
            GetUseCaseForModelAccessResponseTypeDef,
        )


    def list_advanced_prompt_optimization_jobs(
        self,
    ) -> None:
        return self._call(
            "list_advanced_prompt_optimization_jobs",
            None,
            None,
        )


    def list_automated_reasoning_policies(
        self, request: ListAutomatedReasoningPoliciesRequestTypeDef,
    ) -> ListAutomatedReasoningPoliciesResponseTypeDef:
        return self._call(
            "list_automated_reasoning_policies",
            request,
            ListAutomatedReasoningPoliciesResponseTypeDef,
        )


    def list_automated_reasoning_policy_build_workflows(
        self, request: ListAutomatedReasoningPolicyBuildWorkflowsRequestTypeDef,
    ) -> ListAutomatedReasoningPolicyBuildWorkflowsResponseTypeDef:
        return self._call(
            "list_automated_reasoning_policy_build_workflows",
            request,
            ListAutomatedReasoningPolicyBuildWorkflowsResponseTypeDef,
        )


    def list_automated_reasoning_policy_test_cases(
        self, request: ListAutomatedReasoningPolicyTestCasesRequestTypeDef,
    ) -> ListAutomatedReasoningPolicyTestCasesResponseTypeDef:
        return self._call(
            "list_automated_reasoning_policy_test_cases",
            request,
            ListAutomatedReasoningPolicyTestCasesResponseTypeDef,
        )


    def list_automated_reasoning_policy_test_results(
        self, request: ListAutomatedReasoningPolicyTestResultsRequestTypeDef,
    ) -> ListAutomatedReasoningPolicyTestResultsResponseTypeDef:
        return self._call(
            "list_automated_reasoning_policy_test_results",
            request,
            ListAutomatedReasoningPolicyTestResultsResponseTypeDef,
        )


    def list_custom_model_deployments(
        self, request: ListCustomModelDeploymentsRequestTypeDef,
    ) -> ListCustomModelDeploymentsResponseTypeDef:
        return self._call(
            "list_custom_model_deployments",
            request,
            ListCustomModelDeploymentsResponseTypeDef,
        )


    def list_custom_models(
        self, request: ListCustomModelsRequestTypeDef,
    ) -> ListCustomModelsResponseTypeDef:
        return self._call(
            "list_custom_models",
            request,
            ListCustomModelsResponseTypeDef,
        )


    def list_enforced_guardrails_configuration(
        self, request: ListEnforcedGuardrailsConfigurationRequestTypeDef,
    ) -> ListEnforcedGuardrailsConfigurationResponseTypeDef:
        return self._call(
            "list_enforced_guardrails_configuration",
            request,
            ListEnforcedGuardrailsConfigurationResponseTypeDef,
        )


    def list_evaluation_jobs(
        self, request: ListEvaluationJobsRequestTypeDef,
    ) -> ListEvaluationJobsResponseTypeDef:
        return self._call(
            "list_evaluation_jobs",
            request,
            ListEvaluationJobsResponseTypeDef,
        )


    def list_foundation_model_agreement_offers(
        self, request: ListFoundationModelAgreementOffersRequestTypeDef,
    ) -> ListFoundationModelAgreementOffersResponseTypeDef:
        return self._call(
            "list_foundation_model_agreement_offers",
            request,
            ListFoundationModelAgreementOffersResponseTypeDef,
        )


    def list_foundation_models(
        self, request: ListFoundationModelsRequestTypeDef,
    ) -> ListFoundationModelsResponseTypeDef:
        return self._call(
            "list_foundation_models",
            request,
            ListFoundationModelsResponseTypeDef,
        )


    def list_guardrails(
        self, request: ListGuardrailsRequestTypeDef,
    ) -> ListGuardrailsResponseTypeDef:
        return self._call(
            "list_guardrails",
            request,
            ListGuardrailsResponseTypeDef,
        )


    def list_imported_models(
        self, request: ListImportedModelsRequestTypeDef,
    ) -> ListImportedModelsResponseTypeDef:
        return self._call(
            "list_imported_models",
            request,
            ListImportedModelsResponseTypeDef,
        )


    def list_inference_profiles(
        self, request: ListInferenceProfilesRequestTypeDef,
    ) -> ListInferenceProfilesResponseTypeDef:
        return self._call(
            "list_inference_profiles",
            request,
            ListInferenceProfilesResponseTypeDef,
        )


    def list_marketplace_model_endpoints(
        self, request: ListMarketplaceModelEndpointsRequestTypeDef,
    ) -> ListMarketplaceModelEndpointsResponseTypeDef:
        return self._call(
            "list_marketplace_model_endpoints",
            request,
            ListMarketplaceModelEndpointsResponseTypeDef,
        )


    def list_model_copy_jobs(
        self, request: ListModelCopyJobsRequestTypeDef,
    ) -> ListModelCopyJobsResponseTypeDef:
        return self._call(
            "list_model_copy_jobs",
            request,
            ListModelCopyJobsResponseTypeDef,
        )


    def list_model_customization_jobs(
        self, request: ListModelCustomizationJobsRequestTypeDef,
    ) -> ListModelCustomizationJobsResponseTypeDef:
        return self._call(
            "list_model_customization_jobs",
            request,
            ListModelCustomizationJobsResponseTypeDef,
        )


    def list_model_import_jobs(
        self, request: ListModelImportJobsRequestTypeDef,
    ) -> ListModelImportJobsResponseTypeDef:
        return self._call(
            "list_model_import_jobs",
            request,
            ListModelImportJobsResponseTypeDef,
        )


    def list_model_invocation_jobs(
        self, request: ListModelInvocationJobsRequestTypeDef,
    ) -> ListModelInvocationJobsResponseTypeDef:
        return self._call(
            "list_model_invocation_jobs",
            request,
            ListModelInvocationJobsResponseTypeDef,
        )


    def list_prompt_routers(
        self, request: ListPromptRoutersRequestTypeDef,
    ) -> ListPromptRoutersResponseTypeDef:
        return self._call(
            "list_prompt_routers",
            request,
            ListPromptRoutersResponseTypeDef,
        )


    def list_provisioned_model_throughputs(
        self, request: ListProvisionedModelThroughputsRequestTypeDef,
    ) -> ListProvisionedModelThroughputsResponseTypeDef:
        return self._call(
            "list_provisioned_model_throughputs",
            request,
            ListProvisionedModelThroughputsResponseTypeDef,
        )


    def list_tags_for_resource(
        self, request: ListTagsForResourceRequestTypeDef,
    ) -> ListTagsForResourceResponseTypeDef:
        return self._call(
            "list_tags_for_resource",
            request,
            ListTagsForResourceResponseTypeDef,
        )


    def put_enforced_guardrail_configuration(
        self, request: PutEnforcedGuardrailConfigurationRequestTypeDef,
    ) -> PutEnforcedGuardrailConfigurationResponseTypeDef:
        return self._call(
            "put_enforced_guardrail_configuration",
            request,
            PutEnforcedGuardrailConfigurationResponseTypeDef,
        )


    def put_model_invocation_logging_configuration(
        self, request: PutModelInvocationLoggingConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_model_invocation_logging_configuration",
            request,
            None,
        )


    def put_resource_policy(
        self, request: PutResourcePolicyRequestTypeDef,
    ) -> PutResourcePolicyResponseTypeDef:
        return self._call(
            "put_resource_policy",
            request,
            PutResourcePolicyResponseTypeDef,
        )


    def put_use_case_for_model_access(
        self, request: PutUseCaseForModelAccessRequestTypeDef,
    ) -> None:
        return self._call(
            "put_use_case_for_model_access",
            request,
            None,
        )


    def register_marketplace_model_endpoint(
        self, request: RegisterMarketplaceModelEndpointRequestTypeDef,
    ) -> RegisterMarketplaceModelEndpointResponseTypeDef:
        return self._call(
            "register_marketplace_model_endpoint",
            request,
            RegisterMarketplaceModelEndpointResponseTypeDef,
        )


    def start_automated_reasoning_policy_build_workflow(
        self, request: StartAutomatedReasoningPolicyBuildWorkflowRequestTypeDef,
    ) -> StartAutomatedReasoningPolicyBuildWorkflowResponseTypeDef:
        return self._call(
            "start_automated_reasoning_policy_build_workflow",
            request,
            StartAutomatedReasoningPolicyBuildWorkflowResponseTypeDef,
        )


    def start_automated_reasoning_policy_test_workflow(
        self, request: StartAutomatedReasoningPolicyTestWorkflowRequestTypeDef,
    ) -> StartAutomatedReasoningPolicyTestWorkflowResponseTypeDef:
        return self._call(
            "start_automated_reasoning_policy_test_workflow",
            request,
            StartAutomatedReasoningPolicyTestWorkflowResponseTypeDef,
        )


    def stop_advanced_prompt_optimization_job(
        self,
    ) -> None:
        return self._call(
            "stop_advanced_prompt_optimization_job",
            None,
            None,
        )


    def stop_evaluation_job(
        self, request: StopEvaluationJobRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_evaluation_job",
            request,
            None,
        )


    def stop_model_customization_job(
        self, request: StopModelCustomizationJobRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_model_customization_job",
            request,
            None,
        )


    def stop_model_invocation_job(
        self, request: StopModelInvocationJobRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_model_invocation_job",
            request,
            None,
        )


    def tag_resource(
        self, request: TagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def untag_resource(
        self, request: UntagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_automated_reasoning_policy(
        self, request: UpdateAutomatedReasoningPolicyRequestTypeDef,
    ) -> UpdateAutomatedReasoningPolicyResponseTypeDef:
        return self._call(
            "update_automated_reasoning_policy",
            request,
            UpdateAutomatedReasoningPolicyResponseTypeDef,
        )


    def update_automated_reasoning_policy_annotations(
        self, request: UpdateAutomatedReasoningPolicyAnnotationsRequestTypeDef,
    ) -> UpdateAutomatedReasoningPolicyAnnotationsResponseTypeDef:
        return self._call(
            "update_automated_reasoning_policy_annotations",
            request,
            UpdateAutomatedReasoningPolicyAnnotationsResponseTypeDef,
        )


    def update_automated_reasoning_policy_test_case(
        self, request: UpdateAutomatedReasoningPolicyTestCaseRequestTypeDef,
    ) -> UpdateAutomatedReasoningPolicyTestCaseResponseTypeDef:
        return self._call(
            "update_automated_reasoning_policy_test_case",
            request,
            UpdateAutomatedReasoningPolicyTestCaseResponseTypeDef,
        )


    def update_custom_model_deployment(
        self, request: UpdateCustomModelDeploymentRequestTypeDef,
    ) -> UpdateCustomModelDeploymentResponseTypeDef:
        return self._call(
            "update_custom_model_deployment",
            request,
            UpdateCustomModelDeploymentResponseTypeDef,
        )


    def update_guardrail(
        self, request: UpdateGuardrailRequestTypeDef,
    ) -> UpdateGuardrailResponseTypeDef:
        return self._call(
            "update_guardrail",
            request,
            UpdateGuardrailResponseTypeDef,
        )


    def update_marketplace_model_endpoint(
        self, request: UpdateMarketplaceModelEndpointRequestTypeDef,
    ) -> UpdateMarketplaceModelEndpointResponseTypeDef:
        return self._call(
            "update_marketplace_model_endpoint",
            request,
            UpdateMarketplaceModelEndpointResponseTypeDef,
        )


    def update_provisioned_model_throughput(
        self, request: UpdateProvisionedModelThroughputRequestTypeDef,
    ) -> None:
        return self._call(
            "update_provisioned_model_throughput",
            request,
            None,
        )

