# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.dynamodb.dynamodb_classes import (
    BatchExecuteStatementInputTypeDef,
    BatchExecuteStatementOutputTypeDef,
    BatchGetItemInputTypeDef,
    BatchGetItemOutputTypeDef,
    BatchWriteItemInputTypeDef,
    BatchWriteItemOutputTypeDef,
    CreateBackupInputTypeDef,
    CreateBackupOutputTypeDef,
    CreateGlobalTableInputTypeDef,
    CreateGlobalTableOutputTypeDef,
    CreateTableInputTypeDef,
    CreateTableOutputTypeDef,
    DeleteBackupInputTypeDef,
    DeleteBackupOutputTypeDef,
    DeleteItemInputTypeDef,
    DeleteItemOutputTypeDef,
    DeleteResourcePolicyInputTypeDef,
    DeleteResourcePolicyOutputTypeDef,
    DeleteTableInputTypeDef,
    DeleteTableOutputTypeDef,
    DescribeBackupInputTypeDef,
    DescribeBackupOutputTypeDef,
    DescribeContinuousBackupsInputTypeDef,
    DescribeContinuousBackupsOutputTypeDef,
    DescribeContributorInsightsInputTypeDef,
    DescribeContributorInsightsOutputTypeDef,
    DescribeEndpointsResponseTypeDef,
    DescribeExportInputTypeDef,
    DescribeExportOutputTypeDef,
    DescribeGlobalTableInputTypeDef,
    DescribeGlobalTableOutputTypeDef,
    DescribeGlobalTableSettingsInputTypeDef,
    DescribeGlobalTableSettingsOutputTypeDef,
    DescribeImportInputTypeDef,
    DescribeImportOutputTypeDef,
    DescribeKinesisStreamingDestinationInputTypeDef,
    DescribeKinesisStreamingDestinationOutputTypeDef,
    DescribeLimitsOutputTypeDef,
    DescribeTableInputTypeDef,
    DescribeTableOutputTypeDef,
    DescribeTableReplicaAutoScalingInputTypeDef,
    DescribeTableReplicaAutoScalingOutputTypeDef,
    DescribeTimeToLiveInputTypeDef,
    DescribeTimeToLiveOutputTypeDef,
    ExecuteStatementInputTypeDef,
    ExecuteStatementOutputTypeDef,
    ExecuteTransactionInputTypeDef,
    ExecuteTransactionOutputTypeDef,
    ExportTableToPointInTimeInputTypeDef,
    ExportTableToPointInTimeOutputTypeDef,
    GetItemInputTypeDef,
    GetItemOutputTypeDef,
    GetResourcePolicyInputTypeDef,
    GetResourcePolicyOutputTypeDef,
    ImportTableInputTypeDef,
    ImportTableOutputTypeDef,
    KinesisStreamingDestinationInputTypeDef,
    KinesisStreamingDestinationOutputTypeDef,
    ListBackupsInputTypeDef,
    ListBackupsOutputTypeDef,
    ListContributorInsightsInputTypeDef,
    ListContributorInsightsOutputTypeDef,
    ListExportsInputTypeDef,
    ListExportsOutputTypeDef,
    ListGlobalTablesInputTypeDef,
    ListGlobalTablesOutputTypeDef,
    ListImportsInputTypeDef,
    ListImportsOutputTypeDef,
    ListTablesInputTypeDef,
    ListTablesOutputTypeDef,
    ListTagsOfResourceInputTypeDef,
    ListTagsOfResourceOutputTypeDef,
    PutItemInputTypeDef,
    PutItemOutputTypeDef,
    PutResourcePolicyInputTypeDef,
    PutResourcePolicyOutputTypeDef,
    QueryInputTypeDef,
    QueryOutputTypeDef,
    RestoreTableFromBackupInputTypeDef,
    RestoreTableFromBackupOutputTypeDef,
    RestoreTableToPointInTimeInputTypeDef,
    RestoreTableToPointInTimeOutputTypeDef,
    ScanInputTypeDef,
    ScanOutputTypeDef,
    TagResourceInputTypeDef,
    TransactGetItemsInputTypeDef,
    TransactGetItemsOutputTypeDef,
    TransactWriteItemsInputTypeDef,
    TransactWriteItemsOutputTypeDef,
    UntagResourceInputTypeDef,
    UpdateContinuousBackupsInputTypeDef,
    UpdateContinuousBackupsOutputTypeDef,
    UpdateContributorInsightsInputTypeDef,
    UpdateContributorInsightsOutputTypeDef,
    UpdateGlobalTableInputTypeDef,
    UpdateGlobalTableOutputTypeDef,
    UpdateGlobalTableSettingsInputTypeDef,
    UpdateGlobalTableSettingsOutputTypeDef,
    UpdateItemInputTypeDef,
    UpdateItemOutputTypeDef,
    UpdateKinesisStreamingDestinationInputTypeDef,
    UpdateKinesisStreamingDestinationOutputTypeDef,
    UpdateTableInputTypeDef,
    UpdateTableOutputTypeDef,
    UpdateTableReplicaAutoScalingInputTypeDef,
    UpdateTableReplicaAutoScalingOutputTypeDef,
    UpdateTimeToLiveInputTypeDef,
    UpdateTimeToLiveOutputTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class DynamodbClient(TypedClientBase):
    _service_name = ServiceName.DYNAMODB


    def batch_execute_statement(
        self, request: BatchExecuteStatementInputTypeDef,
    ) -> BatchExecuteStatementOutputTypeDef:
        return self._call(
            "batch_execute_statement",
            request,
            BatchExecuteStatementOutputTypeDef,
        )


    def batch_get_item(
        self, request: BatchGetItemInputTypeDef,
    ) -> BatchGetItemOutputTypeDef:
        return self._call(
            "batch_get_item",
            request,
            BatchGetItemOutputTypeDef,
        )


    def batch_write_item(
        self, request: BatchWriteItemInputTypeDef,
    ) -> BatchWriteItemOutputTypeDef:
        return self._call(
            "batch_write_item",
            request,
            BatchWriteItemOutputTypeDef,
        )


    def create_backup(
        self, request: CreateBackupInputTypeDef,
    ) -> CreateBackupOutputTypeDef:
        return self._call(
            "create_backup",
            request,
            CreateBackupOutputTypeDef,
        )


    def create_global_table(
        self, request: CreateGlobalTableInputTypeDef,
    ) -> CreateGlobalTableOutputTypeDef:
        return self._call(
            "create_global_table",
            request,
            CreateGlobalTableOutputTypeDef,
        )


    def create_table(
        self, request: CreateTableInputTypeDef,
    ) -> CreateTableOutputTypeDef:
        return self._call(
            "create_table",
            request,
            CreateTableOutputTypeDef,
        )


    def delete_backup(
        self, request: DeleteBackupInputTypeDef,
    ) -> DeleteBackupOutputTypeDef:
        return self._call(
            "delete_backup",
            request,
            DeleteBackupOutputTypeDef,
        )


    def delete_item(
        self, request: DeleteItemInputTypeDef,
    ) -> DeleteItemOutputTypeDef:
        return self._call(
            "delete_item",
            request,
            DeleteItemOutputTypeDef,
        )


    def delete_resource_policy(
        self, request: DeleteResourcePolicyInputTypeDef,
    ) -> DeleteResourcePolicyOutputTypeDef:
        return self._call(
            "delete_resource_policy",
            request,
            DeleteResourcePolicyOutputTypeDef,
        )


    def delete_table(
        self, request: DeleteTableInputTypeDef,
    ) -> DeleteTableOutputTypeDef:
        return self._call(
            "delete_table",
            request,
            DeleteTableOutputTypeDef,
        )


    def describe_backup(
        self, request: DescribeBackupInputTypeDef,
    ) -> DescribeBackupOutputTypeDef:
        return self._call(
            "describe_backup",
            request,
            DescribeBackupOutputTypeDef,
        )


    def describe_continuous_backups(
        self, request: DescribeContinuousBackupsInputTypeDef,
    ) -> DescribeContinuousBackupsOutputTypeDef:
        return self._call(
            "describe_continuous_backups",
            request,
            DescribeContinuousBackupsOutputTypeDef,
        )


    def describe_contributor_insights(
        self, request: DescribeContributorInsightsInputTypeDef,
    ) -> DescribeContributorInsightsOutputTypeDef:
        return self._call(
            "describe_contributor_insights",
            request,
            DescribeContributorInsightsOutputTypeDef,
        )


    def describe_endpoints(
        self,
    ) -> DescribeEndpointsResponseTypeDef:
        return self._call(
            "describe_endpoints",
            None,
            DescribeEndpointsResponseTypeDef,
        )


    def describe_export(
        self, request: DescribeExportInputTypeDef,
    ) -> DescribeExportOutputTypeDef:
        return self._call(
            "describe_export",
            request,
            DescribeExportOutputTypeDef,
        )


    def describe_global_table(
        self, request: DescribeGlobalTableInputTypeDef,
    ) -> DescribeGlobalTableOutputTypeDef:
        return self._call(
            "describe_global_table",
            request,
            DescribeGlobalTableOutputTypeDef,
        )


    def describe_global_table_settings(
        self, request: DescribeGlobalTableSettingsInputTypeDef,
    ) -> DescribeGlobalTableSettingsOutputTypeDef:
        return self._call(
            "describe_global_table_settings",
            request,
            DescribeGlobalTableSettingsOutputTypeDef,
        )


    def describe_import(
        self, request: DescribeImportInputTypeDef,
    ) -> DescribeImportOutputTypeDef:
        return self._call(
            "describe_import",
            request,
            DescribeImportOutputTypeDef,
        )


    def describe_kinesis_streaming_destination(
        self, request: DescribeKinesisStreamingDestinationInputTypeDef,
    ) -> DescribeKinesisStreamingDestinationOutputTypeDef:
        return self._call(
            "describe_kinesis_streaming_destination",
            request,
            DescribeKinesisStreamingDestinationOutputTypeDef,
        )


    def describe_limits(
        self,
    ) -> DescribeLimitsOutputTypeDef:
        return self._call(
            "describe_limits",
            None,
            DescribeLimitsOutputTypeDef,
        )


    def describe_table(
        self, request: DescribeTableInputTypeDef,
    ) -> DescribeTableOutputTypeDef:
        return self._call(
            "describe_table",
            request,
            DescribeTableOutputTypeDef,
        )


    def describe_table_replica_auto_scaling(
        self, request: DescribeTableReplicaAutoScalingInputTypeDef,
    ) -> DescribeTableReplicaAutoScalingOutputTypeDef:
        return self._call(
            "describe_table_replica_auto_scaling",
            request,
            DescribeTableReplicaAutoScalingOutputTypeDef,
        )


    def describe_time_to_live(
        self, request: DescribeTimeToLiveInputTypeDef,
    ) -> DescribeTimeToLiveOutputTypeDef:
        return self._call(
            "describe_time_to_live",
            request,
            DescribeTimeToLiveOutputTypeDef,
        )


    def disable_kinesis_streaming_destination(
        self, request: KinesisStreamingDestinationInputTypeDef,
    ) -> KinesisStreamingDestinationOutputTypeDef:
        return self._call(
            "disable_kinesis_streaming_destination",
            request,
            KinesisStreamingDestinationOutputTypeDef,
        )


    def enable_kinesis_streaming_destination(
        self, request: KinesisStreamingDestinationInputTypeDef,
    ) -> KinesisStreamingDestinationOutputTypeDef:
        return self._call(
            "enable_kinesis_streaming_destination",
            request,
            KinesisStreamingDestinationOutputTypeDef,
        )


    def execute_statement(
        self, request: ExecuteStatementInputTypeDef,
    ) -> ExecuteStatementOutputTypeDef:
        return self._call(
            "execute_statement",
            request,
            ExecuteStatementOutputTypeDef,
        )


    def execute_transaction(
        self, request: ExecuteTransactionInputTypeDef,
    ) -> ExecuteTransactionOutputTypeDef:
        return self._call(
            "execute_transaction",
            request,
            ExecuteTransactionOutputTypeDef,
        )


    def export_table_to_point_in_time(
        self, request: ExportTableToPointInTimeInputTypeDef,
    ) -> ExportTableToPointInTimeOutputTypeDef:
        return self._call(
            "export_table_to_point_in_time",
            request,
            ExportTableToPointInTimeOutputTypeDef,
        )


    def get_item(
        self, request: GetItemInputTypeDef,
    ) -> GetItemOutputTypeDef:
        return self._call(
            "get_item",
            request,
            GetItemOutputTypeDef,
        )


    def get_resource_policy(
        self, request: GetResourcePolicyInputTypeDef,
    ) -> GetResourcePolicyOutputTypeDef:
        return self._call(
            "get_resource_policy",
            request,
            GetResourcePolicyOutputTypeDef,
        )


    def import_table(
        self, request: ImportTableInputTypeDef,
    ) -> ImportTableOutputTypeDef:
        return self._call(
            "import_table",
            request,
            ImportTableOutputTypeDef,
        )


    def list_backups(
        self, request: ListBackupsInputTypeDef,
    ) -> ListBackupsOutputTypeDef:
        return self._call(
            "list_backups",
            request,
            ListBackupsOutputTypeDef,
        )


    def list_contributor_insights(
        self, request: ListContributorInsightsInputTypeDef,
    ) -> ListContributorInsightsOutputTypeDef:
        return self._call(
            "list_contributor_insights",
            request,
            ListContributorInsightsOutputTypeDef,
        )


    def list_exports(
        self, request: ListExportsInputTypeDef,
    ) -> ListExportsOutputTypeDef:
        return self._call(
            "list_exports",
            request,
            ListExportsOutputTypeDef,
        )


    def list_global_tables(
        self, request: ListGlobalTablesInputTypeDef,
    ) -> ListGlobalTablesOutputTypeDef:
        return self._call(
            "list_global_tables",
            request,
            ListGlobalTablesOutputTypeDef,
        )


    def list_imports(
        self, request: ListImportsInputTypeDef,
    ) -> ListImportsOutputTypeDef:
        return self._call(
            "list_imports",
            request,
            ListImportsOutputTypeDef,
        )


    def list_tables(
        self, request: ListTablesInputTypeDef,
    ) -> ListTablesOutputTypeDef:
        return self._call(
            "list_tables",
            request,
            ListTablesOutputTypeDef,
        )


    def list_tags_of_resource(
        self, request: ListTagsOfResourceInputTypeDef,
    ) -> ListTagsOfResourceOutputTypeDef:
        return self._call(
            "list_tags_of_resource",
            request,
            ListTagsOfResourceOutputTypeDef,
        )


    def put_item(
        self, request: PutItemInputTypeDef,
    ) -> PutItemOutputTypeDef:
        return self._call(
            "put_item",
            request,
            PutItemOutputTypeDef,
        )


    def put_resource_policy(
        self, request: PutResourcePolicyInputTypeDef,
    ) -> PutResourcePolicyOutputTypeDef:
        return self._call(
            "put_resource_policy",
            request,
            PutResourcePolicyOutputTypeDef,
        )


    def query(
        self, request: QueryInputTypeDef,
    ) -> QueryOutputTypeDef:
        return self._call(
            "query",
            request,
            QueryOutputTypeDef,
        )


    def restore_table_from_backup(
        self, request: RestoreTableFromBackupInputTypeDef,
    ) -> RestoreTableFromBackupOutputTypeDef:
        return self._call(
            "restore_table_from_backup",
            request,
            RestoreTableFromBackupOutputTypeDef,
        )


    def restore_table_to_point_in_time(
        self, request: RestoreTableToPointInTimeInputTypeDef,
    ) -> RestoreTableToPointInTimeOutputTypeDef:
        return self._call(
            "restore_table_to_point_in_time",
            request,
            RestoreTableToPointInTimeOutputTypeDef,
        )


    def scan(
        self, request: ScanInputTypeDef,
    ) -> ScanOutputTypeDef:
        return self._call(
            "scan",
            request,
            ScanOutputTypeDef,
        )


    def tag_resource(
        self, request: TagResourceInputTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def transact_get_items(
        self, request: TransactGetItemsInputTypeDef,
    ) -> TransactGetItemsOutputTypeDef:
        return self._call(
            "transact_get_items",
            request,
            TransactGetItemsOutputTypeDef,
        )


    def transact_write_items(
        self, request: TransactWriteItemsInputTypeDef,
    ) -> TransactWriteItemsOutputTypeDef:
        return self._call(
            "transact_write_items",
            request,
            TransactWriteItemsOutputTypeDef,
        )


    def untag_resource(
        self, request: UntagResourceInputTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_continuous_backups(
        self, request: UpdateContinuousBackupsInputTypeDef,
    ) -> UpdateContinuousBackupsOutputTypeDef:
        return self._call(
            "update_continuous_backups",
            request,
            UpdateContinuousBackupsOutputTypeDef,
        )


    def update_contributor_insights(
        self, request: UpdateContributorInsightsInputTypeDef,
    ) -> UpdateContributorInsightsOutputTypeDef:
        return self._call(
            "update_contributor_insights",
            request,
            UpdateContributorInsightsOutputTypeDef,
        )


    def update_global_table(
        self, request: UpdateGlobalTableInputTypeDef,
    ) -> UpdateGlobalTableOutputTypeDef:
        return self._call(
            "update_global_table",
            request,
            UpdateGlobalTableOutputTypeDef,
        )


    def update_global_table_settings(
        self, request: UpdateGlobalTableSettingsInputTypeDef,
    ) -> UpdateGlobalTableSettingsOutputTypeDef:
        return self._call(
            "update_global_table_settings",
            request,
            UpdateGlobalTableSettingsOutputTypeDef,
        )


    def update_item(
        self, request: UpdateItemInputTypeDef,
    ) -> UpdateItemOutputTypeDef:
        return self._call(
            "update_item",
            request,
            UpdateItemOutputTypeDef,
        )


    def update_kinesis_streaming_destination(
        self, request: UpdateKinesisStreamingDestinationInputTypeDef,
    ) -> UpdateKinesisStreamingDestinationOutputTypeDef:
        return self._call(
            "update_kinesis_streaming_destination",
            request,
            UpdateKinesisStreamingDestinationOutputTypeDef,
        )


    def update_table(
        self, request: UpdateTableInputTypeDef,
    ) -> UpdateTableOutputTypeDef:
        return self._call(
            "update_table",
            request,
            UpdateTableOutputTypeDef,
        )


    def update_table_replica_auto_scaling(
        self, request: UpdateTableReplicaAutoScalingInputTypeDef,
    ) -> UpdateTableReplicaAutoScalingOutputTypeDef:
        return self._call(
            "update_table_replica_auto_scaling",
            request,
            UpdateTableReplicaAutoScalingOutputTypeDef,
        )


    def update_time_to_live(
        self, request: UpdateTimeToLiveInputTypeDef,
    ) -> UpdateTimeToLiveOutputTypeDef:
        return self._call(
            "update_time_to_live",
            request,
            UpdateTimeToLiveOutputTypeDef,
        )

