# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.firehose.firehose_classes import (
    CreateDeliveryStreamInputTypeDef,
    CreateDeliveryStreamOutputTypeDef,
    DeleteDeliveryStreamInputTypeDef,
    DescribeDeliveryStreamInputTypeDef,
    DescribeDeliveryStreamOutputTypeDef,
    ListDeliveryStreamsInputTypeDef,
    ListDeliveryStreamsOutputTypeDef,
    ListTagsForDeliveryStreamInputTypeDef,
    ListTagsForDeliveryStreamOutputTypeDef,
    PutRecordBatchInputTypeDef,
    PutRecordBatchOutputTypeDef,
    PutRecordInputTypeDef,
    PutRecordOutputTypeDef,
    StartDeliveryStreamEncryptionInputTypeDef,
    StopDeliveryStreamEncryptionInputTypeDef,
    TagDeliveryStreamInputTypeDef,
    UntagDeliveryStreamInputTypeDef,
    UpdateDestinationInputTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class FirehoseClient(TypedClientBase):
    _service_name = ServiceName.FIREHOSE


    def create_delivery_stream(
        self, request: CreateDeliveryStreamInputTypeDef,
    ) -> CreateDeliveryStreamOutputTypeDef:
        return self._call(
            "create_delivery_stream",
            request,
            CreateDeliveryStreamOutputTypeDef,
        )


    def delete_delivery_stream(
        self, request: DeleteDeliveryStreamInputTypeDef,
    ) -> None:
        return self._call(
            "delete_delivery_stream",
            request,
            None,
        )


    def describe_delivery_stream(
        self, request: DescribeDeliveryStreamInputTypeDef,
    ) -> DescribeDeliveryStreamOutputTypeDef:
        return self._call(
            "describe_delivery_stream",
            request,
            DescribeDeliveryStreamOutputTypeDef,
        )


    def list_delivery_streams(
        self, request: ListDeliveryStreamsInputTypeDef,
    ) -> ListDeliveryStreamsOutputTypeDef:
        return self._call(
            "list_delivery_streams",
            request,
            ListDeliveryStreamsOutputTypeDef,
        )


    def list_tags_for_delivery_stream(
        self, request: ListTagsForDeliveryStreamInputTypeDef,
    ) -> ListTagsForDeliveryStreamOutputTypeDef:
        return self._call(
            "list_tags_for_delivery_stream",
            request,
            ListTagsForDeliveryStreamOutputTypeDef,
        )


    def put_record(
        self, request: PutRecordInputTypeDef,
    ) -> PutRecordOutputTypeDef:
        return self._call(
            "put_record",
            request,
            PutRecordOutputTypeDef,
        )


    def put_record_batch(
        self, request: PutRecordBatchInputTypeDef,
    ) -> PutRecordBatchOutputTypeDef:
        return self._call(
            "put_record_batch",
            request,
            PutRecordBatchOutputTypeDef,
        )


    def start_delivery_stream_encryption(
        self, request: StartDeliveryStreamEncryptionInputTypeDef,
    ) -> None:
        return self._call(
            "start_delivery_stream_encryption",
            request,
            None,
        )


    def stop_delivery_stream_encryption(
        self, request: StopDeliveryStreamEncryptionInputTypeDef,
    ) -> None:
        return self._call(
            "stop_delivery_stream_encryption",
            request,
            None,
        )


    def tag_delivery_stream(
        self, request: TagDeliveryStreamInputTypeDef,
    ) -> None:
        return self._call(
            "tag_delivery_stream",
            request,
            None,
        )


    def untag_delivery_stream(
        self, request: UntagDeliveryStreamInputTypeDef,
    ) -> None:
        return self._call(
            "untag_delivery_stream",
            request,
            None,
        )


    def update_destination(
        self, request: UpdateDestinationInputTypeDef,
    ) -> None:
        return self._call(
            "update_destination",
            request,
            None,
        )

