# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.glue.glue_classes import (
    BatchCreatePartitionRequestTypeDef,
    BatchCreatePartitionResponseTypeDef,
    BatchDeleteConnectionRequestTypeDef,
    BatchDeleteConnectionResponseTypeDef,
    BatchDeletePartitionRequestTypeDef,
    BatchDeletePartitionResponseTypeDef,
    BatchDeleteTableRequestTypeDef,
    BatchDeleteTableResponseTypeDef,
    BatchDeleteTableVersionRequestTypeDef,
    BatchDeleteTableVersionResponseTypeDef,
    BatchGetBlueprintsRequestTypeDef,
    BatchGetBlueprintsResponseTypeDef,
    BatchGetCrawlersRequestTypeDef,
    BatchGetCrawlersResponseTypeDef,
    BatchGetCustomEntityTypesRequestTypeDef,
    BatchGetCustomEntityTypesResponseTypeDef,
    BatchGetDataQualityResultRequestTypeDef,
    BatchGetDataQualityResultResponseTypeDef,
    BatchGetDevEndpointsRequestTypeDef,
    BatchGetDevEndpointsResponseTypeDef,
    BatchGetJobsRequestTypeDef,
    BatchGetJobsResponseTypeDef,
    BatchGetPartitionRequestTypeDef,
    BatchGetPartitionResponseTypeDef,
    BatchGetTableOptimizerRequestTypeDef,
    BatchGetTableOptimizerResponseTypeDef,
    BatchGetTriggersRequestTypeDef,
    BatchGetTriggersResponseTypeDef,
    BatchGetWorkflowsRequestTypeDef,
    BatchGetWorkflowsResponseTypeDef,
    BatchPutDataQualityStatisticAnnotationRequestTypeDef,
    BatchPutDataQualityStatisticAnnotationResponseTypeDef,
    BatchStopJobRunRequestTypeDef,
    BatchStopJobRunResponseTypeDef,
    BatchUpdatePartitionRequestTypeDef,
    BatchUpdatePartitionResponseTypeDef,
    CancelDataQualityRuleRecommendationRunRequestTypeDef,
    CancelDataQualityRulesetEvaluationRunRequestTypeDef,
    CancelMLTaskRunRequestTypeDef,
    CancelMLTaskRunResponseTypeDef,
    CancelStatementRequestTypeDef,
    CheckSchemaVersionValidityInputTypeDef,
    CheckSchemaVersionValidityResponseTypeDef,
    CreateBlueprintRequestTypeDef,
    CreateBlueprintResponseTypeDef,
    CreateCatalogRequestTypeDef,
    CreateClassifierRequestTypeDef,
    CreateColumnStatisticsTaskSettingsRequestTypeDef,
    CreateConnectionRequestTypeDef,
    CreateConnectionResponseTypeDef,
    CreateCrawlerRequestTypeDef,
    CreateCustomEntityTypeRequestTypeDef,
    CreateCustomEntityTypeResponseTypeDef,
    CreateDataQualityRulesetRequestTypeDef,
    CreateDataQualityRulesetResponseTypeDef,
    CreateDatabaseRequestTypeDef,
    CreateDevEndpointRequestTypeDef,
    CreateDevEndpointResponseTypeDef,
    CreateGlueIdentityCenterConfigurationRequestTypeDef,
    CreateGlueIdentityCenterConfigurationResponseTypeDef,
    CreateIntegrationRequestTypeDef,
    CreateIntegrationResourcePropertyRequestTypeDef,
    CreateIntegrationResourcePropertyResponseTypeDef,
    CreateIntegrationResponseTypeDef,
    CreateIntegrationTablePropertiesRequestTypeDef,
    CreateJobRequestTypeDef,
    CreateJobResponseTypeDef,
    CreateMLTransformRequestTypeDef,
    CreateMLTransformResponseTypeDef,
    CreatePartitionIndexRequestTypeDef,
    CreatePartitionRequestTypeDef,
    CreateRegistryInputTypeDef,
    CreateRegistryResponseTypeDef,
    CreateSchemaInputTypeDef,
    CreateSchemaResponseTypeDef,
    CreateScriptRequestTypeDef,
    CreateScriptResponseTypeDef,
    CreateSecurityConfigurationRequestTypeDef,
    CreateSecurityConfigurationResponseTypeDef,
    CreateSessionRequestTypeDef,
    CreateSessionResponseTypeDef,
    CreateTableOptimizerRequestTypeDef,
    CreateTableRequestTypeDef,
    CreateTriggerRequestTypeDef,
    CreateTriggerResponseTypeDef,
    CreateUsageProfileRequestTypeDef,
    CreateUsageProfileResponseTypeDef,
    CreateUserDefinedFunctionRequestTypeDef,
    CreateWorkflowRequestTypeDef,
    CreateWorkflowResponseTypeDef,
    DeleteBlueprintRequestTypeDef,
    DeleteBlueprintResponseTypeDef,
    DeleteCatalogRequestTypeDef,
    DeleteClassifierRequestTypeDef,
    DeleteColumnStatisticsForPartitionRequestTypeDef,
    DeleteColumnStatisticsForTableRequestTypeDef,
    DeleteColumnStatisticsTaskSettingsRequestTypeDef,
    DeleteConnectionRequestTypeDef,
    DeleteConnectionTypeRequestTypeDef,
    DeleteCrawlerRequestTypeDef,
    DeleteCustomEntityTypeRequestTypeDef,
    DeleteCustomEntityTypeResponseTypeDef,
    DeleteDataQualityRulesetRequestTypeDef,
    DeleteDatabaseRequestTypeDef,
    DeleteDevEndpointRequestTypeDef,
    DeleteIntegrationRequestTypeDef,
    DeleteIntegrationResourcePropertyRequestTypeDef,
    DeleteIntegrationResponseTypeDef,
    DeleteIntegrationTablePropertiesRequestTypeDef,
    DeleteJobRequestTypeDef,
    DeleteJobResponseTypeDef,
    DeleteMLTransformRequestTypeDef,
    DeleteMLTransformResponseTypeDef,
    DeletePartitionIndexRequestTypeDef,
    DeletePartitionRequestTypeDef,
    DeleteRegistryInputTypeDef,
    DeleteRegistryResponseTypeDef,
    DeleteResourcePolicyRequestTypeDef,
    DeleteSchemaInputTypeDef,
    DeleteSchemaResponseTypeDef,
    DeleteSchemaVersionsInputTypeDef,
    DeleteSchemaVersionsResponseTypeDef,
    DeleteSecurityConfigurationRequestTypeDef,
    DeleteSessionRequestTypeDef,
    DeleteSessionResponseTypeDef,
    DeleteTableOptimizerRequestTypeDef,
    DeleteTableRequestTypeDef,
    DeleteTableVersionRequestTypeDef,
    DeleteTriggerRequestTypeDef,
    DeleteTriggerResponseTypeDef,
    DeleteUsageProfileRequestTypeDef,
    DeleteUserDefinedFunctionRequestTypeDef,
    DeleteWorkflowRequestTypeDef,
    DeleteWorkflowResponseTypeDef,
    DescribeConnectionTypeRequestTypeDef,
    DescribeConnectionTypeResponseTypeDef,
    DescribeEntityRequestTypeDef,
    DescribeEntityResponseTypeDef,
    DescribeInboundIntegrationsRequestTypeDef,
    DescribeInboundIntegrationsResponseTypeDef,
    DescribeIntegrationsRequestTypeDef,
    DescribeIntegrationsResponseTypeDef,
    GetBlueprintRequestTypeDef,
    GetBlueprintResponseTypeDef,
    GetBlueprintRunRequestTypeDef,
    GetBlueprintRunResponseTypeDef,
    GetBlueprintRunsRequestTypeDef,
    GetBlueprintRunsResponseTypeDef,
    GetCatalogImportStatusRequestTypeDef,
    GetCatalogImportStatusResponseTypeDef,
    GetCatalogRequestTypeDef,
    GetCatalogResponseTypeDef,
    GetCatalogsRequestTypeDef,
    GetCatalogsResponseTypeDef,
    GetClassifierRequestTypeDef,
    GetClassifierResponseTypeDef,
    GetClassifiersRequestTypeDef,
    GetClassifiersResponseTypeDef,
    GetColumnStatisticsForPartitionRequestTypeDef,
    GetColumnStatisticsForPartitionResponseTypeDef,
    GetColumnStatisticsForTableRequestTypeDef,
    GetColumnStatisticsForTableResponseTypeDef,
    GetColumnStatisticsTaskRunRequestTypeDef,
    GetColumnStatisticsTaskRunResponseTypeDef,
    GetColumnStatisticsTaskRunsRequestTypeDef,
    GetColumnStatisticsTaskRunsResponseTypeDef,
    GetColumnStatisticsTaskSettingsRequestTypeDef,
    GetColumnStatisticsTaskSettingsResponseTypeDef,
    GetConnectionRequestTypeDef,
    GetConnectionResponseTypeDef,
    GetConnectionsRequestTypeDef,
    GetConnectionsResponseTypeDef,
    GetCrawlerMetricsRequestTypeDef,
    GetCrawlerMetricsResponseTypeDef,
    GetCrawlerRequestTypeDef,
    GetCrawlerResponseTypeDef,
    GetCrawlersRequestTypeDef,
    GetCrawlersResponseTypeDef,
    GetCustomEntityTypeRequestTypeDef,
    GetCustomEntityTypeResponseTypeDef,
    GetDataCatalogEncryptionSettingsRequestTypeDef,
    GetDataCatalogEncryptionSettingsResponseTypeDef,
    GetDataQualityModelRequestTypeDef,
    GetDataQualityModelResponseTypeDef,
    GetDataQualityModelResultRequestTypeDef,
    GetDataQualityModelResultResponseTypeDef,
    GetDataQualityResultRequestTypeDef,
    GetDataQualityResultResponseTypeDef,
    GetDataQualityRuleRecommendationRunRequestTypeDef,
    GetDataQualityRuleRecommendationRunResponseTypeDef,
    GetDataQualityRulesetEvaluationRunRequestTypeDef,
    GetDataQualityRulesetEvaluationRunResponseTypeDef,
    GetDataQualityRulesetRequestTypeDef,
    GetDataQualityRulesetResponseTypeDef,
    GetDatabaseRequestTypeDef,
    GetDatabaseResponseTypeDef,
    GetDatabasesRequestTypeDef,
    GetDatabasesResponseTypeDef,
    GetDataflowGraphRequestTypeDef,
    GetDataflowGraphResponseTypeDef,
    GetDevEndpointRequestTypeDef,
    GetDevEndpointResponseTypeDef,
    GetDevEndpointsRequestTypeDef,
    GetDevEndpointsResponseTypeDef,
    GetEntityRecordsRequestTypeDef,
    GetEntityRecordsResponseTypeDef,
    GetGlueIdentityCenterConfigurationResponseTypeDef,
    GetIntegrationResourcePropertyRequestTypeDef,
    GetIntegrationResourcePropertyResponseTypeDef,
    GetIntegrationTablePropertiesRequestTypeDef,
    GetIntegrationTablePropertiesResponseTypeDef,
    GetJobBookmarkRequestTypeDef,
    GetJobBookmarkResponseTypeDef,
    GetJobRequestTypeDef,
    GetJobResponseTypeDef,
    GetJobRunRequestTypeDef,
    GetJobRunResponseTypeDef,
    GetJobRunsRequestTypeDef,
    GetJobRunsResponseTypeDef,
    GetJobsRequestTypeDef,
    GetJobsResponseTypeDef,
    GetMLTaskRunRequestTypeDef,
    GetMLTaskRunResponseTypeDef,
    GetMLTaskRunsRequestTypeDef,
    GetMLTaskRunsResponseTypeDef,
    GetMLTransformRequestTypeDef,
    GetMLTransformResponseTypeDef,
    GetMLTransformsRequestTypeDef,
    GetMLTransformsResponseTypeDef,
    GetMappingRequestTypeDef,
    GetMappingResponseTypeDef,
    GetMaterializedViewRefreshTaskRunRequestTypeDef,
    GetMaterializedViewRefreshTaskRunResponseTypeDef,
    GetPartitionIndexesRequestTypeDef,
    GetPartitionIndexesResponseTypeDef,
    GetPartitionRequestTypeDef,
    GetPartitionResponseTypeDef,
    GetPartitionsRequestTypeDef,
    GetPartitionsResponseTypeDef,
    GetPlanRequestTypeDef,
    GetPlanResponseTypeDef,
    GetRegistryInputTypeDef,
    GetRegistryResponseTypeDef,
    GetResourcePoliciesRequestTypeDef,
    GetResourcePoliciesResponseTypeDef,
    GetResourcePolicyRequestTypeDef,
    GetResourcePolicyResponseTypeDef,
    GetSchemaByDefinitionInputTypeDef,
    GetSchemaByDefinitionResponseTypeDef,
    GetSchemaInputTypeDef,
    GetSchemaResponseTypeDef,
    GetSchemaVersionInputTypeDef,
    GetSchemaVersionResponseTypeDef,
    GetSchemaVersionsDiffInputTypeDef,
    GetSchemaVersionsDiffResponseTypeDef,
    GetSecurityConfigurationRequestTypeDef,
    GetSecurityConfigurationResponseTypeDef,
    GetSecurityConfigurationsRequestTypeDef,
    GetSecurityConfigurationsResponseTypeDef,
    GetSessionRequestTypeDef,
    GetSessionResponseTypeDef,
    GetStatementRequestTypeDef,
    GetStatementResponseTypeDef,
    GetTableOptimizerRequestTypeDef,
    GetTableOptimizerResponseTypeDef,
    GetTableRequestTypeDef,
    GetTableResponseTypeDef,
    GetTableVersionRequestTypeDef,
    GetTableVersionResponseTypeDef,
    GetTableVersionsRequestTypeDef,
    GetTableVersionsResponseTypeDef,
    GetTablesRequestTypeDef,
    GetTablesResponseTypeDef,
    GetTagsRequestTypeDef,
    GetTagsResponseTypeDef,
    GetTriggerRequestTypeDef,
    GetTriggerResponseTypeDef,
    GetTriggersRequestTypeDef,
    GetTriggersResponseTypeDef,
    GetUnfilteredPartitionMetadataRequestTypeDef,
    GetUnfilteredPartitionMetadataResponseTypeDef,
    GetUnfilteredPartitionsMetadataRequestTypeDef,
    GetUnfilteredPartitionsMetadataResponseTypeDef,
    GetUnfilteredTableMetadataRequestTypeDef,
    GetUnfilteredTableMetadataResponseTypeDef,
    GetUsageProfileRequestTypeDef,
    GetUsageProfileResponseTypeDef,
    GetUserDefinedFunctionRequestTypeDef,
    GetUserDefinedFunctionResponseTypeDef,
    GetUserDefinedFunctionsRequestTypeDef,
    GetUserDefinedFunctionsResponseTypeDef,
    GetWorkflowRequestTypeDef,
    GetWorkflowResponseTypeDef,
    GetWorkflowRunPropertiesRequestTypeDef,
    GetWorkflowRunPropertiesResponseTypeDef,
    GetWorkflowRunRequestTypeDef,
    GetWorkflowRunResponseTypeDef,
    GetWorkflowRunsRequestTypeDef,
    GetWorkflowRunsResponseTypeDef,
    ImportCatalogToGlueRequestTypeDef,
    ListBlueprintsRequestTypeDef,
    ListBlueprintsResponseTypeDef,
    ListColumnStatisticsTaskRunsRequestTypeDef,
    ListColumnStatisticsTaskRunsResponseTypeDef,
    ListConnectionTypesRequestTypeDef,
    ListConnectionTypesResponseTypeDef,
    ListCrawlersRequestTypeDef,
    ListCrawlersResponseTypeDef,
    ListCrawlsRequestTypeDef,
    ListCrawlsResponseTypeDef,
    ListCustomEntityTypesRequestTypeDef,
    ListCustomEntityTypesResponseTypeDef,
    ListDataQualityResultsRequestTypeDef,
    ListDataQualityResultsResponseTypeDef,
    ListDataQualityRuleRecommendationRunsRequestTypeDef,
    ListDataQualityRuleRecommendationRunsResponseTypeDef,
    ListDataQualityRulesetEvaluationRunsRequestTypeDef,
    ListDataQualityRulesetEvaluationRunsResponseTypeDef,
    ListDataQualityRulesetsRequestTypeDef,
    ListDataQualityRulesetsResponseTypeDef,
    ListDataQualityStatisticAnnotationsRequestTypeDef,
    ListDataQualityStatisticAnnotationsResponseTypeDef,
    ListDataQualityStatisticsRequestTypeDef,
    ListDataQualityStatisticsResponseTypeDef,
    ListDevEndpointsRequestTypeDef,
    ListDevEndpointsResponseTypeDef,
    ListEntitiesRequestTypeDef,
    ListEntitiesResponseTypeDef,
    ListIntegrationResourcePropertiesRequestTypeDef,
    ListIntegrationResourcePropertiesResponseTypeDef,
    ListJobsRequestTypeDef,
    ListJobsResponseTypeDef,
    ListMLTransformsRequestTypeDef,
    ListMLTransformsResponseTypeDef,
    ListMaterializedViewRefreshTaskRunsRequestTypeDef,
    ListMaterializedViewRefreshTaskRunsResponseTypeDef,
    ListRegistriesInputTypeDef,
    ListRegistriesResponseTypeDef,
    ListSchemaVersionsInputTypeDef,
    ListSchemaVersionsResponseTypeDef,
    ListSchemasInputTypeDef,
    ListSchemasResponseTypeDef,
    ListSessionsRequestTypeDef,
    ListSessionsResponseTypeDef,
    ListStatementsRequestTypeDef,
    ListStatementsResponseTypeDef,
    ListTableOptimizerRunsRequestTypeDef,
    ListTableOptimizerRunsResponseTypeDef,
    ListTriggersRequestTypeDef,
    ListTriggersResponseTypeDef,
    ListUsageProfilesRequestTypeDef,
    ListUsageProfilesResponseTypeDef,
    ListWorkflowsRequestTypeDef,
    ListWorkflowsResponseTypeDef,
    ModifyIntegrationRequestTypeDef,
    ModifyIntegrationResponseTypeDef,
    PutDataCatalogEncryptionSettingsRequestTypeDef,
    PutDataQualityProfileAnnotationRequestTypeDef,
    PutResourcePolicyRequestTypeDef,
    PutResourcePolicyResponseTypeDef,
    PutSchemaVersionMetadataInputTypeDef,
    PutSchemaVersionMetadataResponseTypeDef,
    PutWorkflowRunPropertiesRequestTypeDef,
    QuerySchemaVersionMetadataInputTypeDef,
    QuerySchemaVersionMetadataResponseTypeDef,
    RegisterConnectionTypeRequestTypeDef,
    RegisterConnectionTypeResponseTypeDef,
    RegisterSchemaVersionInputTypeDef,
    RegisterSchemaVersionResponseTypeDef,
    RemoveSchemaVersionMetadataInputTypeDef,
    RemoveSchemaVersionMetadataResponseTypeDef,
    ResetJobBookmarkRequestTypeDef,
    ResetJobBookmarkResponseTypeDef,
    ResumeWorkflowRunRequestTypeDef,
    ResumeWorkflowRunResponseTypeDef,
    RunStatementRequestTypeDef,
    RunStatementResponseTypeDef,
    SearchTablesRequestTypeDef,
    SearchTablesResponseTypeDef,
    StartBlueprintRunRequestTypeDef,
    StartBlueprintRunResponseTypeDef,
    StartColumnStatisticsTaskRunRequestTypeDef,
    StartColumnStatisticsTaskRunResponseTypeDef,
    StartColumnStatisticsTaskRunScheduleRequestTypeDef,
    StartCrawlerRequestTypeDef,
    StartCrawlerScheduleRequestTypeDef,
    StartDataQualityRuleRecommendationRunRequestTypeDef,
    StartDataQualityRuleRecommendationRunResponseTypeDef,
    StartDataQualityRulesetEvaluationRunRequestTypeDef,
    StartDataQualityRulesetEvaluationRunResponseTypeDef,
    StartExportLabelsTaskRunRequestTypeDef,
    StartExportLabelsTaskRunResponseTypeDef,
    StartImportLabelsTaskRunRequestTypeDef,
    StartImportLabelsTaskRunResponseTypeDef,
    StartJobRunRequestTypeDef,
    StartJobRunResponseTypeDef,
    StartMLEvaluationTaskRunRequestTypeDef,
    StartMLEvaluationTaskRunResponseTypeDef,
    StartMLLabelingSetGenerationTaskRunRequestTypeDef,
    StartMLLabelingSetGenerationTaskRunResponseTypeDef,
    StartMaterializedViewRefreshTaskRunRequestTypeDef,
    StartMaterializedViewRefreshTaskRunResponseTypeDef,
    StartTriggerRequestTypeDef,
    StartTriggerResponseTypeDef,
    StartWorkflowRunRequestTypeDef,
    StartWorkflowRunResponseTypeDef,
    StopColumnStatisticsTaskRunRequestTypeDef,
    StopColumnStatisticsTaskRunScheduleRequestTypeDef,
    StopCrawlerRequestTypeDef,
    StopCrawlerScheduleRequestTypeDef,
    StopMaterializedViewRefreshTaskRunRequestTypeDef,
    StopSessionRequestTypeDef,
    StopSessionResponseTypeDef,
    StopTriggerRequestTypeDef,
    StopTriggerResponseTypeDef,
    StopWorkflowRunRequestTypeDef,
    TagResourceRequestTypeDef,
    TestConnectionRequestTypeDef,
    UntagResourceRequestTypeDef,
    UpdateBlueprintRequestTypeDef,
    UpdateBlueprintResponseTypeDef,
    UpdateCatalogRequestTypeDef,
    UpdateClassifierRequestTypeDef,
    UpdateColumnStatisticsForPartitionRequestTypeDef,
    UpdateColumnStatisticsForPartitionResponseTypeDef,
    UpdateColumnStatisticsForTableRequestTypeDef,
    UpdateColumnStatisticsForTableResponseTypeDef,
    UpdateColumnStatisticsTaskSettingsRequestTypeDef,
    UpdateConnectionRequestTypeDef,
    UpdateCrawlerRequestTypeDef,
    UpdateCrawlerScheduleRequestTypeDef,
    UpdateDataQualityRulesetRequestTypeDef,
    UpdateDataQualityRulesetResponseTypeDef,
    UpdateDatabaseRequestTypeDef,
    UpdateDevEndpointRequestTypeDef,
    UpdateGlueIdentityCenterConfigurationRequestTypeDef,
    UpdateIntegrationResourcePropertyRequestTypeDef,
    UpdateIntegrationResourcePropertyResponseTypeDef,
    UpdateIntegrationTablePropertiesRequestTypeDef,
    UpdateJobFromSourceControlRequestTypeDef,
    UpdateJobFromSourceControlResponseTypeDef,
    UpdateJobRequestTypeDef,
    UpdateJobResponseTypeDef,
    UpdateMLTransformRequestTypeDef,
    UpdateMLTransformResponseTypeDef,
    UpdatePartitionRequestTypeDef,
    UpdateRegistryInputTypeDef,
    UpdateRegistryResponseTypeDef,
    UpdateSchemaInputTypeDef,
    UpdateSchemaResponseTypeDef,
    UpdateSourceControlFromJobRequestTypeDef,
    UpdateSourceControlFromJobResponseTypeDef,
    UpdateTableOptimizerRequestTypeDef,
    UpdateTableRequestTypeDef,
    UpdateTriggerRequestTypeDef,
    UpdateTriggerResponseTypeDef,
    UpdateUsageProfileRequestTypeDef,
    UpdateUsageProfileResponseTypeDef,
    UpdateUserDefinedFunctionRequestTypeDef,
    UpdateWorkflowRequestTypeDef,
    UpdateWorkflowResponseTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class GlueClient(TypedClientBase):
    _service_name = ServiceName.GLUE


    def batch_create_partition(
        self, request: BatchCreatePartitionRequestTypeDef,
    ) -> BatchCreatePartitionResponseTypeDef:
        return self._call(
            "batch_create_partition",
            request,
            BatchCreatePartitionResponseTypeDef,
        )


    def batch_delete_connection(
        self, request: BatchDeleteConnectionRequestTypeDef,
    ) -> BatchDeleteConnectionResponseTypeDef:
        return self._call(
            "batch_delete_connection",
            request,
            BatchDeleteConnectionResponseTypeDef,
        )


    def batch_delete_partition(
        self, request: BatchDeletePartitionRequestTypeDef,
    ) -> BatchDeletePartitionResponseTypeDef:
        return self._call(
            "batch_delete_partition",
            request,
            BatchDeletePartitionResponseTypeDef,
        )


    def batch_delete_table(
        self, request: BatchDeleteTableRequestTypeDef,
    ) -> BatchDeleteTableResponseTypeDef:
        return self._call(
            "batch_delete_table",
            request,
            BatchDeleteTableResponseTypeDef,
        )


    def batch_delete_table_version(
        self, request: BatchDeleteTableVersionRequestTypeDef,
    ) -> BatchDeleteTableVersionResponseTypeDef:
        return self._call(
            "batch_delete_table_version",
            request,
            BatchDeleteTableVersionResponseTypeDef,
        )


    def batch_get_blueprints(
        self, request: BatchGetBlueprintsRequestTypeDef,
    ) -> BatchGetBlueprintsResponseTypeDef:
        return self._call(
            "batch_get_blueprints",
            request,
            BatchGetBlueprintsResponseTypeDef,
        )


    def batch_get_crawlers(
        self, request: BatchGetCrawlersRequestTypeDef,
    ) -> BatchGetCrawlersResponseTypeDef:
        return self._call(
            "batch_get_crawlers",
            request,
            BatchGetCrawlersResponseTypeDef,
        )


    def batch_get_custom_entity_types(
        self, request: BatchGetCustomEntityTypesRequestTypeDef,
    ) -> BatchGetCustomEntityTypesResponseTypeDef:
        return self._call(
            "batch_get_custom_entity_types",
            request,
            BatchGetCustomEntityTypesResponseTypeDef,
        )


    def batch_get_data_quality_result(
        self, request: BatchGetDataQualityResultRequestTypeDef,
    ) -> BatchGetDataQualityResultResponseTypeDef:
        return self._call(
            "batch_get_data_quality_result",
            request,
            BatchGetDataQualityResultResponseTypeDef,
        )


    def batch_get_dev_endpoints(
        self, request: BatchGetDevEndpointsRequestTypeDef,
    ) -> BatchGetDevEndpointsResponseTypeDef:
        return self._call(
            "batch_get_dev_endpoints",
            request,
            BatchGetDevEndpointsResponseTypeDef,
        )


    def batch_get_jobs(
        self, request: BatchGetJobsRequestTypeDef,
    ) -> BatchGetJobsResponseTypeDef:
        return self._call(
            "batch_get_jobs",
            request,
            BatchGetJobsResponseTypeDef,
        )


    def batch_get_partition(
        self, request: BatchGetPartitionRequestTypeDef,
    ) -> BatchGetPartitionResponseTypeDef:
        return self._call(
            "batch_get_partition",
            request,
            BatchGetPartitionResponseTypeDef,
        )


    def batch_get_table_optimizer(
        self, request: BatchGetTableOptimizerRequestTypeDef,
    ) -> BatchGetTableOptimizerResponseTypeDef:
        return self._call(
            "batch_get_table_optimizer",
            request,
            BatchGetTableOptimizerResponseTypeDef,
        )


    def batch_get_triggers(
        self, request: BatchGetTriggersRequestTypeDef,
    ) -> BatchGetTriggersResponseTypeDef:
        return self._call(
            "batch_get_triggers",
            request,
            BatchGetTriggersResponseTypeDef,
        )


    def batch_get_workflows(
        self, request: BatchGetWorkflowsRequestTypeDef,
    ) -> BatchGetWorkflowsResponseTypeDef:
        return self._call(
            "batch_get_workflows",
            request,
            BatchGetWorkflowsResponseTypeDef,
        )


    def batch_put_data_quality_statistic_annotation(
        self, request: BatchPutDataQualityStatisticAnnotationRequestTypeDef,
    ) -> BatchPutDataQualityStatisticAnnotationResponseTypeDef:
        return self._call(
            "batch_put_data_quality_statistic_annotation",
            request,
            BatchPutDataQualityStatisticAnnotationResponseTypeDef,
        )


    def batch_stop_job_run(
        self, request: BatchStopJobRunRequestTypeDef,
    ) -> BatchStopJobRunResponseTypeDef:
        return self._call(
            "batch_stop_job_run",
            request,
            BatchStopJobRunResponseTypeDef,
        )


    def batch_update_partition(
        self, request: BatchUpdatePartitionRequestTypeDef,
    ) -> BatchUpdatePartitionResponseTypeDef:
        return self._call(
            "batch_update_partition",
            request,
            BatchUpdatePartitionResponseTypeDef,
        )


    def cancel_data_quality_rule_recommendation_run(
        self, request: CancelDataQualityRuleRecommendationRunRequestTypeDef,
    ) -> None:
        return self._call(
            "cancel_data_quality_rule_recommendation_run",
            request,
            None,
        )


    def cancel_data_quality_ruleset_evaluation_run(
        self, request: CancelDataQualityRulesetEvaluationRunRequestTypeDef,
    ) -> None:
        return self._call(
            "cancel_data_quality_ruleset_evaluation_run",
            request,
            None,
        )


    def cancel_ml_task_run(
        self, request: CancelMLTaskRunRequestTypeDef,
    ) -> CancelMLTaskRunResponseTypeDef:
        return self._call(
            "cancel_ml_task_run",
            request,
            CancelMLTaskRunResponseTypeDef,
        )


    def cancel_statement(
        self, request: CancelStatementRequestTypeDef,
    ) -> None:
        return self._call(
            "cancel_statement",
            request,
            None,
        )


    def check_schema_version_validity(
        self, request: CheckSchemaVersionValidityInputTypeDef,
    ) -> CheckSchemaVersionValidityResponseTypeDef:
        return self._call(
            "check_schema_version_validity",
            request,
            CheckSchemaVersionValidityResponseTypeDef,
        )


    def create_blueprint(
        self, request: CreateBlueprintRequestTypeDef,
    ) -> CreateBlueprintResponseTypeDef:
        return self._call(
            "create_blueprint",
            request,
            CreateBlueprintResponseTypeDef,
        )


    def create_catalog(
        self, request: CreateCatalogRequestTypeDef,
    ) -> None:
        return self._call(
            "create_catalog",
            request,
            None,
        )


    def create_classifier(
        self, request: CreateClassifierRequestTypeDef,
    ) -> None:
        return self._call(
            "create_classifier",
            request,
            None,
        )


    def create_column_statistics_task_settings(
        self, request: CreateColumnStatisticsTaskSettingsRequestTypeDef,
    ) -> None:
        return self._call(
            "create_column_statistics_task_settings",
            request,
            None,
        )


    def create_connection(
        self, request: CreateConnectionRequestTypeDef,
    ) -> CreateConnectionResponseTypeDef:
        return self._call(
            "create_connection",
            request,
            CreateConnectionResponseTypeDef,
        )


    def create_crawler(
        self, request: CreateCrawlerRequestTypeDef,
    ) -> None:
        return self._call(
            "create_crawler",
            request,
            None,
        )


    def create_custom_entity_type(
        self, request: CreateCustomEntityTypeRequestTypeDef,
    ) -> CreateCustomEntityTypeResponseTypeDef:
        return self._call(
            "create_custom_entity_type",
            request,
            CreateCustomEntityTypeResponseTypeDef,
        )


    def create_data_quality_ruleset(
        self, request: CreateDataQualityRulesetRequestTypeDef,
    ) -> CreateDataQualityRulesetResponseTypeDef:
        return self._call(
            "create_data_quality_ruleset",
            request,
            CreateDataQualityRulesetResponseTypeDef,
        )


    def create_database(
        self, request: CreateDatabaseRequestTypeDef,
    ) -> None:
        return self._call(
            "create_database",
            request,
            None,
        )


    def create_dev_endpoint(
        self, request: CreateDevEndpointRequestTypeDef,
    ) -> CreateDevEndpointResponseTypeDef:
        return self._call(
            "create_dev_endpoint",
            request,
            CreateDevEndpointResponseTypeDef,
        )


    def create_glue_identity_center_configuration(
        self, request: CreateGlueIdentityCenterConfigurationRequestTypeDef,
    ) -> CreateGlueIdentityCenterConfigurationResponseTypeDef:
        return self._call(
            "create_glue_identity_center_configuration",
            request,
            CreateGlueIdentityCenterConfigurationResponseTypeDef,
        )


    def create_integration(
        self, request: CreateIntegrationRequestTypeDef,
    ) -> CreateIntegrationResponseTypeDef:
        return self._call(
            "create_integration",
            request,
            CreateIntegrationResponseTypeDef,
        )


    def create_integration_resource_property(
        self, request: CreateIntegrationResourcePropertyRequestTypeDef,
    ) -> CreateIntegrationResourcePropertyResponseTypeDef:
        return self._call(
            "create_integration_resource_property",
            request,
            CreateIntegrationResourcePropertyResponseTypeDef,
        )


    def create_integration_table_properties(
        self, request: CreateIntegrationTablePropertiesRequestTypeDef,
    ) -> None:
        return self._call(
            "create_integration_table_properties",
            request,
            None,
        )


    def create_job(
        self, request: CreateJobRequestTypeDef,
    ) -> CreateJobResponseTypeDef:
        return self._call(
            "create_job",
            request,
            CreateJobResponseTypeDef,
        )


    def create_ml_transform(
        self, request: CreateMLTransformRequestTypeDef,
    ) -> CreateMLTransformResponseTypeDef:
        return self._call(
            "create_ml_transform",
            request,
            CreateMLTransformResponseTypeDef,
        )


    def create_partition(
        self, request: CreatePartitionRequestTypeDef,
    ) -> None:
        return self._call(
            "create_partition",
            request,
            None,
        )


    def create_partition_index(
        self, request: CreatePartitionIndexRequestTypeDef,
    ) -> None:
        return self._call(
            "create_partition_index",
            request,
            None,
        )


    def create_registry(
        self, request: CreateRegistryInputTypeDef,
    ) -> CreateRegistryResponseTypeDef:
        return self._call(
            "create_registry",
            request,
            CreateRegistryResponseTypeDef,
        )


    def create_schema(
        self, request: CreateSchemaInputTypeDef,
    ) -> CreateSchemaResponseTypeDef:
        return self._call(
            "create_schema",
            request,
            CreateSchemaResponseTypeDef,
        )


    def create_script(
        self, request: CreateScriptRequestTypeDef,
    ) -> CreateScriptResponseTypeDef:
        return self._call(
            "create_script",
            request,
            CreateScriptResponseTypeDef,
        )


    def create_security_configuration(
        self, request: CreateSecurityConfigurationRequestTypeDef,
    ) -> CreateSecurityConfigurationResponseTypeDef:
        return self._call(
            "create_security_configuration",
            request,
            CreateSecurityConfigurationResponseTypeDef,
        )


    def create_session(
        self, request: CreateSessionRequestTypeDef,
    ) -> CreateSessionResponseTypeDef:
        return self._call(
            "create_session",
            request,
            CreateSessionResponseTypeDef,
        )


    def create_table(
        self, request: CreateTableRequestTypeDef,
    ) -> None:
        return self._call(
            "create_table",
            request,
            None,
        )


    def create_table_optimizer(
        self, request: CreateTableOptimizerRequestTypeDef,
    ) -> None:
        return self._call(
            "create_table_optimizer",
            request,
            None,
        )


    def create_trigger(
        self, request: CreateTriggerRequestTypeDef,
    ) -> CreateTriggerResponseTypeDef:
        return self._call(
            "create_trigger",
            request,
            CreateTriggerResponseTypeDef,
        )


    def create_usage_profile(
        self, request: CreateUsageProfileRequestTypeDef,
    ) -> CreateUsageProfileResponseTypeDef:
        return self._call(
            "create_usage_profile",
            request,
            CreateUsageProfileResponseTypeDef,
        )


    def create_user_defined_function(
        self, request: CreateUserDefinedFunctionRequestTypeDef,
    ) -> None:
        return self._call(
            "create_user_defined_function",
            request,
            None,
        )


    def create_workflow(
        self, request: CreateWorkflowRequestTypeDef,
    ) -> CreateWorkflowResponseTypeDef:
        return self._call(
            "create_workflow",
            request,
            CreateWorkflowResponseTypeDef,
        )


    def delete_blueprint(
        self, request: DeleteBlueprintRequestTypeDef,
    ) -> DeleteBlueprintResponseTypeDef:
        return self._call(
            "delete_blueprint",
            request,
            DeleteBlueprintResponseTypeDef,
        )


    def delete_catalog(
        self, request: DeleteCatalogRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_catalog",
            request,
            None,
        )


    def delete_classifier(
        self, request: DeleteClassifierRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_classifier",
            request,
            None,
        )


    def delete_column_statistics_for_partition(
        self, request: DeleteColumnStatisticsForPartitionRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_column_statistics_for_partition",
            request,
            None,
        )


    def delete_column_statistics_for_table(
        self, request: DeleteColumnStatisticsForTableRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_column_statistics_for_table",
            request,
            None,
        )


    def delete_column_statistics_task_settings(
        self, request: DeleteColumnStatisticsTaskSettingsRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_column_statistics_task_settings",
            request,
            None,
        )


    def delete_connection(
        self, request: DeleteConnectionRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_connection",
            request,
            None,
        )


    def delete_connection_type(
        self, request: DeleteConnectionTypeRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_connection_type",
            request,
            None,
        )


    def delete_crawler(
        self, request: DeleteCrawlerRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_crawler",
            request,
            None,
        )


    def delete_custom_entity_type(
        self, request: DeleteCustomEntityTypeRequestTypeDef,
    ) -> DeleteCustomEntityTypeResponseTypeDef:
        return self._call(
            "delete_custom_entity_type",
            request,
            DeleteCustomEntityTypeResponseTypeDef,
        )


    def delete_data_quality_ruleset(
        self, request: DeleteDataQualityRulesetRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_data_quality_ruleset",
            request,
            None,
        )


    def delete_database(
        self, request: DeleteDatabaseRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_database",
            request,
            None,
        )


    def delete_dev_endpoint(
        self, request: DeleteDevEndpointRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_dev_endpoint",
            request,
            None,
        )


    def delete_glue_identity_center_configuration(
        self,
    ) -> None:
        return self._call(
            "delete_glue_identity_center_configuration",
            None,
            None,
        )


    def delete_integration(
        self, request: DeleteIntegrationRequestTypeDef,
    ) -> DeleteIntegrationResponseTypeDef:
        return self._call(
            "delete_integration",
            request,
            DeleteIntegrationResponseTypeDef,
        )


    def delete_integration_resource_property(
        self, request: DeleteIntegrationResourcePropertyRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_integration_resource_property",
            request,
            None,
        )


    def delete_integration_table_properties(
        self, request: DeleteIntegrationTablePropertiesRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_integration_table_properties",
            request,
            None,
        )


    def delete_job(
        self, request: DeleteJobRequestTypeDef,
    ) -> DeleteJobResponseTypeDef:
        return self._call(
            "delete_job",
            request,
            DeleteJobResponseTypeDef,
        )


    def delete_ml_transform(
        self, request: DeleteMLTransformRequestTypeDef,
    ) -> DeleteMLTransformResponseTypeDef:
        return self._call(
            "delete_ml_transform",
            request,
            DeleteMLTransformResponseTypeDef,
        )


    def delete_partition(
        self, request: DeletePartitionRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_partition",
            request,
            None,
        )


    def delete_partition_index(
        self, request: DeletePartitionIndexRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_partition_index",
            request,
            None,
        )


    def delete_registry(
        self, request: DeleteRegistryInputTypeDef,
    ) -> DeleteRegistryResponseTypeDef:
        return self._call(
            "delete_registry",
            request,
            DeleteRegistryResponseTypeDef,
        )


    def delete_resource_policy(
        self, request: DeleteResourcePolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_resource_policy",
            request,
            None,
        )


    def delete_schema(
        self, request: DeleteSchemaInputTypeDef,
    ) -> DeleteSchemaResponseTypeDef:
        return self._call(
            "delete_schema",
            request,
            DeleteSchemaResponseTypeDef,
        )


    def delete_schema_versions(
        self, request: DeleteSchemaVersionsInputTypeDef,
    ) -> DeleteSchemaVersionsResponseTypeDef:
        return self._call(
            "delete_schema_versions",
            request,
            DeleteSchemaVersionsResponseTypeDef,
        )


    def delete_security_configuration(
        self, request: DeleteSecurityConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_security_configuration",
            request,
            None,
        )


    def delete_session(
        self, request: DeleteSessionRequestTypeDef,
    ) -> DeleteSessionResponseTypeDef:
        return self._call(
            "delete_session",
            request,
            DeleteSessionResponseTypeDef,
        )


    def delete_table(
        self, request: DeleteTableRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_table",
            request,
            None,
        )


    def delete_table_optimizer(
        self, request: DeleteTableOptimizerRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_table_optimizer",
            request,
            None,
        )


    def delete_table_version(
        self, request: DeleteTableVersionRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_table_version",
            request,
            None,
        )


    def delete_trigger(
        self, request: DeleteTriggerRequestTypeDef,
    ) -> DeleteTriggerResponseTypeDef:
        return self._call(
            "delete_trigger",
            request,
            DeleteTriggerResponseTypeDef,
        )


    def delete_usage_profile(
        self, request: DeleteUsageProfileRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_usage_profile",
            request,
            None,
        )


    def delete_user_defined_function(
        self, request: DeleteUserDefinedFunctionRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_user_defined_function",
            request,
            None,
        )


    def delete_workflow(
        self, request: DeleteWorkflowRequestTypeDef,
    ) -> DeleteWorkflowResponseTypeDef:
        return self._call(
            "delete_workflow",
            request,
            DeleteWorkflowResponseTypeDef,
        )


    def describe_connection_type(
        self, request: DescribeConnectionTypeRequestTypeDef,
    ) -> DescribeConnectionTypeResponseTypeDef:
        return self._call(
            "describe_connection_type",
            request,
            DescribeConnectionTypeResponseTypeDef,
        )


    def describe_entity(
        self, request: DescribeEntityRequestTypeDef,
    ) -> DescribeEntityResponseTypeDef:
        return self._call(
            "describe_entity",
            request,
            DescribeEntityResponseTypeDef,
        )


    def describe_inbound_integrations(
        self, request: DescribeInboundIntegrationsRequestTypeDef,
    ) -> DescribeInboundIntegrationsResponseTypeDef:
        return self._call(
            "describe_inbound_integrations",
            request,
            DescribeInboundIntegrationsResponseTypeDef,
        )


    def describe_integrations(
        self, request: DescribeIntegrationsRequestTypeDef,
    ) -> DescribeIntegrationsResponseTypeDef:
        return self._call(
            "describe_integrations",
            request,
            DescribeIntegrationsResponseTypeDef,
        )


    def get_blueprint(
        self, request: GetBlueprintRequestTypeDef,
    ) -> GetBlueprintResponseTypeDef:
        return self._call(
            "get_blueprint",
            request,
            GetBlueprintResponseTypeDef,
        )


    def get_blueprint_run(
        self, request: GetBlueprintRunRequestTypeDef,
    ) -> GetBlueprintRunResponseTypeDef:
        return self._call(
            "get_blueprint_run",
            request,
            GetBlueprintRunResponseTypeDef,
        )


    def get_blueprint_runs(
        self, request: GetBlueprintRunsRequestTypeDef,
    ) -> GetBlueprintRunsResponseTypeDef:
        return self._call(
            "get_blueprint_runs",
            request,
            GetBlueprintRunsResponseTypeDef,
        )


    def get_catalog(
        self, request: GetCatalogRequestTypeDef,
    ) -> GetCatalogResponseTypeDef:
        return self._call(
            "get_catalog",
            request,
            GetCatalogResponseTypeDef,
        )


    def get_catalog_import_status(
        self, request: GetCatalogImportStatusRequestTypeDef,
    ) -> GetCatalogImportStatusResponseTypeDef:
        return self._call(
            "get_catalog_import_status",
            request,
            GetCatalogImportStatusResponseTypeDef,
        )


    def get_catalogs(
        self, request: GetCatalogsRequestTypeDef,
    ) -> GetCatalogsResponseTypeDef:
        return self._call(
            "get_catalogs",
            request,
            GetCatalogsResponseTypeDef,
        )


    def get_classifier(
        self, request: GetClassifierRequestTypeDef,
    ) -> GetClassifierResponseTypeDef:
        return self._call(
            "get_classifier",
            request,
            GetClassifierResponseTypeDef,
        )


    def get_classifiers(
        self, request: GetClassifiersRequestTypeDef,
    ) -> GetClassifiersResponseTypeDef:
        return self._call(
            "get_classifiers",
            request,
            GetClassifiersResponseTypeDef,
        )


    def get_column_statistics_for_partition(
        self, request: GetColumnStatisticsForPartitionRequestTypeDef,
    ) -> GetColumnStatisticsForPartitionResponseTypeDef:
        return self._call(
            "get_column_statistics_for_partition",
            request,
            GetColumnStatisticsForPartitionResponseTypeDef,
        )


    def get_column_statistics_for_table(
        self, request: GetColumnStatisticsForTableRequestTypeDef,
    ) -> GetColumnStatisticsForTableResponseTypeDef:
        return self._call(
            "get_column_statistics_for_table",
            request,
            GetColumnStatisticsForTableResponseTypeDef,
        )


    def get_column_statistics_task_run(
        self, request: GetColumnStatisticsTaskRunRequestTypeDef,
    ) -> GetColumnStatisticsTaskRunResponseTypeDef:
        return self._call(
            "get_column_statistics_task_run",
            request,
            GetColumnStatisticsTaskRunResponseTypeDef,
        )


    def get_column_statistics_task_runs(
        self, request: GetColumnStatisticsTaskRunsRequestTypeDef,
    ) -> GetColumnStatisticsTaskRunsResponseTypeDef:
        return self._call(
            "get_column_statistics_task_runs",
            request,
            GetColumnStatisticsTaskRunsResponseTypeDef,
        )


    def get_column_statistics_task_settings(
        self, request: GetColumnStatisticsTaskSettingsRequestTypeDef,
    ) -> GetColumnStatisticsTaskSettingsResponseTypeDef:
        return self._call(
            "get_column_statistics_task_settings",
            request,
            GetColumnStatisticsTaskSettingsResponseTypeDef,
        )


    def get_connection(
        self, request: GetConnectionRequestTypeDef,
    ) -> GetConnectionResponseTypeDef:
        return self._call(
            "get_connection",
            request,
            GetConnectionResponseTypeDef,
        )


    def get_connections(
        self, request: GetConnectionsRequestTypeDef,
    ) -> GetConnectionsResponseTypeDef:
        return self._call(
            "get_connections",
            request,
            GetConnectionsResponseTypeDef,
        )


    def get_crawler(
        self, request: GetCrawlerRequestTypeDef,
    ) -> GetCrawlerResponseTypeDef:
        return self._call(
            "get_crawler",
            request,
            GetCrawlerResponseTypeDef,
        )


    def get_crawler_metrics(
        self, request: GetCrawlerMetricsRequestTypeDef,
    ) -> GetCrawlerMetricsResponseTypeDef:
        return self._call(
            "get_crawler_metrics",
            request,
            GetCrawlerMetricsResponseTypeDef,
        )


    def get_crawlers(
        self, request: GetCrawlersRequestTypeDef,
    ) -> GetCrawlersResponseTypeDef:
        return self._call(
            "get_crawlers",
            request,
            GetCrawlersResponseTypeDef,
        )


    def get_custom_entity_type(
        self, request: GetCustomEntityTypeRequestTypeDef,
    ) -> GetCustomEntityTypeResponseTypeDef:
        return self._call(
            "get_custom_entity_type",
            request,
            GetCustomEntityTypeResponseTypeDef,
        )


    def get_data_catalog_encryption_settings(
        self, request: GetDataCatalogEncryptionSettingsRequestTypeDef,
    ) -> GetDataCatalogEncryptionSettingsResponseTypeDef:
        return self._call(
            "get_data_catalog_encryption_settings",
            request,
            GetDataCatalogEncryptionSettingsResponseTypeDef,
        )


    def get_data_quality_model(
        self, request: GetDataQualityModelRequestTypeDef,
    ) -> GetDataQualityModelResponseTypeDef:
        return self._call(
            "get_data_quality_model",
            request,
            GetDataQualityModelResponseTypeDef,
        )


    def get_data_quality_model_result(
        self, request: GetDataQualityModelResultRequestTypeDef,
    ) -> GetDataQualityModelResultResponseTypeDef:
        return self._call(
            "get_data_quality_model_result",
            request,
            GetDataQualityModelResultResponseTypeDef,
        )


    def get_data_quality_result(
        self, request: GetDataQualityResultRequestTypeDef,
    ) -> GetDataQualityResultResponseTypeDef:
        return self._call(
            "get_data_quality_result",
            request,
            GetDataQualityResultResponseTypeDef,
        )


    def get_data_quality_rule_recommendation_run(
        self, request: GetDataQualityRuleRecommendationRunRequestTypeDef,
    ) -> GetDataQualityRuleRecommendationRunResponseTypeDef:
        return self._call(
            "get_data_quality_rule_recommendation_run",
            request,
            GetDataQualityRuleRecommendationRunResponseTypeDef,
        )


    def get_data_quality_ruleset(
        self, request: GetDataQualityRulesetRequestTypeDef,
    ) -> GetDataQualityRulesetResponseTypeDef:
        return self._call(
            "get_data_quality_ruleset",
            request,
            GetDataQualityRulesetResponseTypeDef,
        )


    def get_data_quality_ruleset_evaluation_run(
        self, request: GetDataQualityRulesetEvaluationRunRequestTypeDef,
    ) -> GetDataQualityRulesetEvaluationRunResponseTypeDef:
        return self._call(
            "get_data_quality_ruleset_evaluation_run",
            request,
            GetDataQualityRulesetEvaluationRunResponseTypeDef,
        )


    def get_database(
        self, request: GetDatabaseRequestTypeDef,
    ) -> GetDatabaseResponseTypeDef:
        return self._call(
            "get_database",
            request,
            GetDatabaseResponseTypeDef,
        )


    def get_databases(
        self, request: GetDatabasesRequestTypeDef,
    ) -> GetDatabasesResponseTypeDef:
        return self._call(
            "get_databases",
            request,
            GetDatabasesResponseTypeDef,
        )


    def get_dataflow_graph(
        self, request: GetDataflowGraphRequestTypeDef,
    ) -> GetDataflowGraphResponseTypeDef:
        return self._call(
            "get_dataflow_graph",
            request,
            GetDataflowGraphResponseTypeDef,
        )


    def get_dev_endpoint(
        self, request: GetDevEndpointRequestTypeDef,
    ) -> GetDevEndpointResponseTypeDef:
        return self._call(
            "get_dev_endpoint",
            request,
            GetDevEndpointResponseTypeDef,
        )


    def get_dev_endpoints(
        self, request: GetDevEndpointsRequestTypeDef,
    ) -> GetDevEndpointsResponseTypeDef:
        return self._call(
            "get_dev_endpoints",
            request,
            GetDevEndpointsResponseTypeDef,
        )


    def get_entity_records(
        self, request: GetEntityRecordsRequestTypeDef,
    ) -> GetEntityRecordsResponseTypeDef:
        return self._call(
            "get_entity_records",
            request,
            GetEntityRecordsResponseTypeDef,
        )


    def get_glue_identity_center_configuration(
        self,
    ) -> GetGlueIdentityCenterConfigurationResponseTypeDef:
        return self._call(
            "get_glue_identity_center_configuration",
            None,
            GetGlueIdentityCenterConfigurationResponseTypeDef,
        )


    def get_integration_resource_property(
        self, request: GetIntegrationResourcePropertyRequestTypeDef,
    ) -> GetIntegrationResourcePropertyResponseTypeDef:
        return self._call(
            "get_integration_resource_property",
            request,
            GetIntegrationResourcePropertyResponseTypeDef,
        )


    def get_integration_table_properties(
        self, request: GetIntegrationTablePropertiesRequestTypeDef,
    ) -> GetIntegrationTablePropertiesResponseTypeDef:
        return self._call(
            "get_integration_table_properties",
            request,
            GetIntegrationTablePropertiesResponseTypeDef,
        )


    def get_job(
        self, request: GetJobRequestTypeDef,
    ) -> GetJobResponseTypeDef:
        return self._call(
            "get_job",
            request,
            GetJobResponseTypeDef,
        )


    def get_job_bookmark(
        self, request: GetJobBookmarkRequestTypeDef,
    ) -> GetJobBookmarkResponseTypeDef:
        return self._call(
            "get_job_bookmark",
            request,
            GetJobBookmarkResponseTypeDef,
        )


    def get_job_run(
        self, request: GetJobRunRequestTypeDef,
    ) -> GetJobRunResponseTypeDef:
        return self._call(
            "get_job_run",
            request,
            GetJobRunResponseTypeDef,
        )


    def get_job_runs(
        self, request: GetJobRunsRequestTypeDef,
    ) -> GetJobRunsResponseTypeDef:
        return self._call(
            "get_job_runs",
            request,
            GetJobRunsResponseTypeDef,
        )


    def get_jobs(
        self, request: GetJobsRequestTypeDef,
    ) -> GetJobsResponseTypeDef:
        return self._call(
            "get_jobs",
            request,
            GetJobsResponseTypeDef,
        )


    def get_mapping(
        self, request: GetMappingRequestTypeDef,
    ) -> GetMappingResponseTypeDef:
        return self._call(
            "get_mapping",
            request,
            GetMappingResponseTypeDef,
        )


    def get_materialized_view_refresh_task_run(
        self, request: GetMaterializedViewRefreshTaskRunRequestTypeDef,
    ) -> GetMaterializedViewRefreshTaskRunResponseTypeDef:
        return self._call(
            "get_materialized_view_refresh_task_run",
            request,
            GetMaterializedViewRefreshTaskRunResponseTypeDef,
        )


    def get_ml_task_run(
        self, request: GetMLTaskRunRequestTypeDef,
    ) -> GetMLTaskRunResponseTypeDef:
        return self._call(
            "get_ml_task_run",
            request,
            GetMLTaskRunResponseTypeDef,
        )


    def get_ml_task_runs(
        self, request: GetMLTaskRunsRequestTypeDef,
    ) -> GetMLTaskRunsResponseTypeDef:
        return self._call(
            "get_ml_task_runs",
            request,
            GetMLTaskRunsResponseTypeDef,
        )


    def get_ml_transform(
        self, request: GetMLTransformRequestTypeDef,
    ) -> GetMLTransformResponseTypeDef:
        return self._call(
            "get_ml_transform",
            request,
            GetMLTransformResponseTypeDef,
        )


    def get_ml_transforms(
        self, request: GetMLTransformsRequestTypeDef,
    ) -> GetMLTransformsResponseTypeDef:
        return self._call(
            "get_ml_transforms",
            request,
            GetMLTransformsResponseTypeDef,
        )


    def get_partition(
        self, request: GetPartitionRequestTypeDef,
    ) -> GetPartitionResponseTypeDef:
        return self._call(
            "get_partition",
            request,
            GetPartitionResponseTypeDef,
        )


    def get_partition_indexes(
        self, request: GetPartitionIndexesRequestTypeDef,
    ) -> GetPartitionIndexesResponseTypeDef:
        return self._call(
            "get_partition_indexes",
            request,
            GetPartitionIndexesResponseTypeDef,
        )


    def get_partitions(
        self, request: GetPartitionsRequestTypeDef,
    ) -> GetPartitionsResponseTypeDef:
        return self._call(
            "get_partitions",
            request,
            GetPartitionsResponseTypeDef,
        )


    def get_plan(
        self, request: GetPlanRequestTypeDef,
    ) -> GetPlanResponseTypeDef:
        return self._call(
            "get_plan",
            request,
            GetPlanResponseTypeDef,
        )


    def get_registry(
        self, request: GetRegistryInputTypeDef,
    ) -> GetRegistryResponseTypeDef:
        return self._call(
            "get_registry",
            request,
            GetRegistryResponseTypeDef,
        )


    def get_resource_policies(
        self, request: GetResourcePoliciesRequestTypeDef,
    ) -> GetResourcePoliciesResponseTypeDef:
        return self._call(
            "get_resource_policies",
            request,
            GetResourcePoliciesResponseTypeDef,
        )


    def get_resource_policy(
        self, request: GetResourcePolicyRequestTypeDef,
    ) -> GetResourcePolicyResponseTypeDef:
        return self._call(
            "get_resource_policy",
            request,
            GetResourcePolicyResponseTypeDef,
        )


    def get_schema(
        self, request: GetSchemaInputTypeDef,
    ) -> GetSchemaResponseTypeDef:
        return self._call(
            "get_schema",
            request,
            GetSchemaResponseTypeDef,
        )


    def get_schema_by_definition(
        self, request: GetSchemaByDefinitionInputTypeDef,
    ) -> GetSchemaByDefinitionResponseTypeDef:
        return self._call(
            "get_schema_by_definition",
            request,
            GetSchemaByDefinitionResponseTypeDef,
        )


    def get_schema_version(
        self, request: GetSchemaVersionInputTypeDef,
    ) -> GetSchemaVersionResponseTypeDef:
        return self._call(
            "get_schema_version",
            request,
            GetSchemaVersionResponseTypeDef,
        )


    def get_schema_versions_diff(
        self, request: GetSchemaVersionsDiffInputTypeDef,
    ) -> GetSchemaVersionsDiffResponseTypeDef:
        return self._call(
            "get_schema_versions_diff",
            request,
            GetSchemaVersionsDiffResponseTypeDef,
        )


    def get_security_configuration(
        self, request: GetSecurityConfigurationRequestTypeDef,
    ) -> GetSecurityConfigurationResponseTypeDef:
        return self._call(
            "get_security_configuration",
            request,
            GetSecurityConfigurationResponseTypeDef,
        )


    def get_security_configurations(
        self, request: GetSecurityConfigurationsRequestTypeDef,
    ) -> GetSecurityConfigurationsResponseTypeDef:
        return self._call(
            "get_security_configurations",
            request,
            GetSecurityConfigurationsResponseTypeDef,
        )


    def get_session(
        self, request: GetSessionRequestTypeDef,
    ) -> GetSessionResponseTypeDef:
        return self._call(
            "get_session",
            request,
            GetSessionResponseTypeDef,
        )


    def get_statement(
        self, request: GetStatementRequestTypeDef,
    ) -> GetStatementResponseTypeDef:
        return self._call(
            "get_statement",
            request,
            GetStatementResponseTypeDef,
        )


    def get_table(
        self, request: GetTableRequestTypeDef,
    ) -> GetTableResponseTypeDef:
        return self._call(
            "get_table",
            request,
            GetTableResponseTypeDef,
        )


    def get_table_optimizer(
        self, request: GetTableOptimizerRequestTypeDef,
    ) -> GetTableOptimizerResponseTypeDef:
        return self._call(
            "get_table_optimizer",
            request,
            GetTableOptimizerResponseTypeDef,
        )


    def get_table_version(
        self, request: GetTableVersionRequestTypeDef,
    ) -> GetTableVersionResponseTypeDef:
        return self._call(
            "get_table_version",
            request,
            GetTableVersionResponseTypeDef,
        )


    def get_table_versions(
        self, request: GetTableVersionsRequestTypeDef,
    ) -> GetTableVersionsResponseTypeDef:
        return self._call(
            "get_table_versions",
            request,
            GetTableVersionsResponseTypeDef,
        )


    def get_tables(
        self, request: GetTablesRequestTypeDef,
    ) -> GetTablesResponseTypeDef:
        return self._call(
            "get_tables",
            request,
            GetTablesResponseTypeDef,
        )


    def get_tags(
        self, request: GetTagsRequestTypeDef,
    ) -> GetTagsResponseTypeDef:
        return self._call(
            "get_tags",
            request,
            GetTagsResponseTypeDef,
        )


    def get_trigger(
        self, request: GetTriggerRequestTypeDef,
    ) -> GetTriggerResponseTypeDef:
        return self._call(
            "get_trigger",
            request,
            GetTriggerResponseTypeDef,
        )


    def get_triggers(
        self, request: GetTriggersRequestTypeDef,
    ) -> GetTriggersResponseTypeDef:
        return self._call(
            "get_triggers",
            request,
            GetTriggersResponseTypeDef,
        )


    def get_unfiltered_partition_metadata(
        self, request: GetUnfilteredPartitionMetadataRequestTypeDef,
    ) -> GetUnfilteredPartitionMetadataResponseTypeDef:
        return self._call(
            "get_unfiltered_partition_metadata",
            request,
            GetUnfilteredPartitionMetadataResponseTypeDef,
        )


    def get_unfiltered_partitions_metadata(
        self, request: GetUnfilteredPartitionsMetadataRequestTypeDef,
    ) -> GetUnfilteredPartitionsMetadataResponseTypeDef:
        return self._call(
            "get_unfiltered_partitions_metadata",
            request,
            GetUnfilteredPartitionsMetadataResponseTypeDef,
        )


    def get_unfiltered_table_metadata(
        self, request: GetUnfilteredTableMetadataRequestTypeDef,
    ) -> GetUnfilteredTableMetadataResponseTypeDef:
        return self._call(
            "get_unfiltered_table_metadata",
            request,
            GetUnfilteredTableMetadataResponseTypeDef,
        )


    def get_usage_profile(
        self, request: GetUsageProfileRequestTypeDef,
    ) -> GetUsageProfileResponseTypeDef:
        return self._call(
            "get_usage_profile",
            request,
            GetUsageProfileResponseTypeDef,
        )


    def get_user_defined_function(
        self, request: GetUserDefinedFunctionRequestTypeDef,
    ) -> GetUserDefinedFunctionResponseTypeDef:
        return self._call(
            "get_user_defined_function",
            request,
            GetUserDefinedFunctionResponseTypeDef,
        )


    def get_user_defined_functions(
        self, request: GetUserDefinedFunctionsRequestTypeDef,
    ) -> GetUserDefinedFunctionsResponseTypeDef:
        return self._call(
            "get_user_defined_functions",
            request,
            GetUserDefinedFunctionsResponseTypeDef,
        )


    def get_workflow(
        self, request: GetWorkflowRequestTypeDef,
    ) -> GetWorkflowResponseTypeDef:
        return self._call(
            "get_workflow",
            request,
            GetWorkflowResponseTypeDef,
        )


    def get_workflow_run(
        self, request: GetWorkflowRunRequestTypeDef,
    ) -> GetWorkflowRunResponseTypeDef:
        return self._call(
            "get_workflow_run",
            request,
            GetWorkflowRunResponseTypeDef,
        )


    def get_workflow_run_properties(
        self, request: GetWorkflowRunPropertiesRequestTypeDef,
    ) -> GetWorkflowRunPropertiesResponseTypeDef:
        return self._call(
            "get_workflow_run_properties",
            request,
            GetWorkflowRunPropertiesResponseTypeDef,
        )


    def get_workflow_runs(
        self, request: GetWorkflowRunsRequestTypeDef,
    ) -> GetWorkflowRunsResponseTypeDef:
        return self._call(
            "get_workflow_runs",
            request,
            GetWorkflowRunsResponseTypeDef,
        )


    def import_catalog_to_glue(
        self, request: ImportCatalogToGlueRequestTypeDef,
    ) -> None:
        return self._call(
            "import_catalog_to_glue",
            request,
            None,
        )


    def list_blueprints(
        self, request: ListBlueprintsRequestTypeDef,
    ) -> ListBlueprintsResponseTypeDef:
        return self._call(
            "list_blueprints",
            request,
            ListBlueprintsResponseTypeDef,
        )


    def list_column_statistics_task_runs(
        self, request: ListColumnStatisticsTaskRunsRequestTypeDef,
    ) -> ListColumnStatisticsTaskRunsResponseTypeDef:
        return self._call(
            "list_column_statistics_task_runs",
            request,
            ListColumnStatisticsTaskRunsResponseTypeDef,
        )


    def list_connection_types(
        self, request: ListConnectionTypesRequestTypeDef,
    ) -> ListConnectionTypesResponseTypeDef:
        return self._call(
            "list_connection_types",
            request,
            ListConnectionTypesResponseTypeDef,
        )


    def list_crawlers(
        self, request: ListCrawlersRequestTypeDef,
    ) -> ListCrawlersResponseTypeDef:
        return self._call(
            "list_crawlers",
            request,
            ListCrawlersResponseTypeDef,
        )


    def list_crawls(
        self, request: ListCrawlsRequestTypeDef,
    ) -> ListCrawlsResponseTypeDef:
        return self._call(
            "list_crawls",
            request,
            ListCrawlsResponseTypeDef,
        )


    def list_custom_entity_types(
        self, request: ListCustomEntityTypesRequestTypeDef,
    ) -> ListCustomEntityTypesResponseTypeDef:
        return self._call(
            "list_custom_entity_types",
            request,
            ListCustomEntityTypesResponseTypeDef,
        )


    def list_data_quality_results(
        self, request: ListDataQualityResultsRequestTypeDef,
    ) -> ListDataQualityResultsResponseTypeDef:
        return self._call(
            "list_data_quality_results",
            request,
            ListDataQualityResultsResponseTypeDef,
        )


    def list_data_quality_rule_recommendation_runs(
        self, request: ListDataQualityRuleRecommendationRunsRequestTypeDef,
    ) -> ListDataQualityRuleRecommendationRunsResponseTypeDef:
        return self._call(
            "list_data_quality_rule_recommendation_runs",
            request,
            ListDataQualityRuleRecommendationRunsResponseTypeDef,
        )


    def list_data_quality_ruleset_evaluation_runs(
        self, request: ListDataQualityRulesetEvaluationRunsRequestTypeDef,
    ) -> ListDataQualityRulesetEvaluationRunsResponseTypeDef:
        return self._call(
            "list_data_quality_ruleset_evaluation_runs",
            request,
            ListDataQualityRulesetEvaluationRunsResponseTypeDef,
        )


    def list_data_quality_rulesets(
        self, request: ListDataQualityRulesetsRequestTypeDef,
    ) -> ListDataQualityRulesetsResponseTypeDef:
        return self._call(
            "list_data_quality_rulesets",
            request,
            ListDataQualityRulesetsResponseTypeDef,
        )


    def list_data_quality_statistic_annotations(
        self, request: ListDataQualityStatisticAnnotationsRequestTypeDef,
    ) -> ListDataQualityStatisticAnnotationsResponseTypeDef:
        return self._call(
            "list_data_quality_statistic_annotations",
            request,
            ListDataQualityStatisticAnnotationsResponseTypeDef,
        )


    def list_data_quality_statistics(
        self, request: ListDataQualityStatisticsRequestTypeDef,
    ) -> ListDataQualityStatisticsResponseTypeDef:
        return self._call(
            "list_data_quality_statistics",
            request,
            ListDataQualityStatisticsResponseTypeDef,
        )


    def list_dev_endpoints(
        self, request: ListDevEndpointsRequestTypeDef,
    ) -> ListDevEndpointsResponseTypeDef:
        return self._call(
            "list_dev_endpoints",
            request,
            ListDevEndpointsResponseTypeDef,
        )


    def list_entities(
        self, request: ListEntitiesRequestTypeDef,
    ) -> ListEntitiesResponseTypeDef:
        return self._call(
            "list_entities",
            request,
            ListEntitiesResponseTypeDef,
        )


    def list_integration_resource_properties(
        self, request: ListIntegrationResourcePropertiesRequestTypeDef,
    ) -> ListIntegrationResourcePropertiesResponseTypeDef:
        return self._call(
            "list_integration_resource_properties",
            request,
            ListIntegrationResourcePropertiesResponseTypeDef,
        )


    def list_jobs(
        self, request: ListJobsRequestTypeDef,
    ) -> ListJobsResponseTypeDef:
        return self._call(
            "list_jobs",
            request,
            ListJobsResponseTypeDef,
        )


    def list_materialized_view_refresh_task_runs(
        self, request: ListMaterializedViewRefreshTaskRunsRequestTypeDef,
    ) -> ListMaterializedViewRefreshTaskRunsResponseTypeDef:
        return self._call(
            "list_materialized_view_refresh_task_runs",
            request,
            ListMaterializedViewRefreshTaskRunsResponseTypeDef,
        )


    def list_ml_transforms(
        self, request: ListMLTransformsRequestTypeDef,
    ) -> ListMLTransformsResponseTypeDef:
        return self._call(
            "list_ml_transforms",
            request,
            ListMLTransformsResponseTypeDef,
        )


    def list_registries(
        self, request: ListRegistriesInputTypeDef,
    ) -> ListRegistriesResponseTypeDef:
        return self._call(
            "list_registries",
            request,
            ListRegistriesResponseTypeDef,
        )


    def list_schema_versions(
        self, request: ListSchemaVersionsInputTypeDef,
    ) -> ListSchemaVersionsResponseTypeDef:
        return self._call(
            "list_schema_versions",
            request,
            ListSchemaVersionsResponseTypeDef,
        )


    def list_schemas(
        self, request: ListSchemasInputTypeDef,
    ) -> ListSchemasResponseTypeDef:
        return self._call(
            "list_schemas",
            request,
            ListSchemasResponseTypeDef,
        )


    def list_sessions(
        self, request: ListSessionsRequestTypeDef,
    ) -> ListSessionsResponseTypeDef:
        return self._call(
            "list_sessions",
            request,
            ListSessionsResponseTypeDef,
        )


    def list_statements(
        self, request: ListStatementsRequestTypeDef,
    ) -> ListStatementsResponseTypeDef:
        return self._call(
            "list_statements",
            request,
            ListStatementsResponseTypeDef,
        )


    def list_table_optimizer_runs(
        self, request: ListTableOptimizerRunsRequestTypeDef,
    ) -> ListTableOptimizerRunsResponseTypeDef:
        return self._call(
            "list_table_optimizer_runs",
            request,
            ListTableOptimizerRunsResponseTypeDef,
        )


    def list_triggers(
        self, request: ListTriggersRequestTypeDef,
    ) -> ListTriggersResponseTypeDef:
        return self._call(
            "list_triggers",
            request,
            ListTriggersResponseTypeDef,
        )


    def list_usage_profiles(
        self, request: ListUsageProfilesRequestTypeDef,
    ) -> ListUsageProfilesResponseTypeDef:
        return self._call(
            "list_usage_profiles",
            request,
            ListUsageProfilesResponseTypeDef,
        )


    def list_workflows(
        self, request: ListWorkflowsRequestTypeDef,
    ) -> ListWorkflowsResponseTypeDef:
        return self._call(
            "list_workflows",
            request,
            ListWorkflowsResponseTypeDef,
        )


    def modify_integration(
        self, request: ModifyIntegrationRequestTypeDef,
    ) -> ModifyIntegrationResponseTypeDef:
        return self._call(
            "modify_integration",
            request,
            ModifyIntegrationResponseTypeDef,
        )


    def put_data_catalog_encryption_settings(
        self, request: PutDataCatalogEncryptionSettingsRequestTypeDef,
    ) -> None:
        return self._call(
            "put_data_catalog_encryption_settings",
            request,
            None,
        )


    def put_data_quality_profile_annotation(
        self, request: PutDataQualityProfileAnnotationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_data_quality_profile_annotation",
            request,
            None,
        )


    def put_resource_policy(
        self, request: PutResourcePolicyRequestTypeDef,
    ) -> PutResourcePolicyResponseTypeDef:
        return self._call(
            "put_resource_policy",
            request,
            PutResourcePolicyResponseTypeDef,
        )


    def put_schema_version_metadata(
        self, request: PutSchemaVersionMetadataInputTypeDef,
    ) -> PutSchemaVersionMetadataResponseTypeDef:
        return self._call(
            "put_schema_version_metadata",
            request,
            PutSchemaVersionMetadataResponseTypeDef,
        )


    def put_workflow_run_properties(
        self, request: PutWorkflowRunPropertiesRequestTypeDef,
    ) -> None:
        return self._call(
            "put_workflow_run_properties",
            request,
            None,
        )


    def query_schema_version_metadata(
        self, request: QuerySchemaVersionMetadataInputTypeDef,
    ) -> QuerySchemaVersionMetadataResponseTypeDef:
        return self._call(
            "query_schema_version_metadata",
            request,
            QuerySchemaVersionMetadataResponseTypeDef,
        )


    def register_connection_type(
        self, request: RegisterConnectionTypeRequestTypeDef,
    ) -> RegisterConnectionTypeResponseTypeDef:
        return self._call(
            "register_connection_type",
            request,
            RegisterConnectionTypeResponseTypeDef,
        )


    def register_schema_version(
        self, request: RegisterSchemaVersionInputTypeDef,
    ) -> RegisterSchemaVersionResponseTypeDef:
        return self._call(
            "register_schema_version",
            request,
            RegisterSchemaVersionResponseTypeDef,
        )


    def remove_schema_version_metadata(
        self, request: RemoveSchemaVersionMetadataInputTypeDef,
    ) -> RemoveSchemaVersionMetadataResponseTypeDef:
        return self._call(
            "remove_schema_version_metadata",
            request,
            RemoveSchemaVersionMetadataResponseTypeDef,
        )


    def reset_job_bookmark(
        self, request: ResetJobBookmarkRequestTypeDef,
    ) -> ResetJobBookmarkResponseTypeDef:
        return self._call(
            "reset_job_bookmark",
            request,
            ResetJobBookmarkResponseTypeDef,
        )


    def resume_workflow_run(
        self, request: ResumeWorkflowRunRequestTypeDef,
    ) -> ResumeWorkflowRunResponseTypeDef:
        return self._call(
            "resume_workflow_run",
            request,
            ResumeWorkflowRunResponseTypeDef,
        )


    def run_statement(
        self, request: RunStatementRequestTypeDef,
    ) -> RunStatementResponseTypeDef:
        return self._call(
            "run_statement",
            request,
            RunStatementResponseTypeDef,
        )


    def search_tables(
        self, request: SearchTablesRequestTypeDef,
    ) -> SearchTablesResponseTypeDef:
        return self._call(
            "search_tables",
            request,
            SearchTablesResponseTypeDef,
        )


    def start_blueprint_run(
        self, request: StartBlueprintRunRequestTypeDef,
    ) -> StartBlueprintRunResponseTypeDef:
        return self._call(
            "start_blueprint_run",
            request,
            StartBlueprintRunResponseTypeDef,
        )


    def start_column_statistics_task_run(
        self, request: StartColumnStatisticsTaskRunRequestTypeDef,
    ) -> StartColumnStatisticsTaskRunResponseTypeDef:
        return self._call(
            "start_column_statistics_task_run",
            request,
            StartColumnStatisticsTaskRunResponseTypeDef,
        )


    def start_column_statistics_task_run_schedule(
        self, request: StartColumnStatisticsTaskRunScheduleRequestTypeDef,
    ) -> None:
        return self._call(
            "start_column_statistics_task_run_schedule",
            request,
            None,
        )


    def start_crawler(
        self, request: StartCrawlerRequestTypeDef,
    ) -> None:
        return self._call(
            "start_crawler",
            request,
            None,
        )


    def start_crawler_schedule(
        self, request: StartCrawlerScheduleRequestTypeDef,
    ) -> None:
        return self._call(
            "start_crawler_schedule",
            request,
            None,
        )


    def start_data_quality_rule_recommendation_run(
        self, request: StartDataQualityRuleRecommendationRunRequestTypeDef,
    ) -> StartDataQualityRuleRecommendationRunResponseTypeDef:
        return self._call(
            "start_data_quality_rule_recommendation_run",
            request,
            StartDataQualityRuleRecommendationRunResponseTypeDef,
        )


    def start_data_quality_ruleset_evaluation_run(
        self, request: StartDataQualityRulesetEvaluationRunRequestTypeDef,
    ) -> StartDataQualityRulesetEvaluationRunResponseTypeDef:
        return self._call(
            "start_data_quality_ruleset_evaluation_run",
            request,
            StartDataQualityRulesetEvaluationRunResponseTypeDef,
        )


    def start_export_labels_task_run(
        self, request: StartExportLabelsTaskRunRequestTypeDef,
    ) -> StartExportLabelsTaskRunResponseTypeDef:
        return self._call(
            "start_export_labels_task_run",
            request,
            StartExportLabelsTaskRunResponseTypeDef,
        )


    def start_import_labels_task_run(
        self, request: StartImportLabelsTaskRunRequestTypeDef,
    ) -> StartImportLabelsTaskRunResponseTypeDef:
        return self._call(
            "start_import_labels_task_run",
            request,
            StartImportLabelsTaskRunResponseTypeDef,
        )


    def start_job_run(
        self, request: StartJobRunRequestTypeDef,
    ) -> StartJobRunResponseTypeDef:
        return self._call(
            "start_job_run",
            request,
            StartJobRunResponseTypeDef,
        )


    def start_materialized_view_refresh_task_run(
        self, request: StartMaterializedViewRefreshTaskRunRequestTypeDef,
    ) -> StartMaterializedViewRefreshTaskRunResponseTypeDef:
        return self._call(
            "start_materialized_view_refresh_task_run",
            request,
            StartMaterializedViewRefreshTaskRunResponseTypeDef,
        )


    def start_ml_evaluation_task_run(
        self, request: StartMLEvaluationTaskRunRequestTypeDef,
    ) -> StartMLEvaluationTaskRunResponseTypeDef:
        return self._call(
            "start_ml_evaluation_task_run",
            request,
            StartMLEvaluationTaskRunResponseTypeDef,
        )


    def start_ml_labeling_set_generation_task_run(
        self, request: StartMLLabelingSetGenerationTaskRunRequestTypeDef,
    ) -> StartMLLabelingSetGenerationTaskRunResponseTypeDef:
        return self._call(
            "start_ml_labeling_set_generation_task_run",
            request,
            StartMLLabelingSetGenerationTaskRunResponseTypeDef,
        )


    def start_trigger(
        self, request: StartTriggerRequestTypeDef,
    ) -> StartTriggerResponseTypeDef:
        return self._call(
            "start_trigger",
            request,
            StartTriggerResponseTypeDef,
        )


    def start_workflow_run(
        self, request: StartWorkflowRunRequestTypeDef,
    ) -> StartWorkflowRunResponseTypeDef:
        return self._call(
            "start_workflow_run",
            request,
            StartWorkflowRunResponseTypeDef,
        )


    def stop_column_statistics_task_run(
        self, request: StopColumnStatisticsTaskRunRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_column_statistics_task_run",
            request,
            None,
        )


    def stop_column_statistics_task_run_schedule(
        self, request: StopColumnStatisticsTaskRunScheduleRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_column_statistics_task_run_schedule",
            request,
            None,
        )


    def stop_crawler(
        self, request: StopCrawlerRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_crawler",
            request,
            None,
        )


    def stop_crawler_schedule(
        self, request: StopCrawlerScheduleRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_crawler_schedule",
            request,
            None,
        )


    def stop_materialized_view_refresh_task_run(
        self, request: StopMaterializedViewRefreshTaskRunRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_materialized_view_refresh_task_run",
            request,
            None,
        )


    def stop_session(
        self, request: StopSessionRequestTypeDef,
    ) -> StopSessionResponseTypeDef:
        return self._call(
            "stop_session",
            request,
            StopSessionResponseTypeDef,
        )


    def stop_trigger(
        self, request: StopTriggerRequestTypeDef,
    ) -> StopTriggerResponseTypeDef:
        return self._call(
            "stop_trigger",
            request,
            StopTriggerResponseTypeDef,
        )


    def stop_workflow_run(
        self, request: StopWorkflowRunRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_workflow_run",
            request,
            None,
        )


    def tag_resource(
        self, request: TagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def test_connection(
        self, request: TestConnectionRequestTypeDef,
    ) -> None:
        return self._call(
            "test_connection",
            request,
            None,
        )


    def untag_resource(
        self, request: UntagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_blueprint(
        self, request: UpdateBlueprintRequestTypeDef,
    ) -> UpdateBlueprintResponseTypeDef:
        return self._call(
            "update_blueprint",
            request,
            UpdateBlueprintResponseTypeDef,
        )


    def update_catalog(
        self, request: UpdateCatalogRequestTypeDef,
    ) -> None:
        return self._call(
            "update_catalog",
            request,
            None,
        )


    def update_classifier(
        self, request: UpdateClassifierRequestTypeDef,
    ) -> None:
        return self._call(
            "update_classifier",
            request,
            None,
        )


    def update_column_statistics_for_partition(
        self, request: UpdateColumnStatisticsForPartitionRequestTypeDef,
    ) -> UpdateColumnStatisticsForPartitionResponseTypeDef:
        return self._call(
            "update_column_statistics_for_partition",
            request,
            UpdateColumnStatisticsForPartitionResponseTypeDef,
        )


    def update_column_statistics_for_table(
        self, request: UpdateColumnStatisticsForTableRequestTypeDef,
    ) -> UpdateColumnStatisticsForTableResponseTypeDef:
        return self._call(
            "update_column_statistics_for_table",
            request,
            UpdateColumnStatisticsForTableResponseTypeDef,
        )


    def update_column_statistics_task_settings(
        self, request: UpdateColumnStatisticsTaskSettingsRequestTypeDef,
    ) -> None:
        return self._call(
            "update_column_statistics_task_settings",
            request,
            None,
        )


    def update_connection(
        self, request: UpdateConnectionRequestTypeDef,
    ) -> None:
        return self._call(
            "update_connection",
            request,
            None,
        )


    def update_crawler(
        self, request: UpdateCrawlerRequestTypeDef,
    ) -> None:
        return self._call(
            "update_crawler",
            request,
            None,
        )


    def update_crawler_schedule(
        self, request: UpdateCrawlerScheduleRequestTypeDef,
    ) -> None:
        return self._call(
            "update_crawler_schedule",
            request,
            None,
        )


    def update_data_quality_ruleset(
        self, request: UpdateDataQualityRulesetRequestTypeDef,
    ) -> UpdateDataQualityRulesetResponseTypeDef:
        return self._call(
            "update_data_quality_ruleset",
            request,
            UpdateDataQualityRulesetResponseTypeDef,
        )


    def update_database(
        self, request: UpdateDatabaseRequestTypeDef,
    ) -> None:
        return self._call(
            "update_database",
            request,
            None,
        )


    def update_dev_endpoint(
        self, request: UpdateDevEndpointRequestTypeDef,
    ) -> None:
        return self._call(
            "update_dev_endpoint",
            request,
            None,
        )


    def update_glue_identity_center_configuration(
        self, request: UpdateGlueIdentityCenterConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "update_glue_identity_center_configuration",
            request,
            None,
        )


    def update_integration_resource_property(
        self, request: UpdateIntegrationResourcePropertyRequestTypeDef,
    ) -> UpdateIntegrationResourcePropertyResponseTypeDef:
        return self._call(
            "update_integration_resource_property",
            request,
            UpdateIntegrationResourcePropertyResponseTypeDef,
        )


    def update_integration_table_properties(
        self, request: UpdateIntegrationTablePropertiesRequestTypeDef,
    ) -> None:
        return self._call(
            "update_integration_table_properties",
            request,
            None,
        )


    def update_job(
        self, request: UpdateJobRequestTypeDef,
    ) -> UpdateJobResponseTypeDef:
        return self._call(
            "update_job",
            request,
            UpdateJobResponseTypeDef,
        )


    def update_job_from_source_control(
        self, request: UpdateJobFromSourceControlRequestTypeDef,
    ) -> UpdateJobFromSourceControlResponseTypeDef:
        return self._call(
            "update_job_from_source_control",
            request,
            UpdateJobFromSourceControlResponseTypeDef,
        )


    def update_ml_transform(
        self, request: UpdateMLTransformRequestTypeDef,
    ) -> UpdateMLTransformResponseTypeDef:
        return self._call(
            "update_ml_transform",
            request,
            UpdateMLTransformResponseTypeDef,
        )


    def update_partition(
        self, request: UpdatePartitionRequestTypeDef,
    ) -> None:
        return self._call(
            "update_partition",
            request,
            None,
        )


    def update_registry(
        self, request: UpdateRegistryInputTypeDef,
    ) -> UpdateRegistryResponseTypeDef:
        return self._call(
            "update_registry",
            request,
            UpdateRegistryResponseTypeDef,
        )


    def update_schema(
        self, request: UpdateSchemaInputTypeDef,
    ) -> UpdateSchemaResponseTypeDef:
        return self._call(
            "update_schema",
            request,
            UpdateSchemaResponseTypeDef,
        )


    def update_source_control_from_job(
        self, request: UpdateSourceControlFromJobRequestTypeDef,
    ) -> UpdateSourceControlFromJobResponseTypeDef:
        return self._call(
            "update_source_control_from_job",
            request,
            UpdateSourceControlFromJobResponseTypeDef,
        )


    def update_table(
        self, request: UpdateTableRequestTypeDef,
    ) -> None:
        return self._call(
            "update_table",
            request,
            None,
        )


    def update_table_optimizer(
        self, request: UpdateTableOptimizerRequestTypeDef,
    ) -> None:
        return self._call(
            "update_table_optimizer",
            request,
            None,
        )


    def update_trigger(
        self, request: UpdateTriggerRequestTypeDef,
    ) -> UpdateTriggerResponseTypeDef:
        return self._call(
            "update_trigger",
            request,
            UpdateTriggerResponseTypeDef,
        )


    def update_usage_profile(
        self, request: UpdateUsageProfileRequestTypeDef,
    ) -> UpdateUsageProfileResponseTypeDef:
        return self._call(
            "update_usage_profile",
            request,
            UpdateUsageProfileResponseTypeDef,
        )


    def update_user_defined_function(
        self, request: UpdateUserDefinedFunctionRequestTypeDef,
    ) -> None:
        return self._call(
            "update_user_defined_function",
            request,
            None,
        )


    def update_workflow(
        self, request: UpdateWorkflowRequestTypeDef,
    ) -> UpdateWorkflowResponseTypeDef:
        return self._call(
            "update_workflow",
            request,
            UpdateWorkflowResponseTypeDef,
        )

