# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.kinesis.kinesis_classes import (
    AddTagsToStreamInputTypeDef,
    CreateStreamInputTypeDef,
    DecreaseStreamRetentionPeriodInputTypeDef,
    DeleteResourcePolicyInputTypeDef,
    DeleteStreamInputTypeDef,
    DeregisterStreamConsumerInputTypeDef,
    DescribeAccountSettingsOutputTypeDef,
    DescribeLimitsOutputTypeDef,
    DescribeStreamConsumerInputTypeDef,
    DescribeStreamConsumerOutputTypeDef,
    DescribeStreamInputTypeDef,
    DescribeStreamOutputTypeDef,
    DescribeStreamSummaryInputTypeDef,
    DescribeStreamSummaryOutputTypeDef,
    DisableEnhancedMonitoringInputTypeDef,
    EnableEnhancedMonitoringInputTypeDef,
    EnhancedMonitoringOutputTypeDef,
    GetRecordsInputTypeDef,
    GetRecordsOutputTypeDef,
    GetResourcePolicyInputTypeDef,
    GetResourcePolicyOutputTypeDef,
    GetShardIteratorInputTypeDef,
    GetShardIteratorOutputTypeDef,
    IncreaseStreamRetentionPeriodInputTypeDef,
    ListShardsInputTypeDef,
    ListShardsOutputTypeDef,
    ListStreamConsumersInputTypeDef,
    ListStreamConsumersOutputTypeDef,
    ListStreamsInputTypeDef,
    ListStreamsOutputTypeDef,
    ListTagsForResourceInputTypeDef,
    ListTagsForResourceOutputTypeDef,
    ListTagsForStreamInputTypeDef,
    ListTagsForStreamOutputTypeDef,
    MergeShardsInputTypeDef,
    PutRecordInputTypeDef,
    PutRecordOutputTypeDef,
    PutRecordsInputTypeDef,
    PutRecordsOutputTypeDef,
    PutResourcePolicyInputTypeDef,
    RegisterStreamConsumerInputTypeDef,
    RegisterStreamConsumerOutputTypeDef,
    RemoveTagsFromStreamInputTypeDef,
    SplitShardInputTypeDef,
    StartStreamEncryptionInputTypeDef,
    StopStreamEncryptionInputTypeDef,
    SubscribeToShardInputTypeDef,
    SubscribeToShardOutputTypeDef,
    TagResourceInputTypeDef,
    UntagResourceInputTypeDef,
    UpdateAccountSettingsInputTypeDef,
    UpdateAccountSettingsOutputTypeDef,
    UpdateMaxRecordSizeInputTypeDef,
    UpdateShardCountInputTypeDef,
    UpdateShardCountOutputTypeDef,
    UpdateStreamModeInputTypeDef,
    UpdateStreamWarmThroughputInputTypeDef,
    UpdateStreamWarmThroughputOutputTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class KinesisClient(TypedClientBase):
    _service_name = ServiceName.KINESIS


    def add_tags_to_stream(
        self, request: AddTagsToStreamInputTypeDef,
    ) -> None:
        return self._call(
            "add_tags_to_stream",
            request,
            None,
        )


    def create_stream(
        self, request: CreateStreamInputTypeDef,
    ) -> None:
        return self._call(
            "create_stream",
            request,
            None,
        )


    def decrease_stream_retention_period(
        self, request: DecreaseStreamRetentionPeriodInputTypeDef,
    ) -> None:
        return self._call(
            "decrease_stream_retention_period",
            request,
            None,
        )


    def delete_resource_policy(
        self, request: DeleteResourcePolicyInputTypeDef,
    ) -> None:
        return self._call(
            "delete_resource_policy",
            request,
            None,
        )


    def delete_stream(
        self, request: DeleteStreamInputTypeDef,
    ) -> None:
        return self._call(
            "delete_stream",
            request,
            None,
        )


    def deregister_stream_consumer(
        self, request: DeregisterStreamConsumerInputTypeDef,
    ) -> None:
        return self._call(
            "deregister_stream_consumer",
            request,
            None,
        )


    def describe_account_settings(
        self,
    ) -> DescribeAccountSettingsOutputTypeDef:
        return self._call(
            "describe_account_settings",
            None,
            DescribeAccountSettingsOutputTypeDef,
        )


    def describe_limits(
        self,
    ) -> DescribeLimitsOutputTypeDef:
        return self._call(
            "describe_limits",
            None,
            DescribeLimitsOutputTypeDef,
        )


    def describe_stream(
        self, request: DescribeStreamInputTypeDef,
    ) -> DescribeStreamOutputTypeDef:
        return self._call(
            "describe_stream",
            request,
            DescribeStreamOutputTypeDef,
        )


    def describe_stream_consumer(
        self, request: DescribeStreamConsumerInputTypeDef,
    ) -> DescribeStreamConsumerOutputTypeDef:
        return self._call(
            "describe_stream_consumer",
            request,
            DescribeStreamConsumerOutputTypeDef,
        )


    def describe_stream_summary(
        self, request: DescribeStreamSummaryInputTypeDef,
    ) -> DescribeStreamSummaryOutputTypeDef:
        return self._call(
            "describe_stream_summary",
            request,
            DescribeStreamSummaryOutputTypeDef,
        )


    def disable_enhanced_monitoring(
        self, request: DisableEnhancedMonitoringInputTypeDef,
    ) -> EnhancedMonitoringOutputTypeDef:
        return self._call(
            "disable_enhanced_monitoring",
            request,
            EnhancedMonitoringOutputTypeDef,
        )


    def enable_enhanced_monitoring(
        self, request: EnableEnhancedMonitoringInputTypeDef,
    ) -> EnhancedMonitoringOutputTypeDef:
        return self._call(
            "enable_enhanced_monitoring",
            request,
            EnhancedMonitoringOutputTypeDef,
        )


    def get_records(
        self, request: GetRecordsInputTypeDef,
    ) -> GetRecordsOutputTypeDef:
        return self._call(
            "get_records",
            request,
            GetRecordsOutputTypeDef,
        )


    def get_resource_policy(
        self, request: GetResourcePolicyInputTypeDef,
    ) -> GetResourcePolicyOutputTypeDef:
        return self._call(
            "get_resource_policy",
            request,
            GetResourcePolicyOutputTypeDef,
        )


    def get_shard_iterator(
        self, request: GetShardIteratorInputTypeDef,
    ) -> GetShardIteratorOutputTypeDef:
        return self._call(
            "get_shard_iterator",
            request,
            GetShardIteratorOutputTypeDef,
        )


    def increase_stream_retention_period(
        self, request: IncreaseStreamRetentionPeriodInputTypeDef,
    ) -> None:
        return self._call(
            "increase_stream_retention_period",
            request,
            None,
        )


    def list_shards(
        self, request: ListShardsInputTypeDef,
    ) -> ListShardsOutputTypeDef:
        return self._call(
            "list_shards",
            request,
            ListShardsOutputTypeDef,
        )


    def list_stream_consumers(
        self, request: ListStreamConsumersInputTypeDef,
    ) -> ListStreamConsumersOutputTypeDef:
        return self._call(
            "list_stream_consumers",
            request,
            ListStreamConsumersOutputTypeDef,
        )


    def list_streams(
        self, request: ListStreamsInputTypeDef,
    ) -> ListStreamsOutputTypeDef:
        return self._call(
            "list_streams",
            request,
            ListStreamsOutputTypeDef,
        )


    def list_tags_for_resource(
        self, request: ListTagsForResourceInputTypeDef,
    ) -> ListTagsForResourceOutputTypeDef:
        return self._call(
            "list_tags_for_resource",
            request,
            ListTagsForResourceOutputTypeDef,
        )


    def list_tags_for_stream(
        self, request: ListTagsForStreamInputTypeDef,
    ) -> ListTagsForStreamOutputTypeDef:
        return self._call(
            "list_tags_for_stream",
            request,
            ListTagsForStreamOutputTypeDef,
        )


    def merge_shards(
        self, request: MergeShardsInputTypeDef,
    ) -> None:
        return self._call(
            "merge_shards",
            request,
            None,
        )


    def put_record(
        self, request: PutRecordInputTypeDef,
    ) -> PutRecordOutputTypeDef:
        return self._call(
            "put_record",
            request,
            PutRecordOutputTypeDef,
        )


    def put_records(
        self, request: PutRecordsInputTypeDef,
    ) -> PutRecordsOutputTypeDef:
        return self._call(
            "put_records",
            request,
            PutRecordsOutputTypeDef,
        )


    def put_resource_policy(
        self, request: PutResourcePolicyInputTypeDef,
    ) -> None:
        return self._call(
            "put_resource_policy",
            request,
            None,
        )


    def register_stream_consumer(
        self, request: RegisterStreamConsumerInputTypeDef,
    ) -> RegisterStreamConsumerOutputTypeDef:
        return self._call(
            "register_stream_consumer",
            request,
            RegisterStreamConsumerOutputTypeDef,
        )


    def remove_tags_from_stream(
        self, request: RemoveTagsFromStreamInputTypeDef,
    ) -> None:
        return self._call(
            "remove_tags_from_stream",
            request,
            None,
        )


    def split_shard(
        self, request: SplitShardInputTypeDef,
    ) -> None:
        return self._call(
            "split_shard",
            request,
            None,
        )


    def start_stream_encryption(
        self, request: StartStreamEncryptionInputTypeDef,
    ) -> None:
        return self._call(
            "start_stream_encryption",
            request,
            None,
        )


    def stop_stream_encryption(
        self, request: StopStreamEncryptionInputTypeDef,
    ) -> None:
        return self._call(
            "stop_stream_encryption",
            request,
            None,
        )


    def subscribe_to_shard(
        self, request: SubscribeToShardInputTypeDef,
    ) -> SubscribeToShardOutputTypeDef:
        return self._call(
            "subscribe_to_shard",
            request,
            SubscribeToShardOutputTypeDef,
        )


    def tag_resource(
        self, request: TagResourceInputTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def untag_resource(
        self, request: UntagResourceInputTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_account_settings(
        self, request: UpdateAccountSettingsInputTypeDef,
    ) -> UpdateAccountSettingsOutputTypeDef:
        return self._call(
            "update_account_settings",
            request,
            UpdateAccountSettingsOutputTypeDef,
        )


    def update_max_record_size(
        self, request: UpdateMaxRecordSizeInputTypeDef,
    ) -> None:
        return self._call(
            "update_max_record_size",
            request,
            None,
        )


    def update_shard_count(
        self, request: UpdateShardCountInputTypeDef,
    ) -> UpdateShardCountOutputTypeDef:
        return self._call(
            "update_shard_count",
            request,
            UpdateShardCountOutputTypeDef,
        )


    def update_stream_mode(
        self, request: UpdateStreamModeInputTypeDef,
    ) -> None:
        return self._call(
            "update_stream_mode",
            request,
            None,
        )


    def update_stream_warm_throughput(
        self, request: UpdateStreamWarmThroughputInputTypeDef,
    ) -> UpdateStreamWarmThroughputOutputTypeDef:
        return self._call(
            "update_stream_warm_throughput",
            request,
            UpdateStreamWarmThroughputOutputTypeDef,
        )

