# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.kms.kms_classes import (
    CancelKeyDeletionRequestTypeDef,
    CancelKeyDeletionResponseTypeDef,
    ConnectCustomKeyStoreRequestTypeDef,
    CreateAliasRequestTypeDef,
    CreateCustomKeyStoreRequestTypeDef,
    CreateCustomKeyStoreResponseTypeDef,
    CreateGrantRequestTypeDef,
    CreateGrantResponseTypeDef,
    CreateKeyRequestTypeDef,
    CreateKeyResponseTypeDef,
    DecryptRequestTypeDef,
    DecryptResponseTypeDef,
    DeleteAliasRequestTypeDef,
    DeleteCustomKeyStoreRequestTypeDef,
    DeleteImportedKeyMaterialRequestTypeDef,
    DeleteImportedKeyMaterialResponseTypeDef,
    DeriveSharedSecretRequestTypeDef,
    DeriveSharedSecretResponseTypeDef,
    DescribeCustomKeyStoresRequestTypeDef,
    DescribeCustomKeyStoresResponseTypeDef,
    DescribeKeyRequestTypeDef,
    DescribeKeyResponseTypeDef,
    DisableKeyRequestTypeDef,
    DisableKeyRotationRequestTypeDef,
    DisconnectCustomKeyStoreRequestTypeDef,
    EnableKeyRequestTypeDef,
    EnableKeyRotationRequestTypeDef,
    EncryptRequestTypeDef,
    EncryptResponseTypeDef,
    GenerateDataKeyPairRequestTypeDef,
    GenerateDataKeyPairResponseTypeDef,
    GenerateDataKeyPairWithoutPlaintextRequestTypeDef,
    GenerateDataKeyPairWithoutPlaintextResponseTypeDef,
    GenerateDataKeyRequestTypeDef,
    GenerateDataKeyResponseTypeDef,
    GenerateDataKeyWithoutPlaintextRequestTypeDef,
    GenerateDataKeyWithoutPlaintextResponseTypeDef,
    GenerateMacRequestTypeDef,
    GenerateMacResponseTypeDef,
    GenerateRandomRequestTypeDef,
    GenerateRandomResponseTypeDef,
    GetKeyLastUsageRequestTypeDef,
    GetKeyLastUsageResponseTypeDef,
    GetKeyPolicyRequestTypeDef,
    GetKeyPolicyResponseTypeDef,
    GetKeyRotationStatusRequestTypeDef,
    GetKeyRotationStatusResponseTypeDef,
    GetParametersForImportRequestTypeDef,
    GetParametersForImportResponseTypeDef,
    GetPublicKeyRequestTypeDef,
    GetPublicKeyResponseTypeDef,
    ImportKeyMaterialRequestTypeDef,
    ImportKeyMaterialResponseTypeDef,
    ListAliasesRequestTypeDef,
    ListAliasesResponseTypeDef,
    ListGrantsRequestTypeDef,
    ListGrantsResponseTypeDef,
    ListKeyPoliciesRequestTypeDef,
    ListKeyPoliciesResponseTypeDef,
    ListKeyRotationsRequestTypeDef,
    ListKeyRotationsResponseTypeDef,
    ListKeysRequestTypeDef,
    ListKeysResponseTypeDef,
    ListResourceTagsRequestTypeDef,
    ListResourceTagsResponseTypeDef,
    ListRetirableGrantsRequestTypeDef,
    PutKeyPolicyRequestTypeDef,
    ReEncryptRequestTypeDef,
    ReEncryptResponseTypeDef,
    ReplicateKeyRequestTypeDef,
    ReplicateKeyResponseTypeDef,
    RetireGrantRequestTypeDef,
    RevokeGrantRequestTypeDef,
    RotateKeyOnDemandRequestTypeDef,
    RotateKeyOnDemandResponseTypeDef,
    ScheduleKeyDeletionRequestTypeDef,
    ScheduleKeyDeletionResponseTypeDef,
    SignRequestTypeDef,
    SignResponseTypeDef,
    TagResourceRequestTypeDef,
    UntagResourceRequestTypeDef,
    UpdateAliasRequestTypeDef,
    UpdateCustomKeyStoreRequestTypeDef,
    UpdateKeyDescriptionRequestTypeDef,
    UpdatePrimaryRegionRequestTypeDef,
    VerifyMacRequestTypeDef,
    VerifyMacResponseTypeDef,
    VerifyRequestTypeDef,
    VerifyResponseTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class KmsClient(TypedClientBase):
    _service_name = ServiceName.KMS


    def cancel_key_deletion(
        self, request: CancelKeyDeletionRequestTypeDef,
    ) -> CancelKeyDeletionResponseTypeDef:
        return self._call(
            "cancel_key_deletion",
            request,
            CancelKeyDeletionResponseTypeDef,
        )


    def connect_custom_key_store(
        self, request: ConnectCustomKeyStoreRequestTypeDef,
    ) -> None:
        return self._call(
            "connect_custom_key_store",
            request,
            None,
        )


    def create_alias(
        self, request: CreateAliasRequestTypeDef,
    ) -> None:
        return self._call(
            "create_alias",
            request,
            None,
        )


    def create_custom_key_store(
        self, request: CreateCustomKeyStoreRequestTypeDef,
    ) -> CreateCustomKeyStoreResponseTypeDef:
        return self._call(
            "create_custom_key_store",
            request,
            CreateCustomKeyStoreResponseTypeDef,
        )


    def create_grant(
        self, request: CreateGrantRequestTypeDef,
    ) -> CreateGrantResponseTypeDef:
        return self._call(
            "create_grant",
            request,
            CreateGrantResponseTypeDef,
        )


    def create_key(
        self, request: CreateKeyRequestTypeDef,
    ) -> CreateKeyResponseTypeDef:
        return self._call(
            "create_key",
            request,
            CreateKeyResponseTypeDef,
        )


    def decrypt(
        self, request: DecryptRequestTypeDef,
    ) -> DecryptResponseTypeDef:
        return self._call(
            "decrypt",
            request,
            DecryptResponseTypeDef,
        )


    def delete_alias(
        self, request: DeleteAliasRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_alias",
            request,
            None,
        )


    def delete_custom_key_store(
        self, request: DeleteCustomKeyStoreRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_custom_key_store",
            request,
            None,
        )


    def delete_imported_key_material(
        self, request: DeleteImportedKeyMaterialRequestTypeDef,
    ) -> DeleteImportedKeyMaterialResponseTypeDef:
        return self._call(
            "delete_imported_key_material",
            request,
            DeleteImportedKeyMaterialResponseTypeDef,
        )


    def derive_shared_secret(
        self, request: DeriveSharedSecretRequestTypeDef,
    ) -> DeriveSharedSecretResponseTypeDef:
        return self._call(
            "derive_shared_secret",
            request,
            DeriveSharedSecretResponseTypeDef,
        )


    def describe_custom_key_stores(
        self, request: DescribeCustomKeyStoresRequestTypeDef,
    ) -> DescribeCustomKeyStoresResponseTypeDef:
        return self._call(
            "describe_custom_key_stores",
            request,
            DescribeCustomKeyStoresResponseTypeDef,
        )


    def describe_key(
        self, request: DescribeKeyRequestTypeDef,
    ) -> DescribeKeyResponseTypeDef:
        return self._call(
            "describe_key",
            request,
            DescribeKeyResponseTypeDef,
        )


    def disable_key(
        self, request: DisableKeyRequestTypeDef,
    ) -> None:
        return self._call(
            "disable_key",
            request,
            None,
        )


    def disable_key_rotation(
        self, request: DisableKeyRotationRequestTypeDef,
    ) -> None:
        return self._call(
            "disable_key_rotation",
            request,
            None,
        )


    def disconnect_custom_key_store(
        self, request: DisconnectCustomKeyStoreRequestTypeDef,
    ) -> None:
        return self._call(
            "disconnect_custom_key_store",
            request,
            None,
        )


    def enable_key(
        self, request: EnableKeyRequestTypeDef,
    ) -> None:
        return self._call(
            "enable_key",
            request,
            None,
        )


    def enable_key_rotation(
        self, request: EnableKeyRotationRequestTypeDef,
    ) -> None:
        return self._call(
            "enable_key_rotation",
            request,
            None,
        )


    def encrypt(
        self, request: EncryptRequestTypeDef,
    ) -> EncryptResponseTypeDef:
        return self._call(
            "encrypt",
            request,
            EncryptResponseTypeDef,
        )


    def generate_data_key(
        self, request: GenerateDataKeyRequestTypeDef,
    ) -> GenerateDataKeyResponseTypeDef:
        return self._call(
            "generate_data_key",
            request,
            GenerateDataKeyResponseTypeDef,
        )


    def generate_data_key_pair(
        self, request: GenerateDataKeyPairRequestTypeDef,
    ) -> GenerateDataKeyPairResponseTypeDef:
        return self._call(
            "generate_data_key_pair",
            request,
            GenerateDataKeyPairResponseTypeDef,
        )


    def generate_data_key_pair_without_plaintext(
        self, request: GenerateDataKeyPairWithoutPlaintextRequestTypeDef,
    ) -> GenerateDataKeyPairWithoutPlaintextResponseTypeDef:
        return self._call(
            "generate_data_key_pair_without_plaintext",
            request,
            GenerateDataKeyPairWithoutPlaintextResponseTypeDef,
        )


    def generate_data_key_without_plaintext(
        self, request: GenerateDataKeyWithoutPlaintextRequestTypeDef,
    ) -> GenerateDataKeyWithoutPlaintextResponseTypeDef:
        return self._call(
            "generate_data_key_without_plaintext",
            request,
            GenerateDataKeyWithoutPlaintextResponseTypeDef,
        )


    def generate_mac(
        self, request: GenerateMacRequestTypeDef,
    ) -> GenerateMacResponseTypeDef:
        return self._call(
            "generate_mac",
            request,
            GenerateMacResponseTypeDef,
        )


    def generate_random(
        self, request: GenerateRandomRequestTypeDef,
    ) -> GenerateRandomResponseTypeDef:
        return self._call(
            "generate_random",
            request,
            GenerateRandomResponseTypeDef,
        )


    def get_key_last_usage(
        self, request: GetKeyLastUsageRequestTypeDef,
    ) -> GetKeyLastUsageResponseTypeDef:
        return self._call(
            "get_key_last_usage",
            request,
            GetKeyLastUsageResponseTypeDef,
        )


    def get_key_policy(
        self, request: GetKeyPolicyRequestTypeDef,
    ) -> GetKeyPolicyResponseTypeDef:
        return self._call(
            "get_key_policy",
            request,
            GetKeyPolicyResponseTypeDef,
        )


    def get_key_rotation_status(
        self, request: GetKeyRotationStatusRequestTypeDef,
    ) -> GetKeyRotationStatusResponseTypeDef:
        return self._call(
            "get_key_rotation_status",
            request,
            GetKeyRotationStatusResponseTypeDef,
        )


    def get_parameters_for_import(
        self, request: GetParametersForImportRequestTypeDef,
    ) -> GetParametersForImportResponseTypeDef:
        return self._call(
            "get_parameters_for_import",
            request,
            GetParametersForImportResponseTypeDef,
        )


    def get_public_key(
        self, request: GetPublicKeyRequestTypeDef,
    ) -> GetPublicKeyResponseTypeDef:
        return self._call(
            "get_public_key",
            request,
            GetPublicKeyResponseTypeDef,
        )


    def import_key_material(
        self, request: ImportKeyMaterialRequestTypeDef,
    ) -> ImportKeyMaterialResponseTypeDef:
        return self._call(
            "import_key_material",
            request,
            ImportKeyMaterialResponseTypeDef,
        )


    def list_aliases(
        self, request: ListAliasesRequestTypeDef,
    ) -> ListAliasesResponseTypeDef:
        return self._call(
            "list_aliases",
            request,
            ListAliasesResponseTypeDef,
        )


    def list_grants(
        self, request: ListGrantsRequestTypeDef,
    ) -> ListGrantsResponseTypeDef:
        return self._call(
            "list_grants",
            request,
            ListGrantsResponseTypeDef,
        )


    def list_key_policies(
        self, request: ListKeyPoliciesRequestTypeDef,
    ) -> ListKeyPoliciesResponseTypeDef:
        return self._call(
            "list_key_policies",
            request,
            ListKeyPoliciesResponseTypeDef,
        )


    def list_key_rotations(
        self, request: ListKeyRotationsRequestTypeDef,
    ) -> ListKeyRotationsResponseTypeDef:
        return self._call(
            "list_key_rotations",
            request,
            ListKeyRotationsResponseTypeDef,
        )


    def list_keys(
        self, request: ListKeysRequestTypeDef,
    ) -> ListKeysResponseTypeDef:
        return self._call(
            "list_keys",
            request,
            ListKeysResponseTypeDef,
        )


    def list_resource_tags(
        self, request: ListResourceTagsRequestTypeDef,
    ) -> ListResourceTagsResponseTypeDef:
        return self._call(
            "list_resource_tags",
            request,
            ListResourceTagsResponseTypeDef,
        )


    def list_retirable_grants(
        self, request: ListRetirableGrantsRequestTypeDef,
    ) -> ListGrantsResponseTypeDef:
        return self._call(
            "list_retirable_grants",
            request,
            ListGrantsResponseTypeDef,
        )


    def put_key_policy(
        self, request: PutKeyPolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "put_key_policy",
            request,
            None,
        )


    def re_encrypt(
        self, request: ReEncryptRequestTypeDef,
    ) -> ReEncryptResponseTypeDef:
        return self._call(
            "re_encrypt",
            request,
            ReEncryptResponseTypeDef,
        )


    def replicate_key(
        self, request: ReplicateKeyRequestTypeDef,
    ) -> ReplicateKeyResponseTypeDef:
        return self._call(
            "replicate_key",
            request,
            ReplicateKeyResponseTypeDef,
        )


    def retire_grant(
        self, request: RetireGrantRequestTypeDef,
    ) -> None:
        return self._call(
            "retire_grant",
            request,
            None,
        )


    def revoke_grant(
        self, request: RevokeGrantRequestTypeDef,
    ) -> None:
        return self._call(
            "revoke_grant",
            request,
            None,
        )


    def rotate_key_on_demand(
        self, request: RotateKeyOnDemandRequestTypeDef,
    ) -> RotateKeyOnDemandResponseTypeDef:
        return self._call(
            "rotate_key_on_demand",
            request,
            RotateKeyOnDemandResponseTypeDef,
        )


    def schedule_key_deletion(
        self, request: ScheduleKeyDeletionRequestTypeDef,
    ) -> ScheduleKeyDeletionResponseTypeDef:
        return self._call(
            "schedule_key_deletion",
            request,
            ScheduleKeyDeletionResponseTypeDef,
        )


    def sign(
        self, request: SignRequestTypeDef,
    ) -> SignResponseTypeDef:
        return self._call(
            "sign",
            request,
            SignResponseTypeDef,
        )


    def tag_resource(
        self, request: TagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def untag_resource(
        self, request: UntagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_alias(
        self, request: UpdateAliasRequestTypeDef,
    ) -> None:
        return self._call(
            "update_alias",
            request,
            None,
        )


    def update_custom_key_store(
        self, request: UpdateCustomKeyStoreRequestTypeDef,
    ) -> None:
        return self._call(
            "update_custom_key_store",
            request,
            None,
        )


    def update_key_description(
        self, request: UpdateKeyDescriptionRequestTypeDef,
    ) -> None:
        return self._call(
            "update_key_description",
            request,
            None,
        )


    def update_primary_region(
        self, request: UpdatePrimaryRegionRequestTypeDef,
    ) -> None:
        return self._call(
            "update_primary_region",
            request,
            None,
        )


    def verify(
        self, request: VerifyRequestTypeDef,
    ) -> VerifyResponseTypeDef:
        return self._call(
            "verify",
            request,
            VerifyResponseTypeDef,
        )


    def verify_mac(
        self, request: VerifyMacRequestTypeDef,
    ) -> VerifyMacResponseTypeDef:
        return self._call(
            "verify_mac",
            request,
            VerifyMacResponseTypeDef,
        )

