# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.lambda_.lambda__classes import (
    AddLayerVersionPermissionRequestTypeDef,
    AddLayerVersionPermissionResponseTypeDef,
    AddPermissionRequestTypeDef,
    AddPermissionResponseTypeDef,
    AliasConfigurationTypeDef,
    CheckpointDurableExecutionRequestTypeDef,
    CheckpointDurableExecutionResponseTypeDef,
    ConcurrencyTypeDef,
    CreateAliasRequestTypeDef,
    CreateCapacityProviderRequestTypeDef,
    CreateCapacityProviderResponseTypeDef,
    CreateCodeSigningConfigRequestTypeDef,
    CreateCodeSigningConfigResponseTypeDef,
    CreateEventSourceMappingRequestTypeDef,
    CreateFunctionRequestTypeDef,
    CreateFunctionUrlConfigRequestTypeDef,
    CreateFunctionUrlConfigResponseTypeDef,
    DeleteAliasRequestTypeDef,
    DeleteCapacityProviderRequestTypeDef,
    DeleteCapacityProviderResponseTypeDef,
    DeleteCodeSigningConfigRequestTypeDef,
    DeleteEventSourceMappingRequestTypeDef,
    DeleteFunctionCodeSigningConfigRequestTypeDef,
    DeleteFunctionConcurrencyRequestTypeDef,
    DeleteFunctionEventInvokeConfigRequestTypeDef,
    DeleteFunctionRequestTypeDef,
    DeleteFunctionResponseTypeDef,
    DeleteFunctionUrlConfigRequestTypeDef,
    DeleteLayerVersionRequestTypeDef,
    DeleteProvisionedConcurrencyConfigRequestTypeDef,
    EventSourceMappingConfigurationTypeDef,
    FunctionConfigurationTypeDef,
    FunctionEventInvokeConfigTypeDef,
    GetAccountSettingsResponseTypeDef,
    GetAliasRequestTypeDef,
    GetCapacityProviderRequestTypeDef,
    GetCapacityProviderResponseTypeDef,
    GetCodeSigningConfigRequestTypeDef,
    GetCodeSigningConfigResponseTypeDef,
    GetDurableExecutionHistoryRequestTypeDef,
    GetDurableExecutionHistoryResponseTypeDef,
    GetDurableExecutionRequestTypeDef,
    GetDurableExecutionResponseTypeDef,
    GetDurableExecutionStateRequestTypeDef,
    GetDurableExecutionStateResponseTypeDef,
    GetEventSourceMappingRequestTypeDef,
    GetFunctionCodeSigningConfigRequestTypeDef,
    GetFunctionCodeSigningConfigResponseTypeDef,
    GetFunctionConcurrencyRequestTypeDef,
    GetFunctionConcurrencyResponseTypeDef,
    GetFunctionConfigurationRequestTypeDef,
    GetFunctionEventInvokeConfigRequestTypeDef,
    GetFunctionRecursionConfigRequestTypeDef,
    GetFunctionRecursionConfigResponseTypeDef,
    GetFunctionRequestTypeDef,
    GetFunctionResponseTypeDef,
    GetFunctionScalingConfigRequestTypeDef,
    GetFunctionScalingConfigResponseTypeDef,
    GetFunctionUrlConfigRequestTypeDef,
    GetFunctionUrlConfigResponseTypeDef,
    GetLayerVersionByArnRequestTypeDef,
    GetLayerVersionPolicyRequestTypeDef,
    GetLayerVersionPolicyResponseTypeDef,
    GetLayerVersionRequestTypeDef,
    GetLayerVersionResponseTypeDef,
    GetPolicyRequestTypeDef,
    GetPolicyResponseTypeDef,
    GetProvisionedConcurrencyConfigRequestTypeDef,
    GetProvisionedConcurrencyConfigResponseTypeDef,
    GetRuntimeManagementConfigRequestTypeDef,
    GetRuntimeManagementConfigResponseTypeDef,
    InvocationRequestTypeDef,
    InvocationResponseTypeDef,
    InvokeAsyncRequestTypeDef,
    InvokeAsyncResponseTypeDef,
    InvokeWithResponseStreamRequestTypeDef,
    InvokeWithResponseStreamResponseTypeDef,
    ListAliasesRequestTypeDef,
    ListAliasesResponseTypeDef,
    ListCapacityProvidersRequestTypeDef,
    ListCapacityProvidersResponseTypeDef,
    ListCodeSigningConfigsRequestTypeDef,
    ListCodeSigningConfigsResponseTypeDef,
    ListDurableExecutionsByFunctionRequestTypeDef,
    ListDurableExecutionsByFunctionResponseTypeDef,
    ListEventSourceMappingsRequestTypeDef,
    ListEventSourceMappingsResponseTypeDef,
    ListFunctionEventInvokeConfigsRequestTypeDef,
    ListFunctionEventInvokeConfigsResponseTypeDef,
    ListFunctionUrlConfigsRequestTypeDef,
    ListFunctionUrlConfigsResponseTypeDef,
    ListFunctionVersionsByCapacityProviderRequestTypeDef,
    ListFunctionVersionsByCapacityProviderResponseTypeDef,
    ListFunctionsByCodeSigningConfigRequestTypeDef,
    ListFunctionsByCodeSigningConfigResponseTypeDef,
    ListFunctionsRequestTypeDef,
    ListFunctionsResponseTypeDef,
    ListLayerVersionsRequestTypeDef,
    ListLayerVersionsResponseTypeDef,
    ListLayersRequestTypeDef,
    ListLayersResponseTypeDef,
    ListProvisionedConcurrencyConfigsRequestTypeDef,
    ListProvisionedConcurrencyConfigsResponseTypeDef,
    ListTagsRequestTypeDef,
    ListTagsResponseTypeDef,
    ListVersionsByFunctionRequestTypeDef,
    ListVersionsByFunctionResponseTypeDef,
    PublishLayerVersionRequestTypeDef,
    PublishLayerVersionResponseTypeDef,
    PublishVersionRequestTypeDef,
    PutFunctionCodeSigningConfigRequestTypeDef,
    PutFunctionCodeSigningConfigResponseTypeDef,
    PutFunctionConcurrencyRequestTypeDef,
    PutFunctionEventInvokeConfigRequestTypeDef,
    PutFunctionRecursionConfigRequestTypeDef,
    PutFunctionRecursionConfigResponseTypeDef,
    PutFunctionScalingConfigRequestTypeDef,
    PutFunctionScalingConfigResponseTypeDef,
    PutProvisionedConcurrencyConfigRequestTypeDef,
    PutProvisionedConcurrencyConfigResponseTypeDef,
    PutRuntimeManagementConfigRequestTypeDef,
    PutRuntimeManagementConfigResponseTypeDef,
    RemoveLayerVersionPermissionRequestTypeDef,
    RemovePermissionRequestTypeDef,
    SendDurableExecutionCallbackFailureRequestTypeDef,
    SendDurableExecutionCallbackHeartbeatRequestTypeDef,
    SendDurableExecutionCallbackSuccessRequestTypeDef,
    StopDurableExecutionRequestTypeDef,
    StopDurableExecutionResponseTypeDef,
    TagResourceRequestTypeDef,
    UntagResourceRequestTypeDef,
    UpdateAliasRequestTypeDef,
    UpdateCapacityProviderRequestTypeDef,
    UpdateCapacityProviderResponseTypeDef,
    UpdateCodeSigningConfigRequestTypeDef,
    UpdateCodeSigningConfigResponseTypeDef,
    UpdateEventSourceMappingRequestTypeDef,
    UpdateFunctionCodeRequestTypeDef,
    UpdateFunctionConfigurationRequestTypeDef,
    UpdateFunctionEventInvokeConfigRequestTypeDef,
    UpdateFunctionUrlConfigRequestTypeDef,
    UpdateFunctionUrlConfigResponseTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class LambdaClient(TypedClientBase):
    _service_name = ServiceName.LAMBDA


    def add_layer_version_permission(
        self, request: AddLayerVersionPermissionRequestTypeDef,
    ) -> AddLayerVersionPermissionResponseTypeDef:
        return self._call(
            "add_layer_version_permission",
            request,
            AddLayerVersionPermissionResponseTypeDef,
        )


    def add_permission(
        self, request: AddPermissionRequestTypeDef,
    ) -> AddPermissionResponseTypeDef:
        return self._call(
            "add_permission",
            request,
            AddPermissionResponseTypeDef,
        )


    def checkpoint_durable_execution(
        self, request: CheckpointDurableExecutionRequestTypeDef,
    ) -> CheckpointDurableExecutionResponseTypeDef:
        return self._call(
            "checkpoint_durable_execution",
            request,
            CheckpointDurableExecutionResponseTypeDef,
        )


    def create_alias(
        self, request: CreateAliasRequestTypeDef,
    ) -> AliasConfigurationTypeDef:
        return self._call(
            "create_alias",
            request,
            AliasConfigurationTypeDef,
        )


    def create_capacity_provider(
        self, request: CreateCapacityProviderRequestTypeDef,
    ) -> CreateCapacityProviderResponseTypeDef:
        return self._call(
            "create_capacity_provider",
            request,
            CreateCapacityProviderResponseTypeDef,
        )


    def create_code_signing_config(
        self, request: CreateCodeSigningConfigRequestTypeDef,
    ) -> CreateCodeSigningConfigResponseTypeDef:
        return self._call(
            "create_code_signing_config",
            request,
            CreateCodeSigningConfigResponseTypeDef,
        )


    def create_event_source_mapping(
        self, request: CreateEventSourceMappingRequestTypeDef,
    ) -> EventSourceMappingConfigurationTypeDef:
        return self._call(
            "create_event_source_mapping",
            request,
            EventSourceMappingConfigurationTypeDef,
        )


    def create_function(
        self, request: CreateFunctionRequestTypeDef,
    ) -> FunctionConfigurationTypeDef:
        return self._call(
            "create_function",
            request,
            FunctionConfigurationTypeDef,
        )


    def create_function_url_config(
        self, request: CreateFunctionUrlConfigRequestTypeDef,
    ) -> CreateFunctionUrlConfigResponseTypeDef:
        return self._call(
            "create_function_url_config",
            request,
            CreateFunctionUrlConfigResponseTypeDef,
        )


    def delete_alias(
        self, request: DeleteAliasRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_alias",
            request,
            None,
        )


    def delete_capacity_provider(
        self, request: DeleteCapacityProviderRequestTypeDef,
    ) -> DeleteCapacityProviderResponseTypeDef:
        return self._call(
            "delete_capacity_provider",
            request,
            DeleteCapacityProviderResponseTypeDef,
        )


    def delete_code_signing_config(
        self, request: DeleteCodeSigningConfigRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_code_signing_config",
            request,
            None,
        )


    def delete_event_source_mapping(
        self, request: DeleteEventSourceMappingRequestTypeDef,
    ) -> EventSourceMappingConfigurationTypeDef:
        return self._call(
            "delete_event_source_mapping",
            request,
            EventSourceMappingConfigurationTypeDef,
        )


    def delete_function(
        self, request: DeleteFunctionRequestTypeDef,
    ) -> DeleteFunctionResponseTypeDef:
        return self._call(
            "delete_function",
            request,
            DeleteFunctionResponseTypeDef,
        )


    def delete_function_code_signing_config(
        self, request: DeleteFunctionCodeSigningConfigRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_function_code_signing_config",
            request,
            None,
        )


    def delete_function_concurrency(
        self, request: DeleteFunctionConcurrencyRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_function_concurrency",
            request,
            None,
        )


    def delete_function_event_invoke_config(
        self, request: DeleteFunctionEventInvokeConfigRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_function_event_invoke_config",
            request,
            None,
        )


    def delete_function_url_config(
        self, request: DeleteFunctionUrlConfigRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_function_url_config",
            request,
            None,
        )


    def delete_layer_version(
        self, request: DeleteLayerVersionRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_layer_version",
            request,
            None,
        )


    def delete_provisioned_concurrency_config(
        self, request: DeleteProvisionedConcurrencyConfigRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_provisioned_concurrency_config",
            request,
            None,
        )


    def get_account_settings(
        self,
    ) -> GetAccountSettingsResponseTypeDef:
        return self._call(
            "get_account_settings",
            None,
            GetAccountSettingsResponseTypeDef,
        )


    def get_alias(
        self, request: GetAliasRequestTypeDef,
    ) -> AliasConfigurationTypeDef:
        return self._call(
            "get_alias",
            request,
            AliasConfigurationTypeDef,
        )


    def get_capacity_provider(
        self, request: GetCapacityProviderRequestTypeDef,
    ) -> GetCapacityProviderResponseTypeDef:
        return self._call(
            "get_capacity_provider",
            request,
            GetCapacityProviderResponseTypeDef,
        )


    def get_code_signing_config(
        self, request: GetCodeSigningConfigRequestTypeDef,
    ) -> GetCodeSigningConfigResponseTypeDef:
        return self._call(
            "get_code_signing_config",
            request,
            GetCodeSigningConfigResponseTypeDef,
        )


    def get_durable_execution(
        self, request: GetDurableExecutionRequestTypeDef,
    ) -> GetDurableExecutionResponseTypeDef:
        return self._call(
            "get_durable_execution",
            request,
            GetDurableExecutionResponseTypeDef,
        )


    def get_durable_execution_history(
        self, request: GetDurableExecutionHistoryRequestTypeDef,
    ) -> GetDurableExecutionHistoryResponseTypeDef:
        return self._call(
            "get_durable_execution_history",
            request,
            GetDurableExecutionHistoryResponseTypeDef,
        )


    def get_durable_execution_state(
        self, request: GetDurableExecutionStateRequestTypeDef,
    ) -> GetDurableExecutionStateResponseTypeDef:
        return self._call(
            "get_durable_execution_state",
            request,
            GetDurableExecutionStateResponseTypeDef,
        )


    def get_event_source_mapping(
        self, request: GetEventSourceMappingRequestTypeDef,
    ) -> EventSourceMappingConfigurationTypeDef:
        return self._call(
            "get_event_source_mapping",
            request,
            EventSourceMappingConfigurationTypeDef,
        )


    def get_function(
        self, request: GetFunctionRequestTypeDef,
    ) -> GetFunctionResponseTypeDef:
        return self._call(
            "get_function",
            request,
            GetFunctionResponseTypeDef,
        )


    def get_function_code_signing_config(
        self, request: GetFunctionCodeSigningConfigRequestTypeDef,
    ) -> GetFunctionCodeSigningConfigResponseTypeDef:
        return self._call(
            "get_function_code_signing_config",
            request,
            GetFunctionCodeSigningConfigResponseTypeDef,
        )


    def get_function_concurrency(
        self, request: GetFunctionConcurrencyRequestTypeDef,
    ) -> GetFunctionConcurrencyResponseTypeDef:
        return self._call(
            "get_function_concurrency",
            request,
            GetFunctionConcurrencyResponseTypeDef,
        )


    def get_function_configuration(
        self, request: GetFunctionConfigurationRequestTypeDef,
    ) -> FunctionConfigurationTypeDef:
        return self._call(
            "get_function_configuration",
            request,
            FunctionConfigurationTypeDef,
        )


    def get_function_event_invoke_config(
        self, request: GetFunctionEventInvokeConfigRequestTypeDef,
    ) -> FunctionEventInvokeConfigTypeDef:
        return self._call(
            "get_function_event_invoke_config",
            request,
            FunctionEventInvokeConfigTypeDef,
        )


    def get_function_recursion_config(
        self, request: GetFunctionRecursionConfigRequestTypeDef,
    ) -> GetFunctionRecursionConfigResponseTypeDef:
        return self._call(
            "get_function_recursion_config",
            request,
            GetFunctionRecursionConfigResponseTypeDef,
        )


    def get_function_scaling_config(
        self, request: GetFunctionScalingConfigRequestTypeDef,
    ) -> GetFunctionScalingConfigResponseTypeDef:
        return self._call(
            "get_function_scaling_config",
            request,
            GetFunctionScalingConfigResponseTypeDef,
        )


    def get_function_url_config(
        self, request: GetFunctionUrlConfigRequestTypeDef,
    ) -> GetFunctionUrlConfigResponseTypeDef:
        return self._call(
            "get_function_url_config",
            request,
            GetFunctionUrlConfigResponseTypeDef,
        )


    def get_layer_version(
        self, request: GetLayerVersionRequestTypeDef,
    ) -> GetLayerVersionResponseTypeDef:
        return self._call(
            "get_layer_version",
            request,
            GetLayerVersionResponseTypeDef,
        )


    def get_layer_version_by_arn(
        self, request: GetLayerVersionByArnRequestTypeDef,
    ) -> GetLayerVersionResponseTypeDef:
        return self._call(
            "get_layer_version_by_arn",
            request,
            GetLayerVersionResponseTypeDef,
        )


    def get_layer_version_policy(
        self, request: GetLayerVersionPolicyRequestTypeDef,
    ) -> GetLayerVersionPolicyResponseTypeDef:
        return self._call(
            "get_layer_version_policy",
            request,
            GetLayerVersionPolicyResponseTypeDef,
        )


    def get_policy(
        self, request: GetPolicyRequestTypeDef,
    ) -> GetPolicyResponseTypeDef:
        return self._call(
            "get_policy",
            request,
            GetPolicyResponseTypeDef,
        )


    def get_provisioned_concurrency_config(
        self, request: GetProvisionedConcurrencyConfigRequestTypeDef,
    ) -> GetProvisionedConcurrencyConfigResponseTypeDef:
        return self._call(
            "get_provisioned_concurrency_config",
            request,
            GetProvisionedConcurrencyConfigResponseTypeDef,
        )


    def get_runtime_management_config(
        self, request: GetRuntimeManagementConfigRequestTypeDef,
    ) -> GetRuntimeManagementConfigResponseTypeDef:
        return self._call(
            "get_runtime_management_config",
            request,
            GetRuntimeManagementConfigResponseTypeDef,
        )


    def invoke(
        self, request: InvocationRequestTypeDef,
    ) -> InvocationResponseTypeDef:
        return self._call(
            "invoke",
            request,
            InvocationResponseTypeDef,
        )


    def invoke_async(
        self, request: InvokeAsyncRequestTypeDef,
    ) -> InvokeAsyncResponseTypeDef:
        return self._call(
            "invoke_async",
            request,
            InvokeAsyncResponseTypeDef,
        )


    def invoke_with_response_stream(
        self, request: InvokeWithResponseStreamRequestTypeDef,
    ) -> InvokeWithResponseStreamResponseTypeDef:
        return self._call(
            "invoke_with_response_stream",
            request,
            InvokeWithResponseStreamResponseTypeDef,
        )


    def list_aliases(
        self, request: ListAliasesRequestTypeDef,
    ) -> ListAliasesResponseTypeDef:
        return self._call(
            "list_aliases",
            request,
            ListAliasesResponseTypeDef,
        )


    def list_capacity_providers(
        self, request: ListCapacityProvidersRequestTypeDef,
    ) -> ListCapacityProvidersResponseTypeDef:
        return self._call(
            "list_capacity_providers",
            request,
            ListCapacityProvidersResponseTypeDef,
        )


    def list_code_signing_configs(
        self, request: ListCodeSigningConfigsRequestTypeDef,
    ) -> ListCodeSigningConfigsResponseTypeDef:
        return self._call(
            "list_code_signing_configs",
            request,
            ListCodeSigningConfigsResponseTypeDef,
        )


    def list_durable_executions_by_function(
        self, request: ListDurableExecutionsByFunctionRequestTypeDef,
    ) -> ListDurableExecutionsByFunctionResponseTypeDef:
        return self._call(
            "list_durable_executions_by_function",
            request,
            ListDurableExecutionsByFunctionResponseTypeDef,
        )


    def list_event_source_mappings(
        self, request: ListEventSourceMappingsRequestTypeDef,
    ) -> ListEventSourceMappingsResponseTypeDef:
        return self._call(
            "list_event_source_mappings",
            request,
            ListEventSourceMappingsResponseTypeDef,
        )


    def list_function_event_invoke_configs(
        self, request: ListFunctionEventInvokeConfigsRequestTypeDef,
    ) -> ListFunctionEventInvokeConfigsResponseTypeDef:
        return self._call(
            "list_function_event_invoke_configs",
            request,
            ListFunctionEventInvokeConfigsResponseTypeDef,
        )


    def list_function_url_configs(
        self, request: ListFunctionUrlConfigsRequestTypeDef,
    ) -> ListFunctionUrlConfigsResponseTypeDef:
        return self._call(
            "list_function_url_configs",
            request,
            ListFunctionUrlConfigsResponseTypeDef,
        )


    def list_function_versions_by_capacity_provider(
        self, request: ListFunctionVersionsByCapacityProviderRequestTypeDef,
    ) -> ListFunctionVersionsByCapacityProviderResponseTypeDef:
        return self._call(
            "list_function_versions_by_capacity_provider",
            request,
            ListFunctionVersionsByCapacityProviderResponseTypeDef,
        )


    def list_functions(
        self, request: ListFunctionsRequestTypeDef,
    ) -> ListFunctionsResponseTypeDef:
        return self._call(
            "list_functions",
            request,
            ListFunctionsResponseTypeDef,
        )


    def list_functions_by_code_signing_config(
        self, request: ListFunctionsByCodeSigningConfigRequestTypeDef,
    ) -> ListFunctionsByCodeSigningConfigResponseTypeDef:
        return self._call(
            "list_functions_by_code_signing_config",
            request,
            ListFunctionsByCodeSigningConfigResponseTypeDef,
        )


    def list_layer_versions(
        self, request: ListLayerVersionsRequestTypeDef,
    ) -> ListLayerVersionsResponseTypeDef:
        return self._call(
            "list_layer_versions",
            request,
            ListLayerVersionsResponseTypeDef,
        )


    def list_layers(
        self, request: ListLayersRequestTypeDef,
    ) -> ListLayersResponseTypeDef:
        return self._call(
            "list_layers",
            request,
            ListLayersResponseTypeDef,
        )


    def list_provisioned_concurrency_configs(
        self, request: ListProvisionedConcurrencyConfigsRequestTypeDef,
    ) -> ListProvisionedConcurrencyConfigsResponseTypeDef:
        return self._call(
            "list_provisioned_concurrency_configs",
            request,
            ListProvisionedConcurrencyConfigsResponseTypeDef,
        )


    def list_tags(
        self, request: ListTagsRequestTypeDef,
    ) -> ListTagsResponseTypeDef:
        return self._call(
            "list_tags",
            request,
            ListTagsResponseTypeDef,
        )


    def list_versions_by_function(
        self, request: ListVersionsByFunctionRequestTypeDef,
    ) -> ListVersionsByFunctionResponseTypeDef:
        return self._call(
            "list_versions_by_function",
            request,
            ListVersionsByFunctionResponseTypeDef,
        )


    def publish_layer_version(
        self, request: PublishLayerVersionRequestTypeDef,
    ) -> PublishLayerVersionResponseTypeDef:
        return self._call(
            "publish_layer_version",
            request,
            PublishLayerVersionResponseTypeDef,
        )


    def publish_version(
        self, request: PublishVersionRequestTypeDef,
    ) -> FunctionConfigurationTypeDef:
        return self._call(
            "publish_version",
            request,
            FunctionConfigurationTypeDef,
        )


    def put_function_code_signing_config(
        self, request: PutFunctionCodeSigningConfigRequestTypeDef,
    ) -> PutFunctionCodeSigningConfigResponseTypeDef:
        return self._call(
            "put_function_code_signing_config",
            request,
            PutFunctionCodeSigningConfigResponseTypeDef,
        )


    def put_function_concurrency(
        self, request: PutFunctionConcurrencyRequestTypeDef,
    ) -> ConcurrencyTypeDef:
        return self._call(
            "put_function_concurrency",
            request,
            ConcurrencyTypeDef,
        )


    def put_function_event_invoke_config(
        self, request: PutFunctionEventInvokeConfigRequestTypeDef,
    ) -> FunctionEventInvokeConfigTypeDef:
        return self._call(
            "put_function_event_invoke_config",
            request,
            FunctionEventInvokeConfigTypeDef,
        )


    def put_function_recursion_config(
        self, request: PutFunctionRecursionConfigRequestTypeDef,
    ) -> PutFunctionRecursionConfigResponseTypeDef:
        return self._call(
            "put_function_recursion_config",
            request,
            PutFunctionRecursionConfigResponseTypeDef,
        )


    def put_function_scaling_config(
        self, request: PutFunctionScalingConfigRequestTypeDef,
    ) -> PutFunctionScalingConfigResponseTypeDef:
        return self._call(
            "put_function_scaling_config",
            request,
            PutFunctionScalingConfigResponseTypeDef,
        )


    def put_provisioned_concurrency_config(
        self, request: PutProvisionedConcurrencyConfigRequestTypeDef,
    ) -> PutProvisionedConcurrencyConfigResponseTypeDef:
        return self._call(
            "put_provisioned_concurrency_config",
            request,
            PutProvisionedConcurrencyConfigResponseTypeDef,
        )


    def put_runtime_management_config(
        self, request: PutRuntimeManagementConfigRequestTypeDef,
    ) -> PutRuntimeManagementConfigResponseTypeDef:
        return self._call(
            "put_runtime_management_config",
            request,
            PutRuntimeManagementConfigResponseTypeDef,
        )


    def remove_layer_version_permission(
        self, request: RemoveLayerVersionPermissionRequestTypeDef,
    ) -> None:
        return self._call(
            "remove_layer_version_permission",
            request,
            None,
        )


    def remove_permission(
        self, request: RemovePermissionRequestTypeDef,
    ) -> None:
        return self._call(
            "remove_permission",
            request,
            None,
        )


    def send_durable_execution_callback_failure(
        self, request: SendDurableExecutionCallbackFailureRequestTypeDef,
    ) -> None:
        return self._call(
            "send_durable_execution_callback_failure",
            request,
            None,
        )


    def send_durable_execution_callback_heartbeat(
        self, request: SendDurableExecutionCallbackHeartbeatRequestTypeDef,
    ) -> None:
        return self._call(
            "send_durable_execution_callback_heartbeat",
            request,
            None,
        )


    def send_durable_execution_callback_success(
        self, request: SendDurableExecutionCallbackSuccessRequestTypeDef,
    ) -> None:
        return self._call(
            "send_durable_execution_callback_success",
            request,
            None,
        )


    def stop_durable_execution(
        self, request: StopDurableExecutionRequestTypeDef,
    ) -> StopDurableExecutionResponseTypeDef:
        return self._call(
            "stop_durable_execution",
            request,
            StopDurableExecutionResponseTypeDef,
        )


    def tag_resource(
        self, request: TagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def untag_resource(
        self, request: UntagResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_alias(
        self, request: UpdateAliasRequestTypeDef,
    ) -> AliasConfigurationTypeDef:
        return self._call(
            "update_alias",
            request,
            AliasConfigurationTypeDef,
        )


    def update_capacity_provider(
        self, request: UpdateCapacityProviderRequestTypeDef,
    ) -> UpdateCapacityProviderResponseTypeDef:
        return self._call(
            "update_capacity_provider",
            request,
            UpdateCapacityProviderResponseTypeDef,
        )


    def update_code_signing_config(
        self, request: UpdateCodeSigningConfigRequestTypeDef,
    ) -> UpdateCodeSigningConfigResponseTypeDef:
        return self._call(
            "update_code_signing_config",
            request,
            UpdateCodeSigningConfigResponseTypeDef,
        )


    def update_event_source_mapping(
        self, request: UpdateEventSourceMappingRequestTypeDef,
    ) -> EventSourceMappingConfigurationTypeDef:
        return self._call(
            "update_event_source_mapping",
            request,
            EventSourceMappingConfigurationTypeDef,
        )


    def update_function_code(
        self, request: UpdateFunctionCodeRequestTypeDef,
    ) -> FunctionConfigurationTypeDef:
        return self._call(
            "update_function_code",
            request,
            FunctionConfigurationTypeDef,
        )


    def update_function_configuration(
        self, request: UpdateFunctionConfigurationRequestTypeDef,
    ) -> FunctionConfigurationTypeDef:
        return self._call(
            "update_function_configuration",
            request,
            FunctionConfigurationTypeDef,
        )


    def update_function_event_invoke_config(
        self, request: UpdateFunctionEventInvokeConfigRequestTypeDef,
    ) -> FunctionEventInvokeConfigTypeDef:
        return self._call(
            "update_function_event_invoke_config",
            request,
            FunctionEventInvokeConfigTypeDef,
        )


    def update_function_url_config(
        self, request: UpdateFunctionUrlConfigRequestTypeDef,
    ) -> UpdateFunctionUrlConfigResponseTypeDef:
        return self._call(
            "update_function_url_config",
            request,
            UpdateFunctionUrlConfigResponseTypeDef,
        )

