# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.rds.rds_classes import (
    AccountAttributesMessageTypeDef,
    AddRoleToDBClusterMessageTypeDef,
    AddRoleToDBInstanceMessageTypeDef,
    AddSourceIdentifierToSubscriptionMessageTypeDef,
    AddSourceIdentifierToSubscriptionResultTypeDef,
    AddTagsToResourceMessageTypeDef,
    ApplyPendingMaintenanceActionMessageTypeDef,
    ApplyPendingMaintenanceActionResultTypeDef,
    AuthorizeDBSecurityGroupIngressMessageTypeDef,
    AuthorizeDBSecurityGroupIngressResultTypeDef,
    BacktrackDBClusterMessageTypeDef,
    CancelExportTaskMessageTypeDef,
    CertificateMessageTypeDef,
    CopyDBClusterParameterGroupMessageTypeDef,
    CopyDBClusterParameterGroupResultTypeDef,
    CopyDBClusterSnapshotMessageTypeDef,
    CopyDBClusterSnapshotResultTypeDef,
    CopyDBParameterGroupMessageTypeDef,
    CopyDBParameterGroupResultTypeDef,
    CopyDBSnapshotMessageTypeDef,
    CopyDBSnapshotResultTypeDef,
    CopyOptionGroupMessageTypeDef,
    CopyOptionGroupResultTypeDef,
    CreateBlueGreenDeploymentRequestTypeDef,
    CreateBlueGreenDeploymentResponseTypeDef,
    CreateCustomDBEngineVersionMessageTypeDef,
    CreateDBClusterEndpointMessageTypeDef,
    CreateDBClusterMessageTypeDef,
    CreateDBClusterParameterGroupMessageTypeDef,
    CreateDBClusterParameterGroupResultTypeDef,
    CreateDBClusterResultTypeDef,
    CreateDBClusterSnapshotMessageTypeDef,
    CreateDBClusterSnapshotResultTypeDef,
    CreateDBInstanceMessageTypeDef,
    CreateDBInstanceReadReplicaMessageTypeDef,
    CreateDBInstanceReadReplicaResultTypeDef,
    CreateDBInstanceResultTypeDef,
    CreateDBParameterGroupMessageTypeDef,
    CreateDBParameterGroupResultTypeDef,
    CreateDBProxyEndpointRequestTypeDef,
    CreateDBProxyEndpointResponseTypeDef,
    CreateDBProxyRequestTypeDef,
    CreateDBProxyResponseTypeDef,
    CreateDBSecurityGroupMessageTypeDef,
    CreateDBSecurityGroupResultTypeDef,
    CreateDBShardGroupMessageTypeDef,
    CreateDBSnapshotMessageTypeDef,
    CreateDBSnapshotResultTypeDef,
    CreateDBSubnetGroupMessageTypeDef,
    CreateDBSubnetGroupResultTypeDef,
    CreateEventSubscriptionMessageTypeDef,
    CreateEventSubscriptionResultTypeDef,
    CreateGlobalClusterMessageTypeDef,
    CreateGlobalClusterResultTypeDef,
    CreateIntegrationMessageTypeDef,
    CreateOptionGroupMessageTypeDef,
    CreateOptionGroupResultTypeDef,
    CreateTenantDatabaseMessageTypeDef,
    CreateTenantDatabaseResultTypeDef,
    DBClusterAutomatedBackupMessageTypeDef,
    DBClusterBacktrackMessageTypeDef,
    DBClusterBacktrackTypeDef,
    DBClusterCapacityInfoTypeDef,
    DBClusterEndpointMessageTypeDef,
    DBClusterEndpointTypeDef,
    DBClusterMessageTypeDef,
    DBClusterParameterGroupDetailsTypeDef,
    DBClusterParameterGroupNameMessageTypeDef,
    DBClusterParameterGroupsMessageTypeDef,
    DBClusterSnapshotMessageTypeDef,
    DBEngineVersionMessageTypeDef,
    DBEngineVersionTypeDef,
    DBInstanceAutomatedBackupMessageTypeDef,
    DBInstanceMessageTypeDef,
    DBParameterGroupDetailsTypeDef,
    DBParameterGroupNameMessageTypeDef,
    DBParameterGroupsMessageTypeDef,
    DBRecommendationMessageTypeDef,
    DBRecommendationsMessageTypeDef,
    DBSecurityGroupMessageTypeDef,
    DBShardGroupTypeDef,
    DBSnapshotMessageTypeDef,
    DBSnapshotTenantDatabasesMessageTypeDef,
    DBSubnetGroupMessageTypeDef,
    DeleteBlueGreenDeploymentRequestTypeDef,
    DeleteBlueGreenDeploymentResponseTypeDef,
    DeleteCustomDBEngineVersionMessageTypeDef,
    DeleteDBClusterAutomatedBackupMessageTypeDef,
    DeleteDBClusterAutomatedBackupResultTypeDef,
    DeleteDBClusterEndpointMessageTypeDef,
    DeleteDBClusterMessageTypeDef,
    DeleteDBClusterParameterGroupMessageTypeDef,
    DeleteDBClusterResultTypeDef,
    DeleteDBClusterSnapshotMessageTypeDef,
    DeleteDBClusterSnapshotResultTypeDef,
    DeleteDBInstanceAutomatedBackupMessageTypeDef,
    DeleteDBInstanceAutomatedBackupResultTypeDef,
    DeleteDBInstanceMessageTypeDef,
    DeleteDBInstanceResultTypeDef,
    DeleteDBParameterGroupMessageTypeDef,
    DeleteDBProxyEndpointRequestTypeDef,
    DeleteDBProxyEndpointResponseTypeDef,
    DeleteDBProxyRequestTypeDef,
    DeleteDBProxyResponseTypeDef,
    DeleteDBSecurityGroupMessageTypeDef,
    DeleteDBShardGroupMessageTypeDef,
    DeleteDBSnapshotMessageTypeDef,
    DeleteDBSnapshotResultTypeDef,
    DeleteDBSubnetGroupMessageTypeDef,
    DeleteEventSubscriptionMessageTypeDef,
    DeleteEventSubscriptionResultTypeDef,
    DeleteGlobalClusterMessageTypeDef,
    DeleteGlobalClusterResultTypeDef,
    DeleteIntegrationMessageTypeDef,
    DeleteOptionGroupMessageTypeDef,
    DeleteTenantDatabaseMessageTypeDef,
    DeleteTenantDatabaseResultTypeDef,
    DeregisterDBProxyTargetsRequestTypeDef,
    DescribeBlueGreenDeploymentsRequestTypeDef,
    DescribeBlueGreenDeploymentsResponseTypeDef,
    DescribeCertificatesMessageTypeDef,
    DescribeDBClusterAutomatedBackupsMessageTypeDef,
    DescribeDBClusterBacktracksMessageTypeDef,
    DescribeDBClusterEndpointsMessageTypeDef,
    DescribeDBClusterParameterGroupsMessageTypeDef,
    DescribeDBClusterParametersMessageTypeDef,
    DescribeDBClusterSnapshotAttributesMessageTypeDef,
    DescribeDBClusterSnapshotAttributesResultTypeDef,
    DescribeDBClusterSnapshotsMessageTypeDef,
    DescribeDBClustersMessageTypeDef,
    DescribeDBEngineVersionsMessageTypeDef,
    DescribeDBInstanceAutomatedBackupsMessageTypeDef,
    DescribeDBInstancesMessageTypeDef,
    DescribeDBLogFilesMessageTypeDef,
    DescribeDBLogFilesResponseTypeDef,
    DescribeDBMajorEngineVersionsRequestTypeDef,
    DescribeDBMajorEngineVersionsResponseTypeDef,
    DescribeDBParameterGroupsMessageTypeDef,
    DescribeDBParametersMessageTypeDef,
    DescribeDBProxiesRequestTypeDef,
    DescribeDBProxiesResponseTypeDef,
    DescribeDBProxyEndpointsRequestTypeDef,
    DescribeDBProxyEndpointsResponseTypeDef,
    DescribeDBProxyTargetGroupsRequestTypeDef,
    DescribeDBProxyTargetGroupsResponseTypeDef,
    DescribeDBProxyTargetsRequestTypeDef,
    DescribeDBProxyTargetsResponseTypeDef,
    DescribeDBRecommendationsMessageTypeDef,
    DescribeDBSecurityGroupsMessageTypeDef,
    DescribeDBShardGroupsMessageTypeDef,
    DescribeDBShardGroupsResponseTypeDef,
    DescribeDBSnapshotAttributesMessageTypeDef,
    DescribeDBSnapshotAttributesResultTypeDef,
    DescribeDBSnapshotTenantDatabasesMessageTypeDef,
    DescribeDBSnapshotsMessageTypeDef,
    DescribeDBSubnetGroupsMessageTypeDef,
    DescribeEngineDefaultClusterParametersMessageTypeDef,
    DescribeEngineDefaultClusterParametersResultTypeDef,
    DescribeEngineDefaultParametersMessageTypeDef,
    DescribeEngineDefaultParametersResultTypeDef,
    DescribeEventCategoriesMessageTypeDef,
    DescribeEventSubscriptionsMessageTypeDef,
    DescribeEventsMessageTypeDef,
    DescribeExportTasksMessageTypeDef,
    DescribeGlobalClustersMessageTypeDef,
    DescribeIntegrationsMessageTypeDef,
    DescribeIntegrationsResponseTypeDef,
    DescribeOptionGroupOptionsMessageTypeDef,
    DescribeOptionGroupsMessageTypeDef,
    DescribeOrderableDBInstanceOptionsMessageTypeDef,
    DescribePendingMaintenanceActionsMessageTypeDef,
    DescribeReservedDBInstancesMessageTypeDef,
    DescribeReservedDBInstancesOfferingsMessageTypeDef,
    DescribeServerlessV2PlatformVersionsMessageTypeDef,
    DescribeSourceRegionsMessageTypeDef,
    DescribeTenantDatabasesMessageTypeDef,
    DescribeValidDBInstanceModificationsMessageTypeDef,
    DescribeValidDBInstanceModificationsResultTypeDef,
    DisableHttpEndpointRequestTypeDef,
    DisableHttpEndpointResponseTypeDef,
    DownloadDBLogFilePortionDetailsTypeDef,
    DownloadDBLogFilePortionMessageTypeDef,
    EnableHttpEndpointRequestTypeDef,
    EnableHttpEndpointResponseTypeDef,
    EventCategoriesMessageTypeDef,
    EventSubscriptionsMessageTypeDef,
    EventsMessageTypeDef,
    ExportTaskTypeDef,
    ExportTasksMessageTypeDef,
    FailoverDBClusterMessageTypeDef,
    FailoverDBClusterResultTypeDef,
    FailoverGlobalClusterMessageTypeDef,
    FailoverGlobalClusterResultTypeDef,
    GlobalClustersMessageTypeDef,
    IntegrationTypeDef,
    ListTagsForResourceMessageTypeDef,
    ModifyActivityStreamRequestTypeDef,
    ModifyActivityStreamResponseTypeDef,
    ModifyCertificatesMessageTypeDef,
    ModifyCertificatesResultTypeDef,
    ModifyCurrentDBClusterCapacityMessageTypeDef,
    ModifyCustomDBEngineVersionMessageTypeDef,
    ModifyDBClusterEndpointMessageTypeDef,
    ModifyDBClusterMessageTypeDef,
    ModifyDBClusterParameterGroupMessageTypeDef,
    ModifyDBClusterResultTypeDef,
    ModifyDBClusterSnapshotAttributeMessageTypeDef,
    ModifyDBClusterSnapshotAttributeResultTypeDef,
    ModifyDBInstanceMessageTypeDef,
    ModifyDBInstanceResultTypeDef,
    ModifyDBParameterGroupMessageTypeDef,
    ModifyDBProxyEndpointRequestTypeDef,
    ModifyDBProxyEndpointResponseTypeDef,
    ModifyDBProxyRequestTypeDef,
    ModifyDBProxyResponseTypeDef,
    ModifyDBProxyTargetGroupRequestTypeDef,
    ModifyDBProxyTargetGroupResponseTypeDef,
    ModifyDBRecommendationMessageTypeDef,
    ModifyDBShardGroupMessageTypeDef,
    ModifyDBSnapshotAttributeMessageTypeDef,
    ModifyDBSnapshotAttributeResultTypeDef,
    ModifyDBSnapshotMessageTypeDef,
    ModifyDBSnapshotResultTypeDef,
    ModifyDBSubnetGroupMessageTypeDef,
    ModifyDBSubnetGroupResultTypeDef,
    ModifyEventSubscriptionMessageTypeDef,
    ModifyEventSubscriptionResultTypeDef,
    ModifyGlobalClusterMessageTypeDef,
    ModifyGlobalClusterResultTypeDef,
    ModifyIntegrationMessageTypeDef,
    ModifyOptionGroupMessageTypeDef,
    ModifyOptionGroupResultTypeDef,
    ModifyTenantDatabaseMessageTypeDef,
    ModifyTenantDatabaseResultTypeDef,
    OptionGroupOptionsMessageTypeDef,
    OptionGroupsTypeDef,
    OrderableDBInstanceOptionsMessageTypeDef,
    PendingMaintenanceActionsMessageTypeDef,
    PromoteReadReplicaDBClusterMessageTypeDef,
    PromoteReadReplicaDBClusterResultTypeDef,
    PromoteReadReplicaMessageTypeDef,
    PromoteReadReplicaResultTypeDef,
    PurchaseReservedDBInstancesOfferingMessageTypeDef,
    PurchaseReservedDBInstancesOfferingResultTypeDef,
    RebootDBClusterMessageTypeDef,
    RebootDBClusterResultTypeDef,
    RebootDBInstanceMessageTypeDef,
    RebootDBInstanceResultTypeDef,
    RebootDBShardGroupMessageTypeDef,
    RegisterDBProxyTargetsRequestTypeDef,
    RegisterDBProxyTargetsResponseTypeDef,
    RemoveFromGlobalClusterMessageTypeDef,
    RemoveFromGlobalClusterResultTypeDef,
    RemoveRoleFromDBClusterMessageTypeDef,
    RemoveRoleFromDBInstanceMessageTypeDef,
    RemoveSourceIdentifierFromSubscriptionMessageTypeDef,
    RemoveSourceIdentifierFromSubscriptionResultTypeDef,
    RemoveTagsFromResourceMessageTypeDef,
    ReservedDBInstanceMessageTypeDef,
    ReservedDBInstancesOfferingMessageTypeDef,
    ResetDBClusterParameterGroupMessageTypeDef,
    ResetDBParameterGroupMessageTypeDef,
    RestoreDBClusterFromS3MessageTypeDef,
    RestoreDBClusterFromS3ResultTypeDef,
    RestoreDBClusterFromSnapshotMessageTypeDef,
    RestoreDBClusterFromSnapshotResultTypeDef,
    RestoreDBClusterToPointInTimeMessageTypeDef,
    RestoreDBClusterToPointInTimeResultTypeDef,
    RestoreDBInstanceFromDBSnapshotMessageTypeDef,
    RestoreDBInstanceFromDBSnapshotResultTypeDef,
    RestoreDBInstanceFromS3MessageTypeDef,
    RestoreDBInstanceFromS3ResultTypeDef,
    RestoreDBInstanceToPointInTimeMessageTypeDef,
    RestoreDBInstanceToPointInTimeResultTypeDef,
    RevokeDBSecurityGroupIngressMessageTypeDef,
    RevokeDBSecurityGroupIngressResultTypeDef,
    ServerlessV2PlatformVersionsMessageTypeDef,
    SourceRegionMessageTypeDef,
    StartActivityStreamRequestTypeDef,
    StartActivityStreamResponseTypeDef,
    StartDBClusterMessageTypeDef,
    StartDBClusterResultTypeDef,
    StartDBInstanceAutomatedBackupsReplicationMessageTypeDef,
    StartDBInstanceAutomatedBackupsReplicationResultTypeDef,
    StartDBInstanceMessageTypeDef,
    StartDBInstanceResultTypeDef,
    StartExportTaskMessageTypeDef,
    StopActivityStreamRequestTypeDef,
    StopActivityStreamResponseTypeDef,
    StopDBClusterMessageTypeDef,
    StopDBClusterResultTypeDef,
    StopDBInstanceAutomatedBackupsReplicationMessageTypeDef,
    StopDBInstanceAutomatedBackupsReplicationResultTypeDef,
    StopDBInstanceMessageTypeDef,
    StopDBInstanceResultTypeDef,
    SwitchoverBlueGreenDeploymentRequestTypeDef,
    SwitchoverBlueGreenDeploymentResponseTypeDef,
    SwitchoverGlobalClusterMessageTypeDef,
    SwitchoverGlobalClusterResultTypeDef,
    SwitchoverReadReplicaMessageTypeDef,
    SwitchoverReadReplicaResultTypeDef,
    TagListMessageTypeDef,
    TenantDatabasesMessageTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class RdsClient(TypedClientBase):
    _service_name = ServiceName.RDS


    def add_role_to_db_cluster(
        self, request: AddRoleToDBClusterMessageTypeDef,
    ) -> None:
        return self._call(
            "add_role_to_db_cluster",
            request,
            None,
        )


    def add_role_to_db_instance(
        self, request: AddRoleToDBInstanceMessageTypeDef,
    ) -> None:
        return self._call(
            "add_role_to_db_instance",
            request,
            None,
        )


    def add_source_identifier_to_subscription(
        self, request: AddSourceIdentifierToSubscriptionMessageTypeDef,
    ) -> AddSourceIdentifierToSubscriptionResultTypeDef:
        return self._call(
            "add_source_identifier_to_subscription",
            request,
            AddSourceIdentifierToSubscriptionResultTypeDef,
        )


    def add_tags_to_resource(
        self, request: AddTagsToResourceMessageTypeDef,
    ) -> None:
        return self._call(
            "add_tags_to_resource",
            request,
            None,
        )


    def apply_pending_maintenance_action(
        self, request: ApplyPendingMaintenanceActionMessageTypeDef,
    ) -> ApplyPendingMaintenanceActionResultTypeDef:
        return self._call(
            "apply_pending_maintenance_action",
            request,
            ApplyPendingMaintenanceActionResultTypeDef,
        )


    def authorize_db_security_group_ingress(
        self, request: AuthorizeDBSecurityGroupIngressMessageTypeDef,
    ) -> AuthorizeDBSecurityGroupIngressResultTypeDef:
        return self._call(
            "authorize_db_security_group_ingress",
            request,
            AuthorizeDBSecurityGroupIngressResultTypeDef,
        )


    def backtrack_db_cluster(
        self, request: BacktrackDBClusterMessageTypeDef,
    ) -> DBClusterBacktrackTypeDef:
        return self._call(
            "backtrack_db_cluster",
            request,
            DBClusterBacktrackTypeDef,
        )


    def cancel_export_task(
        self, request: CancelExportTaskMessageTypeDef,
    ) -> ExportTaskTypeDef:
        return self._call(
            "cancel_export_task",
            request,
            ExportTaskTypeDef,
        )


    def copy_db_cluster_parameter_group(
        self, request: CopyDBClusterParameterGroupMessageTypeDef,
    ) -> CopyDBClusterParameterGroupResultTypeDef:
        return self._call(
            "copy_db_cluster_parameter_group",
            request,
            CopyDBClusterParameterGroupResultTypeDef,
        )


    def copy_db_cluster_snapshot(
        self, request: CopyDBClusterSnapshotMessageTypeDef,
    ) -> CopyDBClusterSnapshotResultTypeDef:
        return self._call(
            "copy_db_cluster_snapshot",
            request,
            CopyDBClusterSnapshotResultTypeDef,
        )


    def copy_db_parameter_group(
        self, request: CopyDBParameterGroupMessageTypeDef,
    ) -> CopyDBParameterGroupResultTypeDef:
        return self._call(
            "copy_db_parameter_group",
            request,
            CopyDBParameterGroupResultTypeDef,
        )


    def copy_db_snapshot(
        self, request: CopyDBSnapshotMessageTypeDef,
    ) -> CopyDBSnapshotResultTypeDef:
        return self._call(
            "copy_db_snapshot",
            request,
            CopyDBSnapshotResultTypeDef,
        )


    def copy_option_group(
        self, request: CopyOptionGroupMessageTypeDef,
    ) -> CopyOptionGroupResultTypeDef:
        return self._call(
            "copy_option_group",
            request,
            CopyOptionGroupResultTypeDef,
        )


    def create_blue_green_deployment(
        self, request: CreateBlueGreenDeploymentRequestTypeDef,
    ) -> CreateBlueGreenDeploymentResponseTypeDef:
        return self._call(
            "create_blue_green_deployment",
            request,
            CreateBlueGreenDeploymentResponseTypeDef,
        )


    def create_custom_db_engine_version(
        self, request: CreateCustomDBEngineVersionMessageTypeDef,
    ) -> DBEngineVersionTypeDef:
        return self._call(
            "create_custom_db_engine_version",
            request,
            DBEngineVersionTypeDef,
        )


    def create_db_cluster(
        self, request: CreateDBClusterMessageTypeDef,
    ) -> CreateDBClusterResultTypeDef:
        return self._call(
            "create_db_cluster",
            request,
            CreateDBClusterResultTypeDef,
        )


    def create_db_cluster_endpoint(
        self, request: CreateDBClusterEndpointMessageTypeDef,
    ) -> DBClusterEndpointTypeDef:
        return self._call(
            "create_db_cluster_endpoint",
            request,
            DBClusterEndpointTypeDef,
        )


    def create_db_cluster_parameter_group(
        self, request: CreateDBClusterParameterGroupMessageTypeDef,
    ) -> CreateDBClusterParameterGroupResultTypeDef:
        return self._call(
            "create_db_cluster_parameter_group",
            request,
            CreateDBClusterParameterGroupResultTypeDef,
        )


    def create_db_cluster_snapshot(
        self, request: CreateDBClusterSnapshotMessageTypeDef,
    ) -> CreateDBClusterSnapshotResultTypeDef:
        return self._call(
            "create_db_cluster_snapshot",
            request,
            CreateDBClusterSnapshotResultTypeDef,
        )


    def create_db_instance(
        self, request: CreateDBInstanceMessageTypeDef,
    ) -> CreateDBInstanceResultTypeDef:
        return self._call(
            "create_db_instance",
            request,
            CreateDBInstanceResultTypeDef,
        )


    def create_db_instance_read_replica(
        self, request: CreateDBInstanceReadReplicaMessageTypeDef,
    ) -> CreateDBInstanceReadReplicaResultTypeDef:
        return self._call(
            "create_db_instance_read_replica",
            request,
            CreateDBInstanceReadReplicaResultTypeDef,
        )


    def create_db_parameter_group(
        self, request: CreateDBParameterGroupMessageTypeDef,
    ) -> CreateDBParameterGroupResultTypeDef:
        return self._call(
            "create_db_parameter_group",
            request,
            CreateDBParameterGroupResultTypeDef,
        )


    def create_db_proxy(
        self, request: CreateDBProxyRequestTypeDef,
    ) -> CreateDBProxyResponseTypeDef:
        return self._call(
            "create_db_proxy",
            request,
            CreateDBProxyResponseTypeDef,
        )


    def create_db_proxy_endpoint(
        self, request: CreateDBProxyEndpointRequestTypeDef,
    ) -> CreateDBProxyEndpointResponseTypeDef:
        return self._call(
            "create_db_proxy_endpoint",
            request,
            CreateDBProxyEndpointResponseTypeDef,
        )


    def create_db_security_group(
        self, request: CreateDBSecurityGroupMessageTypeDef,
    ) -> CreateDBSecurityGroupResultTypeDef:
        return self._call(
            "create_db_security_group",
            request,
            CreateDBSecurityGroupResultTypeDef,
        )


    def create_db_shard_group(
        self, request: CreateDBShardGroupMessageTypeDef,
    ) -> DBShardGroupTypeDef:
        return self._call(
            "create_db_shard_group",
            request,
            DBShardGroupTypeDef,
        )


    def create_db_snapshot(
        self, request: CreateDBSnapshotMessageTypeDef,
    ) -> CreateDBSnapshotResultTypeDef:
        return self._call(
            "create_db_snapshot",
            request,
            CreateDBSnapshotResultTypeDef,
        )


    def create_db_subnet_group(
        self, request: CreateDBSubnetGroupMessageTypeDef,
    ) -> CreateDBSubnetGroupResultTypeDef:
        return self._call(
            "create_db_subnet_group",
            request,
            CreateDBSubnetGroupResultTypeDef,
        )


    def create_event_subscription(
        self, request: CreateEventSubscriptionMessageTypeDef,
    ) -> CreateEventSubscriptionResultTypeDef:
        return self._call(
            "create_event_subscription",
            request,
            CreateEventSubscriptionResultTypeDef,
        )


    def create_global_cluster(
        self, request: CreateGlobalClusterMessageTypeDef,
    ) -> CreateGlobalClusterResultTypeDef:
        return self._call(
            "create_global_cluster",
            request,
            CreateGlobalClusterResultTypeDef,
        )


    def create_integration(
        self, request: CreateIntegrationMessageTypeDef,
    ) -> IntegrationTypeDef:
        return self._call(
            "create_integration",
            request,
            IntegrationTypeDef,
        )


    def create_option_group(
        self, request: CreateOptionGroupMessageTypeDef,
    ) -> CreateOptionGroupResultTypeDef:
        return self._call(
            "create_option_group",
            request,
            CreateOptionGroupResultTypeDef,
        )


    def create_tenant_database(
        self, request: CreateTenantDatabaseMessageTypeDef,
    ) -> CreateTenantDatabaseResultTypeDef:
        return self._call(
            "create_tenant_database",
            request,
            CreateTenantDatabaseResultTypeDef,
        )


    def delete_blue_green_deployment(
        self, request: DeleteBlueGreenDeploymentRequestTypeDef,
    ) -> DeleteBlueGreenDeploymentResponseTypeDef:
        return self._call(
            "delete_blue_green_deployment",
            request,
            DeleteBlueGreenDeploymentResponseTypeDef,
        )


    def delete_custom_db_engine_version(
        self, request: DeleteCustomDBEngineVersionMessageTypeDef,
    ) -> DBEngineVersionTypeDef:
        return self._call(
            "delete_custom_db_engine_version",
            request,
            DBEngineVersionTypeDef,
        )


    def delete_db_cluster(
        self, request: DeleteDBClusterMessageTypeDef,
    ) -> DeleteDBClusterResultTypeDef:
        return self._call(
            "delete_db_cluster",
            request,
            DeleteDBClusterResultTypeDef,
        )


    def delete_db_cluster_automated_backup(
        self, request: DeleteDBClusterAutomatedBackupMessageTypeDef,
    ) -> DeleteDBClusterAutomatedBackupResultTypeDef:
        return self._call(
            "delete_db_cluster_automated_backup",
            request,
            DeleteDBClusterAutomatedBackupResultTypeDef,
        )


    def delete_db_cluster_endpoint(
        self, request: DeleteDBClusterEndpointMessageTypeDef,
    ) -> DBClusterEndpointTypeDef:
        return self._call(
            "delete_db_cluster_endpoint",
            request,
            DBClusterEndpointTypeDef,
        )


    def delete_db_cluster_parameter_group(
        self, request: DeleteDBClusterParameterGroupMessageTypeDef,
    ) -> None:
        return self._call(
            "delete_db_cluster_parameter_group",
            request,
            None,
        )


    def delete_db_cluster_snapshot(
        self, request: DeleteDBClusterSnapshotMessageTypeDef,
    ) -> DeleteDBClusterSnapshotResultTypeDef:
        return self._call(
            "delete_db_cluster_snapshot",
            request,
            DeleteDBClusterSnapshotResultTypeDef,
        )


    def delete_db_instance(
        self, request: DeleteDBInstanceMessageTypeDef,
    ) -> DeleteDBInstanceResultTypeDef:
        return self._call(
            "delete_db_instance",
            request,
            DeleteDBInstanceResultTypeDef,
        )


    def delete_db_instance_automated_backup(
        self, request: DeleteDBInstanceAutomatedBackupMessageTypeDef,
    ) -> DeleteDBInstanceAutomatedBackupResultTypeDef:
        return self._call(
            "delete_db_instance_automated_backup",
            request,
            DeleteDBInstanceAutomatedBackupResultTypeDef,
        )


    def delete_db_parameter_group(
        self, request: DeleteDBParameterGroupMessageTypeDef,
    ) -> None:
        return self._call(
            "delete_db_parameter_group",
            request,
            None,
        )


    def delete_db_proxy(
        self, request: DeleteDBProxyRequestTypeDef,
    ) -> DeleteDBProxyResponseTypeDef:
        return self._call(
            "delete_db_proxy",
            request,
            DeleteDBProxyResponseTypeDef,
        )


    def delete_db_proxy_endpoint(
        self, request: DeleteDBProxyEndpointRequestTypeDef,
    ) -> DeleteDBProxyEndpointResponseTypeDef:
        return self._call(
            "delete_db_proxy_endpoint",
            request,
            DeleteDBProxyEndpointResponseTypeDef,
        )


    def delete_db_security_group(
        self, request: DeleteDBSecurityGroupMessageTypeDef,
    ) -> None:
        return self._call(
            "delete_db_security_group",
            request,
            None,
        )


    def delete_db_shard_group(
        self, request: DeleteDBShardGroupMessageTypeDef,
    ) -> DBShardGroupTypeDef:
        return self._call(
            "delete_db_shard_group",
            request,
            DBShardGroupTypeDef,
        )


    def delete_db_snapshot(
        self, request: DeleteDBSnapshotMessageTypeDef,
    ) -> DeleteDBSnapshotResultTypeDef:
        return self._call(
            "delete_db_snapshot",
            request,
            DeleteDBSnapshotResultTypeDef,
        )


    def delete_db_subnet_group(
        self, request: DeleteDBSubnetGroupMessageTypeDef,
    ) -> None:
        return self._call(
            "delete_db_subnet_group",
            request,
            None,
        )


    def delete_event_subscription(
        self, request: DeleteEventSubscriptionMessageTypeDef,
    ) -> DeleteEventSubscriptionResultTypeDef:
        return self._call(
            "delete_event_subscription",
            request,
            DeleteEventSubscriptionResultTypeDef,
        )


    def delete_global_cluster(
        self, request: DeleteGlobalClusterMessageTypeDef,
    ) -> DeleteGlobalClusterResultTypeDef:
        return self._call(
            "delete_global_cluster",
            request,
            DeleteGlobalClusterResultTypeDef,
        )


    def delete_integration(
        self, request: DeleteIntegrationMessageTypeDef,
    ) -> IntegrationTypeDef:
        return self._call(
            "delete_integration",
            request,
            IntegrationTypeDef,
        )


    def delete_option_group(
        self, request: DeleteOptionGroupMessageTypeDef,
    ) -> None:
        return self._call(
            "delete_option_group",
            request,
            None,
        )


    def delete_tenant_database(
        self, request: DeleteTenantDatabaseMessageTypeDef,
    ) -> DeleteTenantDatabaseResultTypeDef:
        return self._call(
            "delete_tenant_database",
            request,
            DeleteTenantDatabaseResultTypeDef,
        )


    def deregister_db_proxy_targets(
        self, request: DeregisterDBProxyTargetsRequestTypeDef,
    ) -> None:
        return self._call(
            "deregister_db_proxy_targets",
            request,
            None,
        )


    def describe_account_attributes(
        self,
    ) -> AccountAttributesMessageTypeDef:
        return self._call(
            "describe_account_attributes",
            None,
            AccountAttributesMessageTypeDef,
        )


    def describe_blue_green_deployments(
        self, request: DescribeBlueGreenDeploymentsRequestTypeDef,
    ) -> DescribeBlueGreenDeploymentsResponseTypeDef:
        return self._call(
            "describe_blue_green_deployments",
            request,
            DescribeBlueGreenDeploymentsResponseTypeDef,
        )


    def describe_certificates(
        self, request: DescribeCertificatesMessageTypeDef,
    ) -> CertificateMessageTypeDef:
        return self._call(
            "describe_certificates",
            request,
            CertificateMessageTypeDef,
        )


    def describe_db_cluster_automated_backups(
        self, request: DescribeDBClusterAutomatedBackupsMessageTypeDef,
    ) -> DBClusterAutomatedBackupMessageTypeDef:
        return self._call(
            "describe_db_cluster_automated_backups",
            request,
            DBClusterAutomatedBackupMessageTypeDef,
        )


    def describe_db_cluster_backtracks(
        self, request: DescribeDBClusterBacktracksMessageTypeDef,
    ) -> DBClusterBacktrackMessageTypeDef:
        return self._call(
            "describe_db_cluster_backtracks",
            request,
            DBClusterBacktrackMessageTypeDef,
        )


    def describe_db_cluster_endpoints(
        self, request: DescribeDBClusterEndpointsMessageTypeDef,
    ) -> DBClusterEndpointMessageTypeDef:
        return self._call(
            "describe_db_cluster_endpoints",
            request,
            DBClusterEndpointMessageTypeDef,
        )


    def describe_db_cluster_parameter_groups(
        self, request: DescribeDBClusterParameterGroupsMessageTypeDef,
    ) -> DBClusterParameterGroupsMessageTypeDef:
        return self._call(
            "describe_db_cluster_parameter_groups",
            request,
            DBClusterParameterGroupsMessageTypeDef,
        )


    def describe_db_cluster_parameters(
        self, request: DescribeDBClusterParametersMessageTypeDef,
    ) -> DBClusterParameterGroupDetailsTypeDef:
        return self._call(
            "describe_db_cluster_parameters",
            request,
            DBClusterParameterGroupDetailsTypeDef,
        )


    def describe_db_cluster_snapshot_attributes(
        self, request: DescribeDBClusterSnapshotAttributesMessageTypeDef,
    ) -> DescribeDBClusterSnapshotAttributesResultTypeDef:
        return self._call(
            "describe_db_cluster_snapshot_attributes",
            request,
            DescribeDBClusterSnapshotAttributesResultTypeDef,
        )


    def describe_db_cluster_snapshots(
        self, request: DescribeDBClusterSnapshotsMessageTypeDef,
    ) -> DBClusterSnapshotMessageTypeDef:
        return self._call(
            "describe_db_cluster_snapshots",
            request,
            DBClusterSnapshotMessageTypeDef,
        )


    def describe_db_clusters(
        self, request: DescribeDBClustersMessageTypeDef,
    ) -> DBClusterMessageTypeDef:
        return self._call(
            "describe_db_clusters",
            request,
            DBClusterMessageTypeDef,
        )


    def describe_db_engine_versions(
        self, request: DescribeDBEngineVersionsMessageTypeDef,
    ) -> DBEngineVersionMessageTypeDef:
        return self._call(
            "describe_db_engine_versions",
            request,
            DBEngineVersionMessageTypeDef,
        )


    def describe_db_instance_automated_backups(
        self, request: DescribeDBInstanceAutomatedBackupsMessageTypeDef,
    ) -> DBInstanceAutomatedBackupMessageTypeDef:
        return self._call(
            "describe_db_instance_automated_backups",
            request,
            DBInstanceAutomatedBackupMessageTypeDef,
        )


    def describe_db_instances(
        self, request: DescribeDBInstancesMessageTypeDef,
    ) -> DBInstanceMessageTypeDef:
        return self._call(
            "describe_db_instances",
            request,
            DBInstanceMessageTypeDef,
        )


    def describe_db_log_files(
        self, request: DescribeDBLogFilesMessageTypeDef,
    ) -> DescribeDBLogFilesResponseTypeDef:
        return self._call(
            "describe_db_log_files",
            request,
            DescribeDBLogFilesResponseTypeDef,
        )


    def describe_db_major_engine_versions(
        self, request: DescribeDBMajorEngineVersionsRequestTypeDef,
    ) -> DescribeDBMajorEngineVersionsResponseTypeDef:
        return self._call(
            "describe_db_major_engine_versions",
            request,
            DescribeDBMajorEngineVersionsResponseTypeDef,
        )


    def describe_db_parameter_groups(
        self, request: DescribeDBParameterGroupsMessageTypeDef,
    ) -> DBParameterGroupsMessageTypeDef:
        return self._call(
            "describe_db_parameter_groups",
            request,
            DBParameterGroupsMessageTypeDef,
        )


    def describe_db_parameters(
        self, request: DescribeDBParametersMessageTypeDef,
    ) -> DBParameterGroupDetailsTypeDef:
        return self._call(
            "describe_db_parameters",
            request,
            DBParameterGroupDetailsTypeDef,
        )


    def describe_db_proxies(
        self, request: DescribeDBProxiesRequestTypeDef,
    ) -> DescribeDBProxiesResponseTypeDef:
        return self._call(
            "describe_db_proxies",
            request,
            DescribeDBProxiesResponseTypeDef,
        )


    def describe_db_proxy_endpoints(
        self, request: DescribeDBProxyEndpointsRequestTypeDef,
    ) -> DescribeDBProxyEndpointsResponseTypeDef:
        return self._call(
            "describe_db_proxy_endpoints",
            request,
            DescribeDBProxyEndpointsResponseTypeDef,
        )


    def describe_db_proxy_target_groups(
        self, request: DescribeDBProxyTargetGroupsRequestTypeDef,
    ) -> DescribeDBProxyTargetGroupsResponseTypeDef:
        return self._call(
            "describe_db_proxy_target_groups",
            request,
            DescribeDBProxyTargetGroupsResponseTypeDef,
        )


    def describe_db_proxy_targets(
        self, request: DescribeDBProxyTargetsRequestTypeDef,
    ) -> DescribeDBProxyTargetsResponseTypeDef:
        return self._call(
            "describe_db_proxy_targets",
            request,
            DescribeDBProxyTargetsResponseTypeDef,
        )


    def describe_db_recommendations(
        self, request: DescribeDBRecommendationsMessageTypeDef,
    ) -> DBRecommendationsMessageTypeDef:
        return self._call(
            "describe_db_recommendations",
            request,
            DBRecommendationsMessageTypeDef,
        )


    def describe_db_security_groups(
        self, request: DescribeDBSecurityGroupsMessageTypeDef,
    ) -> DBSecurityGroupMessageTypeDef:
        return self._call(
            "describe_db_security_groups",
            request,
            DBSecurityGroupMessageTypeDef,
        )


    def describe_db_shard_groups(
        self, request: DescribeDBShardGroupsMessageTypeDef,
    ) -> DescribeDBShardGroupsResponseTypeDef:
        return self._call(
            "describe_db_shard_groups",
            request,
            DescribeDBShardGroupsResponseTypeDef,
        )


    def describe_db_snapshot_attributes(
        self, request: DescribeDBSnapshotAttributesMessageTypeDef,
    ) -> DescribeDBSnapshotAttributesResultTypeDef:
        return self._call(
            "describe_db_snapshot_attributes",
            request,
            DescribeDBSnapshotAttributesResultTypeDef,
        )


    def describe_db_snapshot_tenant_databases(
        self, request: DescribeDBSnapshotTenantDatabasesMessageTypeDef,
    ) -> DBSnapshotTenantDatabasesMessageTypeDef:
        return self._call(
            "describe_db_snapshot_tenant_databases",
            request,
            DBSnapshotTenantDatabasesMessageTypeDef,
        )


    def describe_db_snapshots(
        self, request: DescribeDBSnapshotsMessageTypeDef,
    ) -> DBSnapshotMessageTypeDef:
        return self._call(
            "describe_db_snapshots",
            request,
            DBSnapshotMessageTypeDef,
        )


    def describe_db_subnet_groups(
        self, request: DescribeDBSubnetGroupsMessageTypeDef,
    ) -> DBSubnetGroupMessageTypeDef:
        return self._call(
            "describe_db_subnet_groups",
            request,
            DBSubnetGroupMessageTypeDef,
        )


    def describe_engine_default_cluster_parameters(
        self, request: DescribeEngineDefaultClusterParametersMessageTypeDef,
    ) -> DescribeEngineDefaultClusterParametersResultTypeDef:
        return self._call(
            "describe_engine_default_cluster_parameters",
            request,
            DescribeEngineDefaultClusterParametersResultTypeDef,
        )


    def describe_engine_default_parameters(
        self, request: DescribeEngineDefaultParametersMessageTypeDef,
    ) -> DescribeEngineDefaultParametersResultTypeDef:
        return self._call(
            "describe_engine_default_parameters",
            request,
            DescribeEngineDefaultParametersResultTypeDef,
        )


    def describe_event_categories(
        self, request: DescribeEventCategoriesMessageTypeDef,
    ) -> EventCategoriesMessageTypeDef:
        return self._call(
            "describe_event_categories",
            request,
            EventCategoriesMessageTypeDef,
        )


    def describe_event_subscriptions(
        self, request: DescribeEventSubscriptionsMessageTypeDef,
    ) -> EventSubscriptionsMessageTypeDef:
        return self._call(
            "describe_event_subscriptions",
            request,
            EventSubscriptionsMessageTypeDef,
        )


    def describe_events(
        self, request: DescribeEventsMessageTypeDef,
    ) -> EventsMessageTypeDef:
        return self._call(
            "describe_events",
            request,
            EventsMessageTypeDef,
        )


    def describe_export_tasks(
        self, request: DescribeExportTasksMessageTypeDef,
    ) -> ExportTasksMessageTypeDef:
        return self._call(
            "describe_export_tasks",
            request,
            ExportTasksMessageTypeDef,
        )


    def describe_global_clusters(
        self, request: DescribeGlobalClustersMessageTypeDef,
    ) -> GlobalClustersMessageTypeDef:
        return self._call(
            "describe_global_clusters",
            request,
            GlobalClustersMessageTypeDef,
        )


    def describe_integrations(
        self, request: DescribeIntegrationsMessageTypeDef,
    ) -> DescribeIntegrationsResponseTypeDef:
        return self._call(
            "describe_integrations",
            request,
            DescribeIntegrationsResponseTypeDef,
        )


    def describe_option_group_options(
        self, request: DescribeOptionGroupOptionsMessageTypeDef,
    ) -> OptionGroupOptionsMessageTypeDef:
        return self._call(
            "describe_option_group_options",
            request,
            OptionGroupOptionsMessageTypeDef,
        )


    def describe_option_groups(
        self, request: DescribeOptionGroupsMessageTypeDef,
    ) -> OptionGroupsTypeDef:
        return self._call(
            "describe_option_groups",
            request,
            OptionGroupsTypeDef,
        )


    def describe_orderable_db_instance_options(
        self, request: DescribeOrderableDBInstanceOptionsMessageTypeDef,
    ) -> OrderableDBInstanceOptionsMessageTypeDef:
        return self._call(
            "describe_orderable_db_instance_options",
            request,
            OrderableDBInstanceOptionsMessageTypeDef,
        )


    def describe_pending_maintenance_actions(
        self, request: DescribePendingMaintenanceActionsMessageTypeDef,
    ) -> PendingMaintenanceActionsMessageTypeDef:
        return self._call(
            "describe_pending_maintenance_actions",
            request,
            PendingMaintenanceActionsMessageTypeDef,
        )


    def describe_reserved_db_instances(
        self, request: DescribeReservedDBInstancesMessageTypeDef,
    ) -> ReservedDBInstanceMessageTypeDef:
        return self._call(
            "describe_reserved_db_instances",
            request,
            ReservedDBInstanceMessageTypeDef,
        )


    def describe_reserved_db_instances_offerings(
        self, request: DescribeReservedDBInstancesOfferingsMessageTypeDef,
    ) -> ReservedDBInstancesOfferingMessageTypeDef:
        return self._call(
            "describe_reserved_db_instances_offerings",
            request,
            ReservedDBInstancesOfferingMessageTypeDef,
        )


    def describe_serverless_v2_platform_versions(
        self, request: DescribeServerlessV2PlatformVersionsMessageTypeDef,
    ) -> ServerlessV2PlatformVersionsMessageTypeDef:
        return self._call(
            "describe_serverless_v2_platform_versions",
            request,
            ServerlessV2PlatformVersionsMessageTypeDef,
        )


    def describe_source_regions(
        self, request: DescribeSourceRegionsMessageTypeDef,
    ) -> SourceRegionMessageTypeDef:
        return self._call(
            "describe_source_regions",
            request,
            SourceRegionMessageTypeDef,
        )


    def describe_tenant_databases(
        self, request: DescribeTenantDatabasesMessageTypeDef,
    ) -> TenantDatabasesMessageTypeDef:
        return self._call(
            "describe_tenant_databases",
            request,
            TenantDatabasesMessageTypeDef,
        )


    def describe_valid_db_instance_modifications(
        self, request: DescribeValidDBInstanceModificationsMessageTypeDef,
    ) -> DescribeValidDBInstanceModificationsResultTypeDef:
        return self._call(
            "describe_valid_db_instance_modifications",
            request,
            DescribeValidDBInstanceModificationsResultTypeDef,
        )


    def disable_http_endpoint(
        self, request: DisableHttpEndpointRequestTypeDef,
    ) -> DisableHttpEndpointResponseTypeDef:
        return self._call(
            "disable_http_endpoint",
            request,
            DisableHttpEndpointResponseTypeDef,
        )


    def download_db_log_file_portion(
        self, request: DownloadDBLogFilePortionMessageTypeDef,
    ) -> DownloadDBLogFilePortionDetailsTypeDef:
        return self._call(
            "download_db_log_file_portion",
            request,
            DownloadDBLogFilePortionDetailsTypeDef,
        )


    def enable_http_endpoint(
        self, request: EnableHttpEndpointRequestTypeDef,
    ) -> EnableHttpEndpointResponseTypeDef:
        return self._call(
            "enable_http_endpoint",
            request,
            EnableHttpEndpointResponseTypeDef,
        )


    def failover_db_cluster(
        self, request: FailoverDBClusterMessageTypeDef,
    ) -> FailoverDBClusterResultTypeDef:
        return self._call(
            "failover_db_cluster",
            request,
            FailoverDBClusterResultTypeDef,
        )


    def failover_global_cluster(
        self, request: FailoverGlobalClusterMessageTypeDef,
    ) -> FailoverGlobalClusterResultTypeDef:
        return self._call(
            "failover_global_cluster",
            request,
            FailoverGlobalClusterResultTypeDef,
        )


    def list_tags_for_resource(
        self, request: ListTagsForResourceMessageTypeDef,
    ) -> TagListMessageTypeDef:
        return self._call(
            "list_tags_for_resource",
            request,
            TagListMessageTypeDef,
        )


    def modify_activity_stream(
        self, request: ModifyActivityStreamRequestTypeDef,
    ) -> ModifyActivityStreamResponseTypeDef:
        return self._call(
            "modify_activity_stream",
            request,
            ModifyActivityStreamResponseTypeDef,
        )


    def modify_certificates(
        self, request: ModifyCertificatesMessageTypeDef,
    ) -> ModifyCertificatesResultTypeDef:
        return self._call(
            "modify_certificates",
            request,
            ModifyCertificatesResultTypeDef,
        )


    def modify_current_db_cluster_capacity(
        self, request: ModifyCurrentDBClusterCapacityMessageTypeDef,
    ) -> DBClusterCapacityInfoTypeDef:
        return self._call(
            "modify_current_db_cluster_capacity",
            request,
            DBClusterCapacityInfoTypeDef,
        )


    def modify_custom_db_engine_version(
        self, request: ModifyCustomDBEngineVersionMessageTypeDef,
    ) -> DBEngineVersionTypeDef:
        return self._call(
            "modify_custom_db_engine_version",
            request,
            DBEngineVersionTypeDef,
        )


    def modify_db_cluster(
        self, request: ModifyDBClusterMessageTypeDef,
    ) -> ModifyDBClusterResultTypeDef:
        return self._call(
            "modify_db_cluster",
            request,
            ModifyDBClusterResultTypeDef,
        )


    def modify_db_cluster_endpoint(
        self, request: ModifyDBClusterEndpointMessageTypeDef,
    ) -> DBClusterEndpointTypeDef:
        return self._call(
            "modify_db_cluster_endpoint",
            request,
            DBClusterEndpointTypeDef,
        )


    def modify_db_cluster_parameter_group(
        self, request: ModifyDBClusterParameterGroupMessageTypeDef,
    ) -> DBClusterParameterGroupNameMessageTypeDef:
        return self._call(
            "modify_db_cluster_parameter_group",
            request,
            DBClusterParameterGroupNameMessageTypeDef,
        )


    def modify_db_cluster_snapshot_attribute(
        self, request: ModifyDBClusterSnapshotAttributeMessageTypeDef,
    ) -> ModifyDBClusterSnapshotAttributeResultTypeDef:
        return self._call(
            "modify_db_cluster_snapshot_attribute",
            request,
            ModifyDBClusterSnapshotAttributeResultTypeDef,
        )


    def modify_db_instance(
        self, request: ModifyDBInstanceMessageTypeDef,
    ) -> ModifyDBInstanceResultTypeDef:
        return self._call(
            "modify_db_instance",
            request,
            ModifyDBInstanceResultTypeDef,
        )


    def modify_db_parameter_group(
        self, request: ModifyDBParameterGroupMessageTypeDef,
    ) -> DBParameterGroupNameMessageTypeDef:
        return self._call(
            "modify_db_parameter_group",
            request,
            DBParameterGroupNameMessageTypeDef,
        )


    def modify_db_proxy(
        self, request: ModifyDBProxyRequestTypeDef,
    ) -> ModifyDBProxyResponseTypeDef:
        return self._call(
            "modify_db_proxy",
            request,
            ModifyDBProxyResponseTypeDef,
        )


    def modify_db_proxy_endpoint(
        self, request: ModifyDBProxyEndpointRequestTypeDef,
    ) -> ModifyDBProxyEndpointResponseTypeDef:
        return self._call(
            "modify_db_proxy_endpoint",
            request,
            ModifyDBProxyEndpointResponseTypeDef,
        )


    def modify_db_proxy_target_group(
        self, request: ModifyDBProxyTargetGroupRequestTypeDef,
    ) -> ModifyDBProxyTargetGroupResponseTypeDef:
        return self._call(
            "modify_db_proxy_target_group",
            request,
            ModifyDBProxyTargetGroupResponseTypeDef,
        )


    def modify_db_recommendation(
        self, request: ModifyDBRecommendationMessageTypeDef,
    ) -> DBRecommendationMessageTypeDef:
        return self._call(
            "modify_db_recommendation",
            request,
            DBRecommendationMessageTypeDef,
        )


    def modify_db_shard_group(
        self, request: ModifyDBShardGroupMessageTypeDef,
    ) -> DBShardGroupTypeDef:
        return self._call(
            "modify_db_shard_group",
            request,
            DBShardGroupTypeDef,
        )


    def modify_db_snapshot(
        self, request: ModifyDBSnapshotMessageTypeDef,
    ) -> ModifyDBSnapshotResultTypeDef:
        return self._call(
            "modify_db_snapshot",
            request,
            ModifyDBSnapshotResultTypeDef,
        )


    def modify_db_snapshot_attribute(
        self, request: ModifyDBSnapshotAttributeMessageTypeDef,
    ) -> ModifyDBSnapshotAttributeResultTypeDef:
        return self._call(
            "modify_db_snapshot_attribute",
            request,
            ModifyDBSnapshotAttributeResultTypeDef,
        )


    def modify_db_subnet_group(
        self, request: ModifyDBSubnetGroupMessageTypeDef,
    ) -> ModifyDBSubnetGroupResultTypeDef:
        return self._call(
            "modify_db_subnet_group",
            request,
            ModifyDBSubnetGroupResultTypeDef,
        )


    def modify_event_subscription(
        self, request: ModifyEventSubscriptionMessageTypeDef,
    ) -> ModifyEventSubscriptionResultTypeDef:
        return self._call(
            "modify_event_subscription",
            request,
            ModifyEventSubscriptionResultTypeDef,
        )


    def modify_global_cluster(
        self, request: ModifyGlobalClusterMessageTypeDef,
    ) -> ModifyGlobalClusterResultTypeDef:
        return self._call(
            "modify_global_cluster",
            request,
            ModifyGlobalClusterResultTypeDef,
        )


    def modify_integration(
        self, request: ModifyIntegrationMessageTypeDef,
    ) -> IntegrationTypeDef:
        return self._call(
            "modify_integration",
            request,
            IntegrationTypeDef,
        )


    def modify_option_group(
        self, request: ModifyOptionGroupMessageTypeDef,
    ) -> ModifyOptionGroupResultTypeDef:
        return self._call(
            "modify_option_group",
            request,
            ModifyOptionGroupResultTypeDef,
        )


    def modify_tenant_database(
        self, request: ModifyTenantDatabaseMessageTypeDef,
    ) -> ModifyTenantDatabaseResultTypeDef:
        return self._call(
            "modify_tenant_database",
            request,
            ModifyTenantDatabaseResultTypeDef,
        )


    def promote_read_replica(
        self, request: PromoteReadReplicaMessageTypeDef,
    ) -> PromoteReadReplicaResultTypeDef:
        return self._call(
            "promote_read_replica",
            request,
            PromoteReadReplicaResultTypeDef,
        )


    def promote_read_replica_db_cluster(
        self, request: PromoteReadReplicaDBClusterMessageTypeDef,
    ) -> PromoteReadReplicaDBClusterResultTypeDef:
        return self._call(
            "promote_read_replica_db_cluster",
            request,
            PromoteReadReplicaDBClusterResultTypeDef,
        )


    def purchase_reserved_db_instances_offering(
        self, request: PurchaseReservedDBInstancesOfferingMessageTypeDef,
    ) -> PurchaseReservedDBInstancesOfferingResultTypeDef:
        return self._call(
            "purchase_reserved_db_instances_offering",
            request,
            PurchaseReservedDBInstancesOfferingResultTypeDef,
        )


    def reboot_db_cluster(
        self, request: RebootDBClusterMessageTypeDef,
    ) -> RebootDBClusterResultTypeDef:
        return self._call(
            "reboot_db_cluster",
            request,
            RebootDBClusterResultTypeDef,
        )


    def reboot_db_instance(
        self, request: RebootDBInstanceMessageTypeDef,
    ) -> RebootDBInstanceResultTypeDef:
        return self._call(
            "reboot_db_instance",
            request,
            RebootDBInstanceResultTypeDef,
        )


    def reboot_db_shard_group(
        self, request: RebootDBShardGroupMessageTypeDef,
    ) -> DBShardGroupTypeDef:
        return self._call(
            "reboot_db_shard_group",
            request,
            DBShardGroupTypeDef,
        )


    def register_db_proxy_targets(
        self, request: RegisterDBProxyTargetsRequestTypeDef,
    ) -> RegisterDBProxyTargetsResponseTypeDef:
        return self._call(
            "register_db_proxy_targets",
            request,
            RegisterDBProxyTargetsResponseTypeDef,
        )


    def remove_from_global_cluster(
        self, request: RemoveFromGlobalClusterMessageTypeDef,
    ) -> RemoveFromGlobalClusterResultTypeDef:
        return self._call(
            "remove_from_global_cluster",
            request,
            RemoveFromGlobalClusterResultTypeDef,
        )


    def remove_role_from_db_cluster(
        self, request: RemoveRoleFromDBClusterMessageTypeDef,
    ) -> None:
        return self._call(
            "remove_role_from_db_cluster",
            request,
            None,
        )


    def remove_role_from_db_instance(
        self, request: RemoveRoleFromDBInstanceMessageTypeDef,
    ) -> None:
        return self._call(
            "remove_role_from_db_instance",
            request,
            None,
        )


    def remove_source_identifier_from_subscription(
        self, request: RemoveSourceIdentifierFromSubscriptionMessageTypeDef,
    ) -> RemoveSourceIdentifierFromSubscriptionResultTypeDef:
        return self._call(
            "remove_source_identifier_from_subscription",
            request,
            RemoveSourceIdentifierFromSubscriptionResultTypeDef,
        )


    def remove_tags_from_resource(
        self, request: RemoveTagsFromResourceMessageTypeDef,
    ) -> None:
        return self._call(
            "remove_tags_from_resource",
            request,
            None,
        )


    def reset_db_cluster_parameter_group(
        self, request: ResetDBClusterParameterGroupMessageTypeDef,
    ) -> DBClusterParameterGroupNameMessageTypeDef:
        return self._call(
            "reset_db_cluster_parameter_group",
            request,
            DBClusterParameterGroupNameMessageTypeDef,
        )


    def reset_db_parameter_group(
        self, request: ResetDBParameterGroupMessageTypeDef,
    ) -> DBParameterGroupNameMessageTypeDef:
        return self._call(
            "reset_db_parameter_group",
            request,
            DBParameterGroupNameMessageTypeDef,
        )


    def restore_db_cluster_from_s3(
        self, request: RestoreDBClusterFromS3MessageTypeDef,
    ) -> RestoreDBClusterFromS3ResultTypeDef:
        return self._call(
            "restore_db_cluster_from_s3",
            request,
            RestoreDBClusterFromS3ResultTypeDef,
        )


    def restore_db_cluster_from_snapshot(
        self, request: RestoreDBClusterFromSnapshotMessageTypeDef,
    ) -> RestoreDBClusterFromSnapshotResultTypeDef:
        return self._call(
            "restore_db_cluster_from_snapshot",
            request,
            RestoreDBClusterFromSnapshotResultTypeDef,
        )


    def restore_db_cluster_to_point_in_time(
        self, request: RestoreDBClusterToPointInTimeMessageTypeDef,
    ) -> RestoreDBClusterToPointInTimeResultTypeDef:
        return self._call(
            "restore_db_cluster_to_point_in_time",
            request,
            RestoreDBClusterToPointInTimeResultTypeDef,
        )


    def restore_db_instance_from_db_snapshot(
        self, request: RestoreDBInstanceFromDBSnapshotMessageTypeDef,
    ) -> RestoreDBInstanceFromDBSnapshotResultTypeDef:
        return self._call(
            "restore_db_instance_from_db_snapshot",
            request,
            RestoreDBInstanceFromDBSnapshotResultTypeDef,
        )


    def restore_db_instance_from_s3(
        self, request: RestoreDBInstanceFromS3MessageTypeDef,
    ) -> RestoreDBInstanceFromS3ResultTypeDef:
        return self._call(
            "restore_db_instance_from_s3",
            request,
            RestoreDBInstanceFromS3ResultTypeDef,
        )


    def restore_db_instance_to_point_in_time(
        self, request: RestoreDBInstanceToPointInTimeMessageTypeDef,
    ) -> RestoreDBInstanceToPointInTimeResultTypeDef:
        return self._call(
            "restore_db_instance_to_point_in_time",
            request,
            RestoreDBInstanceToPointInTimeResultTypeDef,
        )


    def revoke_db_security_group_ingress(
        self, request: RevokeDBSecurityGroupIngressMessageTypeDef,
    ) -> RevokeDBSecurityGroupIngressResultTypeDef:
        return self._call(
            "revoke_db_security_group_ingress",
            request,
            RevokeDBSecurityGroupIngressResultTypeDef,
        )


    def start_activity_stream(
        self, request: StartActivityStreamRequestTypeDef,
    ) -> StartActivityStreamResponseTypeDef:
        return self._call(
            "start_activity_stream",
            request,
            StartActivityStreamResponseTypeDef,
        )


    def start_db_cluster(
        self, request: StartDBClusterMessageTypeDef,
    ) -> StartDBClusterResultTypeDef:
        return self._call(
            "start_db_cluster",
            request,
            StartDBClusterResultTypeDef,
        )


    def start_db_instance(
        self, request: StartDBInstanceMessageTypeDef,
    ) -> StartDBInstanceResultTypeDef:
        return self._call(
            "start_db_instance",
            request,
            StartDBInstanceResultTypeDef,
        )


    def start_db_instance_automated_backups_replication(
        self, request: StartDBInstanceAutomatedBackupsReplicationMessageTypeDef,
    ) -> StartDBInstanceAutomatedBackupsReplicationResultTypeDef:
        return self._call(
            "start_db_instance_automated_backups_replication",
            request,
            StartDBInstanceAutomatedBackupsReplicationResultTypeDef,
        )


    def start_export_task(
        self, request: StartExportTaskMessageTypeDef,
    ) -> ExportTaskTypeDef:
        return self._call(
            "start_export_task",
            request,
            ExportTaskTypeDef,
        )


    def stop_activity_stream(
        self, request: StopActivityStreamRequestTypeDef,
    ) -> StopActivityStreamResponseTypeDef:
        return self._call(
            "stop_activity_stream",
            request,
            StopActivityStreamResponseTypeDef,
        )


    def stop_db_cluster(
        self, request: StopDBClusterMessageTypeDef,
    ) -> StopDBClusterResultTypeDef:
        return self._call(
            "stop_db_cluster",
            request,
            StopDBClusterResultTypeDef,
        )


    def stop_db_instance(
        self, request: StopDBInstanceMessageTypeDef,
    ) -> StopDBInstanceResultTypeDef:
        return self._call(
            "stop_db_instance",
            request,
            StopDBInstanceResultTypeDef,
        )


    def stop_db_instance_automated_backups_replication(
        self, request: StopDBInstanceAutomatedBackupsReplicationMessageTypeDef,
    ) -> StopDBInstanceAutomatedBackupsReplicationResultTypeDef:
        return self._call(
            "stop_db_instance_automated_backups_replication",
            request,
            StopDBInstanceAutomatedBackupsReplicationResultTypeDef,
        )


    def switchover_blue_green_deployment(
        self, request: SwitchoverBlueGreenDeploymentRequestTypeDef,
    ) -> SwitchoverBlueGreenDeploymentResponseTypeDef:
        return self._call(
            "switchover_blue_green_deployment",
            request,
            SwitchoverBlueGreenDeploymentResponseTypeDef,
        )


    def switchover_global_cluster(
        self, request: SwitchoverGlobalClusterMessageTypeDef,
    ) -> SwitchoverGlobalClusterResultTypeDef:
        return self._call(
            "switchover_global_cluster",
            request,
            SwitchoverGlobalClusterResultTypeDef,
        )


    def switchover_read_replica(
        self, request: SwitchoverReadReplicaMessageTypeDef,
    ) -> SwitchoverReadReplicaResultTypeDef:
        return self._call(
            "switchover_read_replica",
            request,
            SwitchoverReadReplicaResultTypeDef,
        )

