# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.s3.s3_classes import (
    AbortMultipartUploadOutputTypeDef,
    AbortMultipartUploadRequestTypeDef,
    CompleteMultipartUploadOutputTypeDef,
    CompleteMultipartUploadRequestTypeDef,
    CopyObjectOutputTypeDef,
    CopyObjectRequestTypeDef,
    CreateBucketMetadataConfigurationRequestTypeDef,
    CreateBucketMetadataTableConfigurationRequestTypeDef,
    CreateBucketOutputTypeDef,
    CreateBucketRequestTypeDef,
    CreateMultipartUploadOutputTypeDef,
    CreateMultipartUploadRequestTypeDef,
    CreateSessionOutputTypeDef,
    CreateSessionRequestTypeDef,
    DeleteBucketAnalyticsConfigurationRequestTypeDef,
    DeleteBucketCorsRequestTypeDef,
    DeleteBucketEncryptionRequestTypeDef,
    DeleteBucketIntelligentTieringConfigurationRequestTypeDef,
    DeleteBucketInventoryConfigurationRequestTypeDef,
    DeleteBucketLifecycleRequestTypeDef,
    DeleteBucketMetadataConfigurationRequestTypeDef,
    DeleteBucketMetadataTableConfigurationRequestTypeDef,
    DeleteBucketMetricsConfigurationRequestTypeDef,
    DeleteBucketOwnershipControlsRequestTypeDef,
    DeleteBucketPolicyRequestTypeDef,
    DeleteBucketReplicationRequestTypeDef,
    DeleteBucketRequestTypeDef,
    DeleteBucketTaggingRequestTypeDef,
    DeleteBucketWebsiteRequestTypeDef,
    DeleteObjectOutputTypeDef,
    DeleteObjectRequestTypeDef,
    DeleteObjectTaggingOutputTypeDef,
    DeleteObjectTaggingRequestTypeDef,
    DeleteObjectsOutputTypeDef,
    DeleteObjectsRequestTypeDef,
    DeletePublicAccessBlockRequestTypeDef,
    GetBucketAbacOutputTypeDef,
    GetBucketAbacRequestTypeDef,
    GetBucketAccelerateConfigurationOutputTypeDef,
    GetBucketAccelerateConfigurationRequestTypeDef,
    GetBucketAclOutputTypeDef,
    GetBucketAclRequestTypeDef,
    GetBucketAnalyticsConfigurationOutputTypeDef,
    GetBucketAnalyticsConfigurationRequestTypeDef,
    GetBucketCorsOutputTypeDef,
    GetBucketCorsRequestTypeDef,
    GetBucketEncryptionOutputTypeDef,
    GetBucketEncryptionRequestTypeDef,
    GetBucketIntelligentTieringConfigurationOutputTypeDef,
    GetBucketIntelligentTieringConfigurationRequestTypeDef,
    GetBucketInventoryConfigurationOutputTypeDef,
    GetBucketInventoryConfigurationRequestTypeDef,
    GetBucketLifecycleConfigurationOutputTypeDef,
    GetBucketLifecycleConfigurationRequestTypeDef,
    GetBucketLifecycleOutputTypeDef,
    GetBucketLifecycleRequestTypeDef,
    GetBucketLocationOutputTypeDef,
    GetBucketLocationRequestTypeDef,
    GetBucketLoggingOutputTypeDef,
    GetBucketLoggingRequestTypeDef,
    GetBucketMetadataConfigurationOutputTypeDef,
    GetBucketMetadataConfigurationRequestTypeDef,
    GetBucketMetadataTableConfigurationOutputTypeDef,
    GetBucketMetadataTableConfigurationRequestTypeDef,
    GetBucketMetricsConfigurationOutputTypeDef,
    GetBucketMetricsConfigurationRequestTypeDef,
    GetBucketNotificationConfigurationRequestTypeDef,
    GetBucketOwnershipControlsOutputTypeDef,
    GetBucketOwnershipControlsRequestTypeDef,
    GetBucketPolicyOutputTypeDef,
    GetBucketPolicyRequestTypeDef,
    GetBucketPolicyStatusOutputTypeDef,
    GetBucketPolicyStatusRequestTypeDef,
    GetBucketReplicationOutputTypeDef,
    GetBucketReplicationRequestTypeDef,
    GetBucketRequestPaymentOutputTypeDef,
    GetBucketRequestPaymentRequestTypeDef,
    GetBucketTaggingOutputTypeDef,
    GetBucketTaggingRequestTypeDef,
    GetBucketVersioningOutputTypeDef,
    GetBucketVersioningRequestTypeDef,
    GetBucketWebsiteOutputTypeDef,
    GetBucketWebsiteRequestTypeDef,
    GetObjectAclOutputTypeDef,
    GetObjectAclRequestTypeDef,
    GetObjectAttributesOutputTypeDef,
    GetObjectAttributesRequestTypeDef,
    GetObjectLegalHoldOutputTypeDef,
    GetObjectLegalHoldRequestTypeDef,
    GetObjectLockConfigurationOutputTypeDef,
    GetObjectLockConfigurationRequestTypeDef,
    GetObjectOutputTypeDef,
    GetObjectRequestTypeDef,
    GetObjectRetentionOutputTypeDef,
    GetObjectRetentionRequestTypeDef,
    GetObjectTaggingOutputTypeDef,
    GetObjectTaggingRequestTypeDef,
    GetObjectTorrentOutputTypeDef,
    GetObjectTorrentRequestTypeDef,
    GetPublicAccessBlockOutputTypeDef,
    GetPublicAccessBlockRequestTypeDef,
    HeadBucketOutputTypeDef,
    HeadBucketRequestTypeDef,
    HeadObjectOutputTypeDef,
    HeadObjectRequestTypeDef,
    ListBucketAnalyticsConfigurationsOutputTypeDef,
    ListBucketAnalyticsConfigurationsRequestTypeDef,
    ListBucketIntelligentTieringConfigurationsOutputTypeDef,
    ListBucketIntelligentTieringConfigurationsRequestTypeDef,
    ListBucketInventoryConfigurationsOutputTypeDef,
    ListBucketInventoryConfigurationsRequestTypeDef,
    ListBucketMetricsConfigurationsOutputTypeDef,
    ListBucketMetricsConfigurationsRequestTypeDef,
    ListBucketsOutputTypeDef,
    ListBucketsRequestTypeDef,
    ListDirectoryBucketsOutputTypeDef,
    ListDirectoryBucketsRequestTypeDef,
    ListMultipartUploadsOutputTypeDef,
    ListMultipartUploadsRequestTypeDef,
    ListObjectVersionsOutputTypeDef,
    ListObjectVersionsRequestTypeDef,
    ListObjectsOutputTypeDef,
    ListObjectsRequestTypeDef,
    ListObjectsV2OutputTypeDef,
    ListObjectsV2RequestTypeDef,
    ListPartsOutputTypeDef,
    ListPartsRequestTypeDef,
    NotificationConfigurationDeprecatedTypeDef,
    NotificationConfigurationTypeDef,
    PutBucketAbacRequestTypeDef,
    PutBucketAccelerateConfigurationRequestTypeDef,
    PutBucketAclRequestTypeDef,
    PutBucketAnalyticsConfigurationRequestTypeDef,
    PutBucketCorsRequestTypeDef,
    PutBucketEncryptionRequestTypeDef,
    PutBucketIntelligentTieringConfigurationRequestTypeDef,
    PutBucketInventoryConfigurationRequestTypeDef,
    PutBucketLifecycleConfigurationOutputTypeDef,
    PutBucketLifecycleConfigurationRequestTypeDef,
    PutBucketLifecycleRequestTypeDef,
    PutBucketLoggingRequestTypeDef,
    PutBucketMetricsConfigurationRequestTypeDef,
    PutBucketNotificationConfigurationRequestTypeDef,
    PutBucketNotificationRequestTypeDef,
    PutBucketOwnershipControlsRequestTypeDef,
    PutBucketPolicyRequestTypeDef,
    PutBucketReplicationRequestTypeDef,
    PutBucketRequestPaymentRequestTypeDef,
    PutBucketTaggingRequestTypeDef,
    PutBucketVersioningRequestTypeDef,
    PutBucketWebsiteRequestTypeDef,
    PutObjectAclOutputTypeDef,
    PutObjectAclRequestTypeDef,
    PutObjectLegalHoldOutputTypeDef,
    PutObjectLegalHoldRequestTypeDef,
    PutObjectLockConfigurationOutputTypeDef,
    PutObjectLockConfigurationRequestTypeDef,
    PutObjectOutputTypeDef,
    PutObjectRequestTypeDef,
    PutObjectRetentionOutputTypeDef,
    PutObjectRetentionRequestTypeDef,
    PutObjectTaggingOutputTypeDef,
    PutObjectTaggingRequestTypeDef,
    PutPublicAccessBlockRequestTypeDef,
    RenameObjectRequestTypeDef,
    RestoreObjectOutputTypeDef,
    RestoreObjectRequestTypeDef,
    SelectObjectContentOutputTypeDef,
    SelectObjectContentRequestTypeDef,
    UpdateBucketMetadataInventoryTableConfigurationRequestTypeDef,
    UpdateBucketMetadataJournalTableConfigurationRequestTypeDef,
    UpdateObjectEncryptionRequestTypeDef,
    UpdateObjectEncryptionResponseTypeDef,
    UploadPartCopyOutputTypeDef,
    UploadPartCopyRequestTypeDef,
    UploadPartOutputTypeDef,
    UploadPartRequestTypeDef,
    WriteGetObjectResponseRequestTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class S3Client(TypedClientBase):
    _service_name = ServiceName.S3


    def abort_multipart_upload(
        self, request: AbortMultipartUploadRequestTypeDef,
    ) -> AbortMultipartUploadOutputTypeDef:
        return self._call(
            "abort_multipart_upload",
            request,
            AbortMultipartUploadOutputTypeDef,
        )


    def complete_multipart_upload(
        self, request: CompleteMultipartUploadRequestTypeDef,
    ) -> CompleteMultipartUploadOutputTypeDef:
        return self._call(
            "complete_multipart_upload",
            request,
            CompleteMultipartUploadOutputTypeDef,
        )


    def copy_object(
        self, request: CopyObjectRequestTypeDef,
    ) -> CopyObjectOutputTypeDef:
        return self._call(
            "copy_object",
            request,
            CopyObjectOutputTypeDef,
        )


    def create_bucket(
        self, request: CreateBucketRequestTypeDef,
    ) -> CreateBucketOutputTypeDef:
        return self._call(
            "create_bucket",
            request,
            CreateBucketOutputTypeDef,
        )


    def create_bucket_metadata_configuration(
        self, request: CreateBucketMetadataConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "create_bucket_metadata_configuration",
            request,
            None,
        )


    def create_bucket_metadata_table_configuration(
        self, request: CreateBucketMetadataTableConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "create_bucket_metadata_table_configuration",
            request,
            None,
        )


    def create_multipart_upload(
        self, request: CreateMultipartUploadRequestTypeDef,
    ) -> CreateMultipartUploadOutputTypeDef:
        return self._call(
            "create_multipart_upload",
            request,
            CreateMultipartUploadOutputTypeDef,
        )


    def create_session(
        self, request: CreateSessionRequestTypeDef,
    ) -> CreateSessionOutputTypeDef:
        return self._call(
            "create_session",
            request,
            CreateSessionOutputTypeDef,
        )


    def delete_bucket(
        self, request: DeleteBucketRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket",
            request,
            None,
        )


    def delete_bucket_analytics_configuration(
        self, request: DeleteBucketAnalyticsConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_analytics_configuration",
            request,
            None,
        )


    def delete_bucket_cors(
        self, request: DeleteBucketCorsRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_cors",
            request,
            None,
        )


    def delete_bucket_encryption(
        self, request: DeleteBucketEncryptionRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_encryption",
            request,
            None,
        )


    def delete_bucket_intelligent_tiering_configuration(
        self, request: DeleteBucketIntelligentTieringConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_intelligent_tiering_configuration",
            request,
            None,
        )


    def delete_bucket_inventory_configuration(
        self, request: DeleteBucketInventoryConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_inventory_configuration",
            request,
            None,
        )


    def delete_bucket_lifecycle(
        self, request: DeleteBucketLifecycleRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_lifecycle",
            request,
            None,
        )


    def delete_bucket_metadata_configuration(
        self, request: DeleteBucketMetadataConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_metadata_configuration",
            request,
            None,
        )


    def delete_bucket_metadata_table_configuration(
        self, request: DeleteBucketMetadataTableConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_metadata_table_configuration",
            request,
            None,
        )


    def delete_bucket_metrics_configuration(
        self, request: DeleteBucketMetricsConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_metrics_configuration",
            request,
            None,
        )


    def delete_bucket_ownership_controls(
        self, request: DeleteBucketOwnershipControlsRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_ownership_controls",
            request,
            None,
        )


    def delete_bucket_policy(
        self, request: DeleteBucketPolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_policy",
            request,
            None,
        )


    def delete_bucket_replication(
        self, request: DeleteBucketReplicationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_replication",
            request,
            None,
        )


    def delete_bucket_tagging(
        self, request: DeleteBucketTaggingRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_tagging",
            request,
            None,
        )


    def delete_bucket_website(
        self, request: DeleteBucketWebsiteRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_bucket_website",
            request,
            None,
        )


    def delete_object(
        self, request: DeleteObjectRequestTypeDef,
    ) -> DeleteObjectOutputTypeDef:
        return self._call(
            "delete_object",
            request,
            DeleteObjectOutputTypeDef,
        )


    def delete_object_tagging(
        self, request: DeleteObjectTaggingRequestTypeDef,
    ) -> DeleteObjectTaggingOutputTypeDef:
        return self._call(
            "delete_object_tagging",
            request,
            DeleteObjectTaggingOutputTypeDef,
        )


    def delete_objects(
        self, request: DeleteObjectsRequestTypeDef,
    ) -> DeleteObjectsOutputTypeDef:
        return self._call(
            "delete_objects",
            request,
            DeleteObjectsOutputTypeDef,
        )


    def delete_public_access_block(
        self, request: DeletePublicAccessBlockRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_public_access_block",
            request,
            None,
        )


    def get_bucket_abac(
        self, request: GetBucketAbacRequestTypeDef,
    ) -> GetBucketAbacOutputTypeDef:
        return self._call(
            "get_bucket_abac",
            request,
            GetBucketAbacOutputTypeDef,
        )


    def get_bucket_accelerate_configuration(
        self, request: GetBucketAccelerateConfigurationRequestTypeDef,
    ) -> GetBucketAccelerateConfigurationOutputTypeDef:
        return self._call(
            "get_bucket_accelerate_configuration",
            request,
            GetBucketAccelerateConfigurationOutputTypeDef,
        )


    def get_bucket_acl(
        self, request: GetBucketAclRequestTypeDef,
    ) -> GetBucketAclOutputTypeDef:
        return self._call(
            "get_bucket_acl",
            request,
            GetBucketAclOutputTypeDef,
        )


    def get_bucket_analytics_configuration(
        self, request: GetBucketAnalyticsConfigurationRequestTypeDef,
    ) -> GetBucketAnalyticsConfigurationOutputTypeDef:
        return self._call(
            "get_bucket_analytics_configuration",
            request,
            GetBucketAnalyticsConfigurationOutputTypeDef,
        )


    def get_bucket_cors(
        self, request: GetBucketCorsRequestTypeDef,
    ) -> GetBucketCorsOutputTypeDef:
        return self._call(
            "get_bucket_cors",
            request,
            GetBucketCorsOutputTypeDef,
        )


    def get_bucket_encryption(
        self, request: GetBucketEncryptionRequestTypeDef,
    ) -> GetBucketEncryptionOutputTypeDef:
        return self._call(
            "get_bucket_encryption",
            request,
            GetBucketEncryptionOutputTypeDef,
        )


    def get_bucket_intelligent_tiering_configuration(
        self, request: GetBucketIntelligentTieringConfigurationRequestTypeDef,
    ) -> GetBucketIntelligentTieringConfigurationOutputTypeDef:
        return self._call(
            "get_bucket_intelligent_tiering_configuration",
            request,
            GetBucketIntelligentTieringConfigurationOutputTypeDef,
        )


    def get_bucket_inventory_configuration(
        self, request: GetBucketInventoryConfigurationRequestTypeDef,
    ) -> GetBucketInventoryConfigurationOutputTypeDef:
        return self._call(
            "get_bucket_inventory_configuration",
            request,
            GetBucketInventoryConfigurationOutputTypeDef,
        )


    def get_bucket_lifecycle(
        self, request: GetBucketLifecycleRequestTypeDef,
    ) -> GetBucketLifecycleOutputTypeDef:
        return self._call(
            "get_bucket_lifecycle",
            request,
            GetBucketLifecycleOutputTypeDef,
        )


    def get_bucket_lifecycle_configuration(
        self, request: GetBucketLifecycleConfigurationRequestTypeDef,
    ) -> GetBucketLifecycleConfigurationOutputTypeDef:
        return self._call(
            "get_bucket_lifecycle_configuration",
            request,
            GetBucketLifecycleConfigurationOutputTypeDef,
        )


    def get_bucket_location(
        self, request: GetBucketLocationRequestTypeDef,
    ) -> GetBucketLocationOutputTypeDef:
        return self._call(
            "get_bucket_location",
            request,
            GetBucketLocationOutputTypeDef,
        )


    def get_bucket_logging(
        self, request: GetBucketLoggingRequestTypeDef,
    ) -> GetBucketLoggingOutputTypeDef:
        return self._call(
            "get_bucket_logging",
            request,
            GetBucketLoggingOutputTypeDef,
        )


    def get_bucket_metadata_configuration(
        self, request: GetBucketMetadataConfigurationRequestTypeDef,
    ) -> GetBucketMetadataConfigurationOutputTypeDef:
        return self._call(
            "get_bucket_metadata_configuration",
            request,
            GetBucketMetadataConfigurationOutputTypeDef,
        )


    def get_bucket_metadata_table_configuration(
        self, request: GetBucketMetadataTableConfigurationRequestTypeDef,
    ) -> GetBucketMetadataTableConfigurationOutputTypeDef:
        return self._call(
            "get_bucket_metadata_table_configuration",
            request,
            GetBucketMetadataTableConfigurationOutputTypeDef,
        )


    def get_bucket_metrics_configuration(
        self, request: GetBucketMetricsConfigurationRequestTypeDef,
    ) -> GetBucketMetricsConfigurationOutputTypeDef:
        return self._call(
            "get_bucket_metrics_configuration",
            request,
            GetBucketMetricsConfigurationOutputTypeDef,
        )


    def get_bucket_notification(
        self, request: GetBucketNotificationConfigurationRequestTypeDef,
    ) -> NotificationConfigurationDeprecatedTypeDef:
        return self._call(
            "get_bucket_notification",
            request,
            NotificationConfigurationDeprecatedTypeDef,
        )


    def get_bucket_notification_configuration(
        self, request: GetBucketNotificationConfigurationRequestTypeDef,
    ) -> NotificationConfigurationTypeDef:
        return self._call(
            "get_bucket_notification_configuration",
            request,
            NotificationConfigurationTypeDef,
        )


    def get_bucket_ownership_controls(
        self, request: GetBucketOwnershipControlsRequestTypeDef,
    ) -> GetBucketOwnershipControlsOutputTypeDef:
        return self._call(
            "get_bucket_ownership_controls",
            request,
            GetBucketOwnershipControlsOutputTypeDef,
        )


    def get_bucket_policy(
        self, request: GetBucketPolicyRequestTypeDef,
    ) -> GetBucketPolicyOutputTypeDef:
        return self._call(
            "get_bucket_policy",
            request,
            GetBucketPolicyOutputTypeDef,
        )


    def get_bucket_policy_status(
        self, request: GetBucketPolicyStatusRequestTypeDef,
    ) -> GetBucketPolicyStatusOutputTypeDef:
        return self._call(
            "get_bucket_policy_status",
            request,
            GetBucketPolicyStatusOutputTypeDef,
        )


    def get_bucket_replication(
        self, request: GetBucketReplicationRequestTypeDef,
    ) -> GetBucketReplicationOutputTypeDef:
        return self._call(
            "get_bucket_replication",
            request,
            GetBucketReplicationOutputTypeDef,
        )


    def get_bucket_request_payment(
        self, request: GetBucketRequestPaymentRequestTypeDef,
    ) -> GetBucketRequestPaymentOutputTypeDef:
        return self._call(
            "get_bucket_request_payment",
            request,
            GetBucketRequestPaymentOutputTypeDef,
        )


    def get_bucket_tagging(
        self, request: GetBucketTaggingRequestTypeDef,
    ) -> GetBucketTaggingOutputTypeDef:
        return self._call(
            "get_bucket_tagging",
            request,
            GetBucketTaggingOutputTypeDef,
        )


    def get_bucket_versioning(
        self, request: GetBucketVersioningRequestTypeDef,
    ) -> GetBucketVersioningOutputTypeDef:
        return self._call(
            "get_bucket_versioning",
            request,
            GetBucketVersioningOutputTypeDef,
        )


    def get_bucket_website(
        self, request: GetBucketWebsiteRequestTypeDef,
    ) -> GetBucketWebsiteOutputTypeDef:
        return self._call(
            "get_bucket_website",
            request,
            GetBucketWebsiteOutputTypeDef,
        )


    def get_object(
        self, request: GetObjectRequestTypeDef,
    ) -> GetObjectOutputTypeDef:
        return self._call(
            "get_object",
            request,
            GetObjectOutputTypeDef,
        )


    def get_object_acl(
        self, request: GetObjectAclRequestTypeDef,
    ) -> GetObjectAclOutputTypeDef:
        return self._call(
            "get_object_acl",
            request,
            GetObjectAclOutputTypeDef,
        )


    def get_object_attributes(
        self, request: GetObjectAttributesRequestTypeDef,
    ) -> GetObjectAttributesOutputTypeDef:
        return self._call(
            "get_object_attributes",
            request,
            GetObjectAttributesOutputTypeDef,
        )


    def get_object_legal_hold(
        self, request: GetObjectLegalHoldRequestTypeDef,
    ) -> GetObjectLegalHoldOutputTypeDef:
        return self._call(
            "get_object_legal_hold",
            request,
            GetObjectLegalHoldOutputTypeDef,
        )


    def get_object_lock_configuration(
        self, request: GetObjectLockConfigurationRequestTypeDef,
    ) -> GetObjectLockConfigurationOutputTypeDef:
        return self._call(
            "get_object_lock_configuration",
            request,
            GetObjectLockConfigurationOutputTypeDef,
        )


    def get_object_retention(
        self, request: GetObjectRetentionRequestTypeDef,
    ) -> GetObjectRetentionOutputTypeDef:
        return self._call(
            "get_object_retention",
            request,
            GetObjectRetentionOutputTypeDef,
        )


    def get_object_tagging(
        self, request: GetObjectTaggingRequestTypeDef,
    ) -> GetObjectTaggingOutputTypeDef:
        return self._call(
            "get_object_tagging",
            request,
            GetObjectTaggingOutputTypeDef,
        )


    def get_object_torrent(
        self, request: GetObjectTorrentRequestTypeDef,
    ) -> GetObjectTorrentOutputTypeDef:
        return self._call(
            "get_object_torrent",
            request,
            GetObjectTorrentOutputTypeDef,
        )


    def get_public_access_block(
        self, request: GetPublicAccessBlockRequestTypeDef,
    ) -> GetPublicAccessBlockOutputTypeDef:
        return self._call(
            "get_public_access_block",
            request,
            GetPublicAccessBlockOutputTypeDef,
        )


    def head_bucket(
        self, request: HeadBucketRequestTypeDef,
    ) -> HeadBucketOutputTypeDef:
        return self._call(
            "head_bucket",
            request,
            HeadBucketOutputTypeDef,
        )


    def head_object(
        self, request: HeadObjectRequestTypeDef,
    ) -> HeadObjectOutputTypeDef:
        return self._call(
            "head_object",
            request,
            HeadObjectOutputTypeDef,
        )


    def list_bucket_analytics_configurations(
        self, request: ListBucketAnalyticsConfigurationsRequestTypeDef,
    ) -> ListBucketAnalyticsConfigurationsOutputTypeDef:
        return self._call(
            "list_bucket_analytics_configurations",
            request,
            ListBucketAnalyticsConfigurationsOutputTypeDef,
        )


    def list_bucket_intelligent_tiering_configurations(
        self, request: ListBucketIntelligentTieringConfigurationsRequestTypeDef,
    ) -> ListBucketIntelligentTieringConfigurationsOutputTypeDef:
        return self._call(
            "list_bucket_intelligent_tiering_configurations",
            request,
            ListBucketIntelligentTieringConfigurationsOutputTypeDef,
        )


    def list_bucket_inventory_configurations(
        self, request: ListBucketInventoryConfigurationsRequestTypeDef,
    ) -> ListBucketInventoryConfigurationsOutputTypeDef:
        return self._call(
            "list_bucket_inventory_configurations",
            request,
            ListBucketInventoryConfigurationsOutputTypeDef,
        )


    def list_bucket_metrics_configurations(
        self, request: ListBucketMetricsConfigurationsRequestTypeDef,
    ) -> ListBucketMetricsConfigurationsOutputTypeDef:
        return self._call(
            "list_bucket_metrics_configurations",
            request,
            ListBucketMetricsConfigurationsOutputTypeDef,
        )


    def list_buckets(
        self, request: ListBucketsRequestTypeDef,
    ) -> ListBucketsOutputTypeDef:
        return self._call(
            "list_buckets",
            request,
            ListBucketsOutputTypeDef,
        )


    def list_directory_buckets(
        self, request: ListDirectoryBucketsRequestTypeDef,
    ) -> ListDirectoryBucketsOutputTypeDef:
        return self._call(
            "list_directory_buckets",
            request,
            ListDirectoryBucketsOutputTypeDef,
        )


    def list_multipart_uploads(
        self, request: ListMultipartUploadsRequestTypeDef,
    ) -> ListMultipartUploadsOutputTypeDef:
        return self._call(
            "list_multipart_uploads",
            request,
            ListMultipartUploadsOutputTypeDef,
        )


    def list_object_versions(
        self, request: ListObjectVersionsRequestTypeDef,
    ) -> ListObjectVersionsOutputTypeDef:
        return self._call(
            "list_object_versions",
            request,
            ListObjectVersionsOutputTypeDef,
        )


    def list_objects(
        self, request: ListObjectsRequestTypeDef,
    ) -> ListObjectsOutputTypeDef:
        return self._call(
            "list_objects",
            request,
            ListObjectsOutputTypeDef,
        )


    def list_objects_v2(
        self, request: ListObjectsV2RequestTypeDef,
    ) -> ListObjectsV2OutputTypeDef:
        return self._call(
            "list_objects_v2",
            request,
            ListObjectsV2OutputTypeDef,
        )


    def list_parts(
        self, request: ListPartsRequestTypeDef,
    ) -> ListPartsOutputTypeDef:
        return self._call(
            "list_parts",
            request,
            ListPartsOutputTypeDef,
        )


    def put_bucket_abac(
        self, request: PutBucketAbacRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_abac",
            request,
            None,
        )


    def put_bucket_accelerate_configuration(
        self, request: PutBucketAccelerateConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_accelerate_configuration",
            request,
            None,
        )


    def put_bucket_acl(
        self, request: PutBucketAclRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_acl",
            request,
            None,
        )


    def put_bucket_analytics_configuration(
        self, request: PutBucketAnalyticsConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_analytics_configuration",
            request,
            None,
        )


    def put_bucket_cors(
        self, request: PutBucketCorsRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_cors",
            request,
            None,
        )


    def put_bucket_encryption(
        self, request: PutBucketEncryptionRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_encryption",
            request,
            None,
        )


    def put_bucket_intelligent_tiering_configuration(
        self, request: PutBucketIntelligentTieringConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_intelligent_tiering_configuration",
            request,
            None,
        )


    def put_bucket_inventory_configuration(
        self, request: PutBucketInventoryConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_inventory_configuration",
            request,
            None,
        )


    def put_bucket_lifecycle(
        self, request: PutBucketLifecycleRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_lifecycle",
            request,
            None,
        )


    def put_bucket_lifecycle_configuration(
        self, request: PutBucketLifecycleConfigurationRequestTypeDef,
    ) -> PutBucketLifecycleConfigurationOutputTypeDef:
        return self._call(
            "put_bucket_lifecycle_configuration",
            request,
            PutBucketLifecycleConfigurationOutputTypeDef,
        )


    def put_bucket_logging(
        self, request: PutBucketLoggingRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_logging",
            request,
            None,
        )


    def put_bucket_metrics_configuration(
        self, request: PutBucketMetricsConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_metrics_configuration",
            request,
            None,
        )


    def put_bucket_notification(
        self, request: PutBucketNotificationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_notification",
            request,
            None,
        )


    def put_bucket_notification_configuration(
        self, request: PutBucketNotificationConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_notification_configuration",
            request,
            None,
        )


    def put_bucket_ownership_controls(
        self, request: PutBucketOwnershipControlsRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_ownership_controls",
            request,
            None,
        )


    def put_bucket_policy(
        self, request: PutBucketPolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_policy",
            request,
            None,
        )


    def put_bucket_replication(
        self, request: PutBucketReplicationRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_replication",
            request,
            None,
        )


    def put_bucket_request_payment(
        self, request: PutBucketRequestPaymentRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_request_payment",
            request,
            None,
        )


    def put_bucket_tagging(
        self, request: PutBucketTaggingRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_tagging",
            request,
            None,
        )


    def put_bucket_versioning(
        self, request: PutBucketVersioningRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_versioning",
            request,
            None,
        )


    def put_bucket_website(
        self, request: PutBucketWebsiteRequestTypeDef,
    ) -> None:
        return self._call(
            "put_bucket_website",
            request,
            None,
        )


    def put_object(
        self, request: PutObjectRequestTypeDef,
    ) -> PutObjectOutputTypeDef:
        return self._call(
            "put_object",
            request,
            PutObjectOutputTypeDef,
        )


    def put_object_acl(
        self, request: PutObjectAclRequestTypeDef,
    ) -> PutObjectAclOutputTypeDef:
        return self._call(
            "put_object_acl",
            request,
            PutObjectAclOutputTypeDef,
        )


    def put_object_legal_hold(
        self, request: PutObjectLegalHoldRequestTypeDef,
    ) -> PutObjectLegalHoldOutputTypeDef:
        return self._call(
            "put_object_legal_hold",
            request,
            PutObjectLegalHoldOutputTypeDef,
        )


    def put_object_lock_configuration(
        self, request: PutObjectLockConfigurationRequestTypeDef,
    ) -> PutObjectLockConfigurationOutputTypeDef:
        return self._call(
            "put_object_lock_configuration",
            request,
            PutObjectLockConfigurationOutputTypeDef,
        )


    def put_object_retention(
        self, request: PutObjectRetentionRequestTypeDef,
    ) -> PutObjectRetentionOutputTypeDef:
        return self._call(
            "put_object_retention",
            request,
            PutObjectRetentionOutputTypeDef,
        )


    def put_object_tagging(
        self, request: PutObjectTaggingRequestTypeDef,
    ) -> PutObjectTaggingOutputTypeDef:
        return self._call(
            "put_object_tagging",
            request,
            PutObjectTaggingOutputTypeDef,
        )


    def put_public_access_block(
        self, request: PutPublicAccessBlockRequestTypeDef,
    ) -> None:
        return self._call(
            "put_public_access_block",
            request,
            None,
        )


    def rename_object(
        self, request: RenameObjectRequestTypeDef,
    ) -> None:
        return self._call(
            "rename_object",
            request,
            None,
        )


    def restore_object(
        self, request: RestoreObjectRequestTypeDef,
    ) -> RestoreObjectOutputTypeDef:
        return self._call(
            "restore_object",
            request,
            RestoreObjectOutputTypeDef,
        )


    def select_object_content(
        self, request: SelectObjectContentRequestTypeDef,
    ) -> SelectObjectContentOutputTypeDef:
        return self._call(
            "select_object_content",
            request,
            SelectObjectContentOutputTypeDef,
        )


    def update_bucket_metadata_inventory_table_configuration(
        self, request: UpdateBucketMetadataInventoryTableConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "update_bucket_metadata_inventory_table_configuration",
            request,
            None,
        )


    def update_bucket_metadata_journal_table_configuration(
        self, request: UpdateBucketMetadataJournalTableConfigurationRequestTypeDef,
    ) -> None:
        return self._call(
            "update_bucket_metadata_journal_table_configuration",
            request,
            None,
        )


    def update_object_encryption(
        self, request: UpdateObjectEncryptionRequestTypeDef,
    ) -> UpdateObjectEncryptionResponseTypeDef:
        return self._call(
            "update_object_encryption",
            request,
            UpdateObjectEncryptionResponseTypeDef,
        )


    def upload_part(
        self, request: UploadPartRequestTypeDef,
    ) -> UploadPartOutputTypeDef:
        return self._call(
            "upload_part",
            request,
            UploadPartOutputTypeDef,
        )


    def upload_part_copy(
        self, request: UploadPartCopyRequestTypeDef,
    ) -> UploadPartCopyOutputTypeDef:
        return self._call(
            "upload_part_copy",
            request,
            UploadPartCopyOutputTypeDef,
        )


    def write_get_object_response(
        self, request: WriteGetObjectResponseRequestTypeDef,
    ) -> None:
        return self._call(
            "write_get_object_response",
            request,
            None,
        )

