# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.sqs.sqs_classes import (
    AddPermissionRequestTypeDef,
    CancelMessageMoveTaskRequestTypeDef,
    CancelMessageMoveTaskResultTypeDef,
    ChangeMessageVisibilityBatchRequestTypeDef,
    ChangeMessageVisibilityBatchResultTypeDef,
    ChangeMessageVisibilityRequestTypeDef,
    CreateQueueRequestTypeDef,
    CreateQueueResultTypeDef,
    DeleteMessageBatchRequestTypeDef,
    DeleteMessageBatchResultTypeDef,
    DeleteMessageRequestTypeDef,
    DeleteQueueRequestTypeDef,
    GetQueueAttributesRequestTypeDef,
    GetQueueAttributesResultTypeDef,
    GetQueueUrlRequestTypeDef,
    GetQueueUrlResultTypeDef,
    ListDeadLetterSourceQueuesRequestTypeDef,
    ListDeadLetterSourceQueuesResultTypeDef,
    ListMessageMoveTasksRequestTypeDef,
    ListMessageMoveTasksResultTypeDef,
    ListQueueTagsRequestTypeDef,
    ListQueueTagsResultTypeDef,
    ListQueuesRequestTypeDef,
    ListQueuesResultTypeDef,
    PurgeQueueRequestTypeDef,
    ReceiveMessageRequestTypeDef,
    ReceiveMessageResultTypeDef,
    RemovePermissionRequestTypeDef,
    SendMessageBatchRequestTypeDef,
    SendMessageBatchResultTypeDef,
    SendMessageRequestTypeDef,
    SendMessageResultTypeDef,
    SetQueueAttributesRequestTypeDef,
    StartMessageMoveTaskRequestTypeDef,
    StartMessageMoveTaskResultTypeDef,
    TagQueueRequestTypeDef,
    UntagQueueRequestTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class SqsClient(TypedClientBase):
    _service_name = ServiceName.SQS


    def add_permission(
        self, request: AddPermissionRequestTypeDef,
    ) -> None:
        return self._call(
            "add_permission",
            request,
            None,
        )


    def cancel_message_move_task(
        self, request: CancelMessageMoveTaskRequestTypeDef,
    ) -> CancelMessageMoveTaskResultTypeDef:
        return self._call(
            "cancel_message_move_task",
            request,
            CancelMessageMoveTaskResultTypeDef,
        )


    def change_message_visibility(
        self, request: ChangeMessageVisibilityRequestTypeDef,
    ) -> None:
        return self._call(
            "change_message_visibility",
            request,
            None,
        )


    def change_message_visibility_batch(
        self, request: ChangeMessageVisibilityBatchRequestTypeDef,
    ) -> ChangeMessageVisibilityBatchResultTypeDef:
        return self._call(
            "change_message_visibility_batch",
            request,
            ChangeMessageVisibilityBatchResultTypeDef,
        )


    def create_queue(
        self, request: CreateQueueRequestTypeDef,
    ) -> CreateQueueResultTypeDef:
        return self._call(
            "create_queue",
            request,
            CreateQueueResultTypeDef,
        )


    def delete_message(
        self, request: DeleteMessageRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_message",
            request,
            None,
        )


    def delete_message_batch(
        self, request: DeleteMessageBatchRequestTypeDef,
    ) -> DeleteMessageBatchResultTypeDef:
        return self._call(
            "delete_message_batch",
            request,
            DeleteMessageBatchResultTypeDef,
        )


    def delete_queue(
        self, request: DeleteQueueRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_queue",
            request,
            None,
        )


    def get_queue_attributes(
        self, request: GetQueueAttributesRequestTypeDef,
    ) -> GetQueueAttributesResultTypeDef:
        return self._call(
            "get_queue_attributes",
            request,
            GetQueueAttributesResultTypeDef,
        )


    def get_queue_url(
        self, request: GetQueueUrlRequestTypeDef,
    ) -> GetQueueUrlResultTypeDef:
        return self._call(
            "get_queue_url",
            request,
            GetQueueUrlResultTypeDef,
        )


    def list_dead_letter_source_queues(
        self, request: ListDeadLetterSourceQueuesRequestTypeDef,
    ) -> ListDeadLetterSourceQueuesResultTypeDef:
        return self._call(
            "list_dead_letter_source_queues",
            request,
            ListDeadLetterSourceQueuesResultTypeDef,
        )


    def list_message_move_tasks(
        self, request: ListMessageMoveTasksRequestTypeDef,
    ) -> ListMessageMoveTasksResultTypeDef:
        return self._call(
            "list_message_move_tasks",
            request,
            ListMessageMoveTasksResultTypeDef,
        )


    def list_queue_tags(
        self, request: ListQueueTagsRequestTypeDef,
    ) -> ListQueueTagsResultTypeDef:
        return self._call(
            "list_queue_tags",
            request,
            ListQueueTagsResultTypeDef,
        )


    def list_queues(
        self, request: ListQueuesRequestTypeDef,
    ) -> ListQueuesResultTypeDef:
        return self._call(
            "list_queues",
            request,
            ListQueuesResultTypeDef,
        )


    def purge_queue(
        self, request: PurgeQueueRequestTypeDef,
    ) -> None:
        return self._call(
            "purge_queue",
            request,
            None,
        )


    def receive_message(
        self, request: ReceiveMessageRequestTypeDef,
    ) -> ReceiveMessageResultTypeDef:
        return self._call(
            "receive_message",
            request,
            ReceiveMessageResultTypeDef,
        )


    def remove_permission(
        self, request: RemovePermissionRequestTypeDef,
    ) -> None:
        return self._call(
            "remove_permission",
            request,
            None,
        )


    def send_message(
        self, request: SendMessageRequestTypeDef,
    ) -> SendMessageResultTypeDef:
        return self._call(
            "send_message",
            request,
            SendMessageResultTypeDef,
        )


    def send_message_batch(
        self, request: SendMessageBatchRequestTypeDef,
    ) -> SendMessageBatchResultTypeDef:
        return self._call(
            "send_message_batch",
            request,
            SendMessageBatchResultTypeDef,
        )


    def set_queue_attributes(
        self, request: SetQueueAttributesRequestTypeDef,
    ) -> None:
        return self._call(
            "set_queue_attributes",
            request,
            None,
        )


    def start_message_move_task(
        self, request: StartMessageMoveTaskRequestTypeDef,
    ) -> StartMessageMoveTaskResultTypeDef:
        return self._call(
            "start_message_move_task",
            request,
            StartMessageMoveTaskResultTypeDef,
        )


    def tag_queue(
        self, request: TagQueueRequestTypeDef,
    ) -> None:
        return self._call(
            "tag_queue",
            request,
            None,
        )


    def untag_queue(
        self, request: UntagQueueRequestTypeDef,
    ) -> None:
        return self._call(
            "untag_queue",
            request,
            None,
        )

