# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.ssm.ssm_classes import (
    AddTagsToResourceRequestTypeDef,
    AssociateOpsItemRelatedItemRequestTypeDef,
    AssociateOpsItemRelatedItemResponseTypeDef,
    CancelCommandRequestTypeDef,
    CancelMaintenanceWindowExecutionRequestTypeDef,
    CancelMaintenanceWindowExecutionResultTypeDef,
    CreateActivationRequestTypeDef,
    CreateActivationResultTypeDef,
    CreateAssociationBatchRequestTypeDef,
    CreateAssociationBatchResultTypeDef,
    CreateAssociationRequestTypeDef,
    CreateAssociationResultTypeDef,
    CreateDocumentRequestTypeDef,
    CreateDocumentResultTypeDef,
    CreateMaintenanceWindowRequestTypeDef,
    CreateMaintenanceWindowResultTypeDef,
    CreateOpsItemRequestTypeDef,
    CreateOpsItemResponseTypeDef,
    CreateOpsMetadataRequestTypeDef,
    CreateOpsMetadataResultTypeDef,
    CreatePatchBaselineRequestTypeDef,
    CreatePatchBaselineResultTypeDef,
    CreateResourceDataSyncRequestTypeDef,
    DeleteActivationRequestTypeDef,
    DeleteAssociationRequestTypeDef,
    DeleteDocumentRequestTypeDef,
    DeleteInventoryRequestTypeDef,
    DeleteInventoryResultTypeDef,
    DeleteMaintenanceWindowRequestTypeDef,
    DeleteMaintenanceWindowResultTypeDef,
    DeleteOpsItemRequestTypeDef,
    DeleteOpsMetadataRequestTypeDef,
    DeleteParameterRequestTypeDef,
    DeleteParametersRequestTypeDef,
    DeleteParametersResultTypeDef,
    DeletePatchBaselineRequestTypeDef,
    DeletePatchBaselineResultTypeDef,
    DeleteResourceDataSyncRequestTypeDef,
    DeleteResourcePolicyRequestTypeDef,
    DeregisterManagedInstanceRequestTypeDef,
    DeregisterPatchBaselineForPatchGroupRequestTypeDef,
    DeregisterPatchBaselineForPatchGroupResultTypeDef,
    DeregisterTargetFromMaintenanceWindowRequestTypeDef,
    DeregisterTargetFromMaintenanceWindowResultTypeDef,
    DeregisterTaskFromMaintenanceWindowRequestTypeDef,
    DeregisterTaskFromMaintenanceWindowResultTypeDef,
    DescribeActivationsRequestTypeDef,
    DescribeActivationsResultTypeDef,
    DescribeAssociationExecutionTargetsRequestTypeDef,
    DescribeAssociationExecutionTargetsResultTypeDef,
    DescribeAssociationExecutionsRequestTypeDef,
    DescribeAssociationExecutionsResultTypeDef,
    DescribeAssociationRequestTypeDef,
    DescribeAssociationResultTypeDef,
    DescribeAutomationExecutionsRequestTypeDef,
    DescribeAutomationExecutionsResultTypeDef,
    DescribeAutomationStepExecutionsRequestTypeDef,
    DescribeAutomationStepExecutionsResultTypeDef,
    DescribeAvailablePatchesRequestTypeDef,
    DescribeAvailablePatchesResultTypeDef,
    DescribeDocumentPermissionRequestTypeDef,
    DescribeDocumentPermissionResponseTypeDef,
    DescribeDocumentRequestTypeDef,
    DescribeDocumentResultTypeDef,
    DescribeEffectiveInstanceAssociationsRequestTypeDef,
    DescribeEffectiveInstanceAssociationsResultTypeDef,
    DescribeEffectivePatchesForPatchBaselineRequestTypeDef,
    DescribeEffectivePatchesForPatchBaselineResultTypeDef,
    DescribeInstanceAssociationsStatusRequestTypeDef,
    DescribeInstanceAssociationsStatusResultTypeDef,
    DescribeInstanceInformationRequestTypeDef,
    DescribeInstanceInformationResultTypeDef,
    DescribeInstancePatchStatesForPatchGroupRequestTypeDef,
    DescribeInstancePatchStatesForPatchGroupResultTypeDef,
    DescribeInstancePatchStatesRequestTypeDef,
    DescribeInstancePatchStatesResultTypeDef,
    DescribeInstancePatchesRequestTypeDef,
    DescribeInstancePatchesResultTypeDef,
    DescribeInstancePropertiesRequestTypeDef,
    DescribeInstancePropertiesResultTypeDef,
    DescribeInventoryDeletionsRequestTypeDef,
    DescribeInventoryDeletionsResultTypeDef,
    DescribeMaintenanceWindowExecutionTaskInvocationsRequestTypeDef,
    DescribeMaintenanceWindowExecutionTaskInvocationsResultTypeDef,
    DescribeMaintenanceWindowExecutionTasksRequestTypeDef,
    DescribeMaintenanceWindowExecutionTasksResultTypeDef,
    DescribeMaintenanceWindowExecutionsRequestTypeDef,
    DescribeMaintenanceWindowExecutionsResultTypeDef,
    DescribeMaintenanceWindowScheduleRequestTypeDef,
    DescribeMaintenanceWindowScheduleResultTypeDef,
    DescribeMaintenanceWindowTargetsRequestTypeDef,
    DescribeMaintenanceWindowTargetsResultTypeDef,
    DescribeMaintenanceWindowTasksRequestTypeDef,
    DescribeMaintenanceWindowTasksResultTypeDef,
    DescribeMaintenanceWindowsForTargetRequestTypeDef,
    DescribeMaintenanceWindowsForTargetResultTypeDef,
    DescribeMaintenanceWindowsRequestTypeDef,
    DescribeMaintenanceWindowsResultTypeDef,
    DescribeOpsItemsRequestTypeDef,
    DescribeOpsItemsResponseTypeDef,
    DescribeParametersRequestTypeDef,
    DescribeParametersResultTypeDef,
    DescribePatchBaselinesRequestTypeDef,
    DescribePatchBaselinesResultTypeDef,
    DescribePatchGroupStateRequestTypeDef,
    DescribePatchGroupStateResultTypeDef,
    DescribePatchGroupsRequestTypeDef,
    DescribePatchGroupsResultTypeDef,
    DescribePatchPropertiesRequestTypeDef,
    DescribePatchPropertiesResultTypeDef,
    DescribeSessionsRequestTypeDef,
    DescribeSessionsResponseTypeDef,
    DisassociateOpsItemRelatedItemRequestTypeDef,
    GetAccessTokenRequestTypeDef,
    GetAccessTokenResponseTypeDef,
    GetAutomationExecutionRequestTypeDef,
    GetAutomationExecutionResultTypeDef,
    GetCalendarStateRequestTypeDef,
    GetCalendarStateResponseTypeDef,
    GetCommandInvocationRequestTypeDef,
    GetCommandInvocationResultTypeDef,
    GetConnectionStatusRequestTypeDef,
    GetConnectionStatusResponseTypeDef,
    GetDefaultPatchBaselineRequestTypeDef,
    GetDefaultPatchBaselineResultTypeDef,
    GetDeployablePatchSnapshotForInstanceRequestTypeDef,
    GetDeployablePatchSnapshotForInstanceResultTypeDef,
    GetDocumentRequestTypeDef,
    GetDocumentResultTypeDef,
    GetExecutionPreviewRequestTypeDef,
    GetExecutionPreviewResponseTypeDef,
    GetInventoryRequestTypeDef,
    GetInventoryResultTypeDef,
    GetInventorySchemaRequestTypeDef,
    GetInventorySchemaResultTypeDef,
    GetMaintenanceWindowExecutionRequestTypeDef,
    GetMaintenanceWindowExecutionResultTypeDef,
    GetMaintenanceWindowExecutionTaskInvocationRequestTypeDef,
    GetMaintenanceWindowExecutionTaskInvocationResultTypeDef,
    GetMaintenanceWindowExecutionTaskRequestTypeDef,
    GetMaintenanceWindowExecutionTaskResultTypeDef,
    GetMaintenanceWindowRequestTypeDef,
    GetMaintenanceWindowResultTypeDef,
    GetMaintenanceWindowTaskRequestTypeDef,
    GetMaintenanceWindowTaskResultTypeDef,
    GetOpsItemRequestTypeDef,
    GetOpsItemResponseTypeDef,
    GetOpsMetadataRequestTypeDef,
    GetOpsMetadataResultTypeDef,
    GetOpsSummaryRequestTypeDef,
    GetOpsSummaryResultTypeDef,
    GetParameterHistoryRequestTypeDef,
    GetParameterHistoryResultTypeDef,
    GetParameterRequestTypeDef,
    GetParameterResultTypeDef,
    GetParametersByPathRequestTypeDef,
    GetParametersByPathResultTypeDef,
    GetParametersRequestTypeDef,
    GetParametersResultTypeDef,
    GetPatchBaselineForPatchGroupRequestTypeDef,
    GetPatchBaselineForPatchGroupResultTypeDef,
    GetPatchBaselineRequestTypeDef,
    GetPatchBaselineResultTypeDef,
    GetResourcePoliciesRequestTypeDef,
    GetResourcePoliciesResponseTypeDef,
    GetServiceSettingRequestTypeDef,
    GetServiceSettingResultTypeDef,
    LabelParameterVersionRequestTypeDef,
    LabelParameterVersionResultTypeDef,
    ListAssociationVersionsRequestTypeDef,
    ListAssociationVersionsResultTypeDef,
    ListAssociationsRequestTypeDef,
    ListAssociationsResultTypeDef,
    ListCommandInvocationsRequestTypeDef,
    ListCommandInvocationsResultTypeDef,
    ListCommandsRequestTypeDef,
    ListCommandsResultTypeDef,
    ListComplianceItemsRequestTypeDef,
    ListComplianceItemsResultTypeDef,
    ListComplianceSummariesRequestTypeDef,
    ListComplianceSummariesResultTypeDef,
    ListDocumentMetadataHistoryRequestTypeDef,
    ListDocumentMetadataHistoryResponseTypeDef,
    ListDocumentVersionsRequestTypeDef,
    ListDocumentVersionsResultTypeDef,
    ListDocumentsRequestTypeDef,
    ListDocumentsResultTypeDef,
    ListInventoryEntriesRequestTypeDef,
    ListInventoryEntriesResultTypeDef,
    ListNodesRequestTypeDef,
    ListNodesResultTypeDef,
    ListNodesSummaryRequestTypeDef,
    ListNodesSummaryResultTypeDef,
    ListOpsItemEventsRequestTypeDef,
    ListOpsItemEventsResponseTypeDef,
    ListOpsItemRelatedItemsRequestTypeDef,
    ListOpsItemRelatedItemsResponseTypeDef,
    ListOpsMetadataRequestTypeDef,
    ListOpsMetadataResultTypeDef,
    ListResourceComplianceSummariesRequestTypeDef,
    ListResourceComplianceSummariesResultTypeDef,
    ListResourceDataSyncRequestTypeDef,
    ListResourceDataSyncResultTypeDef,
    ListTagsForResourceRequestTypeDef,
    ListTagsForResourceResultTypeDef,
    ModifyDocumentPermissionRequestTypeDef,
    PutComplianceItemsRequestTypeDef,
    PutInventoryRequestTypeDef,
    PutInventoryResultTypeDef,
    PutParameterRequestTypeDef,
    PutParameterResultTypeDef,
    PutResourcePolicyRequestTypeDef,
    PutResourcePolicyResponseTypeDef,
    RegisterDefaultPatchBaselineRequestTypeDef,
    RegisterDefaultPatchBaselineResultTypeDef,
    RegisterPatchBaselineForPatchGroupRequestTypeDef,
    RegisterPatchBaselineForPatchGroupResultTypeDef,
    RegisterTargetWithMaintenanceWindowRequestTypeDef,
    RegisterTargetWithMaintenanceWindowResultTypeDef,
    RegisterTaskWithMaintenanceWindowRequestTypeDef,
    RegisterTaskWithMaintenanceWindowResultTypeDef,
    RemoveTagsFromResourceRequestTypeDef,
    ResetServiceSettingRequestTypeDef,
    ResetServiceSettingResultTypeDef,
    ResumeSessionRequestTypeDef,
    ResumeSessionResponseTypeDef,
    SendAutomationSignalRequestTypeDef,
    SendCommandRequestTypeDef,
    SendCommandResultTypeDef,
    StartAccessRequestRequestTypeDef,
    StartAccessRequestResponseTypeDef,
    StartAssociationsOnceRequestTypeDef,
    StartAutomationExecutionRequestTypeDef,
    StartAutomationExecutionResultTypeDef,
    StartChangeRequestExecutionRequestTypeDef,
    StartChangeRequestExecutionResultTypeDef,
    StartExecutionPreviewRequestTypeDef,
    StartExecutionPreviewResponseTypeDef,
    StartSessionRequestTypeDef,
    StartSessionResponseTypeDef,
    StopAutomationExecutionRequestTypeDef,
    TerminateSessionRequestTypeDef,
    TerminateSessionResponseTypeDef,
    UnlabelParameterVersionRequestTypeDef,
    UnlabelParameterVersionResultTypeDef,
    UpdateAssociationRequestTypeDef,
    UpdateAssociationResultTypeDef,
    UpdateAssociationStatusRequestTypeDef,
    UpdateAssociationStatusResultTypeDef,
    UpdateDocumentDefaultVersionRequestTypeDef,
    UpdateDocumentDefaultVersionResultTypeDef,
    UpdateDocumentMetadataRequestTypeDef,
    UpdateDocumentRequestTypeDef,
    UpdateDocumentResultTypeDef,
    UpdateMaintenanceWindowRequestTypeDef,
    UpdateMaintenanceWindowResultTypeDef,
    UpdateMaintenanceWindowTargetRequestTypeDef,
    UpdateMaintenanceWindowTargetResultTypeDef,
    UpdateMaintenanceWindowTaskRequestTypeDef,
    UpdateMaintenanceWindowTaskResultTypeDef,
    UpdateManagedInstanceRoleRequestTypeDef,
    UpdateOpsItemRequestTypeDef,
    UpdateOpsMetadataRequestTypeDef,
    UpdateOpsMetadataResultTypeDef,
    UpdatePatchBaselineRequestTypeDef,
    UpdatePatchBaselineResultTypeDef,
    UpdateResourceDataSyncRequestTypeDef,
    UpdateServiceSettingRequestTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class SsmClient(TypedClientBase):
    _service_name = ServiceName.SSM


    def add_tags_to_resource(
        self, request: AddTagsToResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "add_tags_to_resource",
            request,
            None,
        )


    def associate_ops_item_related_item(
        self, request: AssociateOpsItemRelatedItemRequestTypeDef,
    ) -> AssociateOpsItemRelatedItemResponseTypeDef:
        return self._call(
            "associate_ops_item_related_item",
            request,
            AssociateOpsItemRelatedItemResponseTypeDef,
        )


    def cancel_command(
        self, request: CancelCommandRequestTypeDef,
    ) -> None:
        return self._call(
            "cancel_command",
            request,
            None,
        )


    def cancel_maintenance_window_execution(
        self, request: CancelMaintenanceWindowExecutionRequestTypeDef,
    ) -> CancelMaintenanceWindowExecutionResultTypeDef:
        return self._call(
            "cancel_maintenance_window_execution",
            request,
            CancelMaintenanceWindowExecutionResultTypeDef,
        )


    def create_activation(
        self, request: CreateActivationRequestTypeDef,
    ) -> CreateActivationResultTypeDef:
        return self._call(
            "create_activation",
            request,
            CreateActivationResultTypeDef,
        )


    def create_association(
        self, request: CreateAssociationRequestTypeDef,
    ) -> CreateAssociationResultTypeDef:
        return self._call(
            "create_association",
            request,
            CreateAssociationResultTypeDef,
        )


    def create_association_batch(
        self, request: CreateAssociationBatchRequestTypeDef,
    ) -> CreateAssociationBatchResultTypeDef:
        return self._call(
            "create_association_batch",
            request,
            CreateAssociationBatchResultTypeDef,
        )


    def create_document(
        self, request: CreateDocumentRequestTypeDef,
    ) -> CreateDocumentResultTypeDef:
        return self._call(
            "create_document",
            request,
            CreateDocumentResultTypeDef,
        )


    def create_maintenance_window(
        self, request: CreateMaintenanceWindowRequestTypeDef,
    ) -> CreateMaintenanceWindowResultTypeDef:
        return self._call(
            "create_maintenance_window",
            request,
            CreateMaintenanceWindowResultTypeDef,
        )


    def create_ops_item(
        self, request: CreateOpsItemRequestTypeDef,
    ) -> CreateOpsItemResponseTypeDef:
        return self._call(
            "create_ops_item",
            request,
            CreateOpsItemResponseTypeDef,
        )


    def create_ops_metadata(
        self, request: CreateOpsMetadataRequestTypeDef,
    ) -> CreateOpsMetadataResultTypeDef:
        return self._call(
            "create_ops_metadata",
            request,
            CreateOpsMetadataResultTypeDef,
        )


    def create_patch_baseline(
        self, request: CreatePatchBaselineRequestTypeDef,
    ) -> CreatePatchBaselineResultTypeDef:
        return self._call(
            "create_patch_baseline",
            request,
            CreatePatchBaselineResultTypeDef,
        )


    def create_resource_data_sync(
        self, request: CreateResourceDataSyncRequestTypeDef,
    ) -> None:
        return self._call(
            "create_resource_data_sync",
            request,
            None,
        )


    def delete_activation(
        self, request: DeleteActivationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_activation",
            request,
            None,
        )


    def delete_association(
        self, request: DeleteAssociationRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_association",
            request,
            None,
        )


    def delete_document(
        self, request: DeleteDocumentRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_document",
            request,
            None,
        )


    def delete_inventory(
        self, request: DeleteInventoryRequestTypeDef,
    ) -> DeleteInventoryResultTypeDef:
        return self._call(
            "delete_inventory",
            request,
            DeleteInventoryResultTypeDef,
        )


    def delete_maintenance_window(
        self, request: DeleteMaintenanceWindowRequestTypeDef,
    ) -> DeleteMaintenanceWindowResultTypeDef:
        return self._call(
            "delete_maintenance_window",
            request,
            DeleteMaintenanceWindowResultTypeDef,
        )


    def delete_ops_item(
        self, request: DeleteOpsItemRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_ops_item",
            request,
            None,
        )


    def delete_ops_metadata(
        self, request: DeleteOpsMetadataRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_ops_metadata",
            request,
            None,
        )


    def delete_parameter(
        self, request: DeleteParameterRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_parameter",
            request,
            None,
        )


    def delete_parameters(
        self, request: DeleteParametersRequestTypeDef,
    ) -> DeleteParametersResultTypeDef:
        return self._call(
            "delete_parameters",
            request,
            DeleteParametersResultTypeDef,
        )


    def delete_patch_baseline(
        self, request: DeletePatchBaselineRequestTypeDef,
    ) -> DeletePatchBaselineResultTypeDef:
        return self._call(
            "delete_patch_baseline",
            request,
            DeletePatchBaselineResultTypeDef,
        )


    def delete_resource_data_sync(
        self, request: DeleteResourceDataSyncRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_resource_data_sync",
            request,
            None,
        )


    def delete_resource_policy(
        self, request: DeleteResourcePolicyRequestTypeDef,
    ) -> None:
        return self._call(
            "delete_resource_policy",
            request,
            None,
        )


    def deregister_managed_instance(
        self, request: DeregisterManagedInstanceRequestTypeDef,
    ) -> None:
        return self._call(
            "deregister_managed_instance",
            request,
            None,
        )


    def deregister_patch_baseline_for_patch_group(
        self, request: DeregisterPatchBaselineForPatchGroupRequestTypeDef,
    ) -> DeregisterPatchBaselineForPatchGroupResultTypeDef:
        return self._call(
            "deregister_patch_baseline_for_patch_group",
            request,
            DeregisterPatchBaselineForPatchGroupResultTypeDef,
        )


    def deregister_target_from_maintenance_window(
        self, request: DeregisterTargetFromMaintenanceWindowRequestTypeDef,
    ) -> DeregisterTargetFromMaintenanceWindowResultTypeDef:
        return self._call(
            "deregister_target_from_maintenance_window",
            request,
            DeregisterTargetFromMaintenanceWindowResultTypeDef,
        )


    def deregister_task_from_maintenance_window(
        self, request: DeregisterTaskFromMaintenanceWindowRequestTypeDef,
    ) -> DeregisterTaskFromMaintenanceWindowResultTypeDef:
        return self._call(
            "deregister_task_from_maintenance_window",
            request,
            DeregisterTaskFromMaintenanceWindowResultTypeDef,
        )


    def describe_activations(
        self, request: DescribeActivationsRequestTypeDef,
    ) -> DescribeActivationsResultTypeDef:
        return self._call(
            "describe_activations",
            request,
            DescribeActivationsResultTypeDef,
        )


    def describe_association(
        self, request: DescribeAssociationRequestTypeDef,
    ) -> DescribeAssociationResultTypeDef:
        return self._call(
            "describe_association",
            request,
            DescribeAssociationResultTypeDef,
        )


    def describe_association_execution_targets(
        self, request: DescribeAssociationExecutionTargetsRequestTypeDef,
    ) -> DescribeAssociationExecutionTargetsResultTypeDef:
        return self._call(
            "describe_association_execution_targets",
            request,
            DescribeAssociationExecutionTargetsResultTypeDef,
        )


    def describe_association_executions(
        self, request: DescribeAssociationExecutionsRequestTypeDef,
    ) -> DescribeAssociationExecutionsResultTypeDef:
        return self._call(
            "describe_association_executions",
            request,
            DescribeAssociationExecutionsResultTypeDef,
        )


    def describe_automation_executions(
        self, request: DescribeAutomationExecutionsRequestTypeDef,
    ) -> DescribeAutomationExecutionsResultTypeDef:
        return self._call(
            "describe_automation_executions",
            request,
            DescribeAutomationExecutionsResultTypeDef,
        )


    def describe_automation_step_executions(
        self, request: DescribeAutomationStepExecutionsRequestTypeDef,
    ) -> DescribeAutomationStepExecutionsResultTypeDef:
        return self._call(
            "describe_automation_step_executions",
            request,
            DescribeAutomationStepExecutionsResultTypeDef,
        )


    def describe_available_patches(
        self, request: DescribeAvailablePatchesRequestTypeDef,
    ) -> DescribeAvailablePatchesResultTypeDef:
        return self._call(
            "describe_available_patches",
            request,
            DescribeAvailablePatchesResultTypeDef,
        )


    def describe_document(
        self, request: DescribeDocumentRequestTypeDef,
    ) -> DescribeDocumentResultTypeDef:
        return self._call(
            "describe_document",
            request,
            DescribeDocumentResultTypeDef,
        )


    def describe_document_permission(
        self, request: DescribeDocumentPermissionRequestTypeDef,
    ) -> DescribeDocumentPermissionResponseTypeDef:
        return self._call(
            "describe_document_permission",
            request,
            DescribeDocumentPermissionResponseTypeDef,
        )


    def describe_effective_instance_associations(
        self, request: DescribeEffectiveInstanceAssociationsRequestTypeDef,
    ) -> DescribeEffectiveInstanceAssociationsResultTypeDef:
        return self._call(
            "describe_effective_instance_associations",
            request,
            DescribeEffectiveInstanceAssociationsResultTypeDef,
        )


    def describe_effective_patches_for_patch_baseline(
        self, request: DescribeEffectivePatchesForPatchBaselineRequestTypeDef,
    ) -> DescribeEffectivePatchesForPatchBaselineResultTypeDef:
        return self._call(
            "describe_effective_patches_for_patch_baseline",
            request,
            DescribeEffectivePatchesForPatchBaselineResultTypeDef,
        )


    def describe_instance_associations_status(
        self, request: DescribeInstanceAssociationsStatusRequestTypeDef,
    ) -> DescribeInstanceAssociationsStatusResultTypeDef:
        return self._call(
            "describe_instance_associations_status",
            request,
            DescribeInstanceAssociationsStatusResultTypeDef,
        )


    def describe_instance_information(
        self, request: DescribeInstanceInformationRequestTypeDef,
    ) -> DescribeInstanceInformationResultTypeDef:
        return self._call(
            "describe_instance_information",
            request,
            DescribeInstanceInformationResultTypeDef,
        )


    def describe_instance_patch_states(
        self, request: DescribeInstancePatchStatesRequestTypeDef,
    ) -> DescribeInstancePatchStatesResultTypeDef:
        return self._call(
            "describe_instance_patch_states",
            request,
            DescribeInstancePatchStatesResultTypeDef,
        )


    def describe_instance_patch_states_for_patch_group(
        self, request: DescribeInstancePatchStatesForPatchGroupRequestTypeDef,
    ) -> DescribeInstancePatchStatesForPatchGroupResultTypeDef:
        return self._call(
            "describe_instance_patch_states_for_patch_group",
            request,
            DescribeInstancePatchStatesForPatchGroupResultTypeDef,
        )


    def describe_instance_patches(
        self, request: DescribeInstancePatchesRequestTypeDef,
    ) -> DescribeInstancePatchesResultTypeDef:
        return self._call(
            "describe_instance_patches",
            request,
            DescribeInstancePatchesResultTypeDef,
        )


    def describe_instance_properties(
        self, request: DescribeInstancePropertiesRequestTypeDef,
    ) -> DescribeInstancePropertiesResultTypeDef:
        return self._call(
            "describe_instance_properties",
            request,
            DescribeInstancePropertiesResultTypeDef,
        )


    def describe_inventory_deletions(
        self, request: DescribeInventoryDeletionsRequestTypeDef,
    ) -> DescribeInventoryDeletionsResultTypeDef:
        return self._call(
            "describe_inventory_deletions",
            request,
            DescribeInventoryDeletionsResultTypeDef,
        )


    def describe_maintenance_window_execution_task_invocations(
        self, request: DescribeMaintenanceWindowExecutionTaskInvocationsRequestTypeDef,
    ) -> DescribeMaintenanceWindowExecutionTaskInvocationsResultTypeDef:
        return self._call(
            "describe_maintenance_window_execution_task_invocations",
            request,
            DescribeMaintenanceWindowExecutionTaskInvocationsResultTypeDef,
        )


    def describe_maintenance_window_execution_tasks(
        self, request: DescribeMaintenanceWindowExecutionTasksRequestTypeDef,
    ) -> DescribeMaintenanceWindowExecutionTasksResultTypeDef:
        return self._call(
            "describe_maintenance_window_execution_tasks",
            request,
            DescribeMaintenanceWindowExecutionTasksResultTypeDef,
        )


    def describe_maintenance_window_executions(
        self, request: DescribeMaintenanceWindowExecutionsRequestTypeDef,
    ) -> DescribeMaintenanceWindowExecutionsResultTypeDef:
        return self._call(
            "describe_maintenance_window_executions",
            request,
            DescribeMaintenanceWindowExecutionsResultTypeDef,
        )


    def describe_maintenance_window_schedule(
        self, request: DescribeMaintenanceWindowScheduleRequestTypeDef,
    ) -> DescribeMaintenanceWindowScheduleResultTypeDef:
        return self._call(
            "describe_maintenance_window_schedule",
            request,
            DescribeMaintenanceWindowScheduleResultTypeDef,
        )


    def describe_maintenance_window_targets(
        self, request: DescribeMaintenanceWindowTargetsRequestTypeDef,
    ) -> DescribeMaintenanceWindowTargetsResultTypeDef:
        return self._call(
            "describe_maintenance_window_targets",
            request,
            DescribeMaintenanceWindowTargetsResultTypeDef,
        )


    def describe_maintenance_window_tasks(
        self, request: DescribeMaintenanceWindowTasksRequestTypeDef,
    ) -> DescribeMaintenanceWindowTasksResultTypeDef:
        return self._call(
            "describe_maintenance_window_tasks",
            request,
            DescribeMaintenanceWindowTasksResultTypeDef,
        )


    def describe_maintenance_windows(
        self, request: DescribeMaintenanceWindowsRequestTypeDef,
    ) -> DescribeMaintenanceWindowsResultTypeDef:
        return self._call(
            "describe_maintenance_windows",
            request,
            DescribeMaintenanceWindowsResultTypeDef,
        )


    def describe_maintenance_windows_for_target(
        self, request: DescribeMaintenanceWindowsForTargetRequestTypeDef,
    ) -> DescribeMaintenanceWindowsForTargetResultTypeDef:
        return self._call(
            "describe_maintenance_windows_for_target",
            request,
            DescribeMaintenanceWindowsForTargetResultTypeDef,
        )


    def describe_ops_items(
        self, request: DescribeOpsItemsRequestTypeDef,
    ) -> DescribeOpsItemsResponseTypeDef:
        return self._call(
            "describe_ops_items",
            request,
            DescribeOpsItemsResponseTypeDef,
        )


    def describe_parameters(
        self, request: DescribeParametersRequestTypeDef,
    ) -> DescribeParametersResultTypeDef:
        return self._call(
            "describe_parameters",
            request,
            DescribeParametersResultTypeDef,
        )


    def describe_patch_baselines(
        self, request: DescribePatchBaselinesRequestTypeDef,
    ) -> DescribePatchBaselinesResultTypeDef:
        return self._call(
            "describe_patch_baselines",
            request,
            DescribePatchBaselinesResultTypeDef,
        )


    def describe_patch_group_state(
        self, request: DescribePatchGroupStateRequestTypeDef,
    ) -> DescribePatchGroupStateResultTypeDef:
        return self._call(
            "describe_patch_group_state",
            request,
            DescribePatchGroupStateResultTypeDef,
        )


    def describe_patch_groups(
        self, request: DescribePatchGroupsRequestTypeDef,
    ) -> DescribePatchGroupsResultTypeDef:
        return self._call(
            "describe_patch_groups",
            request,
            DescribePatchGroupsResultTypeDef,
        )


    def describe_patch_properties(
        self, request: DescribePatchPropertiesRequestTypeDef,
    ) -> DescribePatchPropertiesResultTypeDef:
        return self._call(
            "describe_patch_properties",
            request,
            DescribePatchPropertiesResultTypeDef,
        )


    def describe_sessions(
        self, request: DescribeSessionsRequestTypeDef,
    ) -> DescribeSessionsResponseTypeDef:
        return self._call(
            "describe_sessions",
            request,
            DescribeSessionsResponseTypeDef,
        )


    def disassociate_ops_item_related_item(
        self, request: DisassociateOpsItemRelatedItemRequestTypeDef,
    ) -> None:
        return self._call(
            "disassociate_ops_item_related_item",
            request,
            None,
        )


    def get_access_token(
        self, request: GetAccessTokenRequestTypeDef,
    ) -> GetAccessTokenResponseTypeDef:
        return self._call(
            "get_access_token",
            request,
            GetAccessTokenResponseTypeDef,
        )


    def get_automation_execution(
        self, request: GetAutomationExecutionRequestTypeDef,
    ) -> GetAutomationExecutionResultTypeDef:
        return self._call(
            "get_automation_execution",
            request,
            GetAutomationExecutionResultTypeDef,
        )


    def get_calendar_state(
        self, request: GetCalendarStateRequestTypeDef,
    ) -> GetCalendarStateResponseTypeDef:
        return self._call(
            "get_calendar_state",
            request,
            GetCalendarStateResponseTypeDef,
        )


    def get_command_invocation(
        self, request: GetCommandInvocationRequestTypeDef,
    ) -> GetCommandInvocationResultTypeDef:
        return self._call(
            "get_command_invocation",
            request,
            GetCommandInvocationResultTypeDef,
        )


    def get_connection_status(
        self, request: GetConnectionStatusRequestTypeDef,
    ) -> GetConnectionStatusResponseTypeDef:
        return self._call(
            "get_connection_status",
            request,
            GetConnectionStatusResponseTypeDef,
        )


    def get_default_patch_baseline(
        self, request: GetDefaultPatchBaselineRequestTypeDef,
    ) -> GetDefaultPatchBaselineResultTypeDef:
        return self._call(
            "get_default_patch_baseline",
            request,
            GetDefaultPatchBaselineResultTypeDef,
        )


    def get_deployable_patch_snapshot_for_instance(
        self, request: GetDeployablePatchSnapshotForInstanceRequestTypeDef,
    ) -> GetDeployablePatchSnapshotForInstanceResultTypeDef:
        return self._call(
            "get_deployable_patch_snapshot_for_instance",
            request,
            GetDeployablePatchSnapshotForInstanceResultTypeDef,
        )


    def get_document(
        self, request: GetDocumentRequestTypeDef,
    ) -> GetDocumentResultTypeDef:
        return self._call(
            "get_document",
            request,
            GetDocumentResultTypeDef,
        )


    def get_execution_preview(
        self, request: GetExecutionPreviewRequestTypeDef,
    ) -> GetExecutionPreviewResponseTypeDef:
        return self._call(
            "get_execution_preview",
            request,
            GetExecutionPreviewResponseTypeDef,
        )


    def get_inventory(
        self, request: GetInventoryRequestTypeDef,
    ) -> GetInventoryResultTypeDef:
        return self._call(
            "get_inventory",
            request,
            GetInventoryResultTypeDef,
        )


    def get_inventory_schema(
        self, request: GetInventorySchemaRequestTypeDef,
    ) -> GetInventorySchemaResultTypeDef:
        return self._call(
            "get_inventory_schema",
            request,
            GetInventorySchemaResultTypeDef,
        )


    def get_maintenance_window(
        self, request: GetMaintenanceWindowRequestTypeDef,
    ) -> GetMaintenanceWindowResultTypeDef:
        return self._call(
            "get_maintenance_window",
            request,
            GetMaintenanceWindowResultTypeDef,
        )


    def get_maintenance_window_execution(
        self, request: GetMaintenanceWindowExecutionRequestTypeDef,
    ) -> GetMaintenanceWindowExecutionResultTypeDef:
        return self._call(
            "get_maintenance_window_execution",
            request,
            GetMaintenanceWindowExecutionResultTypeDef,
        )


    def get_maintenance_window_execution_task(
        self, request: GetMaintenanceWindowExecutionTaskRequestTypeDef,
    ) -> GetMaintenanceWindowExecutionTaskResultTypeDef:
        return self._call(
            "get_maintenance_window_execution_task",
            request,
            GetMaintenanceWindowExecutionTaskResultTypeDef,
        )


    def get_maintenance_window_execution_task_invocation(
        self, request: GetMaintenanceWindowExecutionTaskInvocationRequestTypeDef,
    ) -> GetMaintenanceWindowExecutionTaskInvocationResultTypeDef:
        return self._call(
            "get_maintenance_window_execution_task_invocation",
            request,
            GetMaintenanceWindowExecutionTaskInvocationResultTypeDef,
        )


    def get_maintenance_window_task(
        self, request: GetMaintenanceWindowTaskRequestTypeDef,
    ) -> GetMaintenanceWindowTaskResultTypeDef:
        return self._call(
            "get_maintenance_window_task",
            request,
            GetMaintenanceWindowTaskResultTypeDef,
        )


    def get_ops_item(
        self, request: GetOpsItemRequestTypeDef,
    ) -> GetOpsItemResponseTypeDef:
        return self._call(
            "get_ops_item",
            request,
            GetOpsItemResponseTypeDef,
        )


    def get_ops_metadata(
        self, request: GetOpsMetadataRequestTypeDef,
    ) -> GetOpsMetadataResultTypeDef:
        return self._call(
            "get_ops_metadata",
            request,
            GetOpsMetadataResultTypeDef,
        )


    def get_ops_summary(
        self, request: GetOpsSummaryRequestTypeDef,
    ) -> GetOpsSummaryResultTypeDef:
        return self._call(
            "get_ops_summary",
            request,
            GetOpsSummaryResultTypeDef,
        )


    def get_parameter(
        self, request: GetParameterRequestTypeDef,
    ) -> GetParameterResultTypeDef:
        return self._call(
            "get_parameter",
            request,
            GetParameterResultTypeDef,
        )


    def get_parameter_history(
        self, request: GetParameterHistoryRequestTypeDef,
    ) -> GetParameterHistoryResultTypeDef:
        return self._call(
            "get_parameter_history",
            request,
            GetParameterHistoryResultTypeDef,
        )


    def get_parameters(
        self, request: GetParametersRequestTypeDef,
    ) -> GetParametersResultTypeDef:
        return self._call(
            "get_parameters",
            request,
            GetParametersResultTypeDef,
        )


    def get_parameters_by_path(
        self, request: GetParametersByPathRequestTypeDef,
    ) -> GetParametersByPathResultTypeDef:
        return self._call(
            "get_parameters_by_path",
            request,
            GetParametersByPathResultTypeDef,
        )


    def get_patch_baseline(
        self, request: GetPatchBaselineRequestTypeDef,
    ) -> GetPatchBaselineResultTypeDef:
        return self._call(
            "get_patch_baseline",
            request,
            GetPatchBaselineResultTypeDef,
        )


    def get_patch_baseline_for_patch_group(
        self, request: GetPatchBaselineForPatchGroupRequestTypeDef,
    ) -> GetPatchBaselineForPatchGroupResultTypeDef:
        return self._call(
            "get_patch_baseline_for_patch_group",
            request,
            GetPatchBaselineForPatchGroupResultTypeDef,
        )


    def get_resource_policies(
        self, request: GetResourcePoliciesRequestTypeDef,
    ) -> GetResourcePoliciesResponseTypeDef:
        return self._call(
            "get_resource_policies",
            request,
            GetResourcePoliciesResponseTypeDef,
        )


    def get_service_setting(
        self, request: GetServiceSettingRequestTypeDef,
    ) -> GetServiceSettingResultTypeDef:
        return self._call(
            "get_service_setting",
            request,
            GetServiceSettingResultTypeDef,
        )


    def label_parameter_version(
        self, request: LabelParameterVersionRequestTypeDef,
    ) -> LabelParameterVersionResultTypeDef:
        return self._call(
            "label_parameter_version",
            request,
            LabelParameterVersionResultTypeDef,
        )


    def list_association_versions(
        self, request: ListAssociationVersionsRequestTypeDef,
    ) -> ListAssociationVersionsResultTypeDef:
        return self._call(
            "list_association_versions",
            request,
            ListAssociationVersionsResultTypeDef,
        )


    def list_associations(
        self, request: ListAssociationsRequestTypeDef,
    ) -> ListAssociationsResultTypeDef:
        return self._call(
            "list_associations",
            request,
            ListAssociationsResultTypeDef,
        )


    def list_command_invocations(
        self, request: ListCommandInvocationsRequestTypeDef,
    ) -> ListCommandInvocationsResultTypeDef:
        return self._call(
            "list_command_invocations",
            request,
            ListCommandInvocationsResultTypeDef,
        )


    def list_commands(
        self, request: ListCommandsRequestTypeDef,
    ) -> ListCommandsResultTypeDef:
        return self._call(
            "list_commands",
            request,
            ListCommandsResultTypeDef,
        )


    def list_compliance_items(
        self, request: ListComplianceItemsRequestTypeDef,
    ) -> ListComplianceItemsResultTypeDef:
        return self._call(
            "list_compliance_items",
            request,
            ListComplianceItemsResultTypeDef,
        )


    def list_compliance_summaries(
        self, request: ListComplianceSummariesRequestTypeDef,
    ) -> ListComplianceSummariesResultTypeDef:
        return self._call(
            "list_compliance_summaries",
            request,
            ListComplianceSummariesResultTypeDef,
        )


    def list_document_metadata_history(
        self, request: ListDocumentMetadataHistoryRequestTypeDef,
    ) -> ListDocumentMetadataHistoryResponseTypeDef:
        return self._call(
            "list_document_metadata_history",
            request,
            ListDocumentMetadataHistoryResponseTypeDef,
        )


    def list_document_versions(
        self, request: ListDocumentVersionsRequestTypeDef,
    ) -> ListDocumentVersionsResultTypeDef:
        return self._call(
            "list_document_versions",
            request,
            ListDocumentVersionsResultTypeDef,
        )


    def list_documents(
        self, request: ListDocumentsRequestTypeDef,
    ) -> ListDocumentsResultTypeDef:
        return self._call(
            "list_documents",
            request,
            ListDocumentsResultTypeDef,
        )


    def list_inventory_entries(
        self, request: ListInventoryEntriesRequestTypeDef,
    ) -> ListInventoryEntriesResultTypeDef:
        return self._call(
            "list_inventory_entries",
            request,
            ListInventoryEntriesResultTypeDef,
        )


    def list_nodes(
        self, request: ListNodesRequestTypeDef,
    ) -> ListNodesResultTypeDef:
        return self._call(
            "list_nodes",
            request,
            ListNodesResultTypeDef,
        )


    def list_nodes_summary(
        self, request: ListNodesSummaryRequestTypeDef,
    ) -> ListNodesSummaryResultTypeDef:
        return self._call(
            "list_nodes_summary",
            request,
            ListNodesSummaryResultTypeDef,
        )


    def list_ops_item_events(
        self, request: ListOpsItemEventsRequestTypeDef,
    ) -> ListOpsItemEventsResponseTypeDef:
        return self._call(
            "list_ops_item_events",
            request,
            ListOpsItemEventsResponseTypeDef,
        )


    def list_ops_item_related_items(
        self, request: ListOpsItemRelatedItemsRequestTypeDef,
    ) -> ListOpsItemRelatedItemsResponseTypeDef:
        return self._call(
            "list_ops_item_related_items",
            request,
            ListOpsItemRelatedItemsResponseTypeDef,
        )


    def list_ops_metadata(
        self, request: ListOpsMetadataRequestTypeDef,
    ) -> ListOpsMetadataResultTypeDef:
        return self._call(
            "list_ops_metadata",
            request,
            ListOpsMetadataResultTypeDef,
        )


    def list_resource_compliance_summaries(
        self, request: ListResourceComplianceSummariesRequestTypeDef,
    ) -> ListResourceComplianceSummariesResultTypeDef:
        return self._call(
            "list_resource_compliance_summaries",
            request,
            ListResourceComplianceSummariesResultTypeDef,
        )


    def list_resource_data_sync(
        self, request: ListResourceDataSyncRequestTypeDef,
    ) -> ListResourceDataSyncResultTypeDef:
        return self._call(
            "list_resource_data_sync",
            request,
            ListResourceDataSyncResultTypeDef,
        )


    def list_tags_for_resource(
        self, request: ListTagsForResourceRequestTypeDef,
    ) -> ListTagsForResourceResultTypeDef:
        return self._call(
            "list_tags_for_resource",
            request,
            ListTagsForResourceResultTypeDef,
        )


    def modify_document_permission(
        self, request: ModifyDocumentPermissionRequestTypeDef,
    ) -> None:
        return self._call(
            "modify_document_permission",
            request,
            None,
        )


    def put_compliance_items(
        self, request: PutComplianceItemsRequestTypeDef,
    ) -> None:
        return self._call(
            "put_compliance_items",
            request,
            None,
        )


    def put_inventory(
        self, request: PutInventoryRequestTypeDef,
    ) -> PutInventoryResultTypeDef:
        return self._call(
            "put_inventory",
            request,
            PutInventoryResultTypeDef,
        )


    def put_parameter(
        self, request: PutParameterRequestTypeDef,
    ) -> PutParameterResultTypeDef:
        return self._call(
            "put_parameter",
            request,
            PutParameterResultTypeDef,
        )


    def put_resource_policy(
        self, request: PutResourcePolicyRequestTypeDef,
    ) -> PutResourcePolicyResponseTypeDef:
        return self._call(
            "put_resource_policy",
            request,
            PutResourcePolicyResponseTypeDef,
        )


    def register_default_patch_baseline(
        self, request: RegisterDefaultPatchBaselineRequestTypeDef,
    ) -> RegisterDefaultPatchBaselineResultTypeDef:
        return self._call(
            "register_default_patch_baseline",
            request,
            RegisterDefaultPatchBaselineResultTypeDef,
        )


    def register_patch_baseline_for_patch_group(
        self, request: RegisterPatchBaselineForPatchGroupRequestTypeDef,
    ) -> RegisterPatchBaselineForPatchGroupResultTypeDef:
        return self._call(
            "register_patch_baseline_for_patch_group",
            request,
            RegisterPatchBaselineForPatchGroupResultTypeDef,
        )


    def register_target_with_maintenance_window(
        self, request: RegisterTargetWithMaintenanceWindowRequestTypeDef,
    ) -> RegisterTargetWithMaintenanceWindowResultTypeDef:
        return self._call(
            "register_target_with_maintenance_window",
            request,
            RegisterTargetWithMaintenanceWindowResultTypeDef,
        )


    def register_task_with_maintenance_window(
        self, request: RegisterTaskWithMaintenanceWindowRequestTypeDef,
    ) -> RegisterTaskWithMaintenanceWindowResultTypeDef:
        return self._call(
            "register_task_with_maintenance_window",
            request,
            RegisterTaskWithMaintenanceWindowResultTypeDef,
        )


    def remove_tags_from_resource(
        self, request: RemoveTagsFromResourceRequestTypeDef,
    ) -> None:
        return self._call(
            "remove_tags_from_resource",
            request,
            None,
        )


    def reset_service_setting(
        self, request: ResetServiceSettingRequestTypeDef,
    ) -> ResetServiceSettingResultTypeDef:
        return self._call(
            "reset_service_setting",
            request,
            ResetServiceSettingResultTypeDef,
        )


    def resume_session(
        self, request: ResumeSessionRequestTypeDef,
    ) -> ResumeSessionResponseTypeDef:
        return self._call(
            "resume_session",
            request,
            ResumeSessionResponseTypeDef,
        )


    def send_automation_signal(
        self, request: SendAutomationSignalRequestTypeDef,
    ) -> None:
        return self._call(
            "send_automation_signal",
            request,
            None,
        )


    def send_command(
        self, request: SendCommandRequestTypeDef,
    ) -> SendCommandResultTypeDef:
        return self._call(
            "send_command",
            request,
            SendCommandResultTypeDef,
        )


    def start_access_request(
        self, request: StartAccessRequestRequestTypeDef,
    ) -> StartAccessRequestResponseTypeDef:
        return self._call(
            "start_access_request",
            request,
            StartAccessRequestResponseTypeDef,
        )


    def start_associations_once(
        self, request: StartAssociationsOnceRequestTypeDef,
    ) -> None:
        return self._call(
            "start_associations_once",
            request,
            None,
        )


    def start_automation_execution(
        self, request: StartAutomationExecutionRequestTypeDef,
    ) -> StartAutomationExecutionResultTypeDef:
        return self._call(
            "start_automation_execution",
            request,
            StartAutomationExecutionResultTypeDef,
        )


    def start_change_request_execution(
        self, request: StartChangeRequestExecutionRequestTypeDef,
    ) -> StartChangeRequestExecutionResultTypeDef:
        return self._call(
            "start_change_request_execution",
            request,
            StartChangeRequestExecutionResultTypeDef,
        )


    def start_execution_preview(
        self, request: StartExecutionPreviewRequestTypeDef,
    ) -> StartExecutionPreviewResponseTypeDef:
        return self._call(
            "start_execution_preview",
            request,
            StartExecutionPreviewResponseTypeDef,
        )


    def start_session(
        self, request: StartSessionRequestTypeDef,
    ) -> StartSessionResponseTypeDef:
        return self._call(
            "start_session",
            request,
            StartSessionResponseTypeDef,
        )


    def stop_automation_execution(
        self, request: StopAutomationExecutionRequestTypeDef,
    ) -> None:
        return self._call(
            "stop_automation_execution",
            request,
            None,
        )


    def terminate_session(
        self, request: TerminateSessionRequestTypeDef,
    ) -> TerminateSessionResponseTypeDef:
        return self._call(
            "terminate_session",
            request,
            TerminateSessionResponseTypeDef,
        )


    def unlabel_parameter_version(
        self, request: UnlabelParameterVersionRequestTypeDef,
    ) -> UnlabelParameterVersionResultTypeDef:
        return self._call(
            "unlabel_parameter_version",
            request,
            UnlabelParameterVersionResultTypeDef,
        )


    def update_association(
        self, request: UpdateAssociationRequestTypeDef,
    ) -> UpdateAssociationResultTypeDef:
        return self._call(
            "update_association",
            request,
            UpdateAssociationResultTypeDef,
        )


    def update_association_status(
        self, request: UpdateAssociationStatusRequestTypeDef,
    ) -> UpdateAssociationStatusResultTypeDef:
        return self._call(
            "update_association_status",
            request,
            UpdateAssociationStatusResultTypeDef,
        )


    def update_document(
        self, request: UpdateDocumentRequestTypeDef,
    ) -> UpdateDocumentResultTypeDef:
        return self._call(
            "update_document",
            request,
            UpdateDocumentResultTypeDef,
        )


    def update_document_default_version(
        self, request: UpdateDocumentDefaultVersionRequestTypeDef,
    ) -> UpdateDocumentDefaultVersionResultTypeDef:
        return self._call(
            "update_document_default_version",
            request,
            UpdateDocumentDefaultVersionResultTypeDef,
        )


    def update_document_metadata(
        self, request: UpdateDocumentMetadataRequestTypeDef,
    ) -> None:
        return self._call(
            "update_document_metadata",
            request,
            None,
        )


    def update_maintenance_window(
        self, request: UpdateMaintenanceWindowRequestTypeDef,
    ) -> UpdateMaintenanceWindowResultTypeDef:
        return self._call(
            "update_maintenance_window",
            request,
            UpdateMaintenanceWindowResultTypeDef,
        )


    def update_maintenance_window_target(
        self, request: UpdateMaintenanceWindowTargetRequestTypeDef,
    ) -> UpdateMaintenanceWindowTargetResultTypeDef:
        return self._call(
            "update_maintenance_window_target",
            request,
            UpdateMaintenanceWindowTargetResultTypeDef,
        )


    def update_maintenance_window_task(
        self, request: UpdateMaintenanceWindowTaskRequestTypeDef,
    ) -> UpdateMaintenanceWindowTaskResultTypeDef:
        return self._call(
            "update_maintenance_window_task",
            request,
            UpdateMaintenanceWindowTaskResultTypeDef,
        )


    def update_managed_instance_role(
        self, request: UpdateManagedInstanceRoleRequestTypeDef,
    ) -> None:
        return self._call(
            "update_managed_instance_role",
            request,
            None,
        )


    def update_ops_item(
        self, request: UpdateOpsItemRequestTypeDef,
    ) -> None:
        return self._call(
            "update_ops_item",
            request,
            None,
        )


    def update_ops_metadata(
        self, request: UpdateOpsMetadataRequestTypeDef,
    ) -> UpdateOpsMetadataResultTypeDef:
        return self._call(
            "update_ops_metadata",
            request,
            UpdateOpsMetadataResultTypeDef,
        )


    def update_patch_baseline(
        self, request: UpdatePatchBaselineRequestTypeDef,
    ) -> UpdatePatchBaselineResultTypeDef:
        return self._call(
            "update_patch_baseline",
            request,
            UpdatePatchBaselineResultTypeDef,
        )


    def update_resource_data_sync(
        self, request: UpdateResourceDataSyncRequestTypeDef,
    ) -> None:
        return self._call(
            "update_resource_data_sync",
            request,
            None,
        )


    def update_service_setting(
        self, request: UpdateServiceSettingRequestTypeDef,
    ) -> None:
        return self._call(
            "update_service_setting",
            request,
            None,
        )

