# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.
from __future__ import annotations

from aws_resource_validator.pydantic_models.stepfunctions.stepfunctions_classes import (
    CreateActivityInputTypeDef,
    CreateActivityOutputTypeDef,
    CreateStateMachineAliasInputTypeDef,
    CreateStateMachineAliasOutputTypeDef,
    CreateStateMachineInputTypeDef,
    CreateStateMachineOutputTypeDef,
    DeleteActivityInputTypeDef,
    DeleteStateMachineAliasInputTypeDef,
    DeleteStateMachineInputTypeDef,
    DeleteStateMachineVersionInputTypeDef,
    DescribeActivityInputTypeDef,
    DescribeActivityOutputTypeDef,
    DescribeExecutionInputTypeDef,
    DescribeExecutionOutputTypeDef,
    DescribeMapRunInputTypeDef,
    DescribeMapRunOutputTypeDef,
    DescribeStateMachineAliasInputTypeDef,
    DescribeStateMachineAliasOutputTypeDef,
    DescribeStateMachineForExecutionInputTypeDef,
    DescribeStateMachineForExecutionOutputTypeDef,
    DescribeStateMachineInputTypeDef,
    DescribeStateMachineOutputTypeDef,
    GetActivityTaskInputTypeDef,
    GetActivityTaskOutputTypeDef,
    GetExecutionHistoryInputTypeDef,
    GetExecutionHistoryOutputTypeDef,
    ListActivitiesInputTypeDef,
    ListActivitiesOutputTypeDef,
    ListExecutionsInputTypeDef,
    ListExecutionsOutputTypeDef,
    ListMapRunsInputTypeDef,
    ListMapRunsOutputTypeDef,
    ListStateMachineAliasesInputTypeDef,
    ListStateMachineAliasesOutputTypeDef,
    ListStateMachineVersionsInputTypeDef,
    ListStateMachineVersionsOutputTypeDef,
    ListStateMachinesInputTypeDef,
    ListStateMachinesOutputTypeDef,
    ListTagsForResourceInputTypeDef,
    ListTagsForResourceOutputTypeDef,
    PublishStateMachineVersionInputTypeDef,
    PublishStateMachineVersionOutputTypeDef,
    RedriveExecutionInputTypeDef,
    RedriveExecutionOutputTypeDef,
    SendTaskFailureInputTypeDef,
    SendTaskHeartbeatInputTypeDef,
    SendTaskSuccessInputTypeDef,
    StartExecutionInputTypeDef,
    StartExecutionOutputTypeDef,
    StartSyncExecutionInputTypeDef,
    StartSyncExecutionOutputTypeDef,
    StopExecutionInputTypeDef,
    StopExecutionOutputTypeDef,
    TagResourceInputTypeDef,
    TestStateInputTypeDef,
    TestStateOutputTypeDef,
    UntagResourceInputTypeDef,
    UpdateMapRunInputTypeDef,
    UpdateStateMachineAliasInputTypeDef,
    UpdateStateMachineAliasOutputTypeDef,
    UpdateStateMachineInputTypeDef,
    UpdateStateMachineOutputTypeDef,
    ValidateStateMachineDefinitionInputTypeDef,
    ValidateStateMachineDefinitionOutputTypeDef,
)

from typed_boto3._service_name import ServiceName
from typed_boto3.core.base import TypedClientBase


class StepfunctionsClient(TypedClientBase):
    _service_name = ServiceName.STEPFUNCTIONS


    def create_activity(
        self, request: CreateActivityInputTypeDef,
    ) -> CreateActivityOutputTypeDef:
        return self._call(
            "create_activity",
            request,
            CreateActivityOutputTypeDef,
        )


    def create_state_machine(
        self, request: CreateStateMachineInputTypeDef,
    ) -> CreateStateMachineOutputTypeDef:
        return self._call(
            "create_state_machine",
            request,
            CreateStateMachineOutputTypeDef,
        )


    def create_state_machine_alias(
        self, request: CreateStateMachineAliasInputTypeDef,
    ) -> CreateStateMachineAliasOutputTypeDef:
        return self._call(
            "create_state_machine_alias",
            request,
            CreateStateMachineAliasOutputTypeDef,
        )


    def delete_activity(
        self, request: DeleteActivityInputTypeDef,
    ) -> None:
        return self._call(
            "delete_activity",
            request,
            None,
        )


    def delete_state_machine(
        self, request: DeleteStateMachineInputTypeDef,
    ) -> None:
        return self._call(
            "delete_state_machine",
            request,
            None,
        )


    def delete_state_machine_alias(
        self, request: DeleteStateMachineAliasInputTypeDef,
    ) -> None:
        return self._call(
            "delete_state_machine_alias",
            request,
            None,
        )


    def delete_state_machine_version(
        self, request: DeleteStateMachineVersionInputTypeDef,
    ) -> None:
        return self._call(
            "delete_state_machine_version",
            request,
            None,
        )


    def describe_activity(
        self, request: DescribeActivityInputTypeDef,
    ) -> DescribeActivityOutputTypeDef:
        return self._call(
            "describe_activity",
            request,
            DescribeActivityOutputTypeDef,
        )


    def describe_execution(
        self, request: DescribeExecutionInputTypeDef,
    ) -> DescribeExecutionOutputTypeDef:
        return self._call(
            "describe_execution",
            request,
            DescribeExecutionOutputTypeDef,
        )


    def describe_map_run(
        self, request: DescribeMapRunInputTypeDef,
    ) -> DescribeMapRunOutputTypeDef:
        return self._call(
            "describe_map_run",
            request,
            DescribeMapRunOutputTypeDef,
        )


    def describe_state_machine(
        self, request: DescribeStateMachineInputTypeDef,
    ) -> DescribeStateMachineOutputTypeDef:
        return self._call(
            "describe_state_machine",
            request,
            DescribeStateMachineOutputTypeDef,
        )


    def describe_state_machine_alias(
        self, request: DescribeStateMachineAliasInputTypeDef,
    ) -> DescribeStateMachineAliasOutputTypeDef:
        return self._call(
            "describe_state_machine_alias",
            request,
            DescribeStateMachineAliasOutputTypeDef,
        )


    def describe_state_machine_for_execution(
        self, request: DescribeStateMachineForExecutionInputTypeDef,
    ) -> DescribeStateMachineForExecutionOutputTypeDef:
        return self._call(
            "describe_state_machine_for_execution",
            request,
            DescribeStateMachineForExecutionOutputTypeDef,
        )


    def get_activity_task(
        self, request: GetActivityTaskInputTypeDef,
    ) -> GetActivityTaskOutputTypeDef:
        return self._call(
            "get_activity_task",
            request,
            GetActivityTaskOutputTypeDef,
        )


    def get_execution_history(
        self, request: GetExecutionHistoryInputTypeDef,
    ) -> GetExecutionHistoryOutputTypeDef:
        return self._call(
            "get_execution_history",
            request,
            GetExecutionHistoryOutputTypeDef,
        )


    def list_activities(
        self, request: ListActivitiesInputTypeDef,
    ) -> ListActivitiesOutputTypeDef:
        return self._call(
            "list_activities",
            request,
            ListActivitiesOutputTypeDef,
        )


    def list_executions(
        self, request: ListExecutionsInputTypeDef,
    ) -> ListExecutionsOutputTypeDef:
        return self._call(
            "list_executions",
            request,
            ListExecutionsOutputTypeDef,
        )


    def list_map_runs(
        self, request: ListMapRunsInputTypeDef,
    ) -> ListMapRunsOutputTypeDef:
        return self._call(
            "list_map_runs",
            request,
            ListMapRunsOutputTypeDef,
        )


    def list_state_machine_aliases(
        self, request: ListStateMachineAliasesInputTypeDef,
    ) -> ListStateMachineAliasesOutputTypeDef:
        return self._call(
            "list_state_machine_aliases",
            request,
            ListStateMachineAliasesOutputTypeDef,
        )


    def list_state_machine_versions(
        self, request: ListStateMachineVersionsInputTypeDef,
    ) -> ListStateMachineVersionsOutputTypeDef:
        return self._call(
            "list_state_machine_versions",
            request,
            ListStateMachineVersionsOutputTypeDef,
        )


    def list_state_machines(
        self, request: ListStateMachinesInputTypeDef,
    ) -> ListStateMachinesOutputTypeDef:
        return self._call(
            "list_state_machines",
            request,
            ListStateMachinesOutputTypeDef,
        )


    def list_tags_for_resource(
        self, request: ListTagsForResourceInputTypeDef,
    ) -> ListTagsForResourceOutputTypeDef:
        return self._call(
            "list_tags_for_resource",
            request,
            ListTagsForResourceOutputTypeDef,
        )


    def publish_state_machine_version(
        self, request: PublishStateMachineVersionInputTypeDef,
    ) -> PublishStateMachineVersionOutputTypeDef:
        return self._call(
            "publish_state_machine_version",
            request,
            PublishStateMachineVersionOutputTypeDef,
        )


    def redrive_execution(
        self, request: RedriveExecutionInputTypeDef,
    ) -> RedriveExecutionOutputTypeDef:
        return self._call(
            "redrive_execution",
            request,
            RedriveExecutionOutputTypeDef,
        )


    def send_task_failure(
        self, request: SendTaskFailureInputTypeDef,
    ) -> None:
        return self._call(
            "send_task_failure",
            request,
            None,
        )


    def send_task_heartbeat(
        self, request: SendTaskHeartbeatInputTypeDef,
    ) -> None:
        return self._call(
            "send_task_heartbeat",
            request,
            None,
        )


    def send_task_success(
        self, request: SendTaskSuccessInputTypeDef,
    ) -> None:
        return self._call(
            "send_task_success",
            request,
            None,
        )


    def start_execution(
        self, request: StartExecutionInputTypeDef,
    ) -> StartExecutionOutputTypeDef:
        return self._call(
            "start_execution",
            request,
            StartExecutionOutputTypeDef,
        )


    def start_sync_execution(
        self, request: StartSyncExecutionInputTypeDef,
    ) -> StartSyncExecutionOutputTypeDef:
        return self._call(
            "start_sync_execution",
            request,
            StartSyncExecutionOutputTypeDef,
        )


    def stop_execution(
        self, request: StopExecutionInputTypeDef,
    ) -> StopExecutionOutputTypeDef:
        return self._call(
            "stop_execution",
            request,
            StopExecutionOutputTypeDef,
        )


    def tag_resource(
        self, request: TagResourceInputTypeDef,
    ) -> None:
        return self._call(
            "tag_resource",
            request,
            None,
        )


    def test_state(
        self, request: TestStateInputTypeDef,
    ) -> TestStateOutputTypeDef:
        return self._call(
            "test_state",
            request,
            TestStateOutputTypeDef,
        )


    def untag_resource(
        self, request: UntagResourceInputTypeDef,
    ) -> None:
        return self._call(
            "untag_resource",
            request,
            None,
        )


    def update_map_run(
        self, request: UpdateMapRunInputTypeDef,
    ) -> None:
        return self._call(
            "update_map_run",
            request,
            None,
        )


    def update_state_machine(
        self, request: UpdateStateMachineInputTypeDef,
    ) -> UpdateStateMachineOutputTypeDef:
        return self._call(
            "update_state_machine",
            request,
            UpdateStateMachineOutputTypeDef,
        )


    def update_state_machine_alias(
        self, request: UpdateStateMachineAliasInputTypeDef,
    ) -> UpdateStateMachineAliasOutputTypeDef:
        return self._call(
            "update_state_machine_alias",
            request,
            UpdateStateMachineAliasOutputTypeDef,
        )


    def validate_state_machine_definition(
        self, request: ValidateStateMachineDefinitionInputTypeDef,
    ) -> ValidateStateMachineDefinitionOutputTypeDef:
        return self._call(
            "validate_state_machine_definition",
            request,
            ValidateStateMachineDefinitionOutputTypeDef,
        )

