from pathlib import Path

from typed_boto3.generator.naming import class_name, enum_member, module_name

BEGIN = "# --- BEGIN GENERATED ---"
END = "# --- END GENERATED ---"


def write_service_name_enum(services: list[str], package_root: Path) -> None:
    lines = [
        "# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.",
        "from enum import StrEnum",
        "",
        "",
        "class ServiceName(StrEnum):",
    ]
    for svc in services:
        lines.append(f'    {enum_member(svc)} = "{svc}"')
    (package_root / "_service_name.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_services_init(services: list[str], services_dir: Path) -> None:
    lines = [
        "# Generated by typed_boto3.generator (mode=--service). Do not edit by hand.",
    ]
    for svc in services:
        lines.append(f"from typed_boto3.services.{module_name(svc)} import {class_name(svc)}")
    lines.append("")
    exported = ", ".join(f'"{class_name(s)}"' for s in services)
    lines.append(f"__all__ = [{exported}]")
    (services_dir / "__init__.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


_DEFAULT_HEADER = '"""typed_boto3 — strongly-typed, SDK-like wrapper around boto3."""\n'


def _render_generated_block(services: list[str]) -> str:
    lines: list[str] = []
    lines.append("from typing import Literal, overload")
    lines.append("from typed_boto3._service_name import ServiceName")
    lines.append("from typed_boto3._region import Region")
    lines.append("from typed_boto3.core.config import ClientConfig, AwsCredentials")
    for svc in services:
        lines.append(f"from typed_boto3.services.{module_name(svc)} import {class_name(svc)}")
    lines.append("")
    for svc in services:
        lines.append("@overload")
        lines.append(
            f"def client(service_name: Literal[ServiceName.{enum_member(svc)}], "
            f"config: ClientConfig | None = None) -> {class_name(svc)}: ..."
        )
    lines.append("")
    union = " | ".join(class_name(s) for s in services) if services else "object"
    lines.append(f"def client(service_name: ServiceName, config: ClientConfig | None = None) -> {union}:")
    lines.append("    mapping: dict[ServiceName, type] = {")
    for svc in services:
        lines.append(f"        ServiceName.{enum_member(svc)}: {class_name(svc)},")
    lines.append("    }")
    lines.append("    return mapping[service_name](config)  # type: ignore[no-any-return]")
    lines.append("")
    all_items = ['"client"', '"ServiceName"', '"Region"', '"ClientConfig"', '"AwsCredentials"']
    all_items += [f'"{class_name(s)}"' for s in services]
    lines.append(f"__all__ = [{', '.join(all_items)}]")
    return "\n".join(lines)


def _splice_generated(existing: str, generated: str) -> str:
    begin = existing.find(BEGIN)
    end = existing.find(END)
    if begin == -1 or end == -1 or end < begin:
        return _DEFAULT_HEADER + "\n" + BEGIN + "\n" + generated + "\n" + END + "\n"
    prefix = existing[: begin + len(BEGIN)]
    suffix = existing[end:]
    return prefix + "\n" + generated + "\n" + suffix


def write_package_init(services: list[str], package_root: Path) -> None:
    generated = _render_generated_block(services)
    init_path = package_root / "__init__.py"
    existing = init_path.read_text(encoding="utf-8") if init_path.exists() else ""
    init_path.write_text(_splice_generated(existing, generated), encoding="utf-8")
