from pathlib import Path

import botocore.session

from typed_boto3.generator.naming import enum_member


def _collect_regions() -> list[str]:
    session = botocore.session.Session()
    regions: set[str] = set()
    # Union across partitions and a couple of anchor services; keeps us from missing
    # regions that some services haven't launched in yet.
    for partition in ("aws", "aws-cn", "aws-us-gov"):
        for svc in ("ec2", "s3", "lambda"):
            regions |= set(session.get_available_regions(svc, partition_name=partition))
    return sorted(regions)


def write_region_enum(package_root: Path) -> None:
    regions = _collect_regions()
    lines = [
        "# Generated by typed_boto3.generator (mode=--regions). Do not edit by hand.",
        "from enum import StrEnum",
        "",
        "",
        "class Region(StrEnum):",
    ]
    for r in regions:
        lines.append(f'    {enum_member(r)} = "{r}"')
    (package_root / "_region.py").write_text("\n".join(lines) + "\n", encoding="utf-8")
